### ISSUE TITLE
Contour lines drawn along degree grid

### ISSUE THREAD

**Issue by kreuzschnabel** [osmandapp/OsmAnd#10161]
Since the November update of contour lines, they gather around the integer-numbered longitude and latitude degree lines. Go to 50°N 8°E, or 49°N 8°E to see that.

Here’s a screenshot of 49N 9E: https://ibb.co/V9M0d3v

In lower zoom levels, they form a fuzzy orange line, when zooming in, this dissolves into separate contour lines with ther elevation labels running along with the meridian. They do not coincide exactly but run parallel.

OsmAnd Version: 3.8.4+
Android/iOS version: LineageOS 17.1 / Android 10
Device model: Oneplus 5T

**Maps used (online or offline):**   offline, standard map, contours and hillshading on. Maps and contours / hillshading data updated a few days ago.

Edit: Already being discussed on https://forum.openstreetmap.org/viewtopic.php?id=71126

--ks

**Comment by vshcherb** [comment]
![Uploading image.png…]()

**Comment by xmd5a2** [comment]
Fixed. Please update contour lines. Update will be available today.

**Comment by pebogufi** [comment]
@xmd5a2 
NOT COMPLETELY solved:
please have look at
-  48.0° N, 8.0° O still wrong contour lines
-  48.0° N, 8.0° O cluttered strange parts of contour lines,  please zoom in-out-in-out... to see.

**Comment by xmd5a2** [comment]
@pebogufi Please update France_europe and/or France_great-east_europe SRTM maps. All SRTM maps are overlapping each other and problematic tiles was located in France maps too.

**Comment by pebogufi** [comment]
Thanks a lot, that solved the problem.

**Comment by Zahnstocher** [comment]
> Thanks a lot, that solved the problem.

Can't confirm.
Issue still exists for me, contour line maps for Germany Baden-Württemberg and also whole Germany have the issues mentioned here:
https://github.com/osmandapp/OsmAnd/issues/10161#issuecomment-727231859
I checked it several times, deleted all maps and only downloaded contour line maps for Germany Baden-Württemberg, issue is still there.

**Comment by pebogufi** [comment]
@Zahnstocher did you read tha last post of xmd5a2 to dnl also france SRTM files ?
THIS solved the problem.

**Comment by Zahnstocher** [comment]
> @Zahnstocher did you read tha last post of xmd5a2 to dnl also france SRTM files ?
> THIS solved the problem.

Yes, I did read ALL comments!
Did you read, that I deleted ALL maps and ONLY downloaded Germany Baden-Württemberg (SRTM) and the problem still exists?
There are NO other maps (no SRTM, no standard maps, no road maps, nothing) installed.
A few minutes ago I double checked, I deleted the complete osmand directory, rebooted my phone and only downloaded Germany Baden-Württemberg SRTM map, problem still exists.

**Comment by pebogufi** [comment]
Which positions are still  buggy ?
please give some examples.

**Comment by xmd5a2** [comment]
Look at screenshots of these point ( 48 10, 48 8):
![Screenshot_2020-11-16_16-06-10](https://user-images.githubusercontent.com/5829014/99255935-b45fa480-2825-11eb-9fd5-4dcf39b027d7.png)
![Screenshot_2020-11-16_16-05-02](https://user-images.githubusercontent.com/5829014/99255943-b590d180-2825-11eb-9dec-1641ac0bc85d.png)
I used only Germany Baden-Württemberg srtm map. No such artefacts at all.

**Comment by pebogufi** [comment]
![Contourproblem at 48N_8E](https://user-images.githubusercontent.com/18628183/99289649-86865a00-283d-11eb-88bd-25a59ebc5b95.jpg)

![Contourproblem at 48N_10E](https://user-images.githubusercontent.com/18628183/99289671-8d14d180-283d-11eb-944b-2051dc69c8f2.jpg)

**Comment by xmd5a2** [comment]
First screen is fine and very hard to fix. Second screen: It would be good to summarize if you can see other places as well. There is nothing like long parallel lines from original issue.

**Comment by pebogufi** [comment]
I will search for more.

**Comment by scaidermern** [comment]
![Screenshot_20201117-102232_OsmAnd+](https://user-images.githubusercontent.com/1040784/99372025-ede4ee00-28bf-11eb-9811-791e79f58c33.png)
![Screenshot_20201117-102548_OsmAnd+](https://user-images.githubusercontent.com/1040784/99372028-ee7d8480-28bf-11eb-87f2-9fa3349a5c89.png)

At 47.5152,13.0 and 47.65011,12.0

**Comment by xmd5a2** [comment]
Sorry but we won't fix such artefacts because they are negligible. They come from gdal_contour processing step. Entire earth DEM contains 21135 tiles by 1x1 degree and almost every osm.xml produced from them contains these artefacts. It is possible to **partially** fix them by removing nodes at every isoline end but such processing (even automatic) will take months.
