### ISSUE TITLE
Plan a route: Using "Straight line" for the next segment breaks routing

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#10206]
Currently it is not possible to switch to "Straight line" for only a few segments while planning a route. As soon as "Straight line" is used, the routing fails for all segments until the route planning gets aborted.

Steps to reproduce:
- Plan a route -> Create new route
- Add a point with the initial mode (straight line, whole track)
- Switch to straight line, next segment
- Add a point
- Switch to car profile, next segment
- A toast appears with the text "Could not calculate route: Application mode 'Browse map' is not supported."

With every new point the same error message appears.

OsmAnd 3.8.4

**Comment by alex-osm** [comment]
Not reproducible in the nightly build. Should be fixed in the next release.

**Comment by scaidermern** [comment]
Confirmed, seems to be gone.

**Comment by scaidermern** [comment]
Problem still exists or reappeared with OsmAnd.

Steps to reproduce:

- Plan a route -> Create new route
- Switch to next segment, car mode
- Add two points (so that the routing starts)
- Switch to next segment, straight line
- A toast appears with the text "Could not calculate route: Application mode 'Browse map' is not supported."

With every new point the same error message appears.

Please reopen.
