### ISSUE TITLE
Website URL of POI displayed as garbage

### ISSUE THREAD

**Issue by aceman444** [osmandapp/OsmAnd#10250]
On https://www.openstreetmap.org/node/8035896488 when viewing the POI details in OsmAnd all information is displayed fine, just the URL is displayed as garbage characters
### Your Environment
OsmAnd Version: 3.8.5
Android 10

**Comment by vshcherb** [comment]
It should have been fixed already this week. Please check

**Comment by aceman444** [comment]
How can I check? There is no new OsmAnd release since 3.8.5 and with latest OsmAnd Live data for Slovakia  the error is still seen.

**Comment by vshcherb** [comment]
beta will be uploaded today

**Comment by aceman444** [comment]
Ah, it was fixed in OsmAnd code, ok then, I will check it, thanks.

**Comment by aceman444** [comment]
And yes, my 'garbage' display also started with the string 'gz' (as in issue #10343), but OsmAnd did not crash.
