### ISSUE TITLE
External imput device map key -  doesn't work with 3.8.4 osmand plus 

### ISSUE THREAD

**Issue by wave2175** [osmandapp/OsmAnd#10523]
Hi, i've made a little bluetooth device that i use with some Android's APPs... and it' work perfectly (using it like a HID Keyboard).
I'm trying to conect it to osmand too but i've some problem:
I've found a KEY MAP on a old issue

KEYCODE_DPAD_RIGHT (22) scroll right
KEYCODE_DPAD_LEFT (21) scroll left
KEYCODE_DPAD_UP (19) scroll up
KEYCODE_DPAD_DOWN (20) scroll down
KEYCODE_PLUS  (81) or KEYCODE_NUMPAD_ADD zoom in
KEYCODE_MINUS (69) or KEYCODE_NUMPAD_SUBTRACT zoom out
KEYCODE_C map centering: 
KEYCODE_R map orientation north up/direction of travel toggle

i've tested it with Osmand plus version 3.8.4 but it doesn't work,
i've set osmand to accept external input bluetooth devices but nothing....
Anybody could help me?

it works only if i set the VOLUME Button option (and it works only with zoom in and zoom out.

tnx

**Comment by vshcherb** [comment]
It was tested with emulator keyboard, probably @nazar-kutz could help how it was tested

**Comment by joostbijl** [comment]
i have a similar experience. I programmed an arduino to send bt hid keystrokes. I configured osmand to have an external generic keyboard and use volume buttons to zoom.

the KEYCODE_DPAD_* are registerd on the device and work just fine in other apps, but not in osmand. KEYCODE_VOLUME_* works fine and zooms the map. KEYCODE_C also works like you would expect.

if i select Wunderlinq or Parrot as external input the exceptions in the source code appear to be honored, because now i can zoom by using the dpad buttons. (https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/src/net/osmand/plus/activities/MapActivityKeyListener.java)

It seems that the map panning for 'generic keyboard' is broken. (using osmand+ 3.9.10)

here you can see the device in action on kurviger: https://www.youtube.com/watch?v=C08YxzOzUv8. I'd like this also to work on Osmand.

**Comment by joostbijl** [comment]
It looks like all the aforementioned issues have been fixed by @nazar-kutz . I installed the beta 4.0.0 and that appears to work just fine. 

Any ideas when these changes will make it to the play store?

**Comment by fpavlic** [comment]
@joostbijl I'm still experiencing issues with KEYCODE_DPAD_* seems they just don't register keyup. Any solution so far?

**Comment by joostbijl** [comment]
> @joostbijl I'm still experiencing issues with KEYCODE_DPAD_* seems they just don't register keyup. Any solution so far?

I did not have issues after 4.0 - but i'll check once i have my arduino soldered back to a new case ;)
