### ISSUE TITLE
(automatic) recording stops when app goes in background

### ISSUE THREAD

**Issue by gronaix** [osmandapp/OsmAnd#11038]
since the lastest update on Android (v3.9.9) I experienced several times, that ongoing recordings disappear when the app is kept in background mode.
so far i have my app setup, that it automatically starts recoding locally and online when using navigation. when the app is kept in background while reaching destination or after manually discarding navigation, the so far recorded track gets lost with no way to recover or save it.

**Comment by vshcherb** [comment]
It's probably crashes in background we have fixed some crashes in 3.9.10 though we have no other information yet about such issue.

**Comment by pkubowicz** [comment]
It is not fixed. I experience it all the time and I have version 4.0.5. It never happened a year ago on the same phone.

Route recording works in the background until you manually finish navigation. Then nothing works: just turning off the screen stops recording. This is a ridiculous behaviour. Please fix this.

**Comment by sonora** [comment]
Sounds like the background power saving behavior of newer Android versions, please read and try https://docs.osmand.net/en/main@latest/osmand/troubleshooting/track-recording-issues#the-system-may-kill-background-apps-to-save-power.

**Comment by pkubowicz** [comment]
So why does navigation work fine, and why recording works without interruption as long as navigation is enabled?

For me it's clear that navigation function is more robust and that there is some influence of finishing navigation on recording function.

**Comment by sonora** [comment]
@pkubowicz You are right , that's unclear to me at the moment: Code-wise, both are handed by a "Foreground" service in recent versions of OsmAnd, hence should be entitled to frequent Location updates even under new versions of Android.

Have you verified that in the OsmAnd "Trip recording" plugin's settings you have truly **disabled** "_Prevent standalone logging_" **for all profiles**? (After a navigation the profile used will automatically change from the transport profile you had chosen for the navigation to your default profile, so this could be a source of error...)

**Comment by pkubowicz** [comment]
I have set cycling as my default profile long ago, so that stopping navigation does not suddenly change the view.

I don't use Android 11. I experience the issue on Sony Xperia X Compact (Android 8) and Sony Xperia XA2 (Android 9).

Adding OsmAnd to energy saving exceptions did not immediately solve the problem, but I have to admit that I haven't restarted OsmAnd or the phone after changing this setting. I will test further with the exception.

Still, I also use Strava on both devices, it is not added to any energy saving exceptions, and I haven't experienced any problems with GPX recording there. So it seems it is possible to avoid this problem without forcing user to manually change system settings.

**Comment by gronaix** [comment]
I just recently observed that behavior with Version 4.1.11 on Sony Xperia 1 iii with Android 12 build 61.1.A.2.211 release-keys
Recording stops / crashes when navigation is stopped and app goes into background.
Once it crashed the track recording notification remains visible without actually recording until the app is forcefully closed.
Different to my first report of this issue I can now find the recorded GPX files in the setup folder, but it only covers the track until it crashed.

**Comment by ossilator** [comment]
i have observed that background recording stops when the foreground app crashes, even though the status bar shows the service to be still running. and it crashes a lot, because the device is rather memory-starved at 2 gb ram.

version 3.4.12, on galaxy s5 with lineageos 18.1 (android 11).
