### ISSUE TITLE
Upgrade to the older versions of some resources

### ISSUE THREAD

**Issue by alexandrz** [osmandapp/Osmand#1146]
OsmAnd offers me to upgrade to the older versions of Worldwide and topic maps / attitude correction and Voice packs:

![Screenshot](https://i.imgur.com/Hn54Zg2.png)

**Comment by vshcherb** [comment]
Fixed in 2.0

**Comment by alexandrz** [comment]
No, the bug is still here in 2.0.1 with English TTS voice.

![screenshot](https://i.imgur.com/UCDR6hr.png)
