### ISSUE TITLE
Small bug in gpx color selector

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#11651]
See the following screenshots:

- While in light theme the selected button (here "Solid") has a well visible frame in blue, the 'selected' indication for the actual color is gray.

- In dark theme it is even worse, the circle around the red dot ( selected color) is in practice hardly visible.

![Inkedlight_LI](https://user-images.githubusercontent.com/845735/117802373-b2ffb980-b255-11eb-8cd0-443def8dbe01.jpg) ![Inkeddark_LI](https://user-images.githubusercontent.com/845735/117802379-b430e680-b255-11eb-82c3-054935e9a3df.jpg)

**Comment by sonora** [comment]
Additional remark about the color selection offered: We offer standard palette colors here, like e.g. a standard light blue, which in many map styles is also used for regular map objects light e.g. water areas.

For the GPX overlay it makes sense (and is used by many map styles as their default) to offer translucent **"hgihlighter"** colors which can help gpx tracks stand out from regular map content. Such colors are e.g. (see https://github.com/osmandapp/OsmAnd-resources/blob/e6211ded294b3f0c0daf78f312777f514b572d76/rendering_styles/Touring-view_(more-contrast-and-details).render.xml#L159)
```
			<case currentTrackColor="translucent_red" color="#88ff0000"/>
			<case currentTrackColor="translucent_orange" color="#88ff7200"/>
			<case currentTrackColor="translucent_yellow" color="#88edc300"/>
			<case currentTrackColor="translucent_lightgreen" color="#886cb52b"/>
			<case currentTrackColor="translucent_green" color="#8800842b"/>
			<case currentTrackColor="translucent_lightblue" color="#882ec6ff"/>
			<case currentTrackColor="translucent_blue" color="#884e4eff"/>
			<case currentTrackColor="translucent_purple" color="#88a71de1"/>
```

**Comment by cepprice** [comment]
The first issue is connected to https://github.com/osmandapp/OsmAnd/issues/11572 and was fixed here https://github.com/osmandapp/OsmAnd/pull/12846

**Comment by sonora** [comment]
This is somehow not fixed right, see screenshots taken with 9-28 build below. My track contains no color information and is displayed correctly in the Touring view's default gpx color (transparent cyan).

**Screenshot 1:** Transparent cyan corresponds to the first disk top left, but it is not circled.

![Screenshot_20210928-195553_OsmAnd~](https://user-images.githubusercontent.com/845735/135142445-d40be37e-395b-4aae-adf4-cf02f6e34709.jpg)

The rest of the colors offered is **correctly displayed** from how it is offered in the Touring view renderer XML.

I then downgraded to a build of late August. Then re-ure-upgradedthe same 9-28 build, and now noe dialog looks like this:

![Screenshot_20210928-200829_OsmAnd~](https://user-images.githubusercontent.com/845735/135142918-b76962fe-b388-4362-81ff-62b5b75110ac.jpg)

I think this color selection now is from the default renderer (and is missing Touring view's default color alltogether), but I have not changed anything, renderer ist still set to Touring view, and the track is still correctly displayed in transparent cyan.

Changing back and forth to a build of 9-23 eventually reproduces screenshot 1.

Looks like 2 issues here:
1. - The selected color seems never circled in the dialog if it is the defaiult color of a non-default rendrendereR
2. - The available color choices are not always reliably read from the active renderer.

**Comment by vshcherb** [comment]
We think to delete different possible values from rendering style in order to make consistent with width & simplify UI understanding, so color selection dialog is consistent for all rendering styles.

We still think about:
1. How to configure translucency for designed set of colors
2. To keep "red" exactly the same for all rendering styles or to allow small grade variations (so "red" will be stored as "red" in GPX-style).

**Comment by sonora** [comment]
I meanwhile managed to solve the issue about the colors being offered, it resulted from the renderer files in ressource  branch r4.0 not having been synced with master in many months. I manually updated the respective color lines in both btanches' xml files and the issue is solved. @vshcherb I suggest we should take no further action with regarrdto this.

This reduces this issue to simply the hardly visible circle around the selected color, as reported in the very first post of this thread.

**Comment by vshcherb** [comment]
@sonora we still think to make an action, 
1) we want colors to be provided by program (not by style ) - doesn't make much sense to make style-dependent
2) we need to have better to UI to configure semi-transparent colors and to have 16 colors list

**Comment by sonora** [comment]
But all map colors are style-defined.  😉 Why remove this flexibility for tracks?

**Comment by vshcherb** [comment]
Map-colors yes, but it doesn't make sense to change color when you switch map style. So you can't expect to have Blue track when you said I would like to have Red track. 
For map style, it happens you have different road colors because you didn't specify which color you want to have it. So only default color could be map styled

**Comment by sonora** [comment]
Yes, that's fine, I think: If you use the default color, it is defined by the style. If you select something specific, it can be sticky.

Regarding the "specific" selections, I suggest to use a conventionally recognized, generic pattern, the most prominent of which is the **rainbow**:, and offer all values both opaque and translucent.

Here is how this is implemented this in the Touring view style: (First blob is the default, then the rainbow selection starts with red - orange - yellow- green - blue - violet):

![image](https://user-images.githubusercontent.com/845735/143011853-a091f81f-b34c-49c5-a296-e712fbc8e163.png)
