### ISSUE TITLE
Offline Routing: turn lanes problem with highway=service/track

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#1174]
I noticed a problem, when a turn lane directs to highway:service/track.
I my example, osmand turns the "left" and "through" arrow to green, what is wrong. only "through" is right
Here my screenshot. 
![Uploading Screenshot_2015-04-27-22-18-55.png…]()

it happens here
http://www.openstreetmap.org/?mlat=48.54169&mlon=8.59083#map=18/48.54169/8.59083&layers=N

http://www.openstreetmap.org/?mlat=48.47241&mlon=8.47823#map=18/48.47241/8.47823&layers=N
(screenshot)
Greetings Simon

**Comment by jf-simon** [comment]
![screenshot_2015-04-27-22-18-55](https://cloud.githubusercontent.com/assets/11144987/7446209/7d7bccb8-f1d1-11e4-9327-7ae3220af14a.png)

**Comment by jf-simon** [comment]
May i ask kindly about some news to this issue? I know that Osmand is under heavy development and time is short. :) 
Thanks 
Simon

**Comment by vshcherb** [comment]
Fixed

**Comment by jf-simon** [comment]
Thanks

**Comment by jf-simon** [comment]
i'm sorry, but i still have an issue with turnlines "highway:track".
The issue is fixes with "highway:service" like here http://www.openstreetmap.org/way/391746384#map=19/48.47224/8.47866&layers=D

but not here: http://www.openstreetmap.org/node/1304174150 with "highway:track"

![screenshot_2016-04-19-20-17-16](https://cloud.githubusercontent.com/assets/11144987/14664738/dd71cc00-06cd-11e6-8425-34f57b7ff4ae.png)


Version: 2.4.0 #16497

Greetings Simon

**Comment by jf-simon** [comment]
thanks
