### ISSUE TITLE
Pubic Transport rout crashes OsmAnd sporadically

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#11819]
### Description
This may be related to #10990, but I think it is a little different. Sometimes when selecting a destination, tapping Directions, then selecting Public Transport, OsmAnd just crashes on me (latest nightly) with no exception log created.

### How to reproduce?
It seems to happen frequently but sporadically. I even think that the same start/end combination works at other times. I usually manage to reproduce by just selecting random targets on the map. If it does not happen on the first try, repeat a few times.

### Your Environment
OsmAnd Version:latest nightly
Android/iOS version:10
Device model:Samsung Xcover 4s

**Maps used (online or offline):**   
Feb 2021 maps.

**Comment by vshcherb** [comment]
Well actually it should have been fixed last week with another issue.

**Comment by sonora** [comment]
@vshcherb I know, but I still get this with our nightly of 2021-06-01, that's why I am reporting this now.

**Comment by vshcherb** [comment]
We're still trying to reproduce...

**Comment by sonora** [comment]
I will check a few more devices and also update maps, maybe it is related to a certain map version. But I can reproduce in say 1 out of 3 to 5 tries (countryside locatios, no big cities).

**Comment by sonora** [comment]
Some more information:

1. I think something has changed lately, with a nightly of June 6 I only find this in maybe 1 out of 20 tries, before it had been  much more frequently.

2. The issue is not destination dependent. Trying the very same destination (and transport mode) subseqruently works perfectly ok.

3. I believe that the issue occurs primarily (or solely) when you have selected a destination, then tapped 'Directions' (our base setup starts a car navigation by default), and **then pretty quickly you tap another transport mode icon**.

4. The issue occurs NOT only by changing to the PT transport, but also e.g. by changing to pedestrian.

It seems to me the crash is caused by changing the means of transport early in an already ongoing routte calculation, and this seems independent of which transport you try to change to.
