### ISSUE TITLE
Missing "Hamburg" and "Saarland" in map sources

### ISSUE THREAD

**Issue by Ausdemwald** [osmandapp/OsmAnd#11854]
Hello everyone,
since there was an update, which made it very easy to dowload all regions of Germany with one click, I miss regions "Hamburg" and "Saarland". Both are searchable and downloadable but can't see them in tab "all downloads".
I use OSMAnd+ on Android 10 with /e/ on Gigaset GS290.
Thank you so much for the best all in one navigation app.

**Comment by vshcherb** [comment]
Fixed in 4.0 (nightlies available) - will be released soon.

**Comment by scaidermern** [comment]
Sounds like #11642.

**Comment by anastasiia936** [comment]
Berlin is still not added to the bulk download. Checked in the last build (30.06.2021)
![image](https://user-images.githubusercontent.com/80623554/124111346-dbe04600-da71-11eb-8e19-9063a170af23.png)

**Comment by scaidermern** [comment]
> Berlin is still not added to the bulk download. Checked in the last build (30.06.2021)

It is contained in the list, but only until you hit refresh. After refresh, Berlin is missing. This is the same bug as explained in #11642.

**Comment by vshcherb** [comment]
Berlin is part of Baden-.. download, so it's correctly not displayed here

**Comment by scaidermern** [comment]
> Berlin is part of Baden-.. download, so it's correctly not displayed here

Berlin is a city _and_ a state, like Bremen and Hamburg.

**Comment by vshcherb** [comment]
Probably a place to open a separate issue but in OsmAnd  Brandenburg contains Berlin
