### ISSUE TITLE
POI control UI is unintuitive

### ISSUE THREAD

**Issue by crosser** [osmandapp/Osmand#1224]
This is a feature request.

In the current UI that controlls the POI layer, it is quite un-obvious how to enable a certain set of POIs (e.g. "Sightseeing" + "Wikipedia"). It is difficult to disable the whole POI layer (you miss the tiny checkmark box and the menu is opened instead). It is difficult (impossible?) to disable some POIs keeping the others.

It would be easier to understand if the POI entry of the layers menu did not have checkmark at all, but instead opened a new scrollable menu with POI sets, with checkmark box in every line. This menu could also have special buttons for "select all" and "unselect all".

**Comment by ddarwish** [comment]
Please, return "display all" special filter to POI menu. This was extremely useful for mapping new POI.

**Comment by sonora** [comment]
Yes, for mapping purposes "Display all" is quite usefule, I agree. Please note that you can simply get it via Search POI, then tap the 3 dots next to the search filter, select custom filter, then "Select all". You can also save this custom filter as e.g. "_Display all", so it will alsways appear in the first position on your device.  Making this an always visible filter for the general users should be quite useless and distracting, though ....

Regarding the request to have "Unselect all": Yes, I think this is mandatory for us to implement. It is a bad UI if you cannot "un-"do things in the very same fashion you did them ...

**Comment by poidi** [comment]
I disagree that the "All" filter is useless for most of the people.

Here's why:
if to find i.e. the neares McDonalds without an "All" filter i have to select "Food" it is not found in "Cafe and restaurants" - although it is a fast food restaurant.

i'm sure there are more examples, where the user knows already what to search - but has to know what category is the right one.

In the previous versions you could always search the nearest POIs and then filter by name - for that, now you have to create an aditional filter "All".

Or am i missing some feature?

**Comment by vshcherb** [comment]
You can certainly type "McDo" and search or type "Food" or even "Fast food". Using filter All has more technical issues dealing with large volume of POI's

**Comment by poidi** [comment]
if i do that, there are 2 issues:
 - i have to know if its ist MacDonald or McDonald - cause Donald is not found
- it takes quite some time, until there are results - the All-Filter and a filter after hat is a lot faster than that

**Comment by vshcherb** [comment]
Some of the issues with select/unselect all are already fixed

**Comment by homersimpsons** [comment]
Maybe this issue could be closed?

**Comment by crosser** [comment]
As of 2.2.4, it is still impossible to tell what POI classes are selected, and to unselect them individually.

**Comment by vshcherb** [comment]
Yes it is fixed in master but not in r2.3 (not there is a multiselection available on poi layer).

**Comment by crosser** [comment]
The problem still exists as of 2.3.5.
(Impossible to see which categories are enabled, impossible to disable individual categories of POI.)
Reopen?

**Comment by vshcherb** [comment]
Yes the problem is in 2.3.5 but not in the master. Please try nightly http://download.osmand.net/latest-night-build/OsmAnd-default.apk
