### ISSUE TITLE
"starting point too far from nearest road"

### ISSUE THREAD

**Issue by bluescreen303** [osmandapp/Osmand#1226]
I'm getting this error message whenever I try to use offline navigation.
I deleted and re-downloaded all my maps and favorites, but that did not help.
I bisected through older versions (http://download.osmand.net/night-builds/) and found the problem got introduced in 2015-04-15 (2015-04-14 is doing fine). This is true both for the normal version as for the qt version.

The map I use is the Netherlands. I'm on cyanogenmod 11 (android 4.4.4) on flo (nexus 7 2013).

**Comment by janvlug** [comment]
I confirm this issue. Both on my Android phone (BQ Aquaris 3.5), and Nexus tablet with Android 5.1.
I also use the map in the Netherlands. Might this be related to the fact that the maps for the Netherlands are now split in separate maps for each province?
I'm using OsmAnd+.

**Comment by hlinden** [comment]
Same here, when trying to navigate from a town in Baden-Würtenberg to an address in Nordrhein-Westfalen, both Germany, last monday, with the OSMand+ version that was current then and up to date maps, stored on the external SD-card.

**Comment by bluescreen303** [comment]
The map cannot be the problem, because the april 14 nightly handles it just
fine.

**Comment by jfburke3** [comment]
I also get this (sometimes it's ending point instead of starting point).

I'm in the U.S., so it's not the Netherlands map. 

I will note that it has happened to me on several long-distance trips that cross state borders, which means multiple map files. I'll try to test some route generations that are long but stay within a state and see if that makes a difference.

**Comment by jfburke3** [comment]
Janvlug, you might be on to something. I just tried a test route from a random location in Miami, Florida to another random location in Tallahassee, Florida, and did not get the error. The generated route was 480 miles and used only the Florida map. 

I got the error every time with the trips I made that crossed state lines.

**Comment by bluescreen303** [comment]
@jfburke3 please try the 2015-04-14 nightly with the same maps to confirm the maps are fine for inter-state/inter-province routing. I'm not saying the issue is not related to this, just that the older versions handle interstate just fine with the same maps.

**Comment by vshcherb** [comment]
I'm using the Netherlands map too and it does work.
>> I deleted and re-downloaded all my maps and favorites, but that did not help.
If you are using different builds it will be better to try full reinstall, it might be related to the native libraries which are not installed correctly.

**Comment by sonora** [comment]
I had tested this extensively recently both in Europe and in the US, and cannot reproduce this at all. I do seem to get correct routes across map borders, consistently. My latest build tested is of yesterday, my maps, however, are (all) from early April. I had seen a similar issue earlier and suggest people who can reproduce this de-activate 1 or 2 of their larger maps (some not needed for the route, obviously ... :-) ), because I had seen funny things when too many maps (>5-10 GB worth of vector maps) are active, so it could be a memory-related issue.  Best, Hardy

**Comment by EmPeWe** [comment]
I can confirm this bug.

It only appears, if you have road-only vector maps enabled. All my germany vector maps were outdated, but this is not causing the problem. These maps are not "large" and de-activating will not solve anything. My tests failed, so it's no memory-related problem

You can reproduce this yourself with e.g. germany - bavarian maps. Download both, the full and road-only up-to-date versions. Disable full and enable road-only will fail offline routing. Switch the two maps by enabling full maps and disabling road-only and the offline routing works again.

**Comment by vshcherb** [comment]
Road only maps were just fixed and we are thinking to create a patch release... So it is better to assume now that for short period of time release version doesn't support roads-only maps.

**Comment by jfburke3** [comment]
I don't think it has anything to do with roads-only maps, mainly because I've never downloaded one but still have the problem.

**Comment by hlinden** [comment]
I have neither used road-only maps.

**Comment by jfburke3** [comment]
@bluescreen303 I have been too busy this weekend to try that build, but will have time this week to do it. 

Anothet pdate: I'm preparing for my return trip from Florida,  and  uninstalled the 2.0.4 release, then installed nightly build Osmsndf~ 2.1.0 #7351D from the osmand.net website, keeping my same map files.  With only my start and end points, I kept getting the error ending point too far....  The route is almost entirely a single Interstate highway from one state to the neighboring state,  in as straight of a line as they can get.  I then added two waypoints on the interstate, each about 15 or so on either side of the state borders, but both are well over 200 miles  (not kilometers) from my start and end points. This nightly build created the route flawlessly. 

I will note that I used the 2.0.4 release build all weekend for routes of various lengths within a single state, including over a hundred miles for one, and it performed well.

**Comment by janvlug** [comment]
I have this issue as well, but I've never intentionally downloaded road only maps (actually, I have now idea how to do this, they are not in my 'all downloads' if I am not mistaken).

**Comment by utack** [comment]
Happens constantly with the "normal" maps in Germany. It bascially broke my navigation, would be great to have a fix.

**Comment by janvlug** [comment]
@vshcherb: I'm a bit surprised that this issue is closed, there are several persons (including me) stating in this issue that the problem is not road map only related. I confirm @utack's statement that navigation is basically broken for me with the latest version of Osmand. I consider this as a critical issue.

**Comment by jfburke3** [comment]
@janvlug, there's another github thread on it, so maybe he's working from that. 

I do see an improvement in the latest nightly builds. Still get the error, but now it generates routes even with it.

**Comment by vshcherb** [comment]
Hi All, recently I managed to see that error. Actually it happened on 1 device by upgrading from 1.8 to 2.0. The biggest issue we can't that issue on more > 10 different devices (OS,...). Of course if we can't reproduce the case, we can't do anything. It is impossible to fix the issue as blind. 
Coming back to the test I saw. Unfortunately I immediately started upgrade of the maps, for me that sounds very strange, but after I downloaded new world map and tried different routes from different start/end point, the issue was gone. I didn't manage to see it anymore. 
So, it sounds harsh but I suggest 2 actions: 1) update map with routing (or disable very old maps) - update base world map 2) give specific lat/lon start and end where it happens.

It is clearly a serious issue in individual cases , but until it won't be reproducible at least on 5% devices, so we can't catch it, there will be no action about it.

**Comment by janvlug** [comment]
1. All my maps are up-to-date.
2. 52.00029/4.33806
I have this issue on all three devices on which I installed v2.0.4

**Comment by vshcherb** [comment]
Just tested with these location, but it works and actually I know at least 3 devices in NL that worked and works, on the other hand it could be the issue of recently split maps for NL

**Comment by bluescreen303** [comment]
No. As stated, older osmand works fine with these new (split) maps. Also,
navigation in germany became totally broken, while germany had split maps
for a long time. Austria seemed to work fine oddly enough.

I must say that current nightlies seem to work ok for me after a full
uninstall/reinstall, but i can't speak for others in this thread

**Comment by vshcherb** [comment]
That what I experienced as well, once at least 1 route gets successful, all other routes starts to work.

**Comment by feichelmann** [comment]
I have this same issue. I'm using a Nexus 4, Android version 4.4.2, Cyanogenmod 11, Osmand 2.0.4-207. My region is Ontario, Canada.

I don't know if this is important but I have both offline tile maps and offline vector maps for the same location. All my apps are blocked from using the internet so Osmand has never downloaded a tile or been online for any reason.

However, I found that the problem only happens when I have the online maps plugin disabled. As soon as I enable the plugin, the directions work. I will reiterate and mention that internet connection is irrelevant here. Only whether the plugin is enabled or disabled is relevant.

**Comment by vshcherb** [comment]
Thanks to all feedback, main reason of the issue was found. Indeed it was required to use Offline Maps to calculate route! 
The symptoms: if the start/end or any intermediate point was from Region that was never displayed on the Offline map, that map wasn't initialized and not used for routing. 
The issue is fixed and it will be hotfix release 2.0.5 next week. Please test it.

**Comment by jfburke3** [comment]
I'll add a note here that I have not encountered the error in several of the nightly builds that have been released since Victor's "fixed" comment, so it really does seem to be working properly now.  (I haven't seen a fresh Play store release that includes the fix, though.)

**Comment by jfburke3** [comment]
Just to further add to this:  yep, looks like you got it.  The 2.1 Play store release is working fine, too.

**Comment by janvlug** [comment]
I also confirm that this issue is fixed in version 2.1.1 on all my devices .

**Comment by hlinden** [comment]
Same here. Navigation through half of Germany across several map borders works fine now.

**Comment by jfburke3** [comment]
@vshcherb I think you can close this issue now.  I haven't encountered the error in a very long time :+1:

**Comment by apaijmans** [comment]
I am using osmand+ since about half a year. Unfortunatly I encountered this error twice already. Both times I was on the road in Germany, turned on osmand+ and got this error when I tried to navigate to my destination. In both cases I was outside the area for which I have downloaded offline maps (and also my destination was outside the offline map area). My 4G and location/gps were both on, but I did not want to download the offline map at that time because of data roaming costs. I am using a Fairphone 2, android 6.0.1. and osmand+ is updated.

**Comment by mihawk90** [comment]
The error is still current, in fact I haven't been able to navigate for half a year at least (only tried it occasionally though). It's a route inside the city, while standing on a street using the current position as starting point and I'm "too far from nearest road".

Using Scout (formerly Skobbler) with the same route works perfectly fine (even across several States and countries), do it is not the map material.

I have not downloaded any maps though, I'm using it purely with online maps.
