### ISSUE TITLE
POI is not rendered correctly in motorbike profile

### ISSUE THREAD

**Issue by thuryn** [osmandapp/OsmAnd#12395]
### Description
I have profile for car and motorbike. Both profiles have set POI for petrol stations. When I switch to car or motorbike profile by hand POIs are correctly displayed. When I start navigation by car POIs are correctly displayed also. When I start navigation by motorbike POIs are displayed as small points (not correct).
OK (navigation by car):
![Screenshot_2021-08-05-21-16-27-179_net osmand plus](https://user-images.githubusercontent.com/11028346/128411386-d26468e9-4450-4b44-97ba-8ae6c821c6b3.jpg)
 
Wrong (navigation by motorbike):
![Screenshot_2021-08-05-21-36-25-983_net osmand plus](https://user-images.githubusercontent.com/11028346/128411534-73c04144-fd3f-451d-b625-ff765f248521.jpg)

### How to reproduce?
Try to navigate by motorbike profile.

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 11
Device model: Xiaomi Mi 9

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

I use offline maps.

**Comment by vshcherb** [comment]
Please test 4.0, should be released today. This issue should be fixed

**Comment by thuryn** [comment]
Tested on 4.0.4 version updated today and the problem still exists.

**Comment by vshcherb** [comment]
OK, I've got it. It's a feature, you use show poi along the roads, in case POI is too far it is displayed as small circle. You can either just display all POI as a layer or increase the radius

**Comment by thuryn** [comment]
I see, I can see it also. It works now as expected. I was thinking that it would be great to be notified about petrol station along my road - so not just 100m around, but along the routed way (and in routed direction). But this is another story. Thank you for you help.
