### ISSUE TITLE
Map goes blank during navigation

### ISSUE THREAD

**Issue by dbolton** [osmandapp/Osmand#1245]
I tested OsmAnd twice today. During both trips the map went blank part way through the trip. Navigation instructions and announcements continued to work, but I couldn't see a map. 

Is there any way I can help diagnose this problem? 

OsmAnd 2.0.4, Android 4.4.2

**Comment by sonora** [comment]
Do you still see the ruler (map scale indicator bar) near the bottom of the screen, when the "map goes blank"?

I have met a number of users at times who had an issue which sounds similar to yours, and it turned out that when it occurred, their map was simply zoomed in extremely far (like the ruler showed only 2 meters or so), creating an overall gray map image due to the large magnification. I never found out what caused the issue for them, if it is a bug in our code, or simply them repeatedly touching the zoom+ button accidentally, or similar.

**Comment by dbolton** [comment]
Sonora, thank you for the reply. I actually checked for that at the time. The zoom level was 500 feet (same as it had been). When I zoomed out to 2000 feet the map still didn't show up.

**Comment by sonora** [comment]
Ok, thanks, then this is not the issue it reminded me of.

I test OsmAnd on many devices and under many circumstances, and it looks like we are in for a full debugging then. All details you can provide here how to reproduce would be helpful, like which map exactly are you using (assuming you use OsmAnd's offline maps and OsmAnd's offline navigation service), on what device, how many other OsmAnd maps are present on your device. Are you travelling near a state or country border, and maybe are missing the map of the neighboring state/country? Is the issue 100% reproducible, or sporadic? If reproducible, could you provide the route start and end point, so we could try to reproduce in a simulation? Etc.

**Comment by skquinn** [comment]
This happened frequently when I was using OsmAnd+ to follow along on a trip from Houston to Dallas. Restarting OsmAnd+ fixed it, though I admit this is a crude workaround.

**Comment by alexey-pelykh** [comment]
It went black blank or beige blank? Or, maybe there's a chance you've taken a screenshot? Maybe some toast (a message in the bottom of the screen) appeared?

**Comment by alexey-pelykh** [comment]
And what device do you use

**Comment by stefanb** [comment]
Same happened to me on Nexus 4, with Android 5.1. Instructions continued, but screen went gray (neither map, nor route ahead (normally purple) was visible anymore). Restarting the app helped.

**Comment by billcnh** [comment]
I installed the App for the first time yesterday off Google play, and on a two hour trip today this problem occurred at least twice maybe three times. The map goes to a blank gray. I was moving the screen with finger gestures at the time, my map was rendering a route navigation actively tracking at the time. I had to cancel the app and re-start the app and re-enter the trip , start from current , and the destination address. I was in the state of massachusetts,usa. Android version 4.1.1 on a samsung galaxy tab, In OFFLINE Mode. I am a software engineer and for me its a bad bug on my device, hope the developers  know how to reproduce it on their hardware devices and have the chance to solve it. My best to the developer, because I love this application and hope to use it more often.

**Comment by dbolton** [comment]
I finally had time to experiment today with the debug plugin. 

The map goes blank whenever the screen changes orientation.

**Comment by dbolton** [comment]
Attached is a requested screen shot. (This one was at night/dark theme)

![screenshot_2015-05-25-00-28-14](https://cloud.githubusercontent.com/assets/712270/7792312/03a91c28-0276-11e5-9659-a9f13b628b51.png)

**Comment by sonora** [comment]
If this is related to map (or screen?) re-orientation, then it looks like it is identical with issue #1187 ... (?)

**Comment by alexey-pelykh** [comment]
So far I can not reproduce it

**Comment by dbolton** [comment]
It is 100 percent reproducible for me. It's there a way to factory reset osmand to see if a particular setting is causing the issue? 

How can I help diagnose this further? 

(Using Alcatel one touch 4037T)

**Comment by alexey-pelykh** [comment]
What does app do if you try to rotate device again? Or e.g. cancel navigation?

**Comment by dbolton** [comment]
The map stays blank after rotating device again or cancelling navigation.

After exiting OsmAnd and restarting the app, the default map view shows the world map as shown in the screenshot attached. I have the following maps installed as offline maps: United States of America Iowa, United States of America Kansas, United States of America Missouri, and World Overview Map. 

![screenshot_2015-05-26-10-11-19](https://cloud.githubusercontent.com/assets/712270/7815912/e6791aba-0390-11e5-84ca-1cf36453a6ab.png)

**Comment by jirislaby** [comment]
This happens to me too. I have Samsung s4 mini. I have never seen this with < 2.0 version. This started happening only after the update to 2.0 and later for me.

I hit it yesterday again. The ruler showed 2000 km (i.e. the map is fully zoomed out), the screen was rotated (from landscape which I use for navigation to portrait). The rotation was caused by some shaking during driving, I suppose. I was travelling from Konice castle to Santovka in Olomouc.

It is not sufficient to rotate back, zoom in, restart navigation or whatever. I have to stop the navigation, close osmand, kill all apps (erase RAM) and restart osmand.

I have 3 offline maps: czech republic, slovakia and world. This happens to me when travelling only in the Czech republic. I haven't tried cross-borders.

**Comment by jirislaby** [comment]
Ok, so I can simulate using the debug plugin. I enabled map drawing statistics to be shown. Until this bug happens, it shows some numbers. Afterwards, it does not even show with zeros or something.

When the navigation runs, it consumes ~ 0-1 % of CPUs. When the bug occurs, I have ~ 50 % CPU load. So it seems to loop infinitely somewhere. Is there a way to generate a backtrace?

**Comment by vshcherb** [comment]
You can only connect with Debug mode and put a breakpoint somewhere or put pause on all threads it is available in Eclipse / Idea/ Android Studio... You don't need to have sources or compiled code

**Comment by jirislaby** [comment]
Hmm, too complicated for me. Could you add a button to the debug plugin which would do Thread.getAllStackTraces() (or similar) to a file in the osmand dir instead?

**Comment by vshcherb** [comment]
At one moment I saw a map blank, but after I clicked zoom in it gets refreshed and continued functioning as usual.

**Comment by sonora** [comment]
I still cannot reproduce here. So if this is strictly caused by dcreen rotation, am I correct assuming that the issue is 100% avoided by preventing screen orientation changes via the Android (display) system settings, right? But what if you leave orientation change allowed there and instead in OsmAnd's General settings change the setting for the screen orientation from the default "Same as device" to to a static portrait or landscape, will this also prevent the issue?

**Comment by jirislaby** [comment]
@sonora: yes and yes. If I disable either of those two, it never occurs.

**Comment by fabeuw** [comment]
I have screen orientation off, and tried different settings in the app, but I still get this error message. I am on OSMand+ and 4.3. I like this app but if there is no solution to this I have to find an alternative.

**Comment by vshcherb** [comment]
Recently we've discovered ui memory leak for screen rotation and we fixed it, we also lowered map density by default, so it should occupy less memory. Also we  It is available in nightlies and it could be related to many not easy reproducible issues.

How to test & reproduce: using development plugin it is possible to see how much memory OsmAnd occupies, after rotation that memory was growing very quickly. After 5-10 rotations it could eat the whole memory.

**Comment by sonora** [comment]
Sounds like there are 2 issues here which should be debugged separately:
- Memory leak is one thing (seems fixed now, btw, thanks!)
- But tweaking map density sounds like something which deserves separate observation, as it is unclear if this caused an issue at all, and if yes, if this is an issue on all or only some low end devices?

**Comment by dbolton** [comment]
I'm still able to reproduce the original bug using the latest nightly build (2.1.0#7905D).

**Comment by chrisgarstin** [comment]
Same issue,  grey screen, sometime locks the phone.  Zoom in/out,  or kill app and restart does not fix.  Seems that I have to restart the phone.

**Comment by JanWielemaker** [comment]
I have the same issue on a Sony Z1 compact, Android 5.1.1.  I have some info that I've not seen here before.  I use it on my bicycle, where it is charged from the dynamo.  The problem doesn't happen if I simply run on battery.  It happens when it switches between charging and not.  The issue already happens a couple of years.

**Comment by sonora** [comment]
No recent reports, I guess this is deprecated.

**Comment by jirislaby** [comment]
Yeah, I didn't encounter this in the latest versions.

**Comment by lfom** [comment]
Unfortunately I usually get a blank map on startup using a small MIPS devices, screen (320x300 pixels, density 238). Going to app Settings and changing screen orientation, forcing the screen to be redraw, fixes it. If you need further info, please drop me a line. Thanks.
