### ISSUE TITLE
Option for disabling or shortening "prepare to..." voice prompts

### ISSUE THREAD

**Issue by Zero3** [osmandapp/OsmAnd#12482]
# 🚀 feature request

### Description

I find OsmAnd voice navigation to be excessively chatty. I disabled most of the stuff already, but one particular annoyance that I cannot find a way to disable is the "prepare to ..." voice promts that tell you about some action X km into the future. I find that these promts are mostly useless and annoying when driving on highways in Denmark, and particularly prone to interrupting conversations with passengers that just started/continued after a turn in an intersection or after a roundabout.

The only case in which I would find a long "prepare to ..." voice promt about something X km into the future useful, would be on motorways, where it can sometimes take a bit of time to get to the right lane.

### Describe the solution you'd like

Suggestions:

1) Make it possible to disable these promts (perhaps except when driving very fast on a road with multiple lanes).

2) Reduce the length of these promts to just "Continue X km". The full length version, ala "in X meters, enter the roundabout, and take the third exit" will come up twice just before the action anyway. Knowing the full details X km in advance is not necessary.

**Comment by sonora** [comment]
This seems the same discussion as in #10150, and the same solution would apply, for whatever language you have in mind.

So if you can make a concrete suggestion which prompts in what language you want shortened to what wording, or even omitted entirely, someone (even me as time  permits) could take a look and decide if we could alter the original announcements file for that language (if it seems it was overly chatty compared to the other language files), or if we should offer an alternative, abbreviated version for tgat language in addition to the one offered now.

So far for German it seems there was no clear community opinion prefeerring one over the other, hence ever since we offer the 2 different alternative versions of German voice prompts.

**Comment by Zero3** [comment]
@sonora Thanks. I replaced the content of my existing `da_tts.js` with the content of the version you provided. I will test it for a while, and let you know what I think.

Regarding a compromise: If the "prepare" announcements simply said "Continue for X meter/kilometer" (in Danish: "Fortsæt X meter/kilometer"), I think they would be acceptable. In that way, we keep the (in my opinion) only useful information (which is to do nothing for X distance), while removing the unnecessary information (what to do after the X distance, which is mostly useless information when said this early) in order to keep the announcement very short.

**Comment by sonora** [comment]
Here is the logic if and when we trigger the audio prompts: https://docs.osmand.net/en/main@latest/development/algorithms/voice-prompt-triggering

The ones in table "Trigger behavior" labeled _"Prepare to turn in X m"_ at 115 seconds out are primarily spaced so that you can watch out for highway signage announcing the correct intersection or exit, so you can be sure how the turn will be signed and recognized in ground truth.

If you mean these by what you call "prepare", I would hate to leave out the turn info per se, as you will likely want to know if turning left or right at that point. My thinking was more that in the Danish file you seem to have wording like "_Forbered_" (prepare...) in place (other language files have not), which may be highly repetitive and obsolete. I would expect simply announcing the type of turn and its distance in the fashion "_After 1 km turn left_" is short and useful?

**Comment by Zero3** [comment]
@sonora I tried to read and understand that table, but I must admit that I find the logic and math somewhat confusing.

I agree that when driving fast on roads with a lot of lanes (in Denmark that would mostly be motorways, and a few larger highways), it makes sense to announce the turn around 115 seconds prior, and to include the direction of a turn, to assist in any necessary lane change. But almost all highways in Denmark have 1-2 lanes in each direction, making most of the "prepare" announcements quite irrelevant (in my humble opinion).

I also agree that removing the word "forbered" (prepare) would be a slight improvement. But the announcements remain annoying in the "boring highway" case, where I would like to get rid of them, or shorten them even more. But yes, it would be great to keep them for the "high speed multi lane" case.

**Comment by Zero3** [comment]
@sonora Feedback: I have been using your modified `da_tts.js` file for a while now, and I think it is a really nice improvement.

**Comment by Zero3** [comment]
@sonora I see you just closed this issue. Was it fixed? Did you remove the "prepare" announcements?

**Comment by sonora** [comment]
I just went through some old voice related issues, and for this one here interpreted your reply https://github.com/osmandapp/OsmAnd/issues/12482#issuecomment-920907416 as this being solved, and noone else had logged any complaint or additional suggestion in over 1 year?

**Comment by sonora** [comment]
PS: I have committed this, see if it is ok: https://github.com/osmandapp/OsmAnd-resources/commit/a7846ce2f49f5d8a8e06d05796b39aa8ae6729d3.

**Comment by sonora** [comment]
PS2: If you want, you could make a pull request for a "da-casual" with short and more casual wording, similar how it was done for German, compare https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/de-casual/de-casual_tts.js vs. https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/de/de_tts.js

**Comment by Zero3** [comment]
> PS: I have committed this, see if it is ok: https://github.com/osmandapp/OsmAnd-resources/commit/a7846ce2f49f5d8a8e06d05796b39aa8ae6729d3.

Yes, that is a slight improvement, as discussed above. I think you forgot to shorten the `prepare_roundabout` function in this commit though.

> PS2: If you want, you could make a pull request for a "da-casual" with short and more casual wording, similar how it was done for German

Alright. If such an addition is welcome, I might make it if/when I get the time. That was what this feature request was all about in the first place though, so I am a bit sad to see it closed without a solution ready.

**Comment by sonora** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/5a3866ad345155645bbaff78ac1f223c8f847b81
