### ISSUE TITLE
Samsung Galaxy phones' menu key doesn't work

### ISSUE THREAD

**Issue by enomat** [osmandapp/Osmand#1274]
I have a Samsung Galaxy S2 (I9100). The phone has a menu key in the bottom-left corner. It used to open the menu, but since the new Osmand UI, it no longer opens the menu.

(I can't try other Samsung phones, but I'm sure it's a general bug in the Osmand UI which affects them too.)

**Comment by vshcherb** [comment]
It should open dashboard now, when you press it on the map screen

**Comment by enomat** [comment]
I have 2.0.4 version and that key doesn't open anything.

**Comment by sonora** [comment]
Seems not device-specific, I can confirm this on all devices I have tried today, we must have somehow lost this functionality in our final versions before the last release ....

**Comment by vshcherb** [comment]
Looks like bad luck for us https://code.google.com/p/android/issues/detail?id=159795
We need to update app compat

**Comment by vshcherb** [comment]
Fixed

**Comment by enomat** [comment]
@vshcherb 
With the changes in the menu and UI, this bug came back again.

**Comment by sonora** [comment]
Yes, confirmed. I had observed when this happened and had created a comment in github on the verv commit (or very near) which caused this, must have been in September time frame.

**Comment by vshcherb** [comment]
Fixed

**Comment by sonora** [comment]
Unfortunately, this did not fix it - no change on a Samsung Galaxy S4mini.

**Comment by vshcherb** [comment]
Are you sure? How did it work before then (September build), I think reverted the code to the original state and made it more generic.

**Comment by Zahnstocher** [comment]
I can confirm that it does not work on a Samsung device (it worked several month ago).

**Comment by Zahnstocher** [comment]
I did some tests on a Samsung device:
dispatchKeyEvent, onKeyUp and onKeyDown are never called for KEYCODE_MENU.

Which AppCompat v7 version is currently used in OsmAnd?

**Comment by vshcherb** [comment]
To be honest I forgot https://github.com/osmandapp/Osmand/blob/master/eclipse-compile/appcompat/build.gradle. It is possibly 22, however now 23.0.1 is out http://developer.android.com/intl/ru/tools/support-library/index.html

**Comment by vshcherb** [comment]
23 version requires java 6 and compileSDKVersion 23 which causes to remove httpserver. We were going to do it anyway, but it is a task after.
Strange enough I don't remember updates in September of support library

**Comment by Zahnstocher** [comment]
> It is possibly 22

I compared sha1 sums, it is 22.2.1:
> 60d9ac18cb076738881c397f0d972fb207d90737  ./eclipse-compile/appcompat/libs/android-support-v7-appcompat.jar
> 60d9ac18cb076738881c397f0d972fb207d90737  ./support_r22.2.1/v7/appcompat/libs/android-support-v7-appcompat.jar

Thus it is one of the broken versions (KEYCODE_MENU bug).

**Comment by Zahnstocher** [comment]
By the way, https://github.com/osmandapp/Osmand/tree/master/android/ contains only old source code and is not used.
Also https://github.com/osmandapp/Osmand/tree/master/recyclerview/ seems to be unused.
Probably both can be removed.

**Comment by Zahnstocher** [comment]
> 23 version requires java 6 and compileSDKVersion 23 which causes to remove httpserver. We were going to do it anyway, but it is a task after.

In the meantime it would be possible to use legacy Apache HTTP (which was added in 23):
platforms/android-23/optional/org.apache.http.legacy.jar

**Comment by Zahnstocher** [comment]
There is a pull request, which solves the legacy Apache HTTP problem:
https://github.com/osmandapp/Osmand/pull/1915

**Comment by Zahnstocher** [comment]
I can confirm the fix (update of Android Support Libraries to 23.1.1):
https://github.com/osmandapp/Osmand/commit/641f150d98533df2ea9ce9ca3b259f1160e05955
Menu key is working now.

**Comment by sonora** [comment]
Well, we reverted that commit (and rightly so, I think Multi-Dex is an issue we should try to avoid ...). Let's jus do a 23 upgrade for now.

**Comment by vshcherb** [comment]
Commit reverted as dangerous, it affects targetSdkVersion and there were crashes on Android M devices

**Comment by vshcherb** [comment]
Commit pushed to master and should appear in nightlies

**Comment by sonora** [comment]
This commit, right?
https://github.com/osmandapp/Osmand/commit/0fe8b3aefddc0cc352d6a7dbaeffa9b4b52cd917

Still does not fix the Samsung menu key issue, it seems ...

**Comment by vshcherb** [comment]
It should...

**Comment by sonora** [comment]
I know - weird. Does not work on current master build #14559M, downloaded just now

**Comment by Zahnstocher** [comment]
> It should...

It can't work, because you did not update AppCompat, it is still 22.2.1.
android-support-multidex.jar only adds Multidex support, but it does not update AppCompat.

**Comment by vshcherb** [comment]
You are completely right android-support library update was lost in the branch somehow.

**Comment by GaidamakUA** [comment]
Support library has been returned. Please try again.

**Comment by Zahnstocher** [comment]
It is working on my phone.
But I had to build OsmAnd myself, because the server can't build, there is a problem with validateTranslate (build.gradle).

**Comment by sonora** [comment]
Confirmed working now on all Samsung phones and tabs I have tried.

Build failed due to wrong path in build.gradle, Victor fixed this already.

I now see the occasional NPE I did not seem to observe with previous builds, but I am not sure this is related to this upgrade.
[exception.txt](https://github.com/osmandapp/Osmand/files/45575/exception.txt)

**Comment by vshcherb** [comment]
Create a new issue for NPE
