### ISSUE TITLE
Yellow arrows are glitching over the screen

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1337]
Hi,

While navigating, OsmAnd spordically draws the white arrows that indicate the next turn over the screen.
This seems to be sporadic and depending on map position, rotation and zoom level.

Found with OsmAndF~2.1.0#7464D.

**Comment by Norbert80** [comment]
@vshcherb below you find some screen shots.

![screenshot_2015-05-29-18-08-12](https://cloud.githubusercontent.com/assets/6921696/8116759/458286c2-1084-11e5-8b30-15e0add386bb.png)
![screenshot_2015-06-03-14-12-17](https://cloud.githubusercontent.com/assets/6921696/8116762/47e01560-1084-11e5-815e-1e104b75acef.png)
![screenshot_2015-06-03-14-12-45](https://cloud.githubusercontent.com/assets/6921696/8116765/47ff03d0-1084-11e5-8ca2-d63c604a2f2c.png)
![screenshot_2015-06-03-14-15-02](https://cloud.githubusercontent.com/assets/6921696/8116760/46b8f9f4-1084-11e5-9166-e1d7d974ab2c.png)
![screenshot_2015-06-03-15-49-23](https://cloud.githubusercontent.com/assets/6921696/8116766/4826b010-1084-11e5-8296-b9624aeef20d.png)

**Comment by jf-simon** [comment]
I noticed this too

**Comment by Norbert80** [comment]
With OsmAndF~2.1.0#7731D I noticed that the arrow color has changed from white to yellow. But the problem still exists.

**Comment by vshcherb** [comment]
It is not reproducible with attached screenshots. Tested with first and this location around

**Comment by Norbert80** [comment]
![screenshot_2015-06-16-16-42-37](https://cloud.githubusercontent.com/assets/6921696/8192529/198c5482-146f-11e5-9cac-36c876a33b9a.png)

@vshcherb strange. I still can reproduce it with OsmAndF~2.1.0#7792D (screen shot above). This time I had tested with OpenGL rendering disabled because I hoped that a bad implementation of OpenGL in my device's firmware could be the reason, but no... :-(

I'm using a Samsung Galaxy S3 (GT-I9300).

@jf-simon on what device type do you experience this bug?

**Comment by Norbert80** [comment]
@vshcherb could you provide a special debug build that generates some logs of the arrow related variables?

**Comment by Norbert80** [comment]
![screenshot_2015-06-17-16-53-19](https://cloud.githubusercontent.com/assets/6921696/8217364/4345a43a-153d-11e5-8fd2-199181295712.png)
![screenshot_2015-06-17-16-56-16](https://cloud.githubusercontent.com/assets/6921696/8217365/434856f8-153d-11e5-91ca-c6cdaac32d3a.png)

@vshcherb these screen shots above are taken with OsmAnd+ 2.1 final release (from Google Play Store). They show graphic problems with my Samsung Galaxy S3 (GT-I9300) device which I encounter rather rare. Arrow glitches happen more often. Are these graphic problems known? Could they be related (common root cause) with the arrow glitches?

**Comment by Norbert80** [comment]
@sonora from issue #1366 we now know, that this also happens on
Motorola Moto E 2nd Gen 4G
devices.

**Comment by jf-simon** [comment]
Today i had this issus too. 2.1.0 #11675. It seem 
happening while changing zoomlevel and rotating map. im on Samsung s4mini cm12.

**Comment by jeenuv** [comment]
I can confirm it happened while changing zoom level for me too.

**Comment by jf-simon** [comment]
I/net.osmand:native( 6074): Native ok (init 0, rendering 1000) 
I/net.osmand( 6074): MapRenderRepositories true
W/net.osmand:native( 6074): End point was found 108147375 [Native]
I/net.osmand( 6074): MapRenderRepositories RENDER MAP: update due zoom/map density
I/net.osmand( 6074): MapRenderRepositories RENDER MAP: Interrupt rendering map
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 68653 y = 45274 z = 17 for 1
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 34326 y = 22637 z = 16 for 0
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 68654 y = 45274 z = 17 for 7
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 34327 y = 22637 z = 16 for 0
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 68655 y = 45272 z = 17 for 1
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 68655 y = 45273 z = 17 for 1
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 68655 y = 45274 z = 17 for 1
I/net.osmand( 6074): MapRenderRepositories RENDER MAP: update due zoom/map density
I/net.osmand( 6074): MapRenderRepositories RENDER MAP: Interrupt rendering map
I/net.osmand( 6074): MapRenderRepositories RENDER MAP: new request RotatedTileBox [lat=48.52852104, lon=8.56295866, rotate=306.6, density=1.5, zoom=17, mapDensity=1.5, zoomAnimation=0.0, zoomFloatPart=0.33333396911621094, cx=450, cy=1013, pixWidth=900, pixHeight=1382]
I/net.osmand:native( 6074): Route objects 1003
I/net.osmand:native( 6074): Ocean 0 fillCompleteArea 1
I/net.osmand:native( 6074): Search : tree - read( 821), accept( 85), objs - visit( 10448), accept(1015), in result(1003) 
I/net.osmand( 6074): MapRenderRepositories BLat=48.52633285522461, TLat=48.53215026855469, LLong=8.559276103973389, RLong=8.569567203521729, zoom=17
I/net.osmand( 6074): MapRenderRepositories Native search: 159 ms 
I/net.osmand:native( 6074): Creating SkBitmap in native w:900 h:1382 s:3600 f:1!
I/net.osmand:native( 6074): Row bytes for RGBA_8888 is 3600
I/net.osmand:native( 6074): Locked 4975200 bytes at 0xa14f800c
I/net.osmand:native( 6074): Initializing rendering
I/net.osmand:native( 6074): Rendering image
I/net.osmand( 6074): RenderingIcons Icon data length is 474
I/net.osmand( 6074): RenderingIcons Icon data length is 417
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 68653 y = 45271 z = 17 for 0
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 34326 y = 22635 z = 16 for 1
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 17163 y = 11317 z = 15 for 1
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 8581 y = 5658 z = 14 for 0
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 68654 y = 45271 z = 17 for 0
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 34327 y = 22635 z = 16 for 0
I/net.osmand( 6074): RenderingIcons Icon data length is 1149
I/net.osmand( 6074): RenderingIcons Icon data length is 739
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 68655 y = 45271 z = 17 for 1
I/net.osmand( 6074): RenderingIcons Icon data length is 743
I/net.osmand( 6074): RenderingIcons Icon data length is 662
I/net.osmand( 6074): RenderingIcons Icon data length is 772
I/net.osmand( 6074): RenderingIcons Icon data length is 791
I/net.osmand( 6074): RenderingIcons Icon data length is 703
I/net.osmand( 6074): RenderingIcons Icon data length is 806
I/net.osmand( 6074): RenderingIcons Icon data length is 948
I/net.osmand( 6074): RenderingIcons Icon data length is 229
I/net.osmand( 6074): RenderingIcons Icon data length is 1025
I/net.osmand( 6074): RenderingIcons Icon data length is 422
I/net.osmand( 6074): RenderingIcons Icon data length is 613
I/net.osmand( 6074): RenderingIcons Icon data length is 760
I/net.osmand( 6074): RenderingIcons Icon data length is 940
I/net.osmand( 6074): RenderingIcons Icon data length is 620
I/net.osmand( 6074): RenderingIcons Icon data length is 503
I/net.osmand( 6074): RenderingIcons Icon data length is 1317
I/net.osmand( 6074): RenderingIcons Icon data length is 711
I/net.osmand( 6074): RenderingIcons Icon data length is 1127
I/net.osmand( 6074): RenderingIcons Icon data length is 885
I/net.osmand( 6074): RenderingIcons Icon data length is 1160
I/net.osmand:native( 6074): Native ok (rendering 1000, text 0 ms) 
I/net.osmand:native( 6074):  (12094 points, 4647 points inside, 1762 of 2495 objects visible)
I/net.osmand:native( 6074): End Rendering image
I/net.osmand:native( 6074): Native ok (init 0, rendering 1000) 
I/net.osmand( 6074): MapRenderRepositories true
I/net.osmand( 6074): MapRenderRepositories RENDER MAP: update due to tile box
I/net.osmand( 6074): MapRenderRepositories RENDER MAP: Interrupt rendering map
I/net.osmand( 6074): MapRenderRepositories RENDER MAP: new request RotatedTileBox [lat=48.52906635, lon=8.56394157, rotate=312.0, density=1.5, zoom=17, mapDensity=1.5, zoomAnimation=0.0, zoomFloatPart=0.33333396911621094, cx=450, cy=1013, pixWidth=900, pixHeight=1382]
I/net.osmand:native( 6074): Route objects 1001
I/net.osmand:native( 6074): Ocean 0 fillCompleteArea 1
I/net.osmand:native( 6074): Search : tree - read( 821), accept( 83), objs - visit( 10368), accept(1013), in result(1001) 
I/net.osmand( 6074): MapRenderRepositories BLat=48.526878356933594, TLat=48.532867431640625, LLong=8.560204601287841, RLong=8.5703782081604, zoom=17
I/net.osmand( 6074): MapRenderRepositories Native search: 127 ms 
I/net.osmand:native( 6074): Creating SkBitmap in native w:900 h:1382 s:3600 f:1!
I/net.osmand:native( 6074): Row bytes for RGBA_8888 is 3600
I/net.osmand:native( 6074): Locked 4975200 bytes at 0xa074f00c
I/net.osmand:native( 6074): Initializing rendering
I/net.osmand:native( 6074): Rendering image
I/net.osmand( 6074): RenderingIcons Icon data length is 923
I/net.osmand( 6074): RenderingIcons Icon data length is 779
I/net.osmand:native( 6074): Native ok (rendering 0, text 0 ms) 
I/net.osmand:native( 6074):  (12165 points, 4810 points inside, 1734 of 2413 objects visible)
I/net.osmand:native( 6074): End Rendering image
I/net.osmand:native( 6074): Native ok (init 0, rendering 0) 
I/net.osmand( 6074): MapRenderRepositories true
W/net.osmand:native( 6074): [Native] Result visited (visited roads 24076, visited segments 44087 / 54390 , queue sizes 1965 / 4368 ) 
W/net.osmand:native( 6074): [Native] Result timing (time to load 3000, time to calc 13000, loaded tiles 612) 
W/net.osmand:native( 6074): [Native] Memory occupied (Routing context 15099 Kb, search 1588 Kb)
I/net.osmand:native( 6074): Routing calculated time distance 1531.218872
I/net.osmand( 6074): RoutePlannerFrontEnd Native routing took 14.976 seconds
I/net.osmand( 6074): MapRenderRepositories RENDER MAP: update due zoom/map density
I/net.osmand( 6074): MapRenderRepositories RENDER MAP: Interrupt rendering map
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 137307 y = 90543 z = 18 for 0
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 137307 y = 90544 z = 18 for 0
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 137308 y = 90543 z = 18 for 0
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 137308 y = 90544 z = 18 for 1
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 137309 y = 90543 z = 18 for 0
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 137309 y = 90544 z = 18 for 0
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 137310 y = 90543 z = 18 for 1
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 137310 y = 90544 z = 18 for 1
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 137310 y = 90545 z = 18 for 0
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 137310 y = 90546 z = 18 for 0
I/net.osmand( 6074): MapRenderRepositories RENDER MAP: update due zoom/map density
I/net.osmand( 6074): MapRenderRepositories RENDER MAP: Interrupt rendering map
I/net.osmand( 6074): MapRenderRepositories RENDER MAP: new request RotatedTileBox [lat=48.52942443, lon=8.56459351, rotate=318.0, density=1.5, zoom=18, mapDensity=1.5, zoomAnimation=0.0, zoomFloatPart=0.0, cx=450, cy=1013, pixWidth=900, pixHeight=1382]
I/net.osmand:native( 6074): Route objects 434
I/net.osmand:native( 6074): Ocean 0 fillCompleteArea 1
I/net.osmand:native( 6074): Search : tree - read( 821), accept( 67), objs - visit( 9728), accept(446), in result(434) 
I/net.osmand( 6074): MapRenderRepositories BLat=48.52806091308594, TLat=48.531917572021484, LLong=8.562227010726929, RLong=8.56850552558899, zoom=18
I/net.osmand( 6074): MapRenderRepositories Native search: 72 ms 
I/net.osmand:native( 6074): Creating SkBitmap in native w:900 h:1382 s:3600 f:1!
I/net.osmand:native( 6074): Row bytes for RGBA_8888 is 3600
I/net.osmand:native( 6074): Locked 4975200 bytes at 0xa14f800c
I/net.osmand:native( 6074): Initializing rendering
I/net.osmand:native( 6074): Rendering image
I/net.osmand:native( 6074): Native ok (rendering 0, text 0 ms) 
I/net.osmand:native( 6074):  (6166 points, 1793 points inside, 756 of 1061 objects visible)
I/net.osmand:native( 6074): End Rendering image
I/net.osmand:native( 6074): Native ok (init 0, rendering 0) 
I/net.osmand( 6074): MapRenderRepositories true
I/net.osmand( 6074): MapRenderRepositories RENDER MAP: update due zoom/map density
I/net.osmand( 6074): MapRenderRepositories RENDER MAP: Interrupt rendering map
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 274616 y = 181089 z = 19 for 1
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 274616 y = 181090 z = 19 for 1
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 274616 y = 181091 z = 19 for 1
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 274616 y = 181092 z = 19 for 1
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 274617 y = 181089 z = 19 for 0
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 274617 y = 181090 z = 19 for 1
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 274617 y = 181091 z = 19 for 2
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 274617 y = 181092 z = 19 for 1
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 274618 y = 181089 z = 19 for 0
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 274618 y = 181090 z = 19 for 0
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 274618 y = 181091 z = 19 for 0
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 274618 y = 181092 z = 19 for 0
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 274619 y = 181089 z = 19 for 0
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 274619 y = 181090 z = 19 for 1
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 274619 y = 181091 z = 19 for 7
D/net.osmand( 6074): SQLiteTileSource Checking tile existance x = 274619 y = 181092 z = 19 for 1
I/net.osmand( 6074): MapRenderRepositories RENDER MAP: update due zoom/map density
I/net.osmand( 6074): MapRenderRepositories RENDER MAP: Interrupt rendering map
I/net.osmand( 6074): RouteResultPreparation <test regions="" description="" best_percent="" vehicle="car" 
I/net.osmand( 6074):     start_lat="48.52826229" start_lon="8.56263133" target_lat="48.56358337402344" target_lon="8.778165817260742" loadedTiles = "612" visitedSegments = "24076" complete_distance = "21006.26" complete_time = "1213.2542" routing_time = "1531.2189"  >
I/net.osmand( 6074): MapRenderRepositories RENDER MAP: update due zoom/map density
I/net.osmand( 6074): MapRenderRepositories RENDER MAP: Interrupt rendering map
I/net.osmand( 6074): RouteProvider Finding route contained 432 points for 20887 ms
I/net.osmand( 6074): MapRenderRepositories RENDER MAP: new request RotatedTileBox [lat=48.52956543, lon=8.56473689, rotate=326.2, density=1.5, zoom=19, mapDensity=1.5, zoomAnimation=0.0, zoomFloatPart=0.0, cx=450, cy=1013, pixWidth=900, pixHeight=1382]
I/net.osmand:native( 6074): Route objects 91
I/net.osmand:native( 6074): Ocean 0 fillCompleteArea 1
I/net.osmand:native( 6074): Search : tree - read( 821), accept( 56), objs - visit( 9288), accept(103), in result(91) 
I/net.osmand( 6074): MapRenderRepositories B

**Comment by Norbert80** [comment]
It is zoom level dependent but it does not require manual change of zoom level. I also experience it while navigating.

**Comment by jf-simon** [comment]
Yes you are right. It happend with automatic map interactions

**Comment by vshcherb** [comment]
Major changes were made in that area and because there was no 100% reproducible static way, this issue could be considered closed. Please report other findings

**Comment by jeenuv** [comment]
The coordinates that used is visible in the screen shot that I attached. Did you try routing though that coordinate (maybe the exact route; it's in the map East of England, Cambridge), and set the zoom to a 200m scale?

**Comment by jeenuv** [comment]
Just also wanted to comment that I tried the 2.1.1, and the bug is there there. Same route, same location, same glitch.

**Comment by Norbert80** [comment]
@vshcherb I can confirm what @jeenuv has written. Today I have installed release 2.1.1 and used it for driving home (nearly 200 km). The situation is absolutely the same. I can't see improvements. Some action arrows still tend to interconnect straight with the next action arrow with high distance. The result are yellow lines flickering over the screen. It looks like this issue is device independent since other users using other device type experience the same. I'm rather sure that you (Victor) cannot reproduce it because you are not driving enough "test kilometers".

I suggest the following steps:
- Reopen this issue
- Remove action arrows from the release brunch until you are able to come up with a proper solution
- Generate test pre-release after you think you found a solution and provide it - before release -  to your test drivers (for example me ;-)

**Comment by vshcherb** [comment]
The issue mentionned https://github.com/osmandapp/Osmand/issues/1366 was reproduced and fixed

**Comment by jeenuv** [comment]
Cheers! Looking forward for the next release.

**Comment by Norbert80** [comment]
@vshcherb I don't understand. We have set the issue that you mention as duplicate of this one.

**Comment by vshcherb** [comment]
Yes and what is not clear?

**Comment by Norbert80** [comment]
@vshcherb So now we should have both or non of these issues fixed. But not only one...

**Comment by vshcherb** [comment]
Which both or none? Yours original issue I didn't manage reproduce, at least in a static way. I did some changes to the similar issue I saw and I said that possibly help in your case. Today I fixed in mentioned case, let's see if there is any reproducible case left.

**Comment by Norbert80** [comment]
@vshcherb is this patch included in yesterdays OsmAnd+ 2.1.1 second release in Play Store?
If yes, might have introduced this regression: issue #1372

(I will inform you here, if I still experience the initial problem of this bug report.)

**Comment by Norbert80** [comment]
@vshcherb the initial problem of this report seems to be fixed. (OsmAnd+ 2.1.1 second release)
