### ISSUE TITLE
currentTrackColor option in UniRS doesn't works

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1418]
This code doesn't work as expected: <case currentTrackColor=".." color="#..."> does nothing.
https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/UniRS.render.xml#L12
`<renderingProperty attr="currentTrackColor" name="Current GPX color" description="Color of the currently recording track" type="string" possibleValues="red,orange,brown,yellow,lightgreen,green,lightblue,blue,purple" defaultValueDescription="default"/>`
`	<renderingAttribute name="gpx" cap="ROUND">`
`		<switch>`
`			<case currentTrackColor="red" color="#ff0000"/>`
`			<case currentTrackColor="orange" color="#ff7200"/>`
`                        ............`
`        		<case strokeWidth="2" color="#ff0000">`
`				<apply_if roadStyle="germanRoadAtlas" color="#aa0088"/>`
`			</case>`
`			<apply_if additional="routePoints=true" pathEffect="6_5"/>`
`	</switch>`
`	</renderingAttribute>`
Also when OsmAnd is started with UniRS with this code strokeWidth="2" doesn't works also - track is shown visually with strokeWidth="1" and with strange purple color. After switching to default style and back strokeWidth becomes 7:6 as in default (that is also unwanted behavior) and purple color. currentTrackColor in these cases is set to non-purple.
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshot_2015-06-28-19-19-34.png
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshot_2015-06-28-19-20-04.png

**Comment by vshcherb** [comment]
Fixed

**Comment by xmd5a2** [comment]
Not fixed. Most of time this <apply> works
'''			<apply_if additional="routePoints=true" pathEffect="6_2"/>

**Comment by vshcherb** [comment]
Fixed
