### ISSUE TITLE
housenumbers not found using postcode

### ISSUE THREAD

**Issue by Hedaja** [osmandapp/Osmand#1462]
Hello
When I search for an address using the postcode instead of the villages name there are no house numbers found. All road are found but when you click one it says there are no house numbers.
If you search using the villages/towns name the house numbers get found.
Tested it with postcode 09221 / Neukirchen/Erz and with 01219 / Dresden and Leipzig/ 04299
It doesn't seem to matter whether th pos code is tagged to the address or not.

App version: OSMAnd+ 2.1.1
Tested map: Germany-Saxony (27.06.15 and version before)
Device: Sony Ericsson Arc S LT18i
Android: 4.0.4

**Comment by rominf** [comment]
@Hedaja, thank you for report.

@vshcherb, the problem lies here:
Cities are written in `writeCityBlockIndex` (https://github.com/osmandapp/OsmAnd-tools/blob/0f07437d1e39179c8c06a33edd4e65bd40aa3c1f/OsmAndMapCreator/src/net/osmand/data/preparation/address/IndexAddressCreator.java#L1038) which calls `readStreetsBuildings` method, which calls `readStreetsAndBuildingsForCity` to read buildings. Postcodes are written in 20 lines of code (https://github.com/osmandapp/OsmAnd-tools/blob/0f07437d1e39179c8c06a33edd4e65bd40aa3c1f/OsmAndMapCreator/src/net/osmand/data/preparation/address/IndexAddressCreator.java#L1041).

I propose to unify postcode and city writing. Should I start doing this?

**Comment by vshcherb** [comment]
How unification could help, there are main differences between this. Postcode doesn't have original data, it just copies that data from other section, so we don't need duplicate the code.

**Comment by rominf** [comment]
This issue is resolved. Leaving it opened to remember to check generated maps next month.

**Comment by vshcherb** [comment]
Well we can already regenerate maps and it should be already regenerated  in an hour http://builder.osmand.net:8080/view/Generate%20Maps/job/Maps_GenerateFullMaps/916/parameters/

**Comment by vshcherb** [comment]
Tested on http://www.openstreetmap.org/way/112973494 (zip code 09221) still doesn't work (relation http://www.openstreetmap.org/relation/1298223#map=18/50.78115/12.86821&layers=N)

**Comment by vshcherb** [comment]
Fixed
