### ISSUE TITLE
Intermittent performance issues with opengl rendering

### ISSUE THREAD

**Issue by tommycrock** [osmandapp/OsmAnd#14666]
### Description
Since v4.2 update I have been having major performance issues with the opengl rendering (not tilted). Sometimes, particularly on first opening, it works very well. Other times, particularly after switching applications, it does not render for in excess of 20 seconds, or does so within 5 or so seconds. There are also intermittent problems with labels not showing. None of these are exactly consistent, i.e. problems can be from app start / may not appear on app switching, but are persistent.
[Edit]
I should have mentioned, I had been using opengl rendering without problems. Disabling and restarting the app with normal rendering resolves the issue. [/Edit]

### How to reproduce?
Use opengl (development option). I have tried different map options, such as fewer details, 150% zoom

### Your Environment
OsmAnd± Version: 4.2.4
Android/iOS version: 12
Device model: Samsung s10e, one UI 4.1

**Comment by Boothy99** [comment]
Just discovered issue of sluggish app with OpenGL rendering enabled (which I've had enabled for years). 
POI icons slow to load. 
Map rendering slow, showing background graph blocks for a short while before map fills.
Disabled OpenGL - OsmAnd+ functions well again. Left disabled for now.

Xiaomi Mi 9T mobile.
Android 11
OsmAnd+ 4.2.4

**Comment by Boothy99** [comment]
Not sure if this is of any use, but hopefully I've saved a logcat file after I enabled OpenGL / closed OsmAnd+ and / restarted app with Rendering debug info enabled. 
POI's were slow to show; map rendering slow to complete.[Logcat log](https://drive.google.com/file/d/1BrJfJRb3vPIyTDeW645YF9yDqPa554kK/view?usp=drivesdk)

**Comment by Boothy99** [comment]
I just tested OsmAnd+ with OpenGL enabled on my tablet (it was off initially). The same problem shows up, but this time, it took 10 to 15 seconds for the map to render (phone & tablet have OsmAnd offline maps enabled).
POI's didn't load until 5+ seconds later.

Device -
Samsung Galaxy Tab S4 (SM-T830)
Android 10
Android security patch 1 March 2022.

**Comment by vshcherb** [comment]
Video would be welcome cause we're testing it on 10-15 devices and didn't see such issues.

**Comment by Boothy99** [comment]
Attempted to attach screen video capture but failed. Here's a link to the video file on Google Photos. 

https://photos.app.goo.gl/iyLh11tkFub9sjEp9

I set OsmAnd+ to use OpenGL in the first half. Typically the maps loaded a little swifter but you can see the POI's are slow to show up.
Second half I close OpenGL rendering and restart app. Maps & POI icons appear much quicker.

**Comment by Boothy99** [comment]
Unfortunately I'm away on holiday currently and can't access WiFi for sending video capture on my tablet with the much slower rendering.

**Comment by tommycrock** [comment]
With apologies for the screen filter (forgot to turn it off, though that's not the cause) https://photos.app.goo.gl/h1eTXVe6eEH5LMcs8
I struggled at first to get the slowness to trigger - the first minute or so is opengl and then I switch it off (paused while switching).

Here is a second video from app open (without filter!) https://photos.app.goo.gl/WP2Ds6vwBrWoF4xL6 
This time it was slow from the start but then went fast when I zoomed out, then very slow on zooming in to extreme levels... That seemed to be what I needed to do to trigger it for the first video too. Just an idea, hope it helps.

**Comment by vshcherb** [comment]
Issue with slowness of tracks has moved to https://github.com/osmandapp/OsmAnd/issues/14666
And issue with rendering frozen hopefully is fixed with 4.2.6

**Comment by tommycrock** [comment]
@vshcherb I'm still seeing this same issue on 4.2.7. You mentioned hopefully fixed in 4.2.6 but I don't know if that was achieved? Thanks

**Comment by vshcherb** [comment]
Please make another issue with video and we will try to reproduce, there is no effort any more on this issue.

**Comment by tommycrock** [comment]
Thanks. https://tommycrock.synology.me:5001/mo/sharing/dvDz1LNOe 
Let me know if that doesn't work and I'll share another way.
