### ISSUE TITLE
OsmAndMapCreator uses mm_wetland.png instead of h_wetland.png in case of shader="wetland"

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1518]
Strangely, OsmAnd doesn't have this bug, only OsmAndMapCreator.

**Comment by vshcherb** [comment]
Yes, they have "different" icons mechanism. Because it is not critical for users, but for testing, I think it has low priority, so I will keep it in mind, once I find it - will fix it.

**Comment by vshcherb** [comment]
Fixed

**Comment by xmd5a2** [comment]
Not really fixed. Icons now use h_* icons
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshot_2015-10-02_20-52-01.png

**Comment by vshcherb** [comment]
As discussed, let's achieve non-duplicate names for icons.
