### ISSUE TITLE
Sluggish map rendering if Internet connection is unstable and OSM notes enabled

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#15801]
The map rendering becomes very laggy if the Internet connection is unstable. Zooming/panning no longer works correctly but just leads to a grid pattern. Favorites and tracks do no longer get rendered. As soon as the Internet connection get's better or if the phone is put into flight mode rendering is fast and stable again.

This is with a vector map of course.

Maybe this is related to the OSM notes plugin. Is it possible that map rendering get's blocked if downloading of OSM notes takes unusually long? If so, it would be a good idea to fetch OSM notes in the background. I haven't really figured out yet how to reproduce this behavior reliably.

OsmAnd 4.3.0 with OpenGL enabled. I haven't seen this behavior before with OsmAnd 4.2. However, maybe I just didn't had the same environment.

**Comment by scaidermern** [comment]
After some more investigations I'm 100% sure it is the OSM notes layer that causes the laggy map rendering if the Internet connection is unstable / slow. Disabling notes immediately resolves this problem.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13973mqta, released: 2022-11-25
Not Reproduced

OpenGL

https://user-images.githubusercontent.com/104760013/203964826-b040cc0b-3203-4ec9-ae6f-7b97741dd3dd.mp4

Non-OpenGL

https://user-images.githubusercontent.com/104760013/203965940-1f559942-8a54-4349-aaec-0fedede5d3ab.mp4

**Comment by scaidermern** [comment]
> Not Reproduced
> Map loading speed with OpenGL and without OpenGL, with 3g connection, with OSM notes enabled and disabled is the same

Well, as explained, you need an unstable and/or very slow connection to experience this problem. With a fast connection everything is fine.

**Comment by Zirochkabila** [comment]
The map rendering speed with OSM notes enabled in 2g mode becomes slower. Although not much.


https://user-images.githubusercontent.com/104760013/204098215-75f39c7f-9706-4cad-9175-4c0538490f4e.mp4

**Comment by scaidermern** [comment]
So this means that you can reproduce it. The rendering speed of the offline map should certainly _not_ be influenced by the speed of the Internet connection.

**Comment by vshcherb** [comment]
Probably the issue exists but it's negligible cause OSM notes could be disabled

**Comment by scaidermern** [comment]
> Probably the issue exists but it's negligible cause OSM notes could be disabled

Sure. But I don't want to toggle them depending on the current network connectivity. I want to keep notes enabled because I want to see and fix them. If the network connection get's bad and I disable them I will forget to re-enable them if the network connection get's better.

I might not even be able to disable them if I'm currently driving a vehicle. Still I want to have a reliable map rendering in this case.

**Comment by vshcherb** [comment]
True, once we understand what's behind this delay it should be fixed, by the attached video the slow down is not very visible

**Comment by scaidermern** [comment]
Problem still exists. While hiking outside in hilly terrain it is quite noticeable and really annoying because map rendering stops for several seconds while panning the map or zooming.

**Comment by mnalis** [comment]
related issues whose solving might help with this too:
- https://github.com/osmandapp/OsmAnd/issues/4424 (solve)
- https://github.com/osmandapp/OsmAnd/issues/12679 (reduce problem)

**Comment by vshcherb** [comment]
Should be fixed https://github.com/osmandapp/OsmAnd/issues/17136
