### ISSUE TITLE
Problems with connecting the Arabic letters

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15818]
### Description
A problem in the central Kurdish branch language (ckb), exactly with (ڵ، ێ، ۆ، ڕ، ە) letters, they didn't connect to the letters that come before or after them as the other letters do.

Notice the attached screenshots, all the texts marked by (true mark) are right and all texts marked by (false mark) are wrong.
The other important point that should you note is: the same text on the map is wrong rendered but it is true rendered in the details menu, as shown in the attached screenshots.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/203827194-aafe3833-c812-411a-9f8e-ddbacf1b6e87.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/203827204-5138476b-8f26-4c3e-aa5d-ec9cbdedd928.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/203827208-5369d9c0-590a-4cd1-af2c-c33d7d2df082.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/203827214-0fa4a33c-64cf-4184-a10d-f6e0f41fefe7.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/203827218-b1f90dcb-cdf1-4a08-aa63-699b64e9594c.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

`35.55602, 44.93055`

[OsmAnd](https://osmand.net/map/?end=40.088340%2C22.489690&mode=truck#16/35.5558/44.9308)
[OSM](https://www.openstreetmap.org/search?query=35.55602%2C%2044.93055#map=19/35.55584/44.93055)

### Your Environment
OsmAnd Version: OsmAnd+ 4.3.0

**Comment by RenasAzad** [comment]
the below list is the cordinations of the screenshots i provided it in the discription of the problem:
35.55602 44.93055
35.68359 44.96371
35.50538 45.01966
35.41754 45.22549
35.89127 44.76814

note: the problem is in the openGL map rendering engine, because when i disable it all the texts turns true.

**Comment by RenasAzad** [comment]
hi vshcherb
does your above comment means the problim was solved?
if yes, in wich version?
the last version (4.3.1) released and the problim still remain!
note: the problem in the openGL map rendering engine only, the  version 1 map rendaring engine is ok and it is working properly without any problim.
thank you very much.

**Comment by vshcherb** [comment]
Problem not solved, we will investigate it later probably we need to update the fonts.

**Comment by RenasAzad** [comment]
thank you very much, i priciate your efforts.

**Comment by Zirochkabila** [comment]
> 

That's right - it can be reproduced only with OpenGL

**Comment by RenasAzad** [comment]
hi all
i updated osmand+ to 4.4.1 version but this problim still remain with openGL map rendering engine!
Is this problem so difficult to solve?
It's a very annoying problem, i hope you solve it.
thank you very much for all osmand developers, they are doing a very great work.

**Comment by vshcherb** [comment]
Japanese external font
![telegram-cloud-photo-size-2-5204128340200507533-m](https://user-images.githubusercontent.com/1042025/223415353-84185f92-787c-4d76-96e6-a01ec22f8765.jpg)
![telegram-cloud-photo-size-2-5204128340200507533-m](https://user-images.githubusercontent.com/1042025/223415374-ae477896-b836-401c-b82a-0df45dab5e7b.jpg)

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd/issues/14336#issuecomment-1368005250

**Comment by RenasAzad** [comment]
note:
the problem is hapening in central kurdish language only, not in all languages who writen by arabic letters. and with openGL engine only.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#14270mqta, Released: 2023-03-25
4.4.6.11
Done

**Comment by RenasAzad** [comment]
thank you very much for all who worked to solve this problem. 🙏
