### ISSUE TITLE
App crashing at startup in DiscountHelper with "Error: JSON parsing error"?

### ISSUE THREAD

**Issue by TheSnoozer** [osmandapp/OsmAnd#15892]
### Description
When I started the application it crashed multiple times at startup until it randomly worked again.

Based on [logcat.log](https://github.com/osmandapp/OsmAnd/files/10149061/logcat.log) I'd assume the following to be the culprit:
```
12-04 17:42:34.018  4731  4731 E DiscountHelper: Error: JSON parsing error: 
12-04 17:42:34.018  4731  4731 E DiscountHelper: org.json.JSONException: No value for message
12-04 17:42:34.018  4731  4731 E DiscountHelper: 	at org.json.JSONObject.get(JSONObject.java:398)
12-04 17:42:34.018  4731  4731 E DiscountHelper: 	at org.json.JSONObject.getString(JSONObject.java:559)
12-04 17:42:34.018  4731  4731 E DiscountHelper: 	at net.osmand.plus.helpers.DiscountHelper$ControllerData.parse(DiscountHelper.java:492)
12-04 17:42:34.018  4731  4731 E DiscountHelper: 	at net.osmand.plus.helpers.DiscountHelper.processDiscountResponse(DiscountHelper.java:143)
12-04 17:42:34.018  4731  4731 E DiscountHelper: 	at net.osmand.plus.helpers.DiscountHelper.access$100(DiscountHelper.java:58)
12-04 17:42:34.018  4731  4731 E DiscountHelper: 	at net.osmand.plus.helpers.DiscountHelper$1.onPostExecute(DiscountHelper.java:131)
12-04 17:42:34.018  4731  4731 E DiscountHelper: 	at net.osmand.plus.helpers.DiscountHelper$1.onPostExecute(DiscountHelper.java:115)
12-04 17:42:34.018  4731  4731 E DiscountHelper: 	at android.os.AsyncTask.finish(AsyncTask.java:771)
12-04 17:42:34.018  4731  4731 E DiscountHelper: 	at android.os.AsyncTask.access$900(AsyncTask.java:199)
12-04 17:42:34.018  4731  4731 E DiscountHelper: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
12-04 17:42:34.018  4731  4731 E DiscountHelper: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-04 17:42:34.018  4731  4731 E DiscountHelper: 	at android.os.Looper.loopOnce(Looper.java:233)
12-04 17:42:34.018  4731  4731 E DiscountHelper: 	at android.os.Looper.loop(Looper.java:344)
12-04 17:42:34.018  4731  4731 E DiscountHelper: 	at android.app.ActivityThread.main(ActivityThread.java:8248)
12-04 17:42:34.018  4731  4731 E DiscountHelper: 	at java.lang.reflect.Method.invoke(Native Method)
12-04 17:42:34.018  4731  4731 E DiscountHelper: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
12-04 17:42:34.018  4731  4731 E DiscountHelper: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
```

### How to reproduce?
Not sure I started the application and it just crashed (three times in a row until it randomly worked)

### Your Environment
Device : RE513CL1
Brand : realme
Model : RMX3241
Product : RMX3241EEA
Build : RMX3241_11_C.05
Version : 12
App Version : OsmAnd+
Apk Version : 4.2.7 4207

**Maps used (online or offline):**   
Offline

**Comment by vshcherb** [comment]
The issue is probably fixed in 4.3 - we need crashlog probably it's native crash

**Comment by TheSnoozer** [comment]
Still an issued in 4.3
```Device : RE513CL1
Brand : realme
Model : RMX3241
Product : RMX3241EEA
Build : RMX3241_11_C.05
Version : 12
App Version : OsmAnd+
Apk Version : 4.3.2 4302
```
Log
```
12-13 14:57:47.863 30086 30086 E DiscountHelper: Error: JSON parsing error: 
12-13 14:57:47.863 30086 30086 E DiscountHelper: org.json.JSONException: No value for message
12-13 14:57:47.863 30086 30086 E DiscountHelper: 	at org.json.JSONObject.get(JSONObject.java:398)
12-13 14:57:47.863 30086 30086 E DiscountHelper: 	at org.json.JSONObject.getString(JSONObject.java:559)
12-13 14:57:47.863 30086 30086 E DiscountHelper: 	at net.osmand.plus.helpers.DiscountHelper$ControllerData.parse(DiscountHelper.java:497)
12-13 14:57:47.863 30086 30086 E DiscountHelper: 	at net.osmand.plus.helpers.DiscountHelper.processDiscountResponse(DiscountHelper.java:145)
12-13 14:57:47.863 30086 30086 E DiscountHelper: 	at net.osmand.plus.helpers.DiscountHelper.access$100(DiscountHelper.java:59)
12-13 14:57:47.863 30086 30086 E DiscountHelper: 	at net.osmand.plus.helpers.DiscountHelper$1.onPostExecute(DiscountHelper.java:133)
12-13 14:57:47.863 30086 30086 E DiscountHelper: 	at net.osmand.plus.helpers.DiscountHelper$1.onPostExecute(DiscountHelper.java:117)
```
Do you need more information here and If so, how do I extract them?

**Comment by TheSnoozer** [comment]
seems fixed in 4.3.3 thanks
