### ISSUE TITLE
Add support for textItalic="true" to old rendering engine

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1591]

**Comment by vshcherb** [comment]
Done

**Comment by xmd5a2** [comment]
Not fixed. Water names should be italic (see OpenGL engine). Text looks like bold instead.
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshot_2015-08-31-20-15-02.png

**Comment by xmd5a2** [comment]
Also note that this text should be bold
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshot_2015-08-31_20-40-06.png
See how OpenGL engine renders it:
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshot_2015-08-31_20-41-13.png
The same is on android.

**Comment by vshcherb** [comment]
Fixed again, please check

**Comment by xmd5a2** [comment]
It works in map creator but not on my phone (4.4.2)
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshot_2015-09-01-09-56-18.png
(OsmAnd-main-qt-arm 5677 from today)
Do I need some fonts?

**Comment by vshcherb** [comment]
Open-Sans fonts are added, so in many areas it should work.
