### ISSUE TITLE
Czechia map Slopes lines

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#15997]
### Description

Lines on the map slopes of Czech:
50.39528° N, 16.00002° E
50.99889° N, 16.00011° E
50.99871° N, 16.15259° E

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/44466116/208069878-f64afbba-5aa1-4341-adaa-b400ac0fb438.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: 4.3.3
Android/iOS version: 12
Device model: S10e

**Maps used (online or offline):**   
Slopes map of Czechia 26 Dec 2020

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14032mqta, released: 2022-12-19
`30.00013° N, 6.00007° W`


https://user-images.githubusercontent.com/104760013/208400345-23b6820f-e777-4e75-8242-4fdb389a90fc.mp4

**Comment by xmd5a2** [comment]
Fixed

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14057mqta, released: 2022-12-28
Still present
`30.00013° N, 6.00007° W`
[Map](https://drive.google.com/file/d/1TPvT7E9NTTI9_yP9P-Bc7zSW2FZ3lgoE/view?usp=sharing)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/209807815-01ce086d-ce12-40af-94b6-cfd83047a1d0.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14059mqta, released: 2022-12-29
Done

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/209918343-5cb0ee83-e936-4606-949d-c245a927764e.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
