### ISSUE TITLE
OsmAnd background Sleep mode starts up randomly

### ISSUE THREAD

**Issue by vrtareg** [osmandapp/Osmand#1600]
Hi

I have a situation on my SG Note 4 that the background sleep mode enables itself after closing OsmAnd and stars to record the GPX data.

Is this something normal?

I have the GPX recording enabled but I was hoping if OsmAnd is closed and completely cleared from memory this should not happen until next start ...

What can trigger this kind waking up? any scheduled job that is hiddenly initialised?

P.S. I am using nightly builds. Android 5.0.1.

Regards,
Areg

**Comment by vshcherb** [comment]
That could be very weird. Can you please find an easy path to reproduce it. There no scheduled job (as I know), there could be an issue that background sleep mode didn't stop, but that's an issue and we want to find it. 
To verify that something is running, you can use task manager there you could 1 foreground and 1 background process...

**Comment by vrtareg** [comment]
Hi

Just got to the same situation.
I have closed all applications, went out and noticed that background
service is up even I did not opened OsmAnd.

Phone shows that service was running from app...

Regards,
Areg

**Comment by vrtareg** [comment]
Hi

This sounds absolutely crazy !!!!

I have Skype, and Mail configured for the notifications in Notification area.
Just now I got Skype message, opened it and OsmAnd background service fired up !!!!

Why????

Regards,
Areg

**Comment by vrtareg** [comment]
It did it again!!!!!!!!

Opening Skype message from notification area firing up OsmAnd sleep service !!!

**Comment by vshcherb** [comment]
how is it possible...

**Comment by vshcherb** [comment]
So, if you kill completely OsmAnd or may be even reboot the phone, does osmand starts up on skype message?

**Comment by vshcherb** [comment]
Still if OsmAnd starts background service, notification should appear in status bar. it is a bit weird I check all receiver and they should not be fired at all. Even if they are fired they will break with exception.

**Comment by vrtareg** [comment]
Hi

Just restarted phone and started Skype - no OsmAnd.
Got a message on Skype, opened it and got OsmAnd service fired up.

Also service started in a middle of night and started to record track.

Regards,
Areg

**Comment by vrtareg** [comment]
Hi

Looks like opening an application which is accessing GPS (so it is firing up "GPS Status" one) triggering OsmAnd background service somehow ...

Regards,
Areg

**Comment by vrtareg** [comment]
I hope that I have narrowed this down to the "GPS Status" app - https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2

If it is configured to show the status of GPS in Notification Area OsmAnd Background service is firing up.

OOOPPPPSS - I am wrong - even if the GPS Status disabled to be visible in Notification area OsmAnd Background service is fired up when the Maps.me was running and tried to access GPS ...

So any application accessing GPS firing up OsmAnd Background service on my phone ...

Regards,
Areg

**Comment by dmpr0** [comment]
Hi, i tried to reproduce this bug, i think this GPS Status app starting OsmAnd. Please try uninstal GPS Status, and reproduce your steps.

**Comment by vrtareg** [comment]
Hi

I have tried to uninstall it but result is the same..

Regards,
Areg

**Comment by vrtareg** [comment]
Hi

Is this confirmed finally? 

Whichever I am doing on my phone it is starting up OsmAnd in background...

Very annoying and requires every time to open OsmAnd and then close it 

Regards, 
Areg

**Comment by sonora** [comment]
I only just now discovered this thread and it reminds me of a weird situation I once had on one of my test devices. I could never reproduce, but later thought that maybe I had started an Android OTA update while he OsmAnd navigation service was active or something. I finally performed a complete uninstall of OsmAnd to clean its settings cache (and I think I also performed a device Factory reset), and one (probably the first) measure seems to have cleaned the situation for good. It may be worth a test. For along time it had looked to me like other apps started the behavior, but I believe it was really just random (OS-related).

From testing many other apps, it seems to me that only very rare situations do actually show interactions between apps, and this is usually via wakelocks and bad hardware implementation, so it affects certain hardwares only.

**Comment by vrtareg** [comment]
Hi

I got out of box fresh Note 4 and I had it set up from scratch.

So it is basically equivalent to factory reset and I got this problem straight away. 

I don't want to reinstall or reset anything as it can cause data and settings loss ...

Regards, 
Areg

**Comment by vshcherb** [comment]
It is not reproducible so far, we are keep trying different devices, so far we have tried 5-6 and we can't understand what is going on. It seems to be impossible due to Android restrictions, but it happens on your device. We don't give up, but we are waiting for other clues. 

Please anyone who gets the same or similar issue please report here.

**Comment by vrtareg** [comment]
Hi

It will be nice to have this confirmed and fixed as it is frustrating to have OsmAnd firing up each time when I am touching anything actually.

I am running Android 5.0.1 on Galaxy Note 4 SM-N910F.

Regards,
Areg

**Comment by vrtareg** [comment]
Hi

Could you please have a look?
Looks like related to the #1779

Whichever I am doing, which application I am opening I am getting notification window that " Can't find poi type for poi reference 'salt_pond' ".

Quite annoying.

Regards,
Areg

![screenshot_2015-10-07-17-09-26](https://cloud.githubusercontent.com/assets/2562730/10367575/3659a3ea-6dc9-11e5-9467-cd74922ab629.png)
![screenshot_2015-10-07-17-09-33](https://cloud.githubusercontent.com/assets/2562730/10367576/365b4312-6dc9-11e5-9dd5-f0eda346c2e7.png)

**Comment by vshcherb** [comment]
I think salt_pond issue was already fixed. Please delete poi_types.xml manually and restart it.

**Comment by vshcherb** [comment]
Please try it again.

**Comment by vrtareg** [comment]
Hi

I can still see this.
After installing new version,  rebooting device or sometimes after running some other applications. 

Regards, 
Areg

**Comment by vrtareg** [comment]
Still can see this occasionally.

**Comment by sonora** [comment]
I guess Android may start often-used apps after a device re-boot even before you manually start OsmAnd.

I wonder what your settings are for the following 2 menu items in Settings/Trip recording: "Log track to GPX file during navigation" (check all profiles) and "Prevent standalone logging". (By default both tick boxes should be cleared)

**Comment by vrtareg** [comment]
Hi 
I got both options enabled for all profiles. 
It is not starting after reboot - I haven't noticed that after latest Android 6.0.1 upgrade. 
I have noticed that it can start randomly or in most cases after updating app's available in Google Play. 

How that can kick off OsmAnd background start only and not other apps which has background function too.

Maps.me behaves ok ...

Regards, 
Areg

**Comment by sonora** [comment]
This may be deprecated, or needs a fresh report how to reproduce.
