### ISSUE TITLE
Live updates sometimes break turn restrictions

### ISSUE THREAD

**Issue by Zahnstocher** [osmandapp/Osmand#1601]
Example:
https://www.openstreetmap.org/relation/3004881

Map Mecklenburg-Vorpommern with live updates.
The routing is correct without live updates.

See also:
https://groups.google.com/forum/#!topic/osmand/SMTfTqJ9jQI

**Comment by stephan75** [comment]
Good catch! Indeed the live update map data seems to be the culprit. After deleting, routing is OK.

**Comment by vshcherb** [comment]
Still trying to find time to debug it properly, on the first glance doesn't look easy at all. It could be an error in some places, first when we generate *.osm (diff file) we don't include restrictions and also it could be an issue when we generate *.obf file. Restrictions are not part of the road itself and it complicates situation, it looks like deleting a restriction could be an issue with live updates, adding a restrictions could work fine.

**Comment by aceman444** [comment]
I think this happens also with other objects. If an object is changed, sometimes traces of the old state is still shown, in addition to the new state. It looks like all data of an object are not replaced properly by the new data.

**Comment by vshcherb** [comment]
No it is not replaced, there are basically 2 files and what should happen 2 ids should be in conflict and 1 should forbid the other road to be used. Please add other non-working cases, so it will be easier to debug.

**Comment by aceman444** [comment]
Download last map of Slovakia. Then download updates. See object https://www.openstreetmap.org/way/259476963 . View this location in OsmAnd (nightly), enable showing Fixmes (mapper's assistant). You will see the pink FIXME border on the stream and also besides it. The tag no longer exists on the object. Also, the FIXME line is shown at the old location of the stream.

**Comment by Barrocas** [comment]
I found another stange result of the Live updates, mear an area that I
added streets yesterday, I see a flooded map with some strange straight
lines cutting through several km of the map, like in the attached
screenshot.

That screenshot is in this OSM location:
https://www.openstreetmap.org/#map=14/41.3897/-8.3866

The straight cutting lines (and resulting map flooded by nearby river)
don't exist in OSM, it's an artifact that only appears when the Live
updates are in use.

But the Live updates are a really excellent add-on! :)


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by vshcherb** [comment]
When the way is deleted, it is added as a straight line, however it should not be rendered and visible.

**Comment by xmd5a2** [comment]
Live updates require some rendering style modification. May be it is a root of evil? Do you use default rendering style? All styles should have this line in <line> section
```xml
		<case tag="osmand_change" value="delete"/>
```

**Comment by xmd5a2** [comment]
Seems not. Found same issue as @aceman444 
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshot_2015-10-14-20-51-42.png

**Comment by aceman444** [comment]
Thanks, xmd5a2. Yes, that is the place I meant. The fixme=check route is no longer existing on the waterway. I also changed the position of the waterway. I am now not sure if I split it into more ways, but maybe not, there are bridges, those roads are split. So the pink route of the FIXME should not be there. I am using default style of OsmAnd nightly, no modifications. I update to a new build often.

**Comment by Barrocas** [comment]
I'm using a modified render file, but only for the routing/track color and
style.
Using the default doesn't make a difference.

I really like the Live updates, and hope it gets to be a solid working
option.
but even as it is, I still prefer to have an updated map with a water
flooded area, then the previous stock map unflooded without the updates.

The nightly version from day 10 could fetch the Live updates, but versions
from day 12 and 14 are unable to download the Live update files.

>

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by vshcherb** [comment]
Updates should be available for day 12-14 http://download.osmand.net/osmc/. Sometimes they are combined under a month update. Can you please specify which flooded area do you see?

**Comment by Barrocas** [comment]
The straight lines that cut the map appear to start at  the city of Ponte
Vedra, in Spain.
Location: geo:42.4319,-8.643171?z=18
http://osmand.net/go?lat=42.4319&lon=-8.643171&z=18

The straight lines go all the way down to Africa (did not follow to where
they end), and are visible when the Osmand zoom is set with a 1km scale.

I have installed the World map, Portugal and Spain.
When the Live Updates are downloaded, these cutting lines appear, and the
rendering gets messed up when rivers go through it, flooding areas around
it.



-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by Barrocas** [comment]
The updates from day 12 to today are available for download, that is not an
issue.
What I meant was that Osmand app does not recognize that they are available.

If I remove the 'live' folder, and launch the night build from day 10, it
shows that there are 2 updates for Spain and 5 for Portugal.
If I install the night builds from day 12 until today, they show 'No
Updates available' when we click on 'Live Updates'.


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by Barrocas** [comment]
Mirco also has the same issue with the night builds after day 10 not being able to do Live Updates:
https://groups.google.com/forum/m/#!msg/osmand/-f5zLajoRPw/zoLfPdCPCwAJ

**Comment by Barrocas** [comment]
![screenshot_2015-10-15-09-23-11](https://cloud.githubusercontent.com/assets/4006691/10516752/afacca0a-7351-11e5-9c88-07b749ac0aca.png)
The screenshots attached to mail messages appear to fail in getting shown here in github. 
This is a screenshot of the straight lines coming out of the city of Ponte Vedra in Spain all the way into Africa, only visible at zoom 1km, with Live Updates.

**Comment by Barrocas** [comment]
And the resulting flooded areas from were the straight lines cut through.


![screenshot_2015-10-15-18-14-35](https://cloud.githubusercontent.com/assets/4006691/10522491/4f5bc0a4-736d-11e5-9810-dbe35c5398cd.png)

**Comment by xmd5a2** [comment]
@Barrocas these straing lines are deleted objects without geometry. Please modify your rendering style with line mentioned above. Although not sure this will help with flooding.

**Comment by Barrocas** [comment]
I placed the line, but it had no effect whatsoever. Does it have to be in
any line in particular?

Here is my rendering file:

<?xml version="1.0" encoding="utf-8"?>
<renderingStyle name="DottedRoute" depends="default" defaultColor="#ff00aa"
version="1">

     <renderingAttribute name="route">
        <filter pathEffect="8_6" strokeWidth="10" color="#00FF00">
            <filter nightMode="true"/>
        </filter>
    </renderingAttribute>
     <renderingAttribute name="gpx">
        <filter strokeWidth="2" color="#FF0000">
            <filter nightMode="true"/>
        </filter>
    </renderingAttribute>
<case tag="osmand_change" value="delete"/>
</renderingStyle>


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by xmd5a2** [comment]
```xml
<line>
  <case tag="osmand_change" value="delete"/>
</line>
```
But your style depends of "default", strange enough that you see these straight lines.

**Comment by mircozorzo** [comment]
For sure the relation highlighted in this two screenshot aren't still existing because I've changed it. After any days I've made live updates but rendering ghost relation is still there. I've checked the osm dates, all right. In my opinion not all data deleted on osm is deleted from the live update. Screenshot refers to Italy-Padua-Piazza del Santo for 21-14-13 and Italy-Padua-Ponte sul Brenta for 21-14-09.
     
![photo_2015-10-15_21-14-13](https://cloud.githubusercontent.com/assets/2377449/10524811/b9d6381a-7381-11e5-9787-3cf44235ca25.jpg)
![photo_2015-10-15_21-14-09](https://cloud.githubusercontent.com/assets/2377449/10524812/b9d712ee-7381-11e5-822c-4c715897c0a2.jpg)

**Comment by xmd5a2** [comment]
We already have found a source of most these issues. It is because of using ```<entity_convert pattern="split"``` in rendering_types.xml. It creates a separate object with new id and this id is not properly processed by live update.

**Comment by Barrocas** [comment]
The line tag still doesn't work, sorry.

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by vshcherb** [comment]
Live updates is fixed in nightlies.

**Comment by Barrocas** [comment]
Yes, now when we click on Live Updates it does not list how many updates
there are, and it's not necessary to click on the bottom bar to begin
download, it just downloads straight away.

I still see the straight cut lines, though, but good job!


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by CJTmmr** [comment]
Hi all,

I really like the live updates.

Found an issue;
I changed [this](http://www.openstreetmap.org/way/90673949#map=19/52.02270/4.67538&layers=D) road segment in Gouda. The Netherlands on 12th of October 2015

from **highway=secondary**

to **highway=construction** 
    **construction=secondary**

This segment is blocked for temporary road constructions from 10th Oct 2015 to 20th Nov 2015.
A good example of how usefull live-updates can be.

With latest nightly's and live updates for Netherland_europe map the segment is rendered okay, with the nice new construction/secondary line-pattern:
![2015-10-13 13 01 04](https://cloud.githubusercontent.com/assets/15076257/10710400/9fa1b5c6-7a59-11e5-918e-e6d6d47e6913.png)

But OsmAnd OffLine routing still uses this segment:
![2015-10-13 06 26 48](https://cloud.githubusercontent.com/assets/15076257/10710409/c0434a06-7a59-11e5-9a25-94e396e38871.png)

Hopefully this is helpful for finding an solution.

Cheers,

CJTmmr

**Comment by Barrocas** [comment]
![screenshot_2015-10-12-22-19-56](https://cloud.githubusercontent.com/assets/4006691/10759522/a34406c2-7caf-11e5-8533-e0fecdecf649.png)
Another screenshot of the 'cutting lines' coming out of the city of Ponte Vedra, and resulting flooding of land areas.

![screenshot_2015-10-27-13-43-06](https://cloud.githubusercontent.com/assets/4006691/10759783/481d5044-7cb1-11e5-9245-6a15b5994161.png)

And viewed from openstreetmap
![screenshot_2015-10-27-13-45-31](https://cloud.githubusercontent.com/assets/4006691/10759801/698fc734-7cb1-11e5-9649-a1bcdbe59e8e.png)

**Comment by aceman444** [comment]
This is still an issue in current nightlies. The updated objects do not fully replace the old versions of them.

**Comment by Barrocas** [comment]
Screenshot of a modified highway=motorway_junction, when passing there today, I noticed that there were the new version and the previous version, both displayed side by side. Panning and zooming the previous version disappears sometimes.

![screenshot_2015-11-11-09-27-31](https://cloud.githubusercontent.com/assets/4006691/11089214/12e4ba42-8860-11e5-9c59-c0f6ada4f328.png)
. It didn't affect routing.

**Comment by CJTmmr** [comment]
Another example:
map: The Netherlands from 2015-02-01
with live updates from 2015-05-04
A new Road: Reeuwijkse Randweg was opened:
way: http://www.openstreetmap.org/way/385911755 
It was modified a few times between Feb 1 and Feb 3 after I made GPS-tracks.
On 3 Feb I also added max-speed;
Now OsmAnd offline routing still routes the old way (with no max_speed set...) ; while rendering is okay:

![2016-02-05 14 26 46](https://cloud.githubusercontent.com/assets/15076257/12866219/2ef207de-ccc7-11e5-8fb5-421e5755f54e.png)

**Comment by vshcherb** [comment]
Fixed. Tested turn restriction http://www.openstreetmap.org/relation/6104572. New diffs require new maps and diffs could be found here http://builder.osmand.net/aosmc/
