### ISSUE TITLE
Version 4.3.x crashes on Nexus 7 tablet

### ISSUE THREAD

**Issue by UAb5eSMn** [osmandapp/OsmAnd#16704]
### Description
Version 4.3.x crash on Google Nexus 7

### Steps to reproduce
 Install 4.3.12 and start Osmand

### Actual result
The application crashes soon after starting it (even without interacting with it). It's probably OpenGL related.

### Your Environment
OsmAnd Version: 4.3.12, downloaded from free-versions on the osmand.net website (I tested other 4.3.x versions before and none work). Version 4.2.x and OsmAnd-default.apk 4.4.0#35568m 2023-03-14 do not crash.
Android/iOS version: Android 11, LineageOS 18.1-20230301-NIGHTLY-flox
Device model: Nexus 7 (2013)

[osmand-4.3.12.log](https://github.com/osmandapp/OsmAnd/files/10973542/osmand-4.3.12.log)

**Comment by Zirochkabila** [comment]
@UAb5eSMn Reproduce failed
It is possible that this is related to the behavior described in https://github.com/osmandapp/OsmAnd/issues/16504.
Please install the nightly version and try again https://osmand.net/docs/versions/nightly_versions

**Comment by UAb5eSMn** [comment]
> It is possible that this is related to the behavior described in #16504.

That issue looks different to me. In that issue, Osmand shows a message about the crash. In my case, the app starts, and simply closes after about 10 seconds or so. The only errors are in the android log.

> Please install the nightly version and try again https://osmand.net/docs/versions/nightly_versions

I had already tried the nightly version in my original report and that version works:
Version 4.2.x and OsmAnd-default.apk 4.4.0#35568m 2023-03-14 do not crash.

**Comment by Zirochkabila** [comment]
@UAb5eSMn IIt is believed that this was one of the bugs that were fixed, which is why the night version works without fail.
But, in any case, we will keep an eye on this behavior

**Comment by UAb5eSMn** [comment]
OK, thank you. I will re-test when 4.4 is released.

**Comment by UAb5eSMn** [comment]
Today I re-tested with version 4.4.7 from https://download.osmand.net/releases/net.osmand-4.4.7-4407.apk
That version still crashes. I've attached tombstones for 4.3.12 and 4.4.7.
[tombstone_31-4.3.12.txt](https://github.com/osmandapp/OsmAnd/files/11360907/tombstone_31-4.3.12.txt)
[tombstone_21-4.4.7.txt](https://github.com/osmandapp/OsmAnd/files/11360910/tombstone_21-4.4.7.txt)

**Comment by Zirochkabila** [comment]
@UAb5eSMn  Most likely, it's all about LineageOS - I need to check with @vshcherb  what we do in such cases.

**Comment by UAb5eSMn** [comment]
> @UAb5eSMn Most likely, it's all about LineageOS - I need to check with @vshcherb what we do in such cases.

I assumed it was an OpenGL issue or just the age of my device, but lineageos could be the cause. I don't have google apps on it.

I performed some additional tests with nightly builds. These versions work:
OsmAnd Nightly 4.4.0#35568m, released 2023-03-14
OsmAnd Nightly 4.5.0#35866m, released 2023-04-30

But I had to use https://download.osmand.net/latest-night-build/OsmAnd-default-legacy.apk for the 2023-04-30 nightly build. The default download https://download.osmand.net/latest-night-build/OsmAnd-default.apk had installation issues on my device, so I was unable to test with that.
