### ISSUE TITLE
improve rendering of natural=cliff ?

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#1714]
is it possible to specify "pattern" kind line types such cliffs? Did not find anything in the documentation

**Comment by xmd5a2** [comment]
What pattern are you talking about? pathEffect?

**Comment by Zahnstocher** [comment]
I think he means direction dependent path rendering (left side line, right side spikes).
The top of the cliff is on the left side of the way direction and the bottom on the right side.
Example:
https://www.openstreetmap.org/way/161531283

**Comment by xmd5a2** [comment]
This can't be done in old engine but already done with OpenGL engine (some months ago).

**Comment by RicoZ-OSM** [comment]
@xmd5a2 : cool, is also a necessary precondition for rendering cutting & embankment

**Comment by RicoZ-OSM** [comment]
I see embankments are now rendered very nicely, is it just a matter of tweaking some configuration file?

**Comment by sonora** [comment]
Fixed, in v2 engine, I guess.

**Comment by endolith** [comment]
I installed OsmAnd, enabled the "OsmAnd development" plugin, turned on "Use OpenGL rendering", yet cliffs are still shown as green lines with symmetrical shape, not showing the direction of the cliff.  Is this really fixed?
