### ISSUE TITLE
Osmand keeps repeating "route recalculated, distance x kilometers" after deviating from route

### ISSUE THREAD

**Issue by forfucsake** [osmandapp/OsmAnd#17575]
### Expected result

**Environment**
OsmAnd Version:
Android/iOS version:
Device model:

**Comment by DmitryAlexei** [comment]
@forfucsake 
Please clarify:

The device you use, OS version, OsmAnd version
Route, start and finish coordinates
The presence of traffic restrictions
A short video and screenshots where we could see the error
Logcat file: Menu > Help > Send logcat log

**Comment by sonora** [comment]
It sounds a bit like #16315 and #16571, but by my testing has been fixed a while ago, certainly in the later 4.4 releases.

**Comment by forfucsake** [comment]
> It sounds a bit like #16315 and #16571, but by my testing has been fixed a while ago, certainly in the later 4.4 releases.

thank's, I just realized I was running 4.3.7. Will open a new report if I find the issue persists after the update.

**Comment by forfucsake** [comment]
> @forfucsake Please clarify:
> 
> The device you use, OS version, OsmAnd version Route, start and finish coordinates The presence of traffic restrictions A short video and screenshots where we could see the error Logcat file: Menu > Help > Send logcat log

OSMand 4.3.7 on a cheap Chinese Umidigi Bison phone with Android 11.
No traffic restriction. Just me chosing a different route than suggested.

**Comment by Nine-Tailed** [comment]
> OSMand 4.3.7

you have a very outdated version.

**Comment by DmitryAlexei** [comment]
@forfucsake 
Try updating to the latest version (preferably beta from Play Store), your problem is probably already solved. 
If the bug does not reproduce, please close the ticket.

**Comment by forfucsake** [comment]
> @forfucsake Please clarify:
> 
> The device you use, OS version, OsmAnd version Route, start and finish coordinates The presence of traffic restrictions A short video and screenshots where we could see the error Logcat file: Menu > Help > Send logcat log

OSMand 4.3.7 on a cheap Chinese Umidigi Bison phone with Android 11.
No traffic restriction. Just me chosing a different route than suggested.

**Comment by forfucsake** [comment]
sorry. was referring to old version

**Comment by EssBee59** [comment]
Hello,

I had yesterday many times the same problem (route recalculated) with Osmand 4.7.12.
(In the worst case the message is spoken more than 20 times)

My system:
Xiaomi MI 12T Pro, android 14
Brouter as routing engine

Would be nice to get this message only once within an area or within a fixed time, a.e. 30 seconds

**Comment by vshcherb** [comment]
> (In the worst case the message is spoken more than 20 times)

There is a delay I think in the code. Obviously we can mute too often repeated message for 5 minutes after 3rd announcement.

**Comment by EssBee59** [comment]
Hello vshcherb,
Not sure it can help, but in the attached file, you can see every call to the Brouter in my tripp.
Some times only one recalculation is done, some times N recalculations are done (nearly every second)

[debug_repeat.txt](https://github.com/osmandapp/OsmAnd/files/15209439/debug_repeat.txt)

I have not a perfect solution, I would mute the message repeating for 1 minute, every time...
Regards and thank for your work
Essbee

**Comment by EssBee59** [comment]
Hello vshcherb,

For a better understanding of the start situation at 16:36:16 I transformed the first call from Osmand to the Brouter in a brouter-web request.
 https://brouter.de/essbee/#map=13/49.9960/8.5413/osm-mapnik-german_style&lonlats=8.438828,49.985776;8.671448,50.027508&profile=trekking_SB

So you can see the distance from my position to the next highway at all (track/cycleway...).

I think, the current behaviour of Osmand is ok: 
(due to the distance, a recalc is triggered...untill the biker is on a highway)

To come back to the spoken message, a better solution as above would be:
- first message is spoken, then mute this message type for 1 minute
- if the recalc stopps , then repeat the lat (muted) message 
regards
