### ISSUE TITLE
App crashes: screen orientation is changed on uploading poi

### ISSUE THREAD

**Issue by muzirian** [osmandapp/Osmand#1776]
app crashes when screen orientation is chnaged,while  Uploading poi to osm.crash reports have been mailed.
Even though the app crashes pois seem to be uploaded.

**Comment by vshcherb** [comment]
Could you please attach some content of that file here.

**Comment by muzirian** [comment]
Thanks for reply, attaching log

Version  OsmAnd 2.1.1
29.07.2015 5:17:32
Apk Version : 2.1.1 212
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{32ba5a52 V.E..... R.....I. 0,0-777,411} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
	at android.app.Dialog.dismissDialog(Dialog.java:341)
	at android.app.Dialog.dismiss(Dialog.java:324)
	at net.osmand.plus.osmedit.UploadOpenstreetmapPointAsyncTask.onPostExecute(UploadOpenstreetmapPointAsyncTask.java:104)
	at net.osmand.plus.osmedit.UploadOpenstreetmapPointAsyncTask.onPostExecute(UploadOpenstreetmapPointAsyncTask.java:15)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5289)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
Version  OsmAnd 2.1.1
29.07.2015 5:17:32
Apk Version : 2.1.1 212
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{32ba5a52 V.E..... R.....I. 0,0-777,411} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
	at android.app.Dialog.dismissDialog(Dialog.java:341)
	at android.app.Dialog.dismiss(Dialog.java:324)
	at net.osmand.plus.osmedit.UploadOpenstreetmapPointAsyncTask.onPostExecute(UploadOpenstreetmapPointAsyncTask.java:104)
	at net.osmand.plus.osmedit.UploadOpenstreetmapPointAsyncTask.onPostExecute(UploadOpenstreetmapPointAsyncTask.java:15)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5289)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
Version  OsmAnd 2.1.1
22.08.2015 9:50:45
Apk Version : 2.1.1 212
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalStateException: Fragment OsmEditsFragment{3bbd432c} not attached to Activity
	at android.support.v4.app.Fragment.getResources(Fragment.java:620)
	at android.support.v4.app.Fragment.getString(Fragment.java:642)
	at net.osmand.plus.osmedit.OsmEditsFragment.uploadEnded(OsmEditsFragment.java:626)
	at net.osmand.plus.osmedit.UploadOpenstreetmapPointAsyncTask.onPostExecute(UploadOpenstreetmapPointAsyncTask.java:106)
	at net.osmand.plus.osmedit.UploadOpenstreetmapPointAsyncTask.onPostExecute(UploadOpenstreetmapPointAsyncTask.java:15)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5289)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
Version  OsmAnd 2.1.1
22.08.2015 9:50:45
Apk Version : 2.1.1 212
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalStateException: Fragment OsmEditsFragment{3bbd432c} not attached to Activity
	at android.support.v4.app.Fragment.getResources(Fragment.java:620)
	at android.support.v4.app.Fragment.getString(Fragment.java:642)
	at net.osmand.plus.osmedit.OsmEditsFragment.uploadEnded(OsmEditsFragment.java:626)
	at net.osmand.plus.osmedit.UploadOpenstreetmapPointAsyncTask.onPostExecute(UploadOpenstreetmapPointAsyncTask.java:106)
	at net.osmand.plus.osmedit.UploadOpenstreetmapPointAsyncTask.onPostExecute(UploadOpenstreetmapPointAsyncTask.java:15)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5289)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
Version  OsmAnd 2.1.1
21.09.2015 4:26:44
Apk Version : 2.1.1 212
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{1b8a4a8f V.E..... R.....I. 0,0-729,411} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
	at android.app.Dialog.dismissDialog(Dialog.java:341)
	at android.app.Dialog.dismiss(Dialog.java:324)
	at net.osmand.plus.osmedit.UploadOpenstreetmapPointAsyncTask.onPostExecute(UploadOpenstreetmapPointAsyncTask.java:104)
	at net.osmand.plus.osmedit.UploadOpenstreetmapPointAsyncTask.onPostExecute(UploadOpenstreetmapPointAsyncTask.java:15)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5289)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
Version  OsmAnd 2.1.1
21.09.2015 4:26:44
Apk Version : 2.1.1 212
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{1b8a4a8f V.E..... R.....I. 0,0-729,411} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
	at android.app.Dialog.dismissDialog(Dialog.java:341)
	at android.app.Dialog.dismiss(Dialog.java:324)
	at net.osmand.plus.osmedit.UploadOpenstreetmapPointAsyncTask.onPostExecute(UploadOpenstreetmapPointAsyncTask.java:104)
	at net.osmand.plus.osmedit.UploadOpenstreetmapPointAsyncTask.onPostExecute(UploadOpenstreetmapPointAsyncTask.java:15)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5289)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
Version  OsmAnd 2.1.1
06.10.2015 3:18:44
Apk Version : 2.1.1 212
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{3de4e513 V.E..... R.....I. 0,0-729,411} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
	at android.app.Dialog.dismissDialog(Dialog.java:341)
	at android.app.Dialog.dismiss(Dialog.java:324)
	at net.osmand.plus.osmedit.UploadOpenstreetmapPointAsyncTask.onPostExecute(UploadOpenstreetmapPointAsyncTask.java:104)
	at net.osmand.plus.osmedit.UploadOpenstreetmapPointAsyncTask.onPostExecute(UploadOpenstreetmapPointAsyncTask.java:15)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Version  OsmAnd 2.1.1
06.10.2015 3:18:44
Apk Version : 2.1.1 212
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{3de4e513 V.E..... R.....I. 0,0-729,411} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
	at android.app.Dialog.dismissDialog(Dialog.java:341)
	at android.app.Dialog.dismiss(Dialog.java:324)
	at net.osmand.plus.osmedit.UploadOpenstreetmapPointAsyncTask.onPostExecute(UploadOpenstreetmapPointAsyncTask.java:104)
	at net.osmand.plus.osmedit.UploadOpenstreetmapPointAsyncTask.onPostExecute(UploadOpenstreetmapPointAsyncTask.java:15)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by GaidamakUA** [comment]
@muzirian It should be fixed now, but please confirm.

**Comment by muzirian** [comment]
Will check when update is pushed to the app

**Comment by muzirian** [comment]
@gaidmakua im on ver 2.2 from playstore, the problem isnt fixed

**Comment by GaidamakUA** [comment]
@muzirian A lot of changes has been made. Please attach new log.

**Comment by vshcherb** [comment]
Deprecated

**Comment by muzirian** [comment]
Couldnt find a way to copy log thus time, logs are sent via google play

**Comment by muzirian** [comment]
Sry fir being late, log is attched.
[Uploading exception.txt…]()

**Comment by muzirian** [comment]
[exception.txt](https://github.com/osmandapp/Osmand/files/53569/exception.txt)
 Log attached
