### ISSUE TITLE
Motor_vehicle:conditional dates not functioning

### ISSUE THREAD

**Issue by NickKatchur** [osmandapp/OsmAnd#17914]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

car
### Start and end points

Kirkwood Avenue (West of Indiana Ave) Bloomington, IN USA

### Actual and expected routes

The road is closed to vehicle traffic at all times during the summer (specific dates listed in the tag), but routes are still being made down the street.

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

</code></pre>

**Device and Android/iOS version:**
iOS 4.4.5

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
Updated map is being used. Consider temporary conditions is on.

**Comment by DmitryAlexei** [comment]
Try updating to the latest version of the app, the problem should have been solved.


https://github.com/osmandapp/OsmAnd/issues/17048

**Comment by NickKatchur** [comment]
Let me preface with the current App Store version (4.4.5) doesn’t fix this. But this is resolved when using the TestFlight beta version (4.4.10.7) so it should work it’s way in eventually. Thanks
