### ISSUE TITLE
favorites: duplicates can not be selected and deleted...

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#17977]
## Description
Somehow it happened, I duplicated all my favorites. 

So I tried to select and delete those duplicates:
my places / favorites / trash bin / selecting every second favorite, every duplicate. I continue one by one by one (every second is marked), and suddenly it happens, that from all selected favorites both, also the ones I want to keep, are marked for delete, automatically!
Tried it a few times, happens always. Like this, it is not possible for me to delete all the duplicates I produced...

Happens in +4.5.10, but I remember, it was also in some previous version like this. My workaround then was replacing the favorites file from a backup. But unfortunately now I can´t do this, the backup also contains the duplicates...

I can select and delete around 20 duplicates before this "marking" happens. When around 30, it happens to mark both of the selected favorites. But it is independent from the selected number, it happens somehow after a certain time. I also can select 15 or 20 and wait, it happens after some seconds.

### Expected result

**Environment**
OsmAnd Version:
Android/iOS version:
Device model:

**Comment by DmitryAlexei** [comment]
@Rowin63 can you make a short video of your issue?
Do you use OsmAnd cloud?
Do you use Auto backup? (https://docs.osmand.net/docs/user/personal/global-settings#auto-backup)

**Comment by Rowin63** [comment]
Here´s the video. 
Behaviour is different today, happens much quicker then last time. Perhaps depending on how busy Osmand is at the moment. You can see, as soon as I select the duplicate, almost immediately the other entry is selected automatically too.

No, I don´t use the cloud.
Yes, "Auto Backup" is set to "on", but the device was in "flight mode". 
(perhaps "auto backup" and "cloud", which I did use some time ago, was the reason to come to all the duplicates).

Anyway, I cant´get rid of them now :-)
As I mentioned before, it´s no new issue in +4.5.10, it happened already weeks or months ago in an earlier version.

https://github.com/osmandapp/OsmAnd/assets/95540936/d4ed8a79-96d4-4580-9360-422d7f9baa5a

**Comment by Rowin63** [comment]
I solved the problem by deleting the favourites and get a copy from another device 👍

**Comment by DmitryAlexei** [comment]
@Rowin63 In your opinion, what was the reason for this behavior?

**Comment by Rowin63** [comment]
I don't really know, but perhaps the fact, that there are two absolutely identical entries in the favorite.gpx file? And then the app gets confused about? Just a guess.

**Comment by Rowin63** [comment]
Yes, I can confirm, it is because the duplicates are _absolutely exact_ duplicates. 
Just changing the symbol or the colour and it does not happen anymore 👍

**Comment by sonora** [comment]
It sound like a bug, then. We should in the app either
- identify and remove "absolutely exact duplicates",
- or we allow them, then the app must be able to treat them separately, e.g. via a uniqe primary key in the favorites database.

**Comment by vshcherb** [comment]
Favroties couldn't be exact duplicates so it's bug during import / copy / etc, actually it should have checks for such situations it looks strange of course

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#792m, released: 2023-09-21
[logcat.log](https://github.com/osmandapp/OsmAnd/files/12698574/logcat.log)

- duplicates of favorites were created while synchronizing with the Cloud between different devices
- when trying to select one of the duplicates (using bulk select in *My places* menu) second one is marked automatically (sometimes 20-30 seconds needed) 
- duplicates of favorites can be deleted using My places, if you manage to do it faster, than second one will be marked

<table style="width:100%">
  <tr>
    <th>Video 1</th>
    <th>Video 2</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/116079541/ca4e7a4c-0a2b-47fc-aeac-20ce210bfe29"  width="200" height="auto"/></td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/116079541/56cd82c2-c42e-451b-a92b-1ce1b44da051"  width="200" height="auto"/></td>
  </tr>

**Comment by DmitryAlexei** [comment]
- when trying to delete duplicates of favorites using *Map context menu* app freezes and sometimes crashes
- duplicates cannot be deleted

https://github.com/osmandapp/OsmAnd/assets/116079541/ac6d5c12-3403-422d-8bcb-3e151b5738d2

**Comment by vshcherb** [comment]
Critical bug for cloud synchronization - favorites should never have duplicates!

**Comment by DmitryAlexei** [comment]
Tested on 2 Android devices with OsmAnd~ 4.6.0#997m, released: 2023-11-08
- duplicates of favorites cannot be created using steps from the message (https://github.com/osmandapp/OsmAnd/issues/18241#issuecomment-1744562603) 
- while importing backup with duplicates of favorites, copies are deleted, and you obtain only one favorite point

**Comment by eurosoba** [comment]
I have much the same problem.
Frequent changes of phone means that I have four copies of every favourite.
Although it looks like you can delete them by checkboxing them it doesn't actually work.
Here's what happens:
Checkbox 3 of the 4 identical entries
Press the dustbin icon
Message to say that I'm going to delete 1 favourite
Press delete
Only one of the three is actually deleted

Apart from the fact that this should work, it would far better if imports of duplicate entries were prevented in the first place!

**Comment by Busterama452** [comment]
This problem was fixed.

**Comment by eurosoba** [comment]
So how come I'm still getting it as of 10 minutes ago?  ---- On Sat, 16 Mar 2024 18:12:15 +0000  ***@***.***  wrote ----
This problem was fixed.

**Comment by Rowin63** [comment]
"duplicates can not be deleted" is back
