### ISSUE TITLE
Guiding instructions replace accentuated characters with non-accentuated characters in french names

### ISSUE THREAD

**Issue by breversa** [osmandapp/OsmAnd#18149]
## Description
Guiding instructions replace accentuated characters with non-accentuated characters both in display and voice (TTS) guidance.

### How to reproduce
1. Plan a route from point A to point B, that goes through roads/streets that have accentuated characters in their name (at least in french).
2. Follow the instructions or check the route’s details.

### Actual result
Both the displayed names and the TTS voice guidance use non-accentuated characters instead of accentuated characters (ex: "Avenue Jean Jaur**e**s" instead of "Avenue Jean Jaur**è**s", or "Rue des J**e**suites" instead of "Rue des J**é**suites").

Please note that it only happens during guidance, and that names on the map are correct (= use accentuated characters).

It’s as if the voice guidance takes the names from the map, runs an accent-removable process, then displays/pronounces the accent-less names. :-/

### Expected result
Accentuated street names are displayed and pronounced with accents.

**Environment**
OsmAnd Version: 4.5.8 from F-Droid
Android/iOS version: Android 10 (/e/OS 1.14)
Device model: Samsung Galaxy S9

Maps:
France Grand Est Bas-Rhin 2023-09-01 02:00

**Comment by breversa** [comment]
![Screenshot_20230913-131741_OsmAnd~_1](https://github.com/osmandapp/OsmAnd/assets/2071276/de27dacf-b5bb-4a7b-ae23-27a142a1434d)
![Screenshot_20230913-131855_OsmAnd~_1](https://github.com/osmandapp/OsmAnd/assets/2071276/5b3931ec-49c6-4404-8f18-05cbd9d4a91e)

**Comment by TheSnoozer** [comment]
Example from above can be found under [48.57184/7.75663](https://www.openstreetmap.org/#map=19/48.57184/7.75663)

**Comment by TheSnoozer** [comment]
Can't reproduce with
```
Device : RE513CL1
Brand : realme
Model : RMX3241
Product : RMX3241EEA
Build : RMX3241_11_F.07
Version : 13
App Version : OsmAnd+
Apk Version : 4.5.10 4510
```
and german as language
![photo_2023-09-13_18-13-30](https://github.com/osmandapp/OsmAnd/assets/6849390/1145ad08-783c-4441-aa21-60217c8f2f2a)

So maybe this is already fixed. Note I'm using OsmAnd 4.5.10 while the reporter uses 4.5.8

**Comment by breversa** [comment]
After updating to 4.5.10, I still have the same issue :
![Screenshot_20230914-085328_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/2071276/0691e246-f591-420f-b44b-a8f564a6e675)

**Comment by TheSnoozer** [comment]
Still can't reproduce with
```
Device : RE513CL1
Brand : realme
Model : RMX3241
Product : RMX3241EEA
Build : RMX3241_11_F.07
Version : 13
App Version : OsmAnd+
Apk Version : 4.5.10 4510
```
Maps last updated on 01 Sept 2023

Tested the following conditions
- Old location: [48.57184/7.75663](https://www.openstreetmap.org/#map=19/48.57184/7.75663)
- New location: [48.53929/7.76363](https://www.openstreetmap.org/#map=19/48.53929/7.76363)

both tested with
- german / french
- map rending V1 / map rending V2 (OpenGL)

Simply no luck to reproduce (yet).

Screenshots:
<details>
1.

![photo_2023-09-14_21-10-38](https://github.com/osmandapp/OsmAnd/assets/6849390/ea9f47dd-ff2d-4c6f-a380-ffe386d33579)
2.
![photo_2023-09-14_21-10-34](https://github.com/osmandapp/OsmAnd/assets/6849390/ef71efaf-6287-48a1-94d1-27304e35ecb8)
3.
![photo_2023-09-14_21-10-31](https://github.com/osmandapp/OsmAnd/assets/6849390/c8db45a7-c404-448d-9e1f-9f58cf0bd1df)
4.
![photo_2023-09-14_21-10-27](https://github.com/osmandapp/OsmAnd/assets/6849390/c3ebaf27-f581-4c80-a89d-ba8686a0a827)
5.
![photo_2023-09-14_21-10-22](https://github.com/osmandapp/OsmAnd/assets/6849390/935e6845-c8e2-435e-a637-5a17894596f4)
</details>

**Comment by DmitryAlexei** [comment]
The issue is similar to https://github.com/osmandapp/OsmAnd/issues/18129 and can be reproduced when Map language is set to English

Steps to reproduce:
- in menu > configure map > map language set **English**
- in menu > navigation > settings > Sound > choose Language French and Announce: Street names (TTS)

Actual result:
- in route simulation I can not notice big difference in pronunciation (accentuated characters and not), but in route details the difference is noticeable (see screenshots)

<table style="width:100%">
  <tr>
    <th>map language french</th>
    <th>map language english</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/fcf62526-bad1-4f67-90bc-d49df3ec3faa"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/9b4b96a8-7f8f-49bc-8d31-fc5dd21341bb"  width="300" height="auto"/> </td>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/0fa18827-908f-40b9-8d83-342c895f8b01"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/1aa1fc11-fb7e-45d2-b965-a432003fe415"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
interesting, that when you use *Use latin names when missing* option, accents disappear in **Street name widget**

<table style="width:100%">
  <tr>
    <th>Map language set to English, Use latin names when missing enabled</th>
    <th>Map language set to English or Polish (without second option) </th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/c62459f4-4629-4593-842a-f34c0dcecab1"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/27650db3-b81e-4555-9d78-be0752bf35a0"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by breversa** [comment]
Proposed solution:
Latin names should use the https://www.w3schools.com/charsets/ref_utf_latin_extended_a.asp charset?
