### ISSUE TITLE
Lost details when using contour lines

### ISSUE THREAD

**Issue by Herman-n** [osmandapp/OsmAnd#18325]
### Description

When using "streets only"-maps together with "contour lines" together with "Rendering Engine Version 2" most map details are invisible.
View is OK:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/143877180/326e49f2-dc00-4ddc-afc5-c9e9bd74f848"  width="300" height="auto"/> </td>
  </tr>
</table>

View is damaged:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/143877180/d5235615-1ab9-4f10-ab2c-fefcde514783"  width="300" height="auto"/> </td>
  </tr>
</table>

(Example location is: "Logger 41, 1186 RM Amstelveen, Netherlands")
(Additional pictures and German description see here: https://www.android-hilfe.de/forum/osmand.1405/osmand-erfahrungsaustausch.207329-page-61.html#post-13628015 )

### Steps to reproduce

Load "streets only"-map (make sure, that no "standard map" for the same area exists).
Load "contour lines" for the same area.
Use "Rendering Engine Version 2".
Zoom around and watch details disappearing...

Everything is OK after deleting contour lines,
or when using "Rendering Engine Version 1", or when using "standard map".

### Actual result

Details disappear depending on the zoom level.

### Expected result

All details visible.

### Your Environment (required)

OsmAnd Version: 4.5.10 (OsmAnd+ from Play Store)
Android version: 13
Device model: Samsung Galaxy S21 5G
Crash-Logs: no crashes

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. When using Rendering Version 1, the map's level of detail is significantly lower, regardless of the Contour Lines being loaded. In Version 2 (OpenGl), the detail is improved, with blocks and streets being visible even when contour lines are loaded. To reproduce the issue, follow these steps:

- Download the Roads-only map of North Holland, Netherlands.
- Navigate to the coordinates 52.282091407457, 4.862700206601706.
- Examine the map at zoom level 13, first on the second rendering version, and then on the first version.
- Download Contour lines for the Netherlands.
- Recheck the map at zoom level 13, first on the second rendering version, and then on the first version.

OsmAnd~ 4.6.0#868m, released: 2023-10-13

<table style="width:100%">
  </tr>
  <tr>
    <th>Rendering V1. No CL</th>
    <th>Rendering V2. No CL</th>
    <th>Rendering V1. With CL</th>
    <th>Rendering V2. With CL</th>
  </tr>
  <tr>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/ab7ac910-e60e-4fae-8467-fbce147b4eec"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/57ea4452-1d97-4fd2-820b-9fa3bc1fb26f"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/9893f8d8-00f5-43e9-aa1d-c81bbf7d81a8"  width="300" height="auto"/> </th>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/f9191f7a-6939-463e-a3c8-387ec391d9b1"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Herman-n** [comment]
Does this mean, that this issue is fixed with version 4.6.0?

If not sure: Is someone able to test with same OsmAnd-version 4.5.10 on same device model "S21"?

**Comment by vshcherb** [comment]
I don't think it's fixed it's just not reproduced. We need to test mainly Rendering Engine v2 with contour lines.

So we need to retest it on 4.5 release version somehow

**Comment by Herman-n** [comment]
Just for information:
Same issue with OsmAnd 4.5.10 on Samsung Galaxy S23 / Android 14

**Comment by zipav** [comment]
```
OsmAnd Version: OsmAnd 4.5.10, released: 2023-08-09
Android version: 12
Device model: Nokia 5.3
```


<table style="width:100%">
  </tr>
  <tr>
    <th>Rendering V1. No CL</th>
    <th>Rendering V1. With CL</th>
    <th>Rendering V2. No CL</th>
    <th>Rendering V2. With CL</th>
  </tr>
  <tr>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/a41b607e-59c1-4efb-b6bf-16e17537abd6"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/2748541a-a78d-4d8e-8fa3-badbdcf22361"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/e6941298-6ea7-417a-868c-16c4b4968e97"  width="300" height="auto"/> </th>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/571df537-5017-490c-9511-5a72f3f74243"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Herman-n** [comment]
"completed"!!??
The issue still exists...
But I don't care. I will not use contour lines anymore...

**Comment by vshcherb** [comment]
We didn't manage to reproduce unforunately, what would you suggest us to do?

**Comment by Herman-n** [comment]
It's OK to close this issue. Seems to be an extremely rare case facing this issue.
I just wanted to notice, that there is no resolution for this topic at the moment.
Thank You!

**Comment by Herman-n** [comment]
Version 4.6.9 (Playstore): Issue persists.

(As I wrote before: This doesn't matter, because I don't use contour lines anymore...)

Happy holidays!

**Comment by Herman-n** [comment]
Version 4.6.11 (Playstore): Issue persists.

**Comment by Herman-n** [comment]
Info: Using version 4.7.9 I cannot reproduce the issue. 
Thank you for fixing!
