### ISSUE TITLE
HH C++ Routing crashes on a long route

### ISSUE THREAD

**Issue by Guylby** [osmandapp/OsmAnd#19266]
### Description

When attempting to calculate long routes (>900kms), Osmand stops calculating after a certain time with a notification : "Could not calculate route: not enough process memory". 
Sometimes this result in a crash.
With the now old routing system, with a modified Heuristic coefficient of 1.8, Osmand did not have a problem and could calculate those routes.

I've checked with the "Available RAM" widget and there was always at least 300MB shown available. 

I've joined some crash logs related to this issue (osmand crashed while calculating these itineraries): (some are from 4.7.1 as this issue was already present there with "Special routing" enabled):

### Steps to reproduce

Coordinates:
Start position: 43.11775°N, 5.93502° E (Toulon, France)

End position: 47.46931° N, 0.54485° W (Angers, France)

What is strange is that this itinerary calculated with online routing is only 931kms long, but cannot be calculated with the Osmand offline routing.

But if you change the end position to: 51.03231°N, 2.37593° E (Dunkirk, France), Osmand offline routing has no trouble calculating it even though it's 1144kms long. 

### Actual result

Osmand either crashes or can't calculate the route. 

### Expected result

Osmand does nos crash and calculates route

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.3
Android/iOS version: Android 13
Device model: Sony Xperia 10 III 6Go Ram 
Crash-Logs: 

> Version  OsmAnd+ 4.7.1
> 13.02.2024 2:41:51
> Apk Version : 4.7.1 4701
> Exception occurred in thread Thread[main,5,main] : 
> java.lang.OutOfMemoryError: Failed to allocate a 256 byte allocation with 78888 free bytes and 77KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
> 	at java.lang.Object.internalClone(Native Method)
> 	at java.lang.Object.clone(Object.java:267)
> 	at java.util.Arrays$ArrayList.toArray(Arrays.java:4192)
> 	at java.util.ArrayList.<init>(ArrayList.java:188)
> 	at net.osmand.plus.views.mapwidgets.MapWidgetInfo.getWidgetsVisibility(MapWidgetInfo.java:193)
> 	at net.osmand.plus.views.mapwidgets.MapWidgetInfo.isEnabledForAppMode(MapWidgetInfo.java:158)
> 	at net.osmand.plus.views.mapwidgets.MapWidgetRegistry.updateWidgetsInfo(MapWidgetRegistry.java:65)
> 	at net.osmand.plus.views.layers.MapInfoLayer.onDraw(MapInfoLayer.java:378)
> 	at net.osmand.plus.views.OsmandMapTileView.drawOverMap(OsmandMapTileView.java:1120)
> 	at net.osmand.plus.views.OsmAndMapLayersView.onDraw(OsmAndMapLayersView.java:84)
> 	at android.view.View.draw(View.java:23209)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22076)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
> 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:688)
> 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:786)
> 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4582)
> 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4293)
> 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3520)
> 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2289)
> 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8958)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1319)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1327)
> 	at android.view.Choreographer.doCallbacks(Choreographer.java:985)
> 	at android.view.Choreographer.doFrame(Choreographer.java:916)
> 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1302)
> 	at android.os.Handler.handleCallback(Handler.java:942)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:346)
> 	at android.os.Looper.loop(Looper.java:475)
> 	at android.app.ActivityThread.main(ActivityThread.java:7950)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)


> Version  OsmAnd+ 4.7.1
> 13.02.2024 2:43:27
> Apk Version : 4.7.1 4701
> Exception occurred in thread Thread[main,5,main] : 
> java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 335832 free bytes and 327KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
> 	at android.icu.util.ULocale.getInstance(ULocale.java:4022)
> 	at android.icu.util.ULocale.-$$Nest$smgetInstance(Unknown Source:0)
> 	at android.icu.util.ULocale$Builder.build(ULocale.java:3954)
> 	at libcore.icu.ICU.getCurrencyCode(ICU.java:551)
> 	at java.util.Currency.getInstance(Currency.java:421)
> 	at java.text.DecimalFormatSymbols.initializeCurrency(DecimalFormatSymbols.java:934)
> 	at java.text.DecimalFormatSymbols.getIcuDecimalFormatSymbols(DecimalFormatSymbols.java:1021)
> 	at java.text.DecimalFormat.initPattern(DecimalFormat.java:499)
> 	at java.text.DecimalFormat.<init>(DecimalFormat.java:459)
> 	at net.osmand.plus.utils.OsmAndFormatter.formatValue(OsmAndFormatter.java:680)
> 	at net.osmand.plus.utils.OsmAndFormatter.formatValue(OsmAndFormatter.java:660)
> 	at net.osmand.plus.utils.OsmAndFormatter.getFormattedDistanceValue(OsmAndFormatter.java:446)
> 	at net.osmand.plus.utils.OsmAndFormatter.getFormattedDistance(OsmAndFormatter.java:374)
> 	at net.osmand.plus.utils.OsmAndFormatter.getFormattedDistance(OsmAndFormatter.java:368)
> 	at net.osmand.plus.views.mapwidgets.widgets.NextTurnBaseWidget.updateDistance(NextTurnBaseWidget.java:123)
> 	at net.osmand.plus.views.mapwidgets.widgets.NextTurnBaseWidget.setTurnDistance(NextTurnBaseWidget.java:113)
> 	at net.osmand.plus.views.mapwidgets.widgets.NextTurnWidget.updateInfo(NextTurnWidget.java:83)
> 	at net.osmand.plus.views.mapwidgets.MapWidgetRegistry.updateWidgetsInfo(MapWidgetRegistry.java:66)
> 	at net.osmand.plus.views.layers.MapInfoLayer.onDraw(MapInfoLayer.java:378)
> 	at net.osmand.plus.views.OsmandMapTileView.drawOverMap(OsmandMapTileView.java:1120)
> 	at net.osmand.plus.views.OsmAndMapLayersView.onDraw(OsmAndMapLayersView.java:84)
> 	at android.view.View.draw(View.java:23209)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22076)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
> 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:688)
> 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:786)
> 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4582)
> 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4293)
> 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3520)
> 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2289)
> 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8958)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1319)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1327)
> 	at android.view.Choreographer.doCallbacks(Choreographer.java:985)
> 	at android.view.Choreographer.doFrame(Choreographer.java:916)
> 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1302)
> 	at android.os.Handler.handleCallback(Handler.java:942)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:346)
> 	at android.os.Looper.loop(Looper.java:475)
> 	at android.app.ActivityThread.main(ActivityThread.java:7950)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)


> Version  OsmAnd+ 4.7.3
> 07.03.2024 1:55:02
> Apk Version : 4.7.3 4703
> Exception occurred in thread Thread[main,5,main] : 
> java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 896504 free bytes and 875KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
> 	at java.util.HashMap.newNode(HashMap.java:1878)
> 	at java.util.HashMap.putVal(HashMap.java:627)
> 	at java.util.HashMap.put(HashMap.java:608)
> 	at androidx.constraintlayout.widget.ConstraintSet.clone(ConstraintSet.java:1510)
> 	at net.osmand.plus.views.mapwidgets.widgets.SimpleWidget.updateValueAlign(SimpleWidget.java:67)
> 	at net.osmand.plus.views.controls.VerticalWidgetPanel.updateValueAlign(VerticalWidgetPanel.java:235)
> 	at net.osmand.plus.views.controls.VerticalWidgetPanel.access$800(VerticalWidgetPanel.java:47)
> 	at net.osmand.plus.views.controls.VerticalWidgetPanel$Row.updateRow(VerticalWidgetPanel.java:365)
> 	at net.osmand.plus.views.controls.VerticalWidgetPanel.updateRow(VerticalWidgetPanel.java:200)
> 	at net.osmand.plus.views.layers.MapInfoLayer.updateRow(MapInfoLayer.java:237)
> 	at net.osmand.plus.views.mapwidgets.widgets.SimpleWidget.updateInfo(SimpleWidget.java:209)
> 	at net.osmand.plus.views.mapwidgets.MapWidgetRegistry.updateWidgetsInfo(MapWidgetRegistry.java:64)
> 	at net.osmand.plus.views.layers.MapInfoLayer.onDraw(MapInfoLayer.java:387)
> 	at net.osmand.plus.views.OsmandMapTileView.drawOverMap(OsmandMapTileView.java:1120)
> 	at net.osmand.plus.views.OsmAndMapLayersView.onDraw(OsmAndMapLayersView.java:84)
> 	at android.view.View.draw(View.java:23209)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22076)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
> 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:688)
> 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:786)
> 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4582)
> 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4293)
> 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3520)
> 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2289)
> 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8958)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1319)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1327)
> 	at android.view.Choreographer.doCallbacks(Choreographer.java:985)
> 	at android.view.Choreographer.doFrame(Choreographer.java:916)
> 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1302)
> 	at android.os.Handler.handleCallback(Handler.java:942)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:346)
> 	at android.os.Looper.loop(Looper.java:475)
> 	at android.app.ActivityThread.main(ActivityThread.java:7950)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

**Comment by Guylby** [comment]
Changing the "Memory allocated for routing" setting in the Osmand Development plugin does not seem to have any effect on this issue

**Comment by DmitryAlexei** [comment]
It is a known issue with old routing.
Have you tried workaround for long routes from our site?
https://osmand.net/docs/user/troubleshooting/navigation#how-to-calculate-routes-longer-than-250km

**Comment by vshcherb** [comment]
The problem is unclear yet, cause it could be related to old maps. Also it strange that OOM happens in Java where we have mostly C++ routing to use. Please check and share:
- development plugin on -> navigation settings -> Routing type
- Are all necessary maps up to date

**Comment by vshcherb** [comment]
Also your crash is from 13 february which is confusing...

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.7.0#1774m, released: 2024-03-07
With fresh France maps downloaded (all France) I managed to calculate proposed route using new (HH x c++ routing) and old (A*2 phase) one without a crash. New routing was pretty fast (less than 15 sec), old took more than 3 min.

- new routing 
03-07 21:45:21.639 29976 29085 D net.osmand:native: Route <time>: timeExtra=0.000000, timeToLoadHeaders=0.208000, timeToFindInitialSegments=0.100000, timeToLoad=6.684000, timeToCalculate=5.389000

- old routing 
03-07 21:55:41.661 29976 29085 I System.out: Route <time>: timeToCalculate=194.0, timeToLoad=137.5, timeToLoadHeaders=4.2, timeToFindInitialSegments=0.0, timeExtra=0.0

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/7a68d738-2192-4d04-ab4d-9711cd17a3e3"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/2c804a1e-796a-459d-b2dd-ce6a10c1fca3"  width="300" height="auto"/> </td>
  </tr>
</table>

@Guylby - Could you please share your profile settings (menu > settings > your driving profile > export profile)?
- Do you have actual (from March) France maps downloaded?

**Comment by Guylby** [comment]
Hi, thanks for all your reply,

@vshcherb Sorry to have not been more clear, but I've joined 3 different crash events, the last one is from March 07 in 4.7.3

For my navigation profile, it was the standard Osmand profile but with "HH x Java" routing. I've changed the routing to "HH x C++" and could manage to calculate the route to Angers as DmitryAlexei could achieve.
Here is the profil as requested: 
[Driving.zip](https://github.com/osmandapp/OsmAnd/files/14535609/Driving.zip)

However, pushing the distance even further resulted in a crash every time. Unfortunatly, the C++ crashes were not written to the exception.log file. 

Here are some videos demonstrating the issue: 

### HH x C++ routing resulting in a crash :

https://github.com/osmandapp/OsmAnd/assets/151167525/9e7ab94e-cea4-4e1d-9d56-b819741cefb9

### HH x Java resulting in an error and stopping of the route calculation :

https://github.com/osmandapp/OsmAnd/assets/151167525/64fac0a4-af62-4234-97df-8b7a7708a60a

### Old A* 2 phase routing with 1.5 heuristic coefficient calculating route without problems:

https://github.com/osmandapp/OsmAnd/assets/151167525/47ba8a6a-a0f8-4966-924c-00e4fdf526ab

### And here is a 4.7.3 crash with HH x Java:

> Version  OsmAnd+ 4.7.3
> 07.03.2024 1:55:02
> Apk Version : 4.7.3 4703
> Exception occurred in thread Thread[main,5,main] : 
> java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 896504 free bytes and 875KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
> 	at java.util.HashMap.newNode(HashMap.java:1878)
> 	at java.util.HashMap.putVal(HashMap.java:627)
> 	at java.util.HashMap.put(HashMap.java:608)
> 	at androidx.constraintlayout.widget.ConstraintSet.clone(ConstraintSet.java:1510)
> 	at net.osmand.plus.views.mapwidgets.widgets.SimpleWidget.updateValueAlign(SimpleWidget.java:67)
> 	at net.osmand.plus.views.controls.VerticalWidgetPanel.updateValueAlign(VerticalWidgetPanel.java:235)
> 	at net.osmand.plus.views.controls.VerticalWidgetPanel.access$800(VerticalWidgetPanel.java:47)
> 	at net.osmand.plus.views.controls.VerticalWidgetPanel$Row.updateRow(VerticalWidgetPanel.java:365)
> 	at net.osmand.plus.views.controls.VerticalWidgetPanel.updateRow(VerticalWidgetPanel.java:200)
> 	at net.osmand.plus.views.layers.MapInfoLayer.updateRow(MapInfoLayer.java:237)
> 	at net.osmand.plus.views.mapwidgets.widgets.SimpleWidget.updateInfo(SimpleWidget.java:209)
> 	at net.osmand.plus.views.mapwidgets.MapWidgetRegistry.updateWidgetsInfo(MapWidgetRegistry.java:64)
> 	at net.osmand.plus.views.layers.MapInfoLayer.onDraw(MapInfoLayer.java:387)
> 	at net.osmand.plus.views.OsmandMapTileView.drawOverMap(OsmandMapTileView.java:1120)
> 	at net.osmand.plus.views.OsmAndMapLayersView.onDraw(OsmAndMapLayersView.java:84)
> 	at android.view.View.draw(View.java:23209)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22076)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22032)
> 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
> 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:688)
> 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:786)
> 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4582)
> 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4293)
> 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3520)
> 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2289)
> 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8958)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1319)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1327)
> 	at android.view.Choreographer.doCallbacks(Choreographer.java:985)
> 	at android.view.Choreographer.doFrame(Choreographer.java:916)
> 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1302)
> 	at android.os.Handler.handleCallback(Handler.java:942)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:346)
> 	at android.os.Looper.loop(Looper.java:475)
> 	at android.app.ActivityThread.main(ActivityThread.java:7950)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

**Comment by DmitryAlexei** [comment]
Situation slightly changed today with fresh nightly build. When reproducing that issue I used default and user's driving profile. I also enabled live updates for all France maps, but this made no difference to the route calculation.
- OsmAnd~ 4.7.0#1774m, released: 2024-03-07 (yesterday nightly build). There was a crash when HH x java routing was selected.
 - OsmAnd~ 4.7.0#1780m, released: 2024-03-08 (today nightly build). There is no crash when HH x java or HH x c++ routing is selected. Although HH x java cannot calculate route and pop-up with  toast "not enough process memory" appears. See screenshots.

<table style="width:100%">
  </tr>
  <tr>
    <th>HH x java </th>
    <th>HH x C++</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/4e7c19f9-7af0-4b9f-919e-cdf0e5af1144"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/32d27f6d-4236-436a-99bb-a64841855981"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Guylby** [comment]
With Osmand 4.7.4, there has been improvement, but the behaviour is still strange. I've made sure that all maps are up to date. 

In Brest, France, I've selected two points, 3kms apart. With the same start, one will calculate the route everytime, one will crash everytime with HH x C++. There really seems to be a hard limit, either you can calculate the route, or you will crash for sure. 

Yellow marker: 48.39698°N, 4.44390°W
Red marker: 48.70037°N, 4.48117°W

| Yellow market itinerary, calculate route everytime | Red marker itinerary, crashes everytime |
| ------------- | ------------- |
|  ![Screenshot_20240311-085853](https://github.com/osmandapp/OsmAnd/assets/151167525/97dabdbf-9092-4082-a112-4186da4a1830)  |  ![Screenshot_20240311-090124](https://github.com/osmandapp/OsmAnd/assets/151167525/eb1472a2-9148-4932-8b5a-c0cb37f7f26f)   |

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.7.0#1797m, released: 2024-03-11

1. It seems you provided wrong coordinates for red marker (search shows marker in the sea). Although route can be calculated with c++ routing on the web and in the app. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/d1482089-cffd-444a-916e-a626db565d52"  width="500" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/93867bf3-7b40-48ee-8d3b-fb06319ddcf3"  width="300" height="auto"/> </td>
  </tr>
</table>

https://test.osmand.net/map/?start=48.396984,-4.443843&finish=48.698212,-4.481046&profile=car&params=car,nativerouting#11/48.5362/-4.4977

2. Using the latest nightly build route can be calculated with c++ routing for different locations in Brest
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/4aef29da-7cd7-490b-ba06-bee3a6f19a04"  width="300" height="auto"/> </td>
  </tr>
</table>

@Guylby Have you tried to update all your maps?

**Comment by Guylby** [comment]
When attempting to calculate the route from 43.11775, 5.93502 to 49.61995, -1.72259 with the Osmand test website, routing did not resolve and an error popped up:
![Screenshot 2024-03-11 at 15-29-17 OsmAnd Map](https://github.com/osmandapp/OsmAnd/assets/151167525/feffca7e-4850-4f43-a98f-7166f85dd4f3)

**Comment by DmitryAlexei** [comment]
1. **Route cannot be calculated** for coordinates 43.11775, 5.93502 to 49.61995, -1.72259 with c++ routing both on the website and in the app. OsmAnd~ 4.7.0#1797m, released: 2024-03-11 HH x c++ is stuck in the first quarter of route calculation and HH x java tries to calculate this route for about 2-3 minutes and shuts down without a crash log.
https://test.osmand.net/map/?start=43.117750,5.935020&finish=49.619950,-1.722590&profile=car&params=car,nativerouting#6/46.423/0.889
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/3c01eca2-506c-43e4-b69d-3c1d5f5a5adf"  width="300" height="auto"/> </td>
  </tr>
</table>

2. For the coordinates 48.35784, -4.77829 to 49.61995, -1.72259 **route cannot be calculated on the web site**, but **can be calculated in the app** both with HH x c++ and java routing engines (OsmAnd~ 4.7.0#1797m, released: 2024-03-11).
https://test.osmand.net/map/?start=48.357840,-4.778290&finish=49.619950,-1.722590&profile=car&params=car,nativerouting#12/49.6212/-1.7405
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/492223fe-110a-4a12-9e46-1071f9649bcd"  width="300" height="auto"/> </td>
  </tr>

**Comment by vshcherb** [comment]
Crash is fixed differences will be handled in another issue

**Comment by DmitryAlexei** [comment]
Issue with the [long route ](https://test.osmand.net/map/?start=43.117750,5.935020&finish=49.619950,-1.722590&profile=car#6/47.100/5.856) still reproducible on mobile devices.
- calculates on the OsmAnd Web, but not fast
- on an Android device, the route was calculated only 1 time. The rest of the attempts app freezes for 3+ minutes despite the increase in memory allocated for rooting up to 1Gb
- on iOS, the calculation freezes and sometimes crashes

**Comment by Guylby** [comment]
With Osmand 4.7.6 the crash on the long route still occurs with HH C++.

I also feel that routing is much slower from 4.7.5 (feels 2x as long to calculate the long routes from previous update).


Routing also results in a crash with HH C++ routing on a "short" route (<400kms length) with these parameters:
Start: 43.11775 , 5.93502
End: 45.43198 , 6.02148
"Fuel efficient way" enabled

On test.osmand/map there's no problem calculating the route with "Short way' enabled:
https://test.osmand.net/map/?start=43.117750,5.935020&end=45.431980,6.021480&profile=car&params=car,short_way,nativerouting#8/44.003/5.587

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/commit/047c4b4bdcec8cb8b97646b276925093408825a0

**Comment by DmitryAlexei** [comment]
Fixed on web and on Android. On iOS new build is needed. 
- Android. Calculation takes about 30 sec.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/9937d7bc-f47e-40c2-ad37-adfa05e84561"  width="300" height="auto"/> </td>
  </tr>
</table>

- Web. route calculation time less than 10 sec  https://test.osmand.net/map/?start=43.117750,5.935020&end=48.400380,-4.481150&profile=car&params=car,nativerouting#6/47.010/1.925
