### ISSUE TITLE
turn to the right (taking exit) is not indicated

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#19379]
### Describe the routing engine used (required)

- [x ] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

Car Profile, Offline routing, Offline maps.
From Kaisermühlen direction to Simmering.
A: Right turn (leaving the highway) at this exit is not indicated, as you can see at the lane widget.
B: The next indicated turn is the one "left" in 700m (it´s at position "X" hidden by my widgets).

So in this situation you´re mislead to keep left (indicated next turn) though one has to take the exit to the right, which is not indicated. Means to cross three lanes in heavy traffic.

### Describe your start and end points (required)

From here 48.19715, 16.42229 to here 48.19165, 16.41747

### Describe the actual route (required)

![Screenshot_20240323_131131_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/fdd7352e-5ec0-468a-9073-a79fb3b0a54e)

### Describe the expected route (required)

routing is correct, but not correctly indicated

### Describe what Maps you used (online or offline) (required)

- [ x] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: +4.7.4
Android/iOS version: 13
Device model: S20+
```

**Comment by vshcherb** [comment]
To do should not be mute: turn right https://test.osmand.net/map/?start=48.197755,16.423198&finish=48.192119,16.414754&profile=car#17/48.19396/16.41448

**Comment by ivanPyrohivskyi** [comment]
https://test.osmand.net/map/?start=48.197755,16.423198&finish=48.191718,16.417426&profile=car#16/48.1949/16.4151

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd/issues/19379https://github.com/osmandapp/OsmAnd-core-legacy/commit/f79f3c2a5e5c728b6e7250018c35077e6c81ac85

**Comment by DmitryAlexei** [comment]
Fixed in OsmAnd~ 4.7.0#1981m, released: 2024-04-04 and OsmAnd Nightly 4.7.3.2
Lanes widget now indicates right turn
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/1b13f7a0-274f-45c4-94c6-c561fea5169f"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/5dcd97a7-9910-49c6-a87c-ae661fea218c"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/c399984d-2731-4281-925d-bd2c7852859a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/ed41a2cd-3f2f-4007-9803-7be6b10a3ee9"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Rowin63** [comment]
Issue still or again exists.

On both screenshots you can see, the next exit was not announced. Next announcement in both situations refers to the last left turn, off the highway.

Start: 48.25158, 16.42795
Finish: 48.09683, 16.25350

No announcements at:

Exit "Knoten Vösendorf 4" (A2 > A21)

![Image](https://github.com/user-attachments/assets/3130b5e5-cce6-401b-a609-f7a835530f83)

Exit "Gießhübl 32" (A21 > L153) 

![Image](https://github.com/user-attachments/assets/58d71bdf-ea2f-4d9f-8cf8-6035d74fa580)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/08171b48-b1dd-4f8f-a604-68499ceddb80"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/e3a64e6e-6f0c-4ce7-90ec-e695ba67e3a7"  width="300" height="auto"/> </td>
  </tr>
</table>

+5.2.13

**Comment by Zirochkabila** [comment]
@Rowin63 I checked the latest nightly version - as far as I can tell, everything is displayed correctly (the announcement was correct).

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/60e03051-285a-48db-823c-e68996ef5a9d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/3396021e-081c-4394-bfa8-6d9fb20eb064"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details>

**Comment by Rowin63** [comment]
I was expecting that, unfortunately. 
But also peviously, it was not really reproduceable on your side. And here, if I start the simulation of a route, I can´t reproduce it. 

The only obvious fact is, it always happens on (longer) highway rides - always highway exits are ignored. 
As you can see on my phone screenshots, on both there´s no command for the next highway exit, but the following command on the minor road does appear again. It always happens like this.

**Comment by Zirochkabila** [comment]
@Rowin63 I will continue to investigate this issue - perhaps during an actual long-distance trip.

**Comment by Rowin63** [comment]
~5.3.0#7210

Happened again, and again on a highway ride. Exit from the A2>A3 was not announced, but another one 7,5km away. Always on highways...

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/764bc9d2-764d-4993-8688-51e6abc6e533"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Rowin63** [comment]
Yesterday update to +5.3.0 and it's still the same.
Drove the same route as described a few posts before, with exactly the same result: no route command on the exit A2>A21, no route command at the exit A21>L153. But always, and already before the first missing highway exit, the final left turn onto the L153 (after the last highway exit) was announced.

**Comment by Zirochkabila** [comment]
@Rowin63 We're keeping an eye on this issue (I'm trying to reproduce it under real-world driving conditions). As soon as I manage to reproduce it, a new issue will be created.

**Comment by Rowin63** [comment]
This issue is going to be at the age of "two" soon and still exists. 
Had to change highway three times, not one single notification. The only announced thing was the first roundabout after finally leaving the highway. 

![Screenshot_20260705_101901_OsmAnd+.jpg](https://github.com/user-attachments/assets/08ccc675-1e04-4fc9-ad0b-d88dccec85b2)

![Screenshot_20260705_102620_OsmAnd+.jpg](https://github.com/user-attachments/assets/3f6233bf-1197-450f-b972-076e8c213dad)

There's only one thing to do, once you realize that announcements are missing: finish/quit navigation and start over from the beginning. Then the correct announcements are back, see here:

![Screenshot_20260705_102736_OsmAnd+.jpg](https://github.com/user-attachments/assets/35e336a1-d501-4a57-86ca-d17a42e9ab20)

I don't know how you solve this issue. 
I only can report it again and again. 

As mentioned every time before, it only happens on highways.

**Comment by Zirochkabila** [comment]
@Rowin63 I have created a brand new tracking issue specifically dedicated to investigating this "silent highway announcements" bug. Please follow the progress here: https://github.com/osmandapp/OsmAnd/issues/25383
