### ISSUE TITLE
Osmand does not show operating time

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#19601]
### Description

Osmand does not show opening_hours for office=property_management
https://www.openstreetmap.org/node/10759315557

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/12549744/6523fffd-0a75-4144-b46f-5ff61f20cfee"  width="300" height="auto"/> </th>
  </tr>
</table>

### Steps to reproduce

Check poi.

### Actual result

Osmand does not show opening_hours for office=property_management.

### Expected result

Osmand show opening_hours for office=property_management.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced.  I attempted to verify this issue at the specified location and another location with the same tag. It appears that for the tag "office=property_management," the hours of operation are indeed not displaying.
Here are the links to the locations:

[First Location](https://www.openstreetmap.org/node/7129246762)
[Second Location](https://www.openstreetmap.org/node/10759315557)

OsmAnd~ 4.8.0#2144m, released: 2024-04-19
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/3c64b649-69d0-4ecb-af9a-af616d214808"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/55dbafca-c09d-4c92-b9d2-b579c4150abb"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Fixed. Map Russia_moscow_asia will be available soon.

**Comment by yuriiurshuliak** [comment]
The bug was not fixed. I tested the same locations with and without live updates.

OsmAnd~ 4.8.0#2184m, released: 2024-04-26

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/2aaca482-d462-4d17-af8d-937b6e434ef1"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/b70c5324-1c10-4d69-975c-e13c35e1c5e3"  width="300" height="auto"/> </th>
  </tr>
</table>
