### ISSUE TITLE
North is up (locked) does not lock north

### ISSUE THREAD

**Issue by MikeTango** [osmandapp/OsmAnd#19694]
### Description

The map view mode "North is up (locked)" does not lock north

### Steps to reproduce

View map in "North is up (locked)" mode and do a two finger rotation motion

### Actual result

Map rotates

### Expected result

Map stays locked to north

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: latest
Android/iOS version: Android 11
Device model: Any (China droid thing and Samsung Tablet)
Crash-Logs: ?
```

**Comment by vshcherb** [comment]
There is no mode "locked" there is only mode ``` <string name="rotate_map_north_opt">North is up</string>```. 
Not sure where the wrong name comes from

**Comment by MikeTango** [comment]
The german version says "fest" - fixed. It is really easy to accidentally rotate the map while hiking or in the car and there is no option to complete lock it. 
![signal-2024-04-29-124036](https://github.com/osmandapp/OsmAnd/assets/3368005/620ce3e0-b54d-48a1-9ab8-40fff08214db)

**Comment by vshcherb** [comment]
Ok we will fix description as it's not correct, Fixed mode requires separate setting to turn on in General Settings.

**Comment by MikeTango** [comment]
If you are referring to this one, it does not lock north. I can still accidentally rotate the map. 
![signal-2024-04-29-134212](https://github.com/osmandapp/OsmAnd/assets/3368005/76cc8766-0d28-44a2-aba8-c370ec8454ab)

**Comment by sonora** [comment]
Perhaps also the solution per se we have now with this singular "extra setting" is umfortunate: Because only when this :extra setting is checked can you rely on the fact that you do not by zooming accidentally / unnoticed leave the "North is up" mode and end up in "Manually rotetad". While out-of-the-box all other map orientation modes 'survive' zooming operations without the users first having to find and set such an extra setting...

**Comment by vshcherb** [comment]
This fix is not correct as we plan to live without that setting but we plan to change orientation modes to have first Manually rotated and last North is up Fixed. I don't think we plan to disable zoom gestures however there is no decision yet. It's too cumbersome and the setting is not good either

**Comment by sonora** [comment]
@vshcherb Yes, sounds like a plan. :wink:

I guess what we can take away from all the feedback is

1. A significant number of users rely on North being up, so that should remain the out-of-the-box default for Map viewing.
2. Users get mad at leaving a Map orientation mode accidentally, so the modes must be reasonably stable and 'survive' all sorts of operations users perform on the map screen when viewing/zooming the map.

**Comment by sonora** [comment]
Yeah, but can we make (keep) "North is up" as the default for the Map viewing Profile? Because having "Manually rotated" as the out-of-the-box default for map viewing would throw many users off, I guess...

**Comment by vshcherb** [comment]
Nope I guess, there is a major group of users including me that need to freely rotate map to enjoy specific view (to put streets according to view) and especially enjoy  3D. I always rotate to view hills in 3D in front of me. Though again it's very specific to user needs.

**Comment by ferromint** [comment]
@vshcherb and team:
Thank for finally providing us with a possibility to actually really lock the orientation in the `North is up` orientation modes where it really does make sense!

I agree with @sonora that the `North is up` mode with the new `Enable Fixed North Up` toggle now enables (hopefully) all the ways in which users of OsmAnd might want to interact with the map.

Most of the time when just browsing the map (not while navigating / driving in a car with the `Movement direction` mode) I am using the `North is up` mode and I am happy from now on to no longer accidentally / unintentionally turn the map 🎉

But even I sometimes deliberately switch to the `Manually rotated` mode by clicking on the orientation mode button. E.g. when looking around in 3D trying to identify the names of mountain peaks form my current viewpoint by visually matching the shape / silhouette of mountain ranges. Or when twisting the map in 2D mode to point into my actual viewing direction (not relying on the slightly wrong compass measurements).

My opinion regarding the default value or sort order of the orientation modes:
As long as the above-mentioned new possibility to explicitly (not accidentally) change orientation mode exists, I think the default value or cycling order is not that important for "pro" users. It should be something intuitive / widespread in other map applications so that new users are not confused by unexpected behavior.

One minor missing but important thing is that the [Map orientation modes doc](https://osmand.net/docs/user/map/interact-with-map/#map-orientation-modes) gets updated too (at least a link to the new [Profiles > Other > Enable Fixed North Up feature](https://osmand.net/docs/user/personal/profiles/#other)).

At the moment it still reads as follows:
> North is up - The map is fixed in the direction of the North, which is the top edge of your device. The map does not have automatic rotation, but you can rotate it manually with a [two-pointer gesture (two-finger touch & rotate)](https://osmand.net/docs/user/map/interact-with-map#gestures). In this case, the map orientation mode will change to Manual rotation.

**Comment by EugeneZmeuk** [comment]
**06.05.2024**
- [ ] added ["Enable Fixed North Up"](https://osmand.net/docs/user/personal/profiles#other)
- [ ] add description and link to  Note of [Map orientation modes](https://osmand.net/docs/user/map/interact-with-map#map-orientation-modes) about North fixed
- [ ] add info with links to [Troubleshooting](https://osmand.net/docs/user/troubleshooting/maps-data#maps)

**Comment by MikeTango** [comment]
@osmandlover

**Comment by vshcherb** [comment]
- [ ] ![image](https://github.com/osmandapp/OsmAnd/assets/1042025/efb2b4b5-5743-4dcf-8d6c-5d2dd69be8ed)
Screenshot is not correct we don't have fixed in strings any more
- [ ] Some new words appear like "hard-lock" without explanation it's better to say " you can still rotate with with map gesture, in case that rotation is not needed disable it by setting Fixed North up link

**Comment by sonora** [comment]
_...the clumsiness of our doc wording reflects the clumsiness of our solution..._ 

(just couldn't resist posting this, please forgive me ... 😉 😉 😉  )

**Comment by scaidermern** [comment]
> _...the clumsiness of our doc wording reflects the clumsiness of our solution..._

Indeed...

I still don't get why the "North is up (fixed)" isn't fixed and allows manual rotations.

Any (good) reason to make it non-fixed? I don't have any.

What about making it (finally) fixed, without this ugly setting hidden at some place where nobody will find it. Just make it fixed. If the user still tries to rotate the map, present a toast with a short message "Map orientation is locked. To rotate the map, choose a different map orientation setting". That's it, everybody will be happy. Easy solutions for easy problems, don't make it so hard :)

**Comment by shurasmiling** [comment]
- [x] [Enable Fixed North Up](https://osmand.net/docs/user/personal/profiles#other).
- [x] [Map orientation modes](https://osmand.net/docs/user/map/interact-with-map#map-orientation-modes)
- [x] [Troubleshooting](https://osmand.net/docs/user/troubleshooting/maps-data/#hard-lock-the-north-map-orientation-mode).
- [x] [Map button](https://osmand.net/docs/user/widgets/map-buttons/#compass)

**Comment by MikeTango** [comment]
Thanks for listening to your users. This is what makes FLOSS Software superior.

**Comment by vshcherb** [comment]
We need to double check that we have task for iOS-compatibility and update documentation
https://osmand.net/docs/user/map/interact-with-map/#map-orientation-modes
https://osmand.net/docs/user/widgets/map-buttons/#compass
```
- for the iOS version you can rotate it manually with a [two-pointer gesture (two-finger touch and rotate)](https://osmand.net/docs/user/map/interact-with-map#gestures), and in this case, the map orientation mode will change to Manually rotated.
```
