### ISSUE TITLE
Premature Rotation of Navigation Arrow During Navigation

### ISSUE THREAD

**Issue by puchu** [osmandapp/OsmAnd#19706]
### Description

if the map orientation is set to "movement direction", the map begins to rotate in the direction the user has to turn in navigation mode at turnings/intersections a few meters before. This weird behavior was introduced in 4.7.10 (version 4.6.14, the version i used before, worked normally) and i can't find an option to turn it off.

### Steps to reproduce

calculate a route with turnings/intersections and set the map orientation to - movement direction

### Actual result

the map begins to rotate in the direction the user has to turn at turnings/intersections a few meters before the actual turnings/intersections

### Expected result

the map orientation should follow the actual "movement direction" like in version 4.6.14 (the version i used before 4.7.10)

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.10
Android/iOS version: 12
Device model: vayu
Crash-Logs: ?
```

**Comment by puchu** [comment]
![Screenshot_20240429-141036_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/3678296/d25836b7-8fc3-4889-9a61-20099930373a)
![Screenshot_20240429-141050_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/3678296/e7f9dcbb-ba49-4e8e-9b9a-c66f1da09900)
![Uploading Screenshot_20240429-141517_OsmAnd~.png…]()

**Comment by yuriiurshuliak** [comment]
Could you please share the exact starting and ending coordinates of the route where this issue occurs? Additionally, could you send us your profile settings? You can find them by going to Menu → Settings → Import/export → Export to file.

**Comment by puchu** [comment]
@yuriiurshuliak you can see the weird behavior also in the video you created for another bug i reported
https://github.com/osmandapp/OsmAnd/issues/19707#issuecomment-2088428885

 disabling "animate own position" doesn't fix the problem

This route with the motorbike shows to problem in the first few turns (and it doesn't happen in all turns)
Start: 8.65394° S, 115.19012° E
End: 8.66916° S, 115.16936° E

The export the file also is missing a file save dialog as it only allows to share the file with/to another app (maybe this can also get fixed?)
[Export_2024-05-02.osf.txt](https://github.com/osmandapp/OsmAnd/files/15182610/Export_2024-05-02.osf.txt)

I will updadate to beta testing as soon as possible

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. After importing your profile and building a route using your coordinates, I switched to the motorcycle profile and changed the map orientation to "movement direction". While simulating navigation, especially near turns, the navigation arrow rotates too quickly towards the upcoming turn. The position icon starts turning towards the direction of the turn even before reaching the actual turn point.

OsmAnd~ 4.8.0#2229m, released: 2024-05-02

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/7408c3a1-1109-4ac9-8de6-f0d069b8d69b"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/bef556a6-1a2c-441b-a14a-591a71d4f81d"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by mxdanger** [comment]
Functionally it makes sense to have the map keep as much of the route on screen even if the current implementation is wonky.

**Comment by puchu** [comment]
what's really weird about it is, that the map rotates before reaching an intersection, the audio tells you at the intersection to go for ex. right and the map shows that you have to go straight. It's very confusing and a nightmare to drive with.

**Comment by Jerome-Herbinet** [comment]
Same for me.

I did a test near my home. My route takes me along a main road and then turns right (90 degree right angle) onto a country road. My arrow, which represents my car, starts to turn several hundred metres ahead, as if I were drifting or riding a surfboard.

This is extremely annoying and makes my car navigation unusable in some common scenarios.

**Comment by Rowin63** [comment]
Same issue here (+4.7.17).
Map turns like "drifting" around a corner.

**Comment by D33zN0tz84** [comment]
I am expiriencing the same issue... I do want this. Anyone Found any solution?

Also maps start turning before i tool my turn, it's confusing.

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. During navigation simulation, the navigation arrow now rotates in sync with the turns, providing a smoother and more timely transition.

OsmAnd~ 4.8.0#2831m, released: 2024-07-24

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/user-attachments/assets/0b6b4173-5b4b-4ac2-b99d-bebb80e6cd76"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/c73f01ed-d54b-4d34-8d28-766f1210d17d"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by Rowin63** [comment]
Still exists in the +4.8.6 but doesn't in the nightlys.

**Comment by Rowin63** [comment]
Still happens in the latest nightly too.
It's not reproduceable to me, but it still happens every now and then. Sometimes it does, sometimes not.

**Comment by Andrewschenko** [comment]
It would be great to watch the video. It shouldn't happen now. Arrow can be rotating smoothly for some time after the turn, but not before.

**Comment by Rowin63** [comment]
I'll try to catch it with my mobile if it happens again. But it's difficult when driving... 😉

**Comment by Rowin63** [comment]
It happened yesterday on a 90km route from a village back home to Vienna. Today I tried to simulate this route again, but unfortunately I don't remember where it happened and so I was not able to reproduce it.

But I don't even know if it happens on certain turns (and would be reproduceable once you know them) or if it happens randomly...

But it's the same as before, map and vehicle symbol turns before the actual turn is reached.
But not often, only sometimes. 

I'll try to catch it by video if possible.

**Comment by DmitryAlexei** [comment]
@Rowin63 Probably your issue is caused by rotation of the map and not the arrow itself?
It may be related to the feature "allow to see next 400m after turn" (see [comment](https://github.com/osmandapp/OsmAnd/issues/20422#issuecomment-2262808948) )

**Comment by Rowin63** [comment]
Very likely you're right!
I didn't know about this feature/function, sorry!
But the linked issue gives an explanation to this behavior, thanks for this information 👍👍👍

**Comment by ejafus** [comment]
Not sure if it is exactly the same issue but seems like it:  Disable "Preview next turn" in navigation settings:

Plot a course button --> Settings --> Navigation Settings --> Map During Navigation --> Preview next turn.
 
This happened for two separate devices I had to setup this year and fixed it in both cases.
