### ISSUE TITLE
Wrongly car navigation routing over path, badly bicycle routing over grass

### ISSUE THREAD

**Issue by SLMapper** [osmandapp/OsmAnd#20117]
### Description

`highway=path` is clearly not for car navigation, but still is wrongly chosen by Osmand.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104768113/9429db37-37b2-41a7-a4d5-c24ee2efd2e8"  width="300" height="auto"/> </td>
  </tr>
</table>

`highway=track, tracktype=grade5, surface=grass` and `highway=path, surface=grass` is clearly not for bike, but still is wrongly chosen by Osmand, when there ways of better surface around it.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104768113/a3852067-2d3f-4487-aa37-de1cee47d4b6"  width="300" height="auto"/> </td>
  </tr>
</table>

### Steps to reproduce

Both appeared in longer route (~30 minute each). Only showing the relevant part here:
- car routing from `48.59359° N, 8.87231° E` to `48.59435° N, 8.87470° E`
(routes over https://www.openstreetmap.org/way/551096127)
- bike routing from `48.55116° N, 8.94187° E` to `48.55221° N, 8.92684° E`
(routes over https://www.openstreetmap.org/way/938199238)

### Actual result

1. Invalid road is chosen
1. Road with poor surface was chosen

### Expected result

1. Chosing a valid route
2. Chosing a route with conditions matching the vehicle
(there is a connection via a [`tracktype=grade1`](https://www.openstreetmap.org/way/24865826) and [`tracktype=grade2`](https://www.openstreetmap.org/way/33097314), which is a bit longer but much more fitting for a bike)

### Your Environment (required)

```
OsmAnd Version: OsmAnd~ 4.7.10
Android/iOS version: -
Device model: -
Crash-Logs: -

Latest map updates of "Baden-Württemberg". Happens with and without live updates enabled.
```

**Comment by yuriiurshuliak** [comment]
The bug was partially reproduced. Initially, I attempted to reproduce the issue by building navigation for a car, where the navigation is built exactly as specified by the user. Following that, I attempted to build navigation for a bicycle, but the method for bicycle navigation is currently different.

Additionally, car navigation on the Web version is constructed differently compared to the app, despite Live updates.

Here are the relevant links for car navigation on OSRM and the Web version:
[Car navigation on OSRM](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.59358%2C8.87214%3B48.59422%2C8.87472#map=17/48.59369/8.87332)
[Car navigation on the Web version](https://test.osmand.net/map/navigate/?start=48.593590,8.872310&end=48.594350,8.874700&profile=car#17/48.59410/8.87174)

Here are the links for bicycle navigation on OSM and the Web version:
[Bicycle navigation on OSM](https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=48.5512%2C8.9419%3B48.5547%2C8.9274#map=15/48.5503/8.9382)
[Bicycle navigation on the Web version](https://test.osmand.net/map/navigate/?start=48.551160,8.941870&end=48.552210,8.926840&profile=bicycle#15/48.5499/8.9308)

OsmAnd~ 4.8.0#2528m, released: 2024-06-18

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/43a0eba0-a497-47e0-8bda-8e78d35a759c"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/6826f2a8-697e-4666-a13f-f8896edbb65f"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced.  In the app, when using the reset car profile, the navigation wrongly routes through [bike paths](https://www.openstreetmap.org/way/839038903#map=19/48.59385/8.87346), even with live updates. On the Web version, the navigation works correctly and takes a detour. However, if you enable the "Short way" option on the Web version, it also incorrectly routes through bike paths, just like the app.

Bicycle navigation is now working correctly.

Here is a link to the web version: [Car navigation on the Web version](https://test.osmand.net/map/navigate/?start=48.593590,8.872310&end=48.594350,8.874700&profile=car#17/48.59410/8.87174)

OsmAnd~ 4.8.0#2568m, released: 2024-06-24

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/d54f0255-efc0-4503-9e16-58597fe8f656"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/31d111bd-5467-4888-97ba-11beb86b7b3c"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Sebastian-ubs** [comment]
Thank you very much for reproducing the issue with car navigation.
I was also able to reproduce the [bicycle issue](https://test.osmand.net/map/navigate/?start=48.552282,8.925362&end=48.551359,8.941004&profile=bicycle&params=bicycle,short_way#16/48.5518/8.9344) of routing over a [highway=path, surface=grass](https://www.openstreetmap.org/way/938199238) using "short way" on the web version.

**Comment by SLMapper** [comment]
Thank you very much for reproducing the issue with car navigation.
I was also able to reproduce the [bicycle issue](https://test.osmand.net/map/navigate/?start=48.552282,8.925362&end=48.551359,8.941004&profile=bicycle&params=bicycle,short_way#16/48.5518/8.9344) of routing over a [highway=path, surface=grass](https://www.openstreetmap.org/way/938199238) using "short way" on the web version.

**Comment by SLMapper** [comment]
Another [bike example](https://test.osmand.net/map/navigate/?start=48.498606,8.916521&end=48.503512,8.932228&profile=bicycle#16/48.5002/8.9185) I experience yesterday even **without** "Short way enabled"
![grafik](https://github.com/osmandapp/OsmAnd/assets/104768113/4cbf0c82-5e9c-4dbe-9da3-e5fdc678ae5f)

where OsmAnd unexpectedly
- prefers tracks with [surface=grass](https://www.openstreetmap.org/way/129582342) &rarr; [surface=grass](https://www.openstreetmap.org/way/1064668500) &rarr; [hw=track without additional information](https://www.openstreetmap.org/way/1170637861/history/1)
- over continuing on the good tracks that can be seen below [surface=gravel, tracktype=grade2](https://www.openstreetmap.org/way/33616734) &rarr; [surface=gravel, tracktype=grade1](https://www.openstreetmap.org/way/33616735)

**Comment by SLMapper** [comment]
Another [crazy bike example](https://test.osmand.net/map/navigate/?start=48.476492,8.929449&end=48.479991,8.923141&profile=bicycle&params=bicycle,short_way#17/48.47811/8.92550) with "Short way" enabled, where
- OsmAnd routes over a [foot=designated, highway=footway, lit=no, surface=asphalt, width=0.8](https://www.openstreetmap.org/way/55608078)
- instead of taking the [roads appropriate for bikes](https://test.osmand.net/map/navigate/?start=48.476492,8.929449&end=48.479991,8.923141&profile=bicycle#17/48.47811/8.92550) (this is when disabling "Short way" on the website, but on my phone I had to manually put a way point for OsmAnd to go there, despite that I had "short way" disabled)

**Comment by vshcherb** [comment]
@xmd5a2 
There are 2 issues going on:
1. https://www.openstreetmap.org/way/1135154135 - highway/path, bicycle/designated. A [highway](https://wiki.openstreetmap.org/wiki/Key:highway)=path is not for use by four-wheeled (two-track) vehicles! - so we need to disable path for vehicles ( "path" != "track") - however we need to confirm for offroads if it makes sense to add an option (To fix)
2. Increase penalty for [surface=grass](https://www.openstreetmap.org/way/938199238) - bicycle

**Comment by xmd5a2** [comment]
All cases were fixed



![Image](https://github.com/user-attachments/assets/507a01d6-aa6d-4fce-a316-43ef459fa873)


![Image](https://github.com/user-attachments/assets/bb1636f0-9ab4-4ca5-a1bd-8644bcac9736)

**Comment by SLMapper** [comment]
Is it supposed to be working on the website already? I can still reproduce the [bicycle example](https://test.osmand.net/map/navigate/?start=48.552282,8.925362&end=48.551359,8.941004&profile=bicycle&params=bicycle,short_way#16/48.5512/8.9300) with the "short way" option.

**Comment by xmd5a2** [comment]
Doesn't this option do what it's supposed to: build a route along the shortest path?

**Comment by DmitryAlexei** [comment]
All two cases were fixed:
- example 1 (bicycle) [link](https://test.osmand.net/map/navigate/?start=48.552282,8.925362&end=48.551359,8.941004&profile=bicycle#16/48.5528/8.9303)
- example 2 (car) [link](https://test.osmand.net/map/navigate/?start=48.593590,8.872310&end=48.594350,8.874700&profile=car#18/48.59393/8.87167)

<img width="597" alt="Screenshot 2024-09-26 at 12 35 35" src="https://github.com/user-attachments/assets/fd3971ae-bbf7-4e03-b291-cde3ab468231">
<img width="597" alt="Screenshot 2024-09-26 at 12 33 58" src="https://github.com/user-attachments/assets/d3bf24ee-ab39-4d3f-94a0-883cb68a46eb">
