### ISSUE TITLE
Rendering speed degraded significantly on 4.8.0 beta

### ISSUE THREAD

**Issue by shadow-identity** [osmandapp/OsmAnd#20142]
### Description

Today I updated to 4.8.0 beta, and I immediately noticed that the rendering speed is few times slower. The phone also heats much more than before.

The bug seems not to be related to https://github.com/osmandapp/OsmAnd/issues/20067 since I don't see any difference if I have any track enabled or not.

https://github.com/osmandapp/OsmAnd/assets/1223112/7c8ca9fd-1bd4-4ba7-989f-4364f83da675

### Steps to reproduce

1. Update to 4.8.0
2. Zoom map in / out

### Actual result

Rendering speed should be faster or the same than on the previous version.

### Expected result

Rendering speed is significantly slower

### Your Environment (required)

```
OsmAnd Version: Osmand+ 4.8.0, 2024-06-18, from  Play store
Android/iOS version: 14
Device model: Google Pixel 6 pro
Crash-Logs: -
```

**Comment by shadow-identity** [comment]
A guy from a telegram chat suggested deleting live updates, and it helped. I'll update the description.

**Comment by Wouter-Lemoine** [comment]
I have noticed the same/similar behaviour, where the map gets rendered (partially) but no text or POI gets drawn. Deleting the live updates fixes this issue. 

## Environment
Device : FP5
Brand : Fairphone
Manufacturer : Fairphone
Model : FP5
Product : FP5
Build : FP5.TT4C.A.154.20240320
Version : 13
App Version : OsmAnd~
Apk Version : 4.7.17 471703

**Comment by yuriiurshuliak** [comment]
The issue with live updates should be fixed by now. Please try completely removing the live updates, clearing the cache, and then re-enabling the live updates.
Related to #20120

**Comment by Sesivany** [comment]
Not fixed for me. I removed live updates, cleared app cache and renabled the live updates and the extreme lagging is back.
I'm using OsmAnd+ 4.7.17 from F-droid (with OsmAnd Cloud Plan enabled) if that could make a difference.

**Comment by vshcherb** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/20120
