### ISSUE TITLE
Route calculation is so slow in +4.8.4

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#20426]
### Description

Since the last update to the playstores +4.8.4 the route calculation is very slow, even if the finish is only one km away. There is always a huge break at around 20% progress. Processing a route to a finish 2km away needs 15-20 sec. Longer routes like 20km seem to never finish calculating. 

### Steps to reproduce

As described. 

### Actual result

Calculating is very slow. 

### Expected result

Calculate quick as usual. 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by Rowin63** [comment]
Deleted the Austrian map and re-downloaded it. Also tried the standard map as well as the road-only-map. No difference.

**Comment by Rowin63** [comment]
Happens in the HHxC++, but not in the A*classic.

**Comment by MarioSwitch** [comment]
Not reproduced 🤔

OsmAnd 4.8.4, Google Pixel 7 (Android 14), HH x C++ routing

Can get a ~1000km route in 15 seconds, as quick as older versions...

**Comment by Rowin63** [comment]
This is the point where the calculation stops, it´s always the same. 
(Very) short routes contiue after a while, longer ones don´t (or I dont wait long enough, but it takes minutes).

Happens only on this device (S20+). 
Happens since the last update (+4.8.4). 
There was a crash at the first app start after the update (I sent the crashlog to your support mail address).

Does not happen on my Tab Act3 (also running A13 and Osmand +4.8.4).

![Screenshot_20240727_130138_OsmAnd+](https://github.com/user-attachments/assets/cb8203cb-94f8-4b88-a869-ace60425bce4)

**Comment by Rowin63** [comment]
Did a de- and re-install (with "keep the app's data), did not help.
Did a de- and re-install (without keeping the data), this helped.
Restored my data from a backup I made before the de-install, and still everything is fine. So the issue shouldn't be hidden in my data, it's the same before and now. Perhaps it was caused by the crash at the update? I don't know. You can see the crashlog I sent. 

By now the problem seems to be solved.

**Comment by vshcherb** [comment]
As I noticed it could be if some maps are not updated (even that are not used in calculation), however if you update all maps it should be fast

**Comment by Rowin63** [comment]
I had looked at that, and all maps have been up to date (also world map, ...)
But as mentioned before, I believe this issue was caused by the crash during/after the update. Everything worked, except the HHxC++ routing.

**Comment by MarioSwitch** [comment]
> I had looked at that, and all maps have been up to date (also world map, ...)
> But as mentioned before, I believe this issue was caused by the crash during/after the update. Everything worked, except the HHxC++ routing. And, as mentioned too, only a fresh install helped. Anyway it's solved and history 😉

So you should close this issue... 🤔

**Comment by vshcherb** [comment]
We need to double check as we also experienced some slowness before update

**Comment by yuriiurshuliak** [comment]
I tried to reproduce this behavior and noticed varying calculation times. To reproduce this, I updated to the beta version, reset the profile settings, and built a navigation route through a densely populated city using the same starting point. Here are the results:

- A 30-kilometer route was built in 25 seconds.
- A 42-kilometer route was built in 10 seconds.
- A 114-kilometer route was built in 17 seconds.

However, I could not reproduce the above-mentioned problem. The route calculation always took a relatively short amount of time.

OsmAnd 4.8.4, released: 2024-07-24

<table style="width:100%">
  </tr>
  <tr>
    <th>The distance is 30 km</th>
    <th>The distance is 42 km</th>
    <th>The distance is 114 km</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/user-attachments/assets/af0f29ef-484d-4a25-9604-2d4acdc7633c"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/15d105f8-0e2f-4b4f-b49d-b38915cf0c5f"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/08fb7cc9-6384-4ec6-afbc-09a87b139ec9"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
@yuriiurshuliak you should try long routes with many maps (some updated and some not), contact @dmpr0 for route details in Germany

**Comment by dmpr0** [comment]
Route start `53.822860, 9.285870`, end `50.385780, 6.656350`
Link https://osmand.net/map/navigate/?start=53.822860,9.285870&end=50.385780,6.656350&profile=car#7/52.147/5.504

**Comment by Famlam** [comment]
I can confirm this issue exists with short routes as well, e.g. if I calculate [this route](https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=51.83730%2C5.83186%3B51.83911%2C5.83334) in OsmAnd. 
Previously this would take < 1 second (bicycle profile).
After the update to 4.8.4. it takes 22 seconds to find this route of ~400m
(Android 11)

Unlike the topic starter I didn't have a crash during the update.

**Comment by anten1222** [comment]
Osmand 4.8.4
Profile Bike
 Start 53.09203° N, 8.85157° E
target point  50.68173° N, 7.16913° E

Osmand crashes

**Comment by vshcherb** [comment]
@Famlam if you delete indexes.cache (you can do it in settings) does it help or not? update maps?

**Comment by Famlam** [comment]
@vshcherb I couldn't find that file, but I deleted the file `Android\data\net.osmand\files\ind.cache`. I also deleted the cache of this app via the Android settings. Unfortunately this didn't resolve the issue.
Live updates to all maps didn't help either. All maps are already the July version, I'll update them again when the August version becomes available (in 2-3 days I think?).

**Comment by Kordolio** [comment]
My Samsung J3 froze for 3 hours after the update. I somehow managed to wake him up without hard reset and now it is working, however:
1. I had a place called "Dom" (polish for "home") saved in my "personal" places folder. This place was marked as system "home" of the OsmAnd. Now I have no "Dom" place anymore. It was replaced (and actually the name translated) by "home" and it took me some time to find it, since I was searching for "Dom".
2. Whenever I take a route, the program writes enormous amount of cache data, filling my phone up. After 20 minutes of navigating it can be even 300 MB and it is all saved in the main phone's memory despite that I marked the "External memory" SD card for storing data.
Hopeless. Please correct these errors asap. Thank you!

**Comment by david-gpu** [comment]
I have also noticed routing calculations taking something like 10x longer than usual over the last week or two.

Problem observed on OsmAnd 4.8.4 on Android 13. Safe mode disabled. HeuristicCoefficient = 1.2. I'm a Pro subscriber, so the maps are all up-to-date.

Deleting all caches and all maps via the Maps & Resources menu, and then re-downloading the necessary maps did not help. Uninstalling the app with "Keep Data" option enabled did not help.

Uninstalling the app with the "Keep Data" option disabled, then manually restoring the tracks and routing configuration from a backup, did not make routing significantly faster, either -- all that was accomplished was losing the appearance/color of the tracks. It is still significantly slower than it was a couple of weeks ago, even when I set HeuristicCoefficient=1.5.

Enabling "Safe Mode" in the Developer Options plugin seems to have no effect on the time it takes for the routing calculations to be done, so I wonder whether there's something causing the faster engine to be disabled, or whether the performance bottleneck is outside of the engine itself (e.g. I/O). I did not measure it carefully, though -- it's just super slow with or without safe mode.

For all practical purposes, the app no longer serves the function I bought it for.

**Comment by Famlam** [comment]
>>update maps?

> I'll update them again when the August version becomes available (in 2-3 days I think?).

Did this just now, and I can confirm that updating the maps does not fix this issue.

I can also confirm that the workaround of @david-gpu (to switch to `A* 2-phase` calculation) solves the issue for the time being. The step of uninstalling was not necessary for me.

**Comment by vshcherb** [comment]
We didn't reproduce the issue yet. It seems that map update helps, once we have it , we will get back working on this issue

**Comment by photoalex** [comment]
I have similar issues, it effects all routing except 'on foot' ..

**Comment by vshcherb** [comment]
Please attach zip logcat files during route calculation

**Comment by Rowin63** [comment]
After the update to +4.8.5 now I have this problem (HHxC++ does not work) on the other device, the Tab Act3)
+4.8.4: HHxC++ did not work on my S20+, but worked on my Tab Act3 (needed a clean fresh install to work again)
+4.8.5: HHxC++ now does not work on my Tab Act3, but works on my S20+

Puh...

**Comment by Rowin63** [comment]
On my side, my initial issue (HHxC++ did not work) is solved by the latest update (+4.8.6) and HHxC++ routing works again on both devices 👍

**Comment by Famlam** [comment]
Unlike Rowin63, 4.8.6 unfortunately doesn't solve the issue for me.

**Comment by anten1222** [comment]
Profile Bike Route Cuxhaven Bonn
Whitout Elevation data Route 2 Minuten 
White Elevation data Osmand Crash

**Comment by Alto5414** [comment]
I've had the same persistent issue since upgrading to 4.8.n (android). Cannot get routes in route planner to attach to roads. 4.7 it worked fine btw. 

Attach to roads route planning is a key feature I bought osmand for, in my move away from gaia gps, but can no longer use it for route planning so now have to move back to gaia for now :(

I've tried all the things suggested in this thread, and some other threads, but regardless I still can't get the route to attach to roads on any profile.

Even if there was a workaround, we shouldn't have to apply a workaround everytime we want to use a key feature.

Note, the web version does attach to roads OK.

**Comment by DmitryAlexei** [comment]
@anten1222 cannot find your route. 
Could you please provide it from https://osmand.net/map ?
Create your route and paste link from the address bar

**Comment by Alto5414** [comment]
> @anten1222 cannot find your route. Could you please provide it from https://osmand.net/map ? Create your route and paste link from the address bar

I can't find a way to share the routes on the website app, that I've created on my phone. There's no share button and the url doesn't change when I select the track. Note, per my previous message the web app attach to roads does work. Juat stopped on my android.

Not sure if it helps but I've attached few example gpx files.
[Gpx.zip](https://github.com/user-attachments/files/16591783/Gpx.zip)

**Comment by Shulcare** [comment]
I can confirm slow routing calculation since my update to 4.8(.4). My holiday trip of ~210 km seemed to never finish (I waited for minutes at 20-25% and finally aborted it, several tries with app restart in between). But it had been able to calculate it before the update.
I do have the latest maps for the relevant regions. I did not clear any caches. Changing the algorithm to A* 2-phase fixed this for me. (Thanks for the tip!)
Even calculating trivially short routes (less than 1km, from one highway to another highway as the only turn) takes noticably longer with HH x C++ than with A* 2-phase.
There seems to be some new problem with the HH x C++ code?

**Comment by cridemichel** [comment]
Hi, same here with osmand 4.8.5 (from F-droid on a Poco F3 with hyperOS 1.0.2.0 TKHEUXM). Planning short routes (10-20km) for trekking or biking it takes a long time or even in some case crashed. Switching to A* 2-phase fixed this also for me,
C.

**Comment by Alto5414** [comment]
> I've had the same persistent issue since upgrading to 4.8.n (android). Cannot get routes in route planner to attach to roads. 4.7 it worked fine btw.
> 
> Attach to roads route planning is a key feature I bought osmand for, in my move away from gaia gps, but can no longer use it for route planning so now have to move back to gaia for now :(
> 
> I've tried all the things suggested in this thread, and some other threads, but regardless I still can't get the route to attach to roads on any profile.
> 
> Even if there was a workaround, we shouldn't have to apply a workaround everytime we want to use a key feature.
> 
> Note, the web version does attach to roads OK.
> 
> ![Screenshot_20240811_212637_OsmAnd](https://private-user-images.githubusercontent.com/178108141/356904124-36bdb84f-17dd-4cc7-96f3-981610383fb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTQ2NTUsIm5iZiI6MTcyMzc5NDM1NSwicGF0aCI6Ii8xNzgxMDgxNDEvMzU2OTA0MTI0LTM2YmRiODRmLTE3ZGQtNGNjNy05NmYzLTk4MTYxMDM4M2ZiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNzQ1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTcxNmMyMDY1NTFmMzQ5YzBkMGY3YjdiMmEzYjFlMzE4ZGIwZDg1NTVlZjE4NDRjNjNlMDlkNzQ2YWU4ZWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bx51c9gGg-Vb9PyNNmw0fz9FLuJxQ6H3zRg2OiQXOgg)

I tried again today and performed exactly the same steps I usually do, and attach to roads briefly worked. I didn't save the route unfortunately. But upon me trying again immediately after it didn't work again. Very frustrating. Having to resort to using gaia to plan routes.

**Comment by Alto5414** [comment]
> @Alto5414 could you please provide your settings (menu > settings > export to file and select all settings) it is also needed to add .txt to the resulting file

See attached
[Export_2024-08-16.zip](https://github.com/user-attachments/files/16638513/Export_2024-08-16.zip)

**Comment by DmitryAlexei** [comment]
@Alto5414 Please note, that "Attach to the roads option" works only with offline vector maps.
And you use online OsmAnd map as a map source. So attach to the roads will not work for the areas without offline vector map.
Probably we can display a warning in such a case.

**Comment by Alto5414** [comment]
Oh. Yeah it would be ideal to make that a lot clearer in the UI, and website in case I missed it.

Is there a reason it doesn't work with online maps? Gaia does it without downloading the map first abd so do some other osm map apps I believe.

**Comment by cridemichel** [comment]
Hi,
I installed version 4.8.6 and on my poco F3 it seems that algorithm HH x C++ works well also with hiking and biking profiles,

best Cristiano

**Comment by Famlam** [comment]
Is this fix already in 4.9.5? I still see the same behavior where `2-phase A*` greatly outperforms the `HH x C++` method

**Comment by DmitryAlexei** [comment]
@Famlam could you provide example of the route where A* algorithm is better than HH ?
You can build your route using https://osmand.net/map/ and copy-paste it from the address bar

**Comment by Famlam** [comment]
@DmitryAlexei 
https://osmand.net/map/navigate/?start=51.844244,5.854383&end=51.836121,5.853571&profile=bicycle#15/51.8404/5.8576
A nearly straight cycle path of about 1 km

2 sec with 2-phase A*
26 sec with HH x C++

**Comment by DmitryAlexei** [comment]
Cannot reproduce using latest maps and default cycling profile
@Famlam could you please provide your profile? You can also try to calculate your route using the default cycling profile.

**Comment by Famlam** [comment]
I just reset the default (build-in) cycling profile to it's defaults and subsequently calculated the same route:
26 sec with HH x C++
1 sec with 2-phase A*

**Comment by DmitryAlexei** [comment]
Could you please try the latest nightly build? https://osmand.net/docs/versions/nightly_versions#nightly-builds

using OsmAnd~ 5.0.0#3727m, released: 2024-11-15 routing works fine
[logcat (1).log](https://github.com/user-attachments/files/17776919/logcat.1.log)

**Comment by Famlam** [comment]
With a fresh install from Nightly, only downloaded Netherlands -> Gelderland, default settings, same route, bicycle profile (and the OSM debug plugin enabled in order to change the calculation method) it's:
- <1 second for 2-phase A*
- 3 seconds for HH x C++

Also downloading another map (Netherlands -> Zuid-Holland/South Holland) doesn't notably change this (average 3-4 seconds for HH x C++). So although significantly slower, the issue is less bad with a fully-default nightly install.

If there's any fix in nightly which isn't in 4.9.5 yet, I'll just patiently await till that arrives in beta/regular releases. 
Otherwise, is there anything else I can test (preferably without removing my settings, as it takes over an hour to set the app up again) to see where the additional 23 seconds come from?

**Comment by vshcherb** [comment]
4.9.6 is fully rolled out, so there is no ongoing development with routing. Please test it

**Comment by Famlam** [comment]
Unfortunately 24 seconds with HHxC++ and 1 second with 2-phase A* for the same route as my earlier post on 4.9.6

**Comment by Famlam** [comment]
Hmm, interesting discovery. On nightly (which I still had installed, see https://github.com/osmandapp/OsmAnd/issues/20426#issuecomment-2479976546 for the history) I can get the route calculation (HHxC++) to increase by 14 seconds by just having this absolutely minimal routing.xml file (and using the corresponding bicycle_test profile)
```xml
<?xml version="1.0" encoding="utf-8" ?>
<osmand_routing_config defaultProfile="bicycle_test">
	<routingProfile name="bicycle_test" baseProfile="bicycle" >

	</routingProfile>
</osmand_routing_config>
```
Also here only the HHxC++ is affected; in 2-phase A* both the regular bicycle profile as the above bicycle_test profile are equally fast.


However, on my 'normal' install I see the slowdown also with the regular (default) bicycle profile. I even reset all its parameters to the default in https://github.com/osmandapp/OsmAnd/issues/20426#issuecomment-2478622241. Hence I'm not sure if these issues are related?

**Comment by IIVQ** [comment]
Yesterday I encountered the same problem (Osmand+ 4.9.10), having downloaded offline maps of Netherlands, Belgium, France, parts of the UK, Germany and Italy, most updated april this year, but The Netherlands all from november or december. I tried to plan a car route from Weesp to Rotterdam and it would take more than 5 minutes, even adding 3 intermediates didn't help.

In the evening I found this thread and first tried a very short (±1,5km) car route, that kept stuck at what seemed <10%, the blue would barely touch the left of the "start" arrow. I tried a foot route a few times an that worked without problem.
Yesterday evening updated all maps and tomorrow tried Weesp-Rotterdam again, and had a route in a lightning fast second or so. 

So it seems old maps (or mix of old and new) really confuse the system.

Did something change in the map format?
Is it possible to warn against old maps when using the new route calc algorithm?

**Comment by MarioSwitch** [comment]
> Edit: I tried the new algorithm on a car route to my aunt's house in southern France (a 1048km route) It took 22s without intermediate points. I remember this route taking >10m to calculate without intermediate points, if OSMAND didn't crash, when I did it half a year ago, and I always used intermediate points about 200km apart. Amazing!

Agree! We can now use OsmAnd for 500+ km-long routes without any problem 👍 

It is possible the problem come from mixing old and new maps, as I have never seen this problem, but I update all my maps every month 😅

**Comment by aaronmeder** [comment]
Ah yes - updating all installed apps made osmAnd work without issues again.

I encountered the same problem with never ending route calculations with osmAnd 5.0.5 on Android 15 on a Pixel 6A.

**Comment by IIVQ** [comment]
I am using OsmAnd+ 5.1.3, and I encountered this problem again.

I don't own a car at the moment, but last week I had to suddenly drive a car from Amsterdam (The Netherlands, North-Holland) to Rotterdam (The Netherlands, South-Holland), so it was the first time in a long time that I tried the car navigation profile.

OsmAnd warned me that some maps were outdated (I forgot the exact wording) and when I tried a route calculation, it made a somewhat normal route from Amsterdam to the A4 Road around the provincial border and then a straight line route towards my destination: See attached screenshot.

It turned out that my South Holland-standard maps-file was about half a year old, I think December 2024 (as that was when [I last had this bug](https://github.com/osmandapp/OsmAnd/issues/20426#issuecomment-2556374991)) or maybe January 2025. I have North-Holland up-to-date with live updates (which I run manually occasionally, but the last update was 2 days ago) - but the base file was also from December 2024.

When I updated South Holland route calculation became very slow - it eventually made it on the way to Rotterdam, but on the way back after 10 minutes I cancelled it (as I didn't bring a USB C-C cable and the car only had C outlets - didn't want to drain the battery). 

Note that the Utrecht standard maps file was quite new (june 2025) - the shortest route from start to destination didn't pass through Utrecht, but it will most certainly concider that route as it is only a few km and a few minutes longer.

When I was home I updated all of the Netherlands files, but still didn't get fast route calculations. Only when I updated all "standard maps" files, route calculation became fast  (7 seconds) again - I didn't try what happened when I would've upgraded the Netherlands and world basemap only.

It would be nice if this bug were either solved, or at least a clearer message about a mixture of old and new maps were present - preferrably a month in advance of the mixture becoming a problem.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/0fff4fdf-ef03-4e0d-9e62-db3b2c37f607"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
IIVQ, it is possible that your proposal should have been included in the most recent issue:
- https://github.com/osmandapp/OsmAnd/issues/22987
