### ISSUE TITLE
Importing settings-backup (osf) that have certain content types does nothing

### ISSUE THREAD

**Issue by Switch123456789** [osmandapp/OsmAnd#20718]
### Description

If I pick a backup to import, nothing happens. I tried many different backups, created some for the purpose of testing the feature but osmand literally does nothing.

### Steps to reproduce

Import a backup.

### Actual result

Nothing happens

### Expected result

Osmand proceeds with the restore-process.

### Your Environment (required)

```
OsmAnd Version: 4.8.6
Android version: 14 (IodeOS)
Device model: Fairphone 5
```

**Comment by yuriiurshuliak** [comment]
Please provide us with the .osf file you're trying to import that results in a failure, and kindly compress it into a zip format.

**Comment by albansuser** [comment]
I have found that only the export/import of "Settings" works. If  "My Places" or "Resources" are included the import doesn't work.

**Comment by JF78770** [comment]
I recently moved to Android 14, Osmand 4.8.6 and I got same issue I had not seen before. I confirm albanuser comment. Same issue if I go through Settings/Import or through Favorite Places/Import. I can read "Load the datas", after that the windows with "Settings, My Places, Resources" does not open.

**Comment by Switch123456789** [comment]
If the backup includes: `Colors`, `Favorites` or `TTS` from the sources-category, this happens. Everything else works (I don't have every kind of data). [This](https://github.com/user-attachments/files/16826975/Export_2024-09-01.zip) is a backup of only the colors, I can't import it.

**Comment by trldp** [comment]
I seem to have a similar issue when importing an export only containing a track (see the file in attachment below). Running `adb logcat` gives the following exception:
```09-04 21:03:13.529 31468  4251 E net.osmand: SettingsHelper Failed to read next entry {AsyncTask #9}
09-04 21:03:13.529 31468  4251 E net.osmand: java.util.zip.ZipException: Invalid zip entry path: /tracks/220822.gpx
09-04 21:03:13.529 31468  4251 E net.osmand: 	at com.android.internal.os.SafeZipPathValidatorCallback.onZipEntryAccess(SafeZipPathValidatorCallback.java:52)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1684)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1436)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at java.util.zip.ZipFile$Source.get(ZipFile.java:1389)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:769)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at java.util.zip.ZipFile.<init>(ZipFile.java:283)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at java.util.zip.ZipFile.<init>(ZipFile.java:239)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at java.util.zip.ZipFile.<init>(ZipFile.java:187)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at java.util.zip.ZipFile.<init>(ZipFile.java:156)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at net.osmand.plus.settings.backend.backup.SettingsImporter.updateFilesInfo(SettingsImporter.java:86)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at net.osmand.plus.settings.backend.backup.SettingsImporter.getItemsFromJson(SettingsImporter.java:66)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at net.osmand.plus.settings.backend.backup.SettingsImporter.processItems(SettingsImporter.java:106)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at net.osmand.plus.settings.backend.backup.SettingsImporter.collectItems(SettingsImporter.java:37)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at net.osmand.plus.settings.backend.backup.ImportFileTask.doInBackground(ImportFileTask.java:103)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at net.osmand.plus.settings.backend.backup.ImportFileTask.doInBackground(ImportFileTask.java:24)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at java.lang.Thread.run(Thread.java:1012)
09-04 21:03:13.529 31468  4251 E net.osmand: SettingsHelper Failed to collect items from: Export.osf {AsyncTask #9}
09-04 21:03:13.529 31468  4251 E net.osmand: java.lang.IllegalArgumentException: No items
09-04 21:03:13.529 31468  4251 E net.osmand: 	at net.osmand.plus.settings.backend.backup.SettingsImporter.processItems(SettingsImporter.java:109)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at net.osmand.plus.settings.backend.backup.SettingsImporter.collectItems(SettingsImporter.java:37)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at net.osmand.plus.settings.backend.backup.ImportFileTask.doInBackground(ImportFileTask.java:103)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at net.osmand.plus.settings.backend.backup.ImportFileTask.doInBackground(ImportFileTask.java:24)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
09-04 21:03:13.529 31468  4251 E net.osmand: 	at java.lang.Thread.run(Thread.java:1012)
```
I'm running 
```
OsmAnd Version: 4.8.6
Android version: 14 (LineageOS 21-20240816-NIGHTLY-instantnoodlep)
Device model: OnePlus 8 Pro
```

[Export.osf.zip](https://github.com/user-attachments/files/16875680/Export.osf.zip)

**Comment by DmitryAlexei** [comment]
@trldp @Switch123456789 
All your backups can be imported to OsmAnd~ 4.9.0#3122m, released: 2024-09-03 Android 13 One UI 5.1
The issue might be related to your operating system. 
Please try nightly and see if it is working for you.  

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/109e5bf4-1fc9-4523-9fb7-e6f590d70bf4"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/9caed922-b2fc-424e-92b4-0148ab30fe5e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/e572a3ee-637d-4123-b32e-42bc2cb4adec"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Switch123456789** [comment]
> Please try nightly and see if it is working for you.

I did, unfortunately it is still not working, even with a fresh install `4.9.0#3125m` and default settings. I tried backups from `4.8.6` and `4.9.0#3125m`.

**Comment by Jasper-Ben** [comment]
Same issue here with same/similar error message when trying to migrate to FP5 running calyxos:

```
java.util.zip.ZipException: Invalid zip entry path: /tracks/Sun 17 Sep 2023_1.gpx
09-05 14:27:47.740  6972 17235 E net.osmand: 	at com.android.internal.os.SafeZipPathValidatorCallback.onZipEntryAccess(SafeZipPathValidatorCallback.java:52)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1684)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1436)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at java.util.zip.ZipFile$Source.get(ZipFile.java:1389)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:769)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at java.util.zip.ZipFile.<init>(ZipFile.java:283)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at java.util.zip.ZipFile.<init>(ZipFile.java:239)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at java.util.zip.ZipFile.<init>(ZipFile.java:187)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at java.util.zip.ZipFile.<init>(ZipFile.java:156)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at net.osmand.plus.settings.backend.backup.SettingsImporter.updateFilesInfo(SettingsImporter.java:86)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at net.osmand.plus.settings.backend.backup.SettingsImporter.getItemsFromJson(SettingsImporter.java:66)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at net.osmand.plus.settings.backend.backup.SettingsImporter.processItems(SettingsImporter.java:106)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at net.osmand.plus.settings.backend.backup.SettingsImporter.collectItems(SettingsImporter.java:37)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at net.osmand.plus.settings.backend.backup.ImportFileTask.doInBackground(ImportFileTask.java:103)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at net.osmand.plus.settings.backend.backup.ImportFileTask.doInBackground(ImportFileTask.java:24)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at java.lang.Thread.run(Thread.java:1012)
09-05 14:27:47.740  6972 17235 E net.osmand: SettingsHelper Failed to collect items from: Export_2024-09-05_20240905132137.osf {AsyncTask #26}
09-05 14:27:47.740  6972 17235 E net.osmand: java.lang.IllegalArgumentException: No items
09-05 14:27:47.740  6972 17235 E net.osmand: 	at net.osmand.plus.settings.backend.backup.SettingsImporter.processItems(SettingsImporter.java:109)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at net.osmand.plus.settings.backend.backup.SettingsImporter.collectItems(SettingsImporter.java:37)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at net.osmand.plus.settings.backend.backup.ImportFileTask.doInBackground(ImportFileTask.java:103)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at net.osmand.plus.settings.backend.backup.ImportFileTask.doInBackground(ImportFileTask.java:24)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
09-05 14:27:47.740  6972 17235 E net.osmand: 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by sonora** [comment]
@vshcherb , @Chumva  I am not an expert here, but I think this smells of a Zip Slip issue, see https://developer.android.com/privacy-and-security/risks/zip-path-traversal, where Android  mechanism try to avert a perceived security risk. Potentially depends on Android version, which is why some setups may see an issue, while it is not reproducible for others...

**Comment by readonly24** [comment]
I think it's Android version specific. I have two Android 12 smartphones which have no problem importing my osf file with settings and places. But i cannot import this osf file with my Android 14 tablet, then just nothing happens. Osmand is 4.8.5

**Comment by mejo-** [comment]
I experience the same problem with latest OsmAnd build from F-Droid. The export is done on Android 13, the import on Android 14. Unfortunately I cannot share the file due to a lot of personal information in it.

**Comment by mejo-** [comment]
Doing some tests, I was able to export + import all settings and everything from "my places" except tracks. Favourites and markers worked.

**Comment by Boothy99** [comment]
I'm having a few issues recently relating to favourites.gpx file size being suddenly smaller, along with export & import of favourites being corrupted....
https://github.com/osmandapp/OsmAnd/issues/20799#issue-2515826223

Wondering if this is related?

**Comment by AndySchroder** [comment]
For me, this problem seems to be isolated to `Tracks`, `A/V Notes`, `Colors`, `Rendering style`, `Voice Prompts (TTS)`, `Topography maps`, and `Road maps`. All other types of settings (including `Standard maps`) I'm trying to export/import don't result in the silent failure and do work (although some setting types are empty, so they aren't tested). I'm running version `4.8.5`, which is the latest suggested available on F-Droid.

**Comment by AndySchroder** [comment]
Also, I read that "you can backup all your data from the previous device if you copy the folder specified in Settings → OsmAnd Settings → Data storage folder (by default it's Android/data/net.osmand.plus). Then, simply paste all the contents of this folder back to the Data storage folder directory." at https://osmand.net/docs/user/troubleshooting/setup/#how-to-copy-my-favorites-and-tracks-to-the-new-device . This does not work. Lots of stuff (but not all) is missing when I open up the app after copying this folder to the new phone.

**Comment by oxsmos** [comment]
actually I think it's an export issue, resulting files seem smaller than size of data exported. Export and import works with small files, actually it's unclear if it is a file size limit or an issue with selected items

**Comment by DmitryAlexei** [comment]
Please try the [latest nightly build](https://osmand.net/docs/versions/nightly_versions/#nightly-builds), the issue might have been resolved

**Comment by Switch123456789** [comment]
> Please try the latest nightly build

I did and it seems to work now. I took a backup on the stable version and successfully imported it in the nightly version (while still not being able to import it to the stable version).

**Comment by oxsmos** [comment]
> Please try the [latest nightly build](https://osmand.net/docs/versions/nightly_versions/#nightly-builds), the issue might have been resolved

worked, thanks
