### ISSUE TITLE
Regression: Compass widget function seems broken?

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#20764]
Has anybody noticed that as of late the compass icon (below the profile icon) on the map screen does not seem to indicate North anymore, at least in modes Manually rotated / Movement direction / Compass direction?

**Comment by DmitryAlexei** [comment]
Fixed in OsmAnd~ 4.9.0#3135m, released: 2024-09-06

**Comment by sonora** [comment]
@DmitryAlexei This commit https://github.com/osmandapp/OsmAnd/commit/f8f34bef05288ef0b8cb307ac707a8b0243cd3c2 ?

Think that's part of my build... Still see that issue, though (v1 renderer).

**Comment by Nine-Tailed** [comment]
Is it normal that the compass buttons are now black and white?

**Comment by Chumva** [comment]
@sonora Do you mean single tap rotation to north in these modes?

**Comment by Nine-Tailed** [comment]
@Chumva, when you rotate the map, the compass needle does not rotate and only points upward.

**Comment by Nine-Tailed** [comment]
![Screenshot_2024-09-06-16-01-39-248_com.mi.android.globallauncher-edit~2.jpg](https://github.com/user-attachments/assets/0302c0a7-2701-4819-8e1d-2ec199701d94)

**Comment by Chumva** [comment]
Looks like it happens if we changed icon (it becomes greyed), if you reset compass button appearance it should work fine

**Comment by sonora** [comment]
Yes, it started when we changed the icons. Now they are always grayscale (which is fine by me), but always static, i.e. **always** pointing to the device top.

I think we should find a better fix than everybody having to reset the widget, that would cause more noise than we can handle upon the next release.

**Comment by Nine-Tailed** [comment]
Also about the buttons - there were quick buttons for showing poi, which changed their appearance when they were turned on, the image in the button became crossed out. Now this does not work

![Screenshot_2024-09-06-16-37-55-309_net.osmand-edit.jpg](https://github.com/user-attachments/assets/629c2af9-4c18-4308-a7cf-98a152acf8ba)
