### ISSUE TITLE
tourism=attraction objects is not found and not displayed in filter Sightseeing

### ISSUE THREAD

**Issue by dypa** [osmandapp/OsmAnd#20782]
### Description

Tourism=attraction for relations and ways is not found and not displayed in search with filter Sightseeing

### Steps to reproduce

- move map to https://www.openstreetmap.org/way/66759388 or https://www.openstreetmap.org/relation/17947791
- open search
- enable filter Sightseeing
- click "show Sightseeing on the map"

### Actual result

Map NOT shows stars for building and multipolygon

### Expected result

Map shows stars for building and multipolygon

### Your Environment (required)

```
OsmAnd Version: 4.8.5
Maps: 2024-09 + live
```

**Comment by dypa** [comment]
also reproduce in `fdroid version 4.8.6 (480603)`

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.9.0#3173m, released: 2024-09-12
Ways and relations tagged with tourism=attraction cannot be found in the search. 

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/3cc48645-2447-484f-87a8-63b58b4fb604"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/6d773069-efeb-4a38-9008-cfa59b94172b"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/26e07df3-27ad-49db-b8f6-644d507c9ffd"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Fixed. leningradskaya map will be updated today.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.9.0#3289m, released: 2024-09-26
objects still cannot be found when filter Sightseeing is applied both for Leningradskaya oblast map and for Saint-Petersburg map. [Comment](https://github.com/osmandapp/OsmAnd/issues/20782#issuecomment-2347224054) remains relevant
59.716152 30.401774
59.729305 30.394610

**Comment by dypa** [comment]
@DmitryAlexei lets wait for 2024-10-01 for map update, because live updates deliver only changed by mapper data. some cases looks working, some not, some looks like new issues :)

lets see on examples when filter works in 4.8.6 fdroid:
- https://www.openstreetmap.org/way/66759388 changed 2024-09-23, renders star after live update (**i think ways works correct**)
- https://www.openstreetmap.org/relation/17947791 not changed in live update, members of relation not changed too, no star
- https://www.openstreetmap.org/relation/8884343 not changed in live update, members of relation changed, no star
- https://www.openstreetmap.org/relation/18082832 and https://www.openstreetmap.org/relation/18082833 new relations for live update, star renders (**but renders in center of relation** - looks like new issue in some cases)

**Comment by DmitryAlexei** [comment]
@dypa thanks for your reply
https://www.openstreetmap.org/way/66759388 changed 2024-09-23 really works after live update

**Comment by dypa** [comment]
@DmitryAlexei received  2024-10-01map update, checked all cases from https://github.com/osmandapp/OsmAnd/issues/20782#issuecomment-2377018234 all passed! 🎉🎉🎉
@xmd5a2 thanks a lot! 🎇
