### ISSUE TITLE
2 city points (1 basemap & 1 address) in search

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#21120]
### How to reproduce
* Download **Berlin** map
* Open **Menu** – **Search** 
* Search for `berlin`

### Actual result

<table style="width:100%">
  <tr>
    <th>Search</th>
    <th>First point</th>
    <th>Second point</th>
    <th>Third point</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/00ee0954-488b-49fa-a311-9320b8f87115"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/59f0615b-0e90-4093-867e-0677ee3b1345"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/6ffe5797-612c-473d-b44f-418a2c5c0f95"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/a7d72e34-8ab9-4015-99ce-74a87581cc8f"  width="200" height="auto"/> </td>
  </tr>
</table>  

* 3 points will be show
* First: opens Address search, street selection
* Second: city POI from basemap
* Third: city POI from detailed map

### Expected result

* One item, tap should open list of streets
* * Tap on Show on map - should open proper POI context menu 

**Environment**
OsmAnd Version:
Android: 15
Device model: Google Pixel 6A

**Comment by vshcherb** [comment]
Easy to reproduce in web as well. 
1. City point from address is not correct - it takes polygon center and not admin_center from relation - Check berlin. This needs to be fixed first
2. In search results filter for 1 point Berlin (that comes from basemap - it has less tags) and display only point from standard map.

![Image](https://github.com/user-attachments/assets/c483856f-ed1e-40b9-92da-fff30dddecab)

**Comment by xmd5a2** [comment]
After merging last [PR](https://github.com/osmandapp/OsmAnd-tools/pull/1028) basemap generation is broken. 

World_basemap zoom 7:
![Image](https://github.com/user-attachments/assets/ec199a61-fbeb-4bdf-a8fe-5410ae21f4e6)
![Image](https://github.com/user-attachments/assets/70850f40-0861-4130-8613-84f787d5612c)
Most of data extracted from our OSM DB (/home/basemap/mapnik-db dir on creator.osmand.net) had positive id. Last PR changes handling of it and object with incorrect geometry are created.

**Comment by xmd5a2** [comment]
Basemap was updated. Now all peaks/volcanos/cities should be searchable without duplicates when detailed map and basemap are used together.

**Comment by Zirochkabila** [comment]
# Testing 1
`Web`
`4.9.5.4981`
`OsmAnd~ 5.0.0#4433m, Released: 2025-02-21`
**Fixed, worked only with World overview map**

**Comment by dmpr0** [comment]
# Review

- [ ] Search for Berlin still shows two points. (World overview map mini should update with the app?)

**Comment by vshcherb** [comment]
- [x] Id and OSM link is correc
- [ ] No deduplication in Search still (they are not necessarily next search items to each other)
- [ ] We would need to merging object information or display the most detailed

**Comment by ivanPyrohivskyi** [comment]
Test with March 2025 maps !

**Comment by Zirochkabila** [comment]
# **Testing 2**

`4.9.5.4987`
`OsmAnd~ 5.0.0#4578m, Released: 2025-03-06`

## 🟠 **Major**

- [ ] **1. The list of sub-results in the first item is different between Android & iOS**
- **Issue:** The search result displays a common result “Berlin,” but the list of results in the first item is different between Android and iOS, leading to potential inconsistencies for users. 
The [administrative](https://www.openstreetmap.org/relation/62422#map=19/52.510997/13.399112) center is the same on both devices.

Initial data:
1. The map is centered at coordinates `52.510997/13.399112`
2. The zoom level is `15`

<details><summary>Search "berlin"</summary>
<table style="width:100%">
<tr>
<th>Android result</th>
<th>iOS result</th>
</tr>
<tr>
<th><img src="https://github.com/user-attachments/assets/48e3fd1f-02d9-4e3a-a85d-12525fefb65f"  width="300" height="auto"/> </th>
<th><img src="https://github.com/user-attachments/assets/5a512860-45c3-4323-9c74-c5c198e73659"  width="500" height="auto"/> </th>
</tr>
</table> 
</details>

<details><summary>List at the first point</summary>
<table style="width:100%">
<tr>
<th>Android</th>
<th>iOS different</th>
</tr>
<tr>
<th><img src="https://github.com/user-attachments/assets/c1755b1f-6823-4d77-9f3b-fe7e683de7e3"  width="300" height="auto"/> </th>
<th><img src="https://github.com/user-attachments/assets/a22a0c93-d92f-4fdc-9d24-1706523f0965"  width="500" height="auto"/> </th>
</tr>
</table> 
</details>

<details><summary>Show on map</summary>
<table style="width:100%">
<tr>
<th>Show all - Android</th>
<th>Show all - iOS</th>
</tr>
<tr>
<th><img src="https://github.com/user-attachments/assets/e06f2e86-75f0-4075-a2d1-a046925c473e"  width="300" height="auto"/> </th>
<th><img src="https://github.com/user-attachments/assets/f4b412ad-a048-4024-a5b5-8ef4c3a296c7"  width="500" height="auto"/> </th>
</tr>
</table> 
</details>

**Comment by vshcherb** [comment]
Needs to be verified "Berliner" is partial search result or complete

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>iOS</th>
        <th>Android</th>
      </tr>
      <tr>
        <td><video src="https://github.com/user-attachments/assets/4283e5a1-b6bf-428c-9249-48b51cc98317"  width="300" height="auto"/> </td>
        <td><video src="https://github.com/user-attachments/assets/d78fba71-e932-418d-b639-9356ce98c2e3"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   


- [ ] Items in search open the next search level (address search). I expect a context menu with a map to open. 
* * Both Android and iOS 

- - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>From Search</th>
        <th>From Map</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/9a68e9d4-29cf-467d-b727-3904f0501fe5"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/7f3552ab-d891-4e5a-b182-8a0c61438cb3"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   


- [ ] Taping Show on map, on the next step, opens half empty context menu

**Comment by vshcherb** [comment]
# To Fix

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>From Search</th>
        <th>From Map</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/9a68e9d4-29cf-467d-b727-3904f0501fe5"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/7f3552ab-d891-4e5a-b182-8a0c61438cb3"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   


- [ ] Taping Show on map, on the next step, opens half empty context menu - this related to wikidata - https://github.com/osmandapp/OsmAnd-Issues/issues/2895. And https://github.com/osmandapp/OsmAnd/issues/22050. Now from search / map all POIs should be combined by wikidata or osmid and tags displayed together. As we always while opening context menu search in a small radius 10-50m all maps all poi sections
