### ISSUE TITLE
Incorrect transparency adjustment when underlay and overlay maps are enabled

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#21158]
### Description

In addition to the vector map, I have the underlay (satellite) and overlay (strava) maps enabled. When adjusting the visibility of the overlay map, vector map objects (roads, rivers, lakes) are hidden. The problem only exists on rendering engine 2. On version 1, everything works correctly.
Rendering v2:

https://github.com/user-attachments/assets/7dae1ebe-24e9-4b31-8d45-4c4ae4d58eee

Rendering v1:

https://github.com/user-attachments/assets/b8bcd878-ba0b-4d1c-bf29-165af9dc6056

### Steps to reproduce

Set underlay: satellite.
Set overlay: strava.
Turn on the transparency slider for the overlay.

### Actual result

When two additional layers are enabled, then when adjusting the overlay makes main layer transparent (roads, rivers, lakes). It leads to wrong situation when underlay is visible but main layer is not visible.

### Expected result

Main layer transparency shouldn't be affected by Overlay transparency. 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 4.9.0#3579m, Дата выпуска: 2024-10-26
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The issue has been successfully reproduced. To replicate this behavior, set the Underlay map to Yandex Satellite, and move the Base map transparency slider to the maximum. Next, set the Overlay map to a custom Strava heatmap. Begin by enabling the Underlay map first, then enable the Overlay map, and try adjusting the map visibility using the lower slider.

As a result, you'll notice that adjusting the visibility of the overlay map causes vector map elements (such as roads, rivers, and lakes) to disappear.

This occurs because the lower slider applies to the last enabled layer (either the Overlay or Underlay map).

OsmAnd~ 4.9.0#3603m, released: 2024-10-30

<table style="width:100%">
  </tr>
  <tr>
    <th>Version 2 (OpenGl)</th>
    <th>Version 1</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/user-attachments/assets/504cc28d-dad9-4f61-a5fc-3bf3cb484a10"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/8dfaf873-a364-4c44-b347-fc2d6d01a4a2"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
I think it's a duplicate, UI element always controled the last selected layer

**Comment by Nine-Tailed** [comment]
In fact, on version rendering engine 2 we lost the ability to see three maps at once. More precisely, you can see them if you collapse and expand the osmand.
https://github.com/user-attachments/assets/d7580cf9-e0c8-4118-970b-ae2b8ea23956

**Comment by Chumva** [comment]
This behaviour for opengl was added [here](https://github.com/osmandapp/OsmAnd/pull/15321)

**Comment by vshcherb** [comment]
Yes, strange it was fixed exactly by your request - https://github.com/osmandapp/OsmAnd/issues/14347 and then https://github.com/osmandapp/OsmAnd/issues/15411

**Comment by Nine-Tailed** [comment]
wait, the problem is not solved. I don't know how you work with layers, but for example in Photoshop, when you adjust the transparency of the top layer, you adjust the transparency of the top layer, without affecting the underlying layers. In Osmand, for some reason, in this case, adjusting the transparency of the overlay map, which is the top layer, simultaneously changes the transparency of the vector map, which should not happen and this is exactly how it works on engine version 1.

**Comment by EugeneZmeuk** [comment]
@Nine-Tailed 
We don't speak about Photoshop. 
There are four scenarios: slider and overlay/underlay.
1. slider on - Overlay, slider off - Underlay
2. slider on - Overlay, slider on - Underlay
3. slider off- Overlay, slider on - Underlay
4. slider off - Overlay, slider off - Underlay

|1|2|3|
|--|--|--|
|https://github.com/user-attachments/assets/fae41d79-d5cd-4570-9232-41dc0fc3ca40|https://github.com/user-attachments/assets/cd8c0107-f1cb-4de6-aed3-fc08d38f7e48|https://github.com/user-attachments/assets/7a735140-107f-4921-8ca9-4afde99eb7e5|

**Comment by EugeneZmeuk** [comment]
@Nine-Tailed 
Yes, the logic of rendering 1 and 2 is light different. 
With this issue, I see the bug for the first scenario (slider on - Overlay, slider off - Underlay). 
@vshcherb we need to reopen this issue. Because there is a bug [with my first test](https://github.com/osmandapp/OsmAnd/issues/21158#issuecomment-2470724508): slider on - Overlay, slider off - Underlay. When we move the slider, the opacity changes for Overlay and Underlay too. But Underlay must have static opacity.  For [scenario 3]https://github.com/osmandapp/OsmAnd/issues/21158#issuecomment-2470724508): slider off- Overlay, slider on - Underlay. Everything is ok: when we move the slider, the Underlay opacity changes, Overlay opacity no.

**Comment by Nine-Tailed** [comment]
@vshcherb, but we are not talking about poi and text, they work fine. We are talking about roads, rivers, lakes.

**Comment by vshcherb** [comment]
I updated your comment with expected result and reproducing steps
