### ISSUE TITLE
Add support for `camp_site=basic/standard/...`

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#21332]
## Description
Add support for `camp_site=basic/standard/...` to categorise campsites. From [Discussions](https://github.com/osmandapp/OsmAnd/discussions/21322).

Wiki – https://wiki.openstreetmap.org/wiki/Key:camp_site
Example – https://www.openstreetmap.org/way/91220973#map=15/52.40895/9.88538

### ToDo
- [ ] Show in POI details
- [ ] Add as filters

**Comment by xmd5a2** [comment]
Fixed. Place to test [1092107305](https://www.openstreetmap.org/way/1092107305)
Map Belgium_wallonia will be updated tomorrow

**Comment by xmd5a2** [comment]
> I wonder if it is possible to change the label in the app so that it says 'Camp site type' instead of 'Camp_site_*'. Currently it looks like this:
> 
> ![Screenshot_20241211-083111](https://private-user-images.githubusercontent.com/80313840/394624336-ec72916c-ed8e-485f-a946-4cd0ec9c9211.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MTkxMTUsIm5iZiI6MTczMzkxODgxNSwicGF0aCI6Ii84MDMxMzg0MC8zOTQ2MjQzMzYtZWM3MjkxNmMtZWQ4ZS00ODVmLWE5NDYtNGNkMGVjOWM5MjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDEyMDY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwZGEzZDY0NmFmNjRkMzFlMDExNWQ4ZWE5MjlmY2JiNTdhMzFjMzcxOTdmZDllNTk0MGRmMDc4NjljNWYyNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Vc4DQpYo1D8DWp0uIteGvtj5EZ5xenVsqWJtb5O2XpI)

It is already in master https://github.com/osmandapp/OsmAnd/commit/61f5fcca4085a02771b4504fbe437b3281fb1101
Will work only after app update

**Comment by Zirochkabila** [comment]
# Testing 1
`OsmAnd~ 5.0.0#3954m, Released: 2024-12-18 ` - **Fixed**
`4.9.1.4927` - Still present
`AppStore version` - Still present


<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/d7788e2d-8f2e-4e1b-8914-459529d97891"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/7aa28010-704f-42de-bc8b-840fceaf3b94"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/cae5b6a5-f18b-4f0a-81c6-b843551145f9"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
@xmd5a2 Does this need to be fixed in iOS?

**Comment by Zirochkabila** [comment]
Needed to check 5.0 iOS
