### ISSUE TITLE
Live Updates Cannot Be Disabled After Canceling OsmAnd Pro Subscription

### ISSUE THREAD

**Issue by yuriiurshuliak** [osmandapp/OsmAnd#21385]
### Description

When a user cancels their OsmAnd Pro subscription, any enabled live map updates remain active in the free version of the application. These updates occur every hour, and the user cannot disable them without re-subscribing to OsmAnd Pro or reinstalling the app.

### Steps to reproduce

1. Install the free version of OsmAnd.
2. Subscribe to OsmAnd Pro.
3. Go to **Menu → Maps & Resources → Updates** and enable **Live Updates** for several maps.
4. Log out of the Pro subscription, reverting to the free version.
5. Observe that live updates for the previously selected maps continue to work in the free version.
6. Try to disable live updates in the free version via the **Updates** tab or any other menu.

### Actual result

- Live updates continue to refresh maps every hour in the free version.
- No option exists in the free version to disable these updates via the **Updates** tab.
- The only workarounds are:
 1.Re-subscribing to OsmAnd Pro, disabling live updates, and then logging out.
 2.Reinstalling the application, which results in the loss of all local data.

### Expected result

- Live updates should automatically disable when the user logs out of OsmAnd Pro and returns to the free version.
- Alternatively, users in the free version should be able to manually disable live updates from the **Updates** tab or another accessible menu.

### Your Environment (required)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/016fc66b-b726-4f36-94d3-b609ca76e7c6"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/7e236113-44d2-428f-bc0c-7df0d48f59ab"  width="300" height="auto"/> </th>
  </tr>
</table>

```
OsmAnd Version: 4.9.7
Android version: 14
Device model: One Plus

```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced your steps. Here’s a summary:

1. Downloaded the free version of OsmAnd from Google Play.  
2. Restored or logged into an OsmAnd Pro subscription.  
3. Downloaded maps and enabled **Live Updates** for them.  
4. Logged out of the OsmAnd Pro subscription, reverting to the free version.  
5. Note that live updates remained enabled in the free version without an option to disable them under **Menu → Maps & Resources → Updates**.  

OsmAnd 4.9.7, released: 2024-11-18

**Comment by vshcherb** [comment]
To do: Live updates should automatically disable when the user logs out of OsmAnd Pro and returns to the free version.

**Comment by Chumva** [comment]
It should be fixed [here](https://github.com/osmandapp/OsmAnd/commit/30c9ac07074f60f88246409c2a326910743e8f9f)

**Comment by Zirochkabila** [comment]
Bug still present 
`OsmAnd~ 5.0.0#3793m, Released: 2024-11-25`
[logcat (91).log](https://github.com/user-attachments/files/17906320/logcat.91.log)



https://github.com/user-attachments/assets/5ff3082e-5dd4-44c5-84a9-4fec0187700e
