### ISSUE TITLE
building=* + abandoned=yes is not rendered

### ISSUE THREAD

**Issue by demonbox73** [osmandapp/OsmAnd#21736]
### Describe the idea

Hi excuse me I noticed that this tag
building=* + abandoned=yes is not rendered
and
abandoned:building=* is not rendered too.

### Expected behaviour

It's kindly possible to render these tags?

building=* + abandoned=yes 

and

abandoned:building=* 

Thanks!
--enrico

### Alternatives you've considered

None

**Comment by mariush444** [comment]
similar discussion to #21505
as I understand `abandoned:building=*` should be use and not `building=* + abandoned=yes`

**Comment by scaidermern** [comment]
> similar discussion to #21505 as I understand `abandoned:building=*` should be use and not `building=* + abandoned=yes`

I'm not quite sure here. An abandoned building is still a building, so `building=*` + `abandoned=yes` is equally valid if not even better better than `abandoned:building=*`.
However, for many other POIs `abandoned:key=value` should be used according to the [lifecycle prefix](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix).

**Comment by demonbox73** [comment]
> > similar discussion to #21505 as I understand `abandoned:building=*` should be use and not `building=* + abandoned=yes`
> 
> I'm not quite sure here. An abandoned building is still a building, so `building=*` + `abandoned=yes` is equally valid if not even better better than `abandoned:building=*`. However, for many other POIs `abandoned:key=value` should be used according to the [lifecycle prefix](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix).

Yes I'm absolutely sure too an abandoned bulding is still a building so it's wrong that it disappear in the render.

Anyway now the situation is this:

building=* + abandoned=yes   NOT RENDERED

abandoned:building=*  NOT RENDERED

Until about 2 months ago both combinations were rendered, so please the OsmAnd Team can fix this issue?
Thanks.

**Comment by demonbox73** [comment]
Wo should be informed about these rendering issues?

**Comment by xmd5a2** [comment]
Not reproducible. We have some rendering tests for abandoned objects and they are passed correctly. See:
![изображение](https://github.com/user-attachments/assets/f779eb74-a44c-41c4-86c2-8b2a861d385f)
If you observe that some building is not rendered please give us OSM link or coordinates.

**Comment by demonbox73** [comment]
This object is not rendered:

https://www.openstreetmap.org/way/295356617

**Comment by demonbox73** [comment]
...and this object is not rendered too:

area:highway=steps

https://www.openstreetmap.org/relation/18557625

Thanks

**Comment by xmd5a2** [comment]
> This object is not rendered:
> https://www.openstreetmap.org/way/295356617

It is rendered but under quarry. Issue is reproduced.

Regarding _area:highway=steps_: please don't mix different issues. Please create a separate issue.

**Comment by demonbox73** [comment]
@xmd5a2 

If it is rendered but under quarry. I think that is still an issue to fix. Don't you?

**Comment by demonbox73** [comment]
@xmd5a2 
Thanks

**Comment by vshcherb** [comment]
@xmd5a2 do you have screenshot? Is this issue related to abanodned or regardless this tag building is rendered under bigger polygon?

**Comment by demonbox73** [comment]
> [@xmd5a2](https://github.com/xmd5a2) do you have screenshot? Is this issue related to abanodned or regardless this tag building is rendered under bigger polygon?

yes

![Image](https://github.com/user-attachments/assets/85c7db97-6937-4113-8ad0-86fbcdaec217)

**Comment by demonbox73** [comment]
The yellow star WP indicates the position of the building+abandoned=yes

**Comment by xmd5a2** [comment]
Dev notes: abandoned:landuse=quarry has order 10 in default style, same as building. Removing order for abandoned:landuse=quarry (5 will be used by default) solves issue:

![Image](https://github.com/user-attachments/assets/a272f4a0-b83f-4607-b937-0d48ad6ee821)

**Comment by demonbox73** [comment]
mmm, now the render is this:

![Image](https://github.com/user-attachments/assets/e2bfc951-e02e-4bb0-819b-077849f44943)

1) I still don't see the building=yes + abandoned=yes
2) The abandoned:landuse=quarry is rendered exactly like landuse=quarry

I'm sorry but overall it seems to me that it is worse than before...

**Comment by xmd5a2** [comment]
I did nothing. This issue was in "reproducing" state and I was checking source of issue and possibility to fix.

**Comment by demonbox73** [comment]
> I did nothing. This issue was in "reproducing" state and I was checking source of issue and possibility to fix.

ok you did nothing but the render is radically changed.....

**Comment by xmd5a2** [comment]
@vshcherb Rendering style correction mentioned in [earlier post](https://github.com/osmandapp/OsmAnd/issues/21736#issuecomment-2609802862) doesn't causes noticeable side issues. I've done some synthetic tests:

![Image](https://github.com/user-attachments/assets/07853ebd-0d4f-4a69-ada5-7531672eb92d)

**Comment by demonbox73** [comment]
ok but I had OsmAnd PRO with Live updates and this abandoned:landuse

https://www.openstreetmap.org/relation/3926366

now has a changed rendering as my previous screenshot

**Comment by demonbox73** [comment]
Hi @xmd5a2 
now the render is correct again as this screenshot just made

![Image](https://github.com/user-attachments/assets/ea47f81c-ce52-4252-a30d-980e05ce8975)

but the building=yes + abandoned=yes is still missing....

**Comment by xmd5a2** [comment]
Fixed. No new maps required.

**Comment by demonbox73** [comment]
> Fixed. No new maps required.

I'm sorry but nothing is changed... building + abandoned=yes is still missing..... as my last screenshot

**Comment by xmd5a2** [comment]
OpenGL nighlty:
![Image](https://github.com/user-attachments/assets/6108bd57-e149-464f-9daa-befb1f76a235)

**Comment by demonbox73** [comment]
> OpenGL nighlty: ![Image](https://github.com/user-attachments/assets/6108bd57-e149-464f-9daa-befb1f76a235)

My screenshot i'ts still the same: without buildings....

**Comment by Zirochkabila** [comment]
# Testing 1
`OsmAnd~ 5.0.0#4239m, Released: 2025-01-27`
`4.9.5.4953`


Displayed in Legacy on Android and in the iOS version
But, it does not display in OpenGL on Android

<details><summary>Legacy</summary>
<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th>OpenGL</th>
    <th>Legacy</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/fb416fe1-7c7d-405a-a042-9eb9a1e429f9"  width="400" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/fdfe8057-4a35-4eea-a3c9-d131543740d7"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/08626dd9-6961-4429-84d0-0b648e4ad6a7"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details>

**Comment by demonbox73** [comment]
> # Testing 1
> `OsmAnd~ 5.0.0#4239m, Released: 2025-01-27` `4.9.5.4953`
> 
> Displayed in Legacy on Android and in the iOS version But, it does not display in OpenGL on Android
> 
> OpenGL

Yes, I'm on Android!
