### ISSUE TITLE
Track folder appearance is not synced with Cloud

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#21928]
After many frustrating tries I reduced my requirements to the "CloudSync" on synching tracks and favorites.

One suggestion to this minimum requirement:
Somewhere hidden in the app there must be the tracks appearance settings. 
I don´t know where, but it has to be somewhere :-)
Make these settings being synched in one go with synching the tracks, please!

This would be incredible helpful. Thanks!

**Comment by vshcherb** [comment]
Track appearance settings should be synced if you selected to sync Tracks.

**Comment by Rowin63** [comment]
I don´t know how this is working.

) I run a sync. So everything is up-to-date on both sides.
) I change the standard appearance of a track-folder (arrows, start/finish icons, color, width)
) all the contained tracks appear with my chosen settings 
) I run a sync - nothing but this single file is synched: /color-palette/user_palette_default.txt (is this the file that contains the track´s settings?)

) if now I sync "Cloud > to device B" (having selected only "my places / tracks"!) nothing happens, because there is no change in the tracks and this color file is placed somewhere else and not synched with the tracks.

So I have to synch more than just the tracks.

**Comment by Rowin63** [comment]
No way to get the track´s colors synced.

Device A (my "master"): 
ALL syncing options set to active/on

Device B: (my minimum goal is to receive "profiles", "quick actions" and "my places" (favorites, av-notes, tracks WITH their appearance) from device A (A>Cloud>B):
Sync options: Section "Settings": ALL / Section "my places": ALL / Section "Sources": style, routing, colors ON

No track color is transfered to device B.

**Comment by Rowin63** [comment]
And how to exclude "global settings". This causes a conflict/change after every app start.

) first it appears as a "conflict"
) upload it to the cloud
) now it appears as a "local change"
) upload it to the cloud again
) now it appears as a new "conflict" on device B
) starting over again, never ending :-)

**Comment by Rowin63** [comment]
Track appearance is only synced if:

) creating a new folder > setting folder standard appearance
) creating a new track (has a standard appearance) > moving this track into new folder > track gets the folders standard appearance
) now syncing > folder and track is synced correctly with the desired appearance from device A > cloud > device B

BUT: 
Any further appearance changes done to this folders or its tracks are ignored at next sync (sync process remains empty - nothing to sync). So appearance changes done to existing tracks and folders can not be synced (nothing to sync after a further change).

**Comment by yuriiurshuliak** [comment]
I was able to reproduce the bug across **Android, iOS, and the Web version** using the following steps:  

1. On an **Android device**, create a **new folder** and add **10 tracks**.  
2. Change the **Default appearance** for the folder (e.g., set **blue color**, enable **Direction Arrows**, and **Show Start/Finish Icons**).  
3. Perform a **Cloud Sync** to ensure all devices are up-to-date.  
4. Verify that the **tracks in the folder correctly reflect the Default appearance**.  
5. On the **same Android device**, modify the **Default appearance** again (e.g., change to **yellow color**, disable **Direction Arrows**, and **Show Start/Finish Icons**).  
6. Confirm that **all tracks in the folder adopt the new appearance**.  
7. Perform **Cloud Sync** again.  
8. On **Device B**, sync from the Cloud.  

### **Observed Result:**  
- The **track appearance settings are not transferred** to the second device.  
- The file **/color-palette/user_palette_default.txt** conflicts, but even manually adding it to **Local Changes** does not apply the settings to tracks on the second device.  

This suggests that **appearance settings for track folders are not syncing correctly across devices**. 

OsmAnd~ 5.0.0#4544m, released: 2025-03-04
OsmAnd 4.9.5 (4986)

<table style="width:100%">
  </tr>
  <tr>
    <th>Android</th>
    <th>iOS</th>
    <th>Web</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/user-attachments/assets/0193740c-6221-4345-ad51-5660a45f1613"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/6c649931-0ff8-4da4-b81f-76d5ad356a64"  width="300" height="auto"/>   </td>
 <th><img src="https://github.com/user-attachments/assets/95e19711-f614-4381-874e-0fb07fc8deb7"  width="500" height="auto"/> </th>
  </tr>
</table>

**Comment by Rowin63** [comment]
At least, now the tracks are not reset anymore to "standard" when renaming a track folder.
So this makes a "workaround" for syncing the track´s appearance possible and a bit more easy, until the final fix :-)

) set "folders standard appearance" as desired (device A)
) all contained tracks are displayed as set (but if you sync now A>cloud>B, the appearance on B gets completely mixed up) 
) now rename this folder (A) 
) sync (now the tracks all appear, in the renamed folder, with the desired appearance settings on B)
) rename the folder back (A)
) sync again
) now A and B have the same track´s appearance 

(no further single appearance changes will be synced correctly, then you have to go over this procedure again - but at least it is a possible way)

Works also between Android release and Nightly.

**Comment by Rowin63** [comment]
Oh. The last four folders I renamed (inside the app) had not been reset and the tracks kept their appearance. Now I moved a subfolder outside to the main directory (by a file manager) and the tracks got reset. No big deal, but different from before.

**Comment by vshcherb** [comment]
To do fix: syncing Android -> Android. Fix track folder appearance stored and loaded. Document in which file it's stored

**Comment by DmitryAlexei** [comment]
To think: how should folder appearance be stored?

**Comment by Chumva** [comment]
Offline backup - no UI changes, online backup - folder change is visible in tabs

**Comment by Rowin63** [comment]
Updatet both devices to the latest release:
Device A: +5.2.3
Device B: ~5.3.0#6294m

Syncing the track appearance via Cloud still is not working correct.
No matter on which side I set the folder appearance, after syncing via cloud the other side gets mixed up.
(though "folder appearance"-settings are displayed the same on both devices, the track´s appearance is different - it always seems to be set back to some previous status)

From A>cloud>B and also from B>cloud>A

Set one device to:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/e7da61f2-15fe-44a9-85b7-d456b75fd767"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/a19df104-b77e-4962-856d-d8e290c188f2"  width="300" height="auto"/> </th>
  </tr>
</table>  

Result synced to the other device:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/f0ab5e62-40f2-48ce-b55d-5f642420df00"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/351e025c-d87b-4a5c-89e6-ecbdb6fecbdf"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Rowin63** [comment]
It seems to be synced correctly **TO** the cloud, but not **FROM** the cloud.
Both directions.

**Comment by Rowin63** [comment]
What is synced after setting a folder appearance on device B:

B>Cloud: folder, tracks, user_palette_default.txt
Cloud>A: tracks, user_palette_default.txt (but NO folder!) 
=> after the sync the (non synced!) folder appears as a "conflict" on the "receiving" device A!

RESULT until here: "folder settings" is NOT synced, but the previous track´s setting on A is mixed up.
SOLVING the "folder" conflict (Cloud>A): tracks still have mixed up settings, but different from right before (some tracks got their "new" folder settings, but most of them don´t)
BUT: this folder immediately appears as a "local change" on (receiving) device A.

It´s not possible to get the same folder appearance on both devices, no matter how often and which direction I try.

Note: 
It´s a bit difficult to reproduce clearly, because on every sync this issue #23637 appears to sync, too ("global settings", "avoid road") and I don´t know, if perhaps "global settings" is involved in this issue here, too...

**Comment by Rowin63** [comment]
And, finally, after this previous procedures ALL folders on Device A are marked as "deleted" again, waiting to get synced (#23663)...

![Image](https://github.com/user-attachments/assets/fc1f5740-faca-42e7-8a5f-4b30af1c8336)

At the moment, syncing seems pretty risky - I never know what is true ("deleted" folders) or not...

**Comment by Rowin63** [comment]
Sorry for creating all this little issues, but at the moment I can´t use Osmand as I want/need to. 
Especially all the issues around syncing are a killjoy.

**Comment by Zirochkabila** [comment]
# Testing 1

> OsmAnd~ 5.3.0#6420m, Released: 2025-11-05

> Device 1 - Android 12
> Device 2 - Android 16
> Device 3 - iPhone
> Device 4 - Web

## **Severity:** 🟠 Major

> **Priority:** 🔴 High / **Frequency:** High

- [ ] 1. The folder synchronization between devices and Cloud is inconsistent — folders either disappear, appear as deleted, or are not displayed at all.

D1 - Create new folder > Change appearance > Download to Cloud

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/95e5505b-cb81-4356-89c3-d9c7670bb488"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/98c7dd44-79fb-48e7-a6bb-b02c318c9581"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details> 

D2 - Find folder in Cloud Changes > Download to Device = Folder is not stored on the device and is displayed as deleted in local changes

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/ac213b8f-44fd-4bb5-9b51-0db6083efcd9"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/c0786388-bd8e-4559-83bc-75c8f537fafe"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/413ede58-3247-4b84-bfe5-e125920a9375"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details> 

D3 - Folder not showing up in the Cloud
D4 - Folder shows up in changes, but doesn't show up in the file list

[tracks_Folder appearance 1.json](https://github.com/user-attachments/files/23367393/tracks_Folder.appearance.1.json)

<details><summary>Details</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/72f73ee0-9c96-4be1-9edd-69800529369f">
</details>

**Comment by dmpr0** [comment]
## UI Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/8ec8af0e-61be-486d-89dc-8a2388b27e3a"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [x] Color palette is shown as Local change after each change of Track folder appearance
* * Log – [logcat (5).log](https://github.com/user-attachments/files/23392311/logcat.5.log)

- - - - - -
 
- [x] Rename `/color-palette/ user_palette_default.txt` to **User palette**.

- - - - - -
 

<img width="300" height="auto" alt="Image" src="https://github.com/user-attachments/assets/fd60abc9-fcaa-400c-90ba-7ed165f527a6" />


- [x] Use `ic_action_folder_appearance` for folder appearance item. 
- [x] Add **Appearance** to the second line after the data, for example `Modified: Yesterday, 13:44 • Appearance`

**Comment by Rowin63** [comment]
I don´t know what we´re doing different, but nothing has changed. 
It´s still the same - track appearance is messed up after syncing.
Both devices run the latest nightly (~5.3.0#6568m)

<table style="width:100%">
  <tr>
    <th>Device A folder settings</th>
    <th>Device A track appearance</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/5b4e2a0a-6253-46b3-ba20-81dbd37d438a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/f236ee62-d9fc-45b8-b5de-bee6f054cd75"  width="300" height="auto"/> </th>
  </tr>   
</table> 


==> Now run a sync A > cloud > B



<table style="width:100%">
  <tr>
    <th>Device B synced (received) folder settings (seems to be synced correctly)</th>
    <th>Device B synced track appearance (nothing has changed to the last releases, appearance still is totally messed up</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/9601b107-512f-4a07-a2f4-d11cf4f9ab99"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/761ca23d-2379-4320-b6d1-a4745d452043"  width="300" height="auto"/> </th>
  </tr>   
</table> 


So on my side NOTHING has changed since "closing as completed" - it is exactly the same misbehaviour as it was before.

**Comment by Rowin63** [comment]
It´s not even possible, to sync "folder appearance" on a freshly reset folder (as described below) A > cloud > B

Creating a freshly reset folder:

closing Osmand > moving a folder away from Osmand by a file manager > reopen Osmand > track database gets refreshed > close Osmand > moving back this folder into Osmand by file manager > restart osmand > track database gets refreshed > this folders appearance now is reset to "standard appearance" (only this procedure resets all tracks in a folder to "standard settings" > doing this on both devices)

Then editing the "track folder appearance" (color, width, arrows, start/finish icons) on device A and sync it to cloud (there the changes seem to appear correctly) and then syncing cloud to B with the result of receiving an incorrect, mixed up "folder appearance" on device B.

==> I don´t see any chance to correctly sync a folders appearance between two devices. The problem still seems to be in the sync from cloud > B

**Comment by Rowin63** [comment]
After solving this #23998 (by deleting the original folder) it was possible to set "folder appearance" on device A and sync it A>cloud>B
The first time I ever managed it correctly. But only for ONE TIME. The next change on device B (changing the color) and syncing B>cloud>A was not successful again - some tracks are correct, others have wrong color. Like always before.

**Comment by Zirochkabila** [comment]
# Testing 1

> OsmAnd~ 5.3.0#6572m, released: 2025-11-25

Fixed:

* Color palette is shown as **Local change** after each change of Track folder appearance.
* Use `ic_action_folder_appearance` for folder appearance item.
* Add **Appearance** to the second line after the data (e.g., *Modified: Yesterday, 13:44 • Appearance*).

<details><summary>Details</summary>
<img src="https://github.com/user-attachments/assets/a4a8ac39-d72e-4b89-b95a-506540969d80" width="400"/>
</details>

---

Track appearance settings are transferred to the second device - Track folder appearance synchronisation works correctly - **Fixed**

<details><summary>Details — Device A</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/771d7861-0faa-4204-a02d-c50f54c0bb1b" width="300"/></td>
    <td><img src="https://github.com/user-attachments/assets/4fb80433-5512-48ad-98fc-606b734259a5" width="300"/></td>
  </tr>
</table>
</details>

<details><summary>Details — Device B</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/136035af-9275-43ec-9679-3021be0ea52d" width="300"/></td>
    <td><img src="https://github.com/user-attachments/assets/8fa88d2a-ca5d-4eda-86cc-4e3c791f2754" width="300"/></td>
  </tr>
</table>
</details>

---

### Severity: 🟠 Major

> Priority: 🟠 Normal / Frequency: High

* [ ] 1. `User palette` file appears in conflicts on each device after synchronising the folder and files.

This indicates incorrect conflict-resolution logic: the file is regenerated independently on each device and repeatedly enters the conflict state.

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th>Device A</th>
    <th>Device B</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/92f251d8-f98d-4bde-8e9a-a8fe6c7fd196" width="300"/></td>
    <td><img src="https://github.com/user-attachments/assets/03266a27-0f96-44bb-a625-031b9928890c" width="300"/></td>
  </tr>
</table>
</details>

**Comment by Chumva** [comment]
@Rowin63 could you provide logs before & after import? 

Also, do you use apply only to new, or to existing during track folder editing? 
Do some track items have an old appearance after sync?

<img width="250" height="600" alt="Image" src="https://github.com/user-attachments/assets/9da96a26-2dd2-463c-9f4b-3dd52cfb60a0" />

**Comment by Rowin63** [comment]
I usually use "apply to existing", because I want to edit my existing tracks (here I'm still missing an option "all" - but that's another story, there should already exist an issue for that)

Will share the logs a bit later.

**Comment by Chumva** [comment]
Do some track items have an old appearance after sync? Like, only some of them got a new appearance from device A?

**Comment by Chumva** [comment]
"apply to existing" - saves appearance to each track + as default appearance to folder - probably works as "all"

"apply only to new" - only changes the default appearance, it will be used for tracks in folder if they do not have a specified appearance

**Comment by Rowin63** [comment]
Yes, (sometimes?) it seems, that old settings come back. But I'm not 100% sure about this. Often the synced tracks have 3 different appearances.

**Comment by Chumva** [comment]
@Rowin63 Could you try new nightly?

**Comment by Zirochkabila** [comment]
# Testing 2

> OsmAnd~ 5.3.0#6592m, Released: 2025-11-28

When synchronising A > Cloud > B, folder settings are transferred, but individual colours/track widths are lost - **Fixed**

@Rowin63 Check it too please



<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th>Device A</th>
    <th>Device A</th>
    <th>Device b</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/65a987d4-c4d3-4dba-bdfa-0da110cf6a9b"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/4ffbe3bc-8b51-4272-afe4-c48f1bfff333"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/b6a29242-35e1-4ae0-94c0-8ef5b3229b40"  width="300" height="auto"/> </th>    
  </tr>
</table>  
</details>

_____

@vshcherb @dmpr0 **Important:** `Apply to existing` only applies to the folder where the actual change in appearance occurred. **That is, it does not apply to subfolders.**

**Comment by Rowin63** [comment]
After a few syncs A>cloud>B, editing and back B>cloud>A it looks really good👌

Thanks for being so patient and persistent on this issue 👍👍👍

**Comment by Rowin63** [comment]
>... 
> [@vshcherb](https://github.com/vshcherb) [@dmpr0](https://github.com/dmpr0) **Important:** `Apply to existing` only applies to the folder where the actual change in appearance occurred. **That is, it does not apply to subfolders.**

I remember me asking about this feature. But meanwhile I'm not sure anymore, if this is "the perfect solution". There's an easy way, editing all sub-folders appearance in one go - just go to the sub level and select all > edit all. 
That's quick & easy and probably more flexible (different colors in different levels).

**Comment by Zirochkabila** [comment]
@Rowin63  Perhaps, it would be worth adding another option that would be as follows:
1. Apply only to new
2. Apply to existing
3. Apply to files in subfolders (appears optionally if there are subfolders)

**Comment by Rowin63** [comment]
This issue is closed since months, but still present. 
Two devices, both synced. One track folder > two appearances > nothing to sync. 

Some issues appear as never ending stories. This is one of them.

Nightly:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/31b3400c-92e5-4f1c-8a82-612fa25ba66d"  width="300" height="auto"/> </th>
  </tr>
</table>


Playstore release:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/02f7fd77-789b-4fc9-80d3-b966da26661c"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Rowin63** [comment]
Or maybe this issue is part of one of those annoying "again and again at every app start reappearing changes" like #25312?

**Comment by Rowin63** [comment]
I wanted to check the existing appearance online, OsmAnd web, but my only experience was being sent "back to groundhog day":

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/fb7104a5-07df-44bf-b3a6-0b75cbfe8509"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Rowin63** [comment]
Except two tracks, the online appearance matches the nightly. But it's not synced to the playstore's device (+5.4.0)

(and the two exceptions are the green and the pink track you can see on the playstore device, they appear somehow "standard" in the web)

**Comment by Rowin63** [comment]
Here too (did it on four devices): Since I did what @sonora mentioned somewhere over here https://github.com/osmandapp/OsmAnd/issues/24213 (re/naming the track folder), my whole database got reset -  but syncing seems to work correctly again.

Wasted hours again.
And still more to come, to get back to my user defined track appearances...
