### ISSUE TITLE
Widgets on display got very big (~5.0.0#4475)

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#21976]
### Description

I just ran the latest Nightly update to #4475 and this is what happened to the widgets in all profiles:

![Image](https://github.com/user-attachments/assets/a887e934-adf2-46e9-bc8e-71872ad6aaf4)

instead of before

![Image](https://github.com/user-attachments/assets/e863846e-35ba-426d-9f20-68d5dc70ff4f)

### Steps to reproduce

see above

### Actual result

...

### Expected result

...

### Your Environment (required)

Nightly 5.0.0#4475

**Comment by Zirochkabila** [comment]
@Rowin63 Probably [related](https://github.com/osmandapp/OsmAnd/issues/21814)

**Comment by Rowin63** [comment]
I don´t know if it is, this happened right now at the latest nightly-update - minutes before widgets were displayed normal size.
Copied the profiles from the other device, widgets still remain giant.

**Comment by DmitryAlexei** [comment]
After updating to the latest nightly one of my widget became big, but after switching profiles it is back to normal size
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/ca076e30-26fc-4116-9d22-bb7d011d0bec"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Rowin63** [comment]
I can switch as much as I want, nothing changes.
But this "effect" does not affect all profiles the same way.
"circle" widget is correct in all profiles.
"start" (audio record) is correct in all profiles. 
"time" sometimes is correct, in other profiles giant.
"satellites" some profiles large, other profiles correct.

Anyway, switchnig profiles does not help.

**Comment by Rowin63** [comment]
In the widgets settings their size was set to "medium".
Had to set them all back to "small" as it was before (the update). 
I never changed this setting, this happened at the previous update (in fact, I never knew there was a "size"-setting at all).

Unfortunately there is no such option "apply to all profiles", so all these size-changes back to "small" have to be done widget per widget and profile per profile. A lot to do.

**Comment by Rowin63** [comment]
"circle" has no "size" setting, but it switches back to "small" after delete/save/add/save it.

**Comment by albansuser** [comment]
> In the widgets settings their size was set to "medium". Had to set them all back to "small" as it was before (the update). I never changed this setting, this happened at the previous update (in fact, I never knew there was a "size"-setting at all).
> 
> Unfortunately there is no such option "apply to all profiles", so all these size-changes back to "small" have to be done widget per widget and profile per profile. A lot to do (up to 10 widgets in seven profies...)

The widget size setting is new. 

Yes, a size "apply to all" widgets in a profile would be useful.

**Comment by Chumva** [comment]
This should be fixed [here](https://github.com/osmandapp/OsmAnd/pull/21983/commits/acf361ad76e474990a3bad8f37015307b1499a53)

**Comment by Zirochkabila** [comment]
# Testing 1
`OsmAnd~ 5.0.0#4507m, Released: 2025-02-28` - Fixed

@Rowin63 It should be fixed here [4507](https://download.osmand.net/night-builds/OsmAnd-master-opengl-nb-2025-02-28.apk) - check it please

**Comment by Rowin63** [comment]
Yes, fixed - thank you!

**Comment by DmitryAlexei** [comment]
Still persist: when importing old .osf (backup) files, widget may become "medium" size (probably additional task is needed)
