### ISSUE TITLE
You are able to get out of the Zoom range

### ISSUE THREAD

**Issue by quelbs** [osmandapp/Osmand#2197]
When pressing the + until the message "Max Zoom" appears and then do a double tap on the screen it zooms in once again, displaying a plain gray map area.

**Comment by GaidamakUA** [comment]
It should be fixed in next nightly.

**Comment by quelbs** [comment]
Still have the same problem with 2.3.0#15492M and it even got worse, you can double tap multiple times and zoom in every time (the scale is adjusted). Additionally I figured out, that you can pinch-zoom in, when you are at "Max Zoom".
If you zoom in multiple times (using doube tap), you get a "Max Zoom" message even when pressing (-), the only way to get out of this is to use pinch-zoom or another option that resets the zoom factor.

**Comment by GaidamakUA** [comment]
Thank you for pointing this out. I believe it should be fixed now.

**Comment by quelbs** [comment]
Thank you for the fixes, most of the problems are solved now, but when on max zoom and performing a double tap it still zooms in once more and shows an empty gray map area.

**Comment by GaidamakUA** [comment]
Fixed with commit 7e27c21496a78738fdf02a6ba1f667084997619e
