### ISSUE TITLE
Plan route crash when changing routing type

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#22519]
[exception.log](https://github.com/user-attachments/files/20060167/exception.log)

Plan a route - Create new route - add some points - try to change whole track or next segment routing type - crash

https://github.com/user-attachments/assets/bbc30bfa-fd54-4d29-993e-710a68f84431

Device : HWMNA
Brand : HUAWEI
Manufacturer : HUAWEI
Model : MNA-LX9
Product : MNA-L29
Build : MNA-L29 14.2.0.168(C10E2R3P2)
Version : 12
App Version : OsmAnd
Apk Version : 5.0.5 5005

**Comment by Zirochkabila** [comment]
@Velomeloman, Please download the [nightly 5145](https://download.osmand.net/latest-night-build/OsmAnd-android-full-arm64.apk) version and check on your device - **the crash should be fixed**

**Comment by Velomeloman** [comment]
> @Velomeloman, Please download the [nightly 5145](https://download.osmand.net/latest-night-build/OsmAnd-android-full-arm64.apk) version and check on your device - **the crash should be fixed**

Commit had merged to r5.0 but not master yet. 5145 still crash.

**Comment by Zirochkabila** [comment]
@Velomeloman, let's try again, please - [nightly 5150](https://download.osmand.net/latest-night-build/OsmAnd-android-full-arm64.apk)
