### ISSUE TITLE
Zoom level & Ground Fov is not working correctly while driving with 3D Terrain

### ISSUE THREAD

**Issue by Buzzz57** [osmandapp/OsmAnd#23377]
### Description

When 3D terrain is active, the zoom level keeps the same whatever your altitude is.
This forces you to constantly increase or decrease the zoom level while in mountainous areas to keep the same view aspect.

### Steps to reproduce

1) Activate the 3D terrain
2) Travel in a mountainous area
3) don't touch the zoom level

### Actual result

On the pictures below, you can clearly see that the view aspect gets ridiculous as you are at a higher altitude, unless you change the zoom level manually, which doesn't make sense.

<img width="2400" height="1080" alt="Image" src="https://github.com/user-attachments/assets/0d1f6382-bbcb-43f7-a5ce-39f29d953cb2" />

<img width="2400" height="1080" alt="Image" src="https://github.com/user-attachments/assets/e12254e6-e84c-4137-8b30-6ae32a2ea82d" />

### Expected result

The higher you are, the lower the zoom, to keep the same view aspect, without having to touch anything while driving.

<img width="2400" height="1080" alt="Image" src="https://github.com/user-attachments/assets/03d9ca79-c499-46e4-96f6-037f7ef5f445" />

<img width="2400" height="1080" alt="Image" src="https://github.com/user-attachments/assets/7e46cec8-c1b5-4933-91de-150a456594d0" />

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 5.1.7
Android version: 13
Device model: Blackview BV8900
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
**With 3D Terrain enabled, the zoom level does not adjust according to altitude. Instead, the zoom behavior is inconsistent — sometimes zooming in closer at higher altitudes, which makes the map aspect look distorted in mountainous areas.**

**Steps to reproduce**

1. Open OsmAnd.
2. Set start: **47.80140, 6.83768** and finish: **47.82042, 6.83500** (D465 ascent to Col du Ballon d’Alsace).
3. Load the map of this area and download **Terrain map**.
4. Go to **Menu → Configure map → 3D Relief** and enable it.
5. Enable **Auto zoom map → Mid-Range**:
   **Menu → Settings → Navigation settings → Map during navigation**.
6. Drive the route in a mountainous area.
7. Do not manually adjust zoom during the drive.

**Actual result**
From a single test run:

* 789 m → 200 m bar (wider)
* 1103 m → 100 m bar (**closer, opposite of expectation**)
* 907 m → 200 m bar (wider)
* 827 m → 100 m bar (closer)

The ground scale changes with turn/route context, but **not with altitude**, so the “view aspect” varies significantly while driving in mountains.

**Expected result**
When **3D Terrain** is ON, the zoom should auto-adjust with elevation (zoom out as altitude increases) to keep a consistent ground footprint and perspective.
Alternatively, provide a dedicated setting such as **“Altitude-aware auto-zoom (3D)”** with configurable min/max clamps.



OsmAnd~ 5.2.0#5968m, released: 2025-09-05

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/3246b4ec-47a6-4ca4-adc9-66e31545c5ba"  width="900" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/83398bf3-0833-4c16-8c0e-bcf16a0bec40"  width="900" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/902d1751-af1f-4a26-be4a-22a00c98f2fb"  width="900" height="auto"/> </th>
  </tr>
</table>

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/7ecce782-9f29-4dc2-9634-b4ee341cc353"  width="900" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/408bc15c-c0b5-488d-a4a1-9c857fdc6364"  width="900" height="auto"/> </th>
  </tr>
</table>

**Comment by Buzzz57** [comment]
> 5. Enable **Auto zoom map → Mid-Range**:

My initial observations were without autozoom activated. Autozoom just adds its own level of inconsistency... :)

**Comment by vshcherb** [comment]
@yuriiurshuliak no issue at your screenshots. Zoom is related to speed - 1, 3 speed is very high and zoom is around 14+1.63=15.63, once speed is 48kmh zoom is closer 14+2.47 = 16.47. So everything is correct here

Original issue has a strange situation with zoom = 15+4.52 = 19.52 which is way closer than needed to be by speed

**Comment by Buzzz57** [comment]
> Original issue has a strange situation with zoom = 15+4.52 = 19.52 which is way closer than needed to be by speed

The screenshot in the original issue don't have auto zoom activated.

**Comment by Zirochkabila** [comment]
`OsmAnd~ 5.2.0#6103m, Released: 2025-09-19`

Retesting was performed (profile settings were not changed) — as can be seen in the video (2x speed), the camera adapts to the height and maintains the angle (no need to interact with the map)
@Buzzz57 @yuriiurshuliak - please attach a video showing the camera's behavior and what exactly you expect - perhaps it is worth comparing it with my current result.



<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/e87edca9-9e82-4428-baed-d6bb6d92a7df"></video>
</details>

**Comment by Buzzz57** [comment]
> `OsmAnd~ 5.2.0#6103m, Released: 2025-09-19`
> 
> Retesting was performed (profile settings were not changed) — as can be seen in the video (2x speed), the camera adapts to the height and maintains the angle (no need to interact with the map) [@Buzzz57](https://github.com/Buzzz57) [@yuriiurshuliak](https://github.com/yuriiurshuliak) - please attach a video showing the camera's behavior and what exactly you expect - perhaps it is worth comparing it with my current result.
> 
> Details
>  2025-09-19.16.28.22.mov

I will try to upload a video. However, your example video is not relevant for the issue :
1) it is with auto zoom clearly
2) it lasts only a few seconds and doesn't show a sufficient altitude change to get the issue.
3) you don't show either zoom level or altitude.

Thanks anyway for taking the time.

**Comment by Buzzz57** [comment]
Here are 2 videos showing the zoom behaviour on the same route, taken in both directions.
Note that there is no external interaction with the map during the capture.
Auto-zoom is off.

https://youtu.be/uoSVGn6XR5c?feature=shared

https://youtu.be/dkIjETmxvWs?feature=shared

**Comment by Zirochkabila** [comment]
`5.2.0#6208m 5299`

[3d map disabled logcat (11).log](https://github.com/user-attachments/files/22719992/logcat.11.log)
[3d map enabled logcat (12).log](https://github.com/user-attachments/files/22719991/logcat.12.log)

`47.71282° N, 14.26198° E` to `47.71140° N, 14.25310° E`

1. When 3D maps are enabled, the zoom level remains static (almost always 17) - for example, navigation along the same route with 3D maps disabled changes the zoom level within the range of 16-18 - **Main issue**

> 2. When 3D maps are enabled, the position starts to jump. 
> 3. Both with 3D maps enabled and disabled, lags in the animation are displayed (most noticeable in p2).


<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th>3d disabled (zoom level 16-18)</th>
    <th>3d enabled (zoom level 17 almost always)</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/121ebe12-f811-4689-9b6a-000f39bf7847"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/db191d5d-d372-496c-bad8-9a1428fb58ba"  width="300" height="auto"/> </td>
  </tr>
</table> 
</details>

**Comment by Buzzz57** [comment]
Sorry but this has nothing to do with the original issue I raised. The problem is the zoom level while altitude changes.
Maybe you should open another issue.

**Comment by Zirochkabila** [comment]
@Buzzz57 Considering what is shown in the video you added, it was specifically mentioned that when 3D maps are enabled, the zoom level remains static (almost always 17), and when 3D maps are disabled, the zoom level changes within the range of 16-18 — is that what you were trying to show in the video (did I understand correctly)?

**Comment by Buzzz57** [comment]
No, not at all. both videos are with the exact same options activated. In both videos, 3D maps are enabled. And you can see the zoom level changing all the time when the actual altitude changes (by 240m in this case), whereas autozoom is off and I'm not touching any button related to zoom.
at the beginning of the first video, you can see the zoom level is 16+1.10 and at the end, it is 16+3.80. in between it varies, sometimes jumping to 17+x.xx sometimes going back to 16+x.xx
On the second video, it's the same. It starts at 17+3.00 and at the end, it's 16+1.19, again jumping between 17+x.xx and 16+x.xx during all the descent. This is actual footage during an actual route. No simulation.

**Comment by Zirochkabila** [comment]
`OsmAnd~ 5.2.0#6213m, Released: 2025-10-07`

Steps:
1. Menu > Settings > Driving profile > Navigation settings > Map during navigation > Auto zoom map > No auto zooming > Apply
2. Build route from `47.71282° N, 14.26198° E` to `47.70961° N, 14.28890° E` > Downloaded and enabled 3d maps > Simulate navigation > Start > Press 3D button

**Result**

If 3D maps are enabled, the zoom level changes four times on this section of the road (`14 +1.22`, `14 +1.20`, `14 + 1.21`, `14 + 1.19`). 
If 3D maps are disabled, the zoom level remains constant (`15 +0.19` - during all simulation).


<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th>3D maps Enabled</th>
    <th>3D maps Disabled</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/e36ae629-bcaf-483f-ac41-433d6089119d"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/a8630ff7-0ffd-4910-9d18-250bf649ec9f"  width="300" height="auto"/> </td>
  </tr>
</table> 
</details>

**Comment by Buzzz57** [comment]
Thanks for reproducing the issue. Your altitude change might not be sufficient though to fully show the problem.
I will record another video with "camera distance to target" widget, because it seems like the camera keeps the same altitude, whatever the altitude of the target is, which makes the camera distance decrease (aka zoom level +) when the altitude of the target increases, and the opposite when the altitude of the target decreases.
The camera distance to the target should stay constant when auto zoom is off, and the zoom level should as well.

**Comment by Buzzz57** [comment]
Here is another video showing the problem. I have added the camera distance.
It's quite long but you can review it in acccelerated mode.
You can clearly see, that something is not right. IMHO, the distance of the camera should remain the same during the whole trip.
https://youtu.be/D6SjQzQ7hl0

And here is one with the autozoom activated.
https://youtu.be/kAkX1VMvzKI
It's better, but still buggy. The constant zoom changes make the map reload portions every now and then with a different aspect and this ruins the global experience.

**Comment by vshcherb** [comment]
@Zirochkabila in your example
> If 3D maps are enabled, the zoom level changes four times on this section of the road (14 +1.22, 14 +1.20, 14 + 1.21, 14 + 1.19).

The changes are minimal, so it's not an issue at all it stays the same .

We have an issue with the title and description:

> Zoom level is not working correctly while driving with 3D Terrain

Zoom should change and distance should change as it depends on speed. Higher speed closer camera, it's described in documentation same works for 2D mode as well. So I don't think I understand what the issue is about based on the video it could feel something is wrong but we need to describe what exactly wrong.

> If 3D maps are disabled, the zoom level remains constant 

That's not a correct statement as well

**Comment by Buzzz57** [comment]
Zirochkabila is not the OP. His examples are not representative of the issue I described.

Please have a look at my examples and the conditions to understand the issue.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 5.3.0#6629m, released: 2025-12-04
**Issue is not reproducible in the latest nightly app version** during navigation simulation.
Camera elevation remains constant; zoom adjusts slightly for elevation gain.

- tested multiple times both in portrait and landscape layouts
- with auto-zoom and primarily without auto-zoom
- starting point 47.80140, 6.83768, end point 47.82042, 6.83500

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/b1555bb9-803c-4c20-9a9c-7e3681ce6614"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/a174c14d-28c1-4035-8851-587830267b88"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/0807ab14-458a-4d13-bfd1-c3160a0b87a0"  width="300" height="auto"/> </td>
  </tr>
</table>

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/d8fd95d3-db9b-4975-add1-89c70f259af1"  width="400" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/7cc8e522-f041-4584-95b0-eda3e2a6aa30"  width="400" height="auto"/> </td>
  </tr>
</table>

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/98079fdb-a500-4722-81c8-a44fd11bfe42"  width="400" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/61d6393a-0f7c-4542-9703-900553df24e5"  width="400" height="auto"/> </td>
  </tr>
</table>

**Comment by Buzzz57** [comment]
Thanks. Can't wait to test it !

**Comment by Zirochkabila** [comment]
This issue will be closed for now.
As soon as we receive new information that allows us to reproduce it, we will reopen it or create a new issue.

**Comment by vshcherb** [comment]
The problem with mountain area and curvy area
- Calculated anotherLatLon  is not on the path and could have very different height so camera doesn't work correctly
- Another problem that in mountain areas camera should also change FOV to make it visible

Current algorithm:
<table>
<tr>
<th>Auto zoom range</th>
<th>Coefficient</th>
<th>Min distance to drive (m)</th>
</tr> 
<tr>
<td>Long-range</td>
<td>1</td>
<td>400</td>
</tr>
<tr>
<td>Mid-range</td>
<td>1.4</td>
<td>200</td>
</tr>
<tr>
<td>Close-up</td>
<td>2</td>
<td>50</td>
</tr>
</table>

- Zoom change speed: 0.1 zoom/second
- Min animation duration: 1.5 seconds (if animation will run < 1.5 second, it won't be started)
- Min speed to animate auto zoom: 7 km/h (if less, zoom doesn't change)
- Focus location (closest of two): located in pixel (1/2 of screen width, 1/3 of screen height) or next turn (displayable in widget)
- Distance to drive (max of two): distance from my location to focus location or min distance to drive (watch table)
- Time to drive: 45 sec / coefficient
- Auto zoom calculation: find such zoom, at which distance to drive will be passed in time to drive with current speed
------------------
Additional description of the same:
- Algorithm calculates anotherLatLon from myLocationLatLon and using showDistanceToDrive = max(minDistanceToDrive, min((45sec*speed / CF), distanceToNextTurn)) - by heading by rhumbdestination
- Then Algorithms puts anotherLatLon into a Focus location which is locate at (x,y) - (50%,66%)
- Once showDistanceToDrive catch the next turn point in focus it will start rotate towards it. For that it needs to happen that distanceToNextTurn >= 45 second * speed / CF or simply put turn should be within 22 seconds of current speed for close up or 45 seconds for long range

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/03691746-002d-499a-bbff-f53084de1c8e"  width="200" height="auto"/> </td>
  </tr>
</table>   

Video – [TurnDriving.mov.zip](https://github.com/user-attachments/files/24494128/TurnDriving.mov.zip)
Route – https://osmand.net/map?start=48.515522%2C24.382755&end=48.488678%2C24.346994&profile=car#13/48.510729/24.430088

**Comment by vshcherb** [comment]
Related - https://github.com/osmandapp/OsmAnd-Issues/issues/2323

**Comment by Zirochkabila** [comment]
- [x]  When navigating with 3D maps enabled, the angle of the map changes constantly (may cause dizziness).

<details><summary>Details</summary>

Steps to reproduce

Go to the `47.1362, 9.2997` > Enable 3D map > Start simulation

### Actual result

Angle of the map is constantly changing 

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th>Vertical exaggeration = 0</th>
    <th>AA</th>
    <th>Vertical exaggeration = 2</th>
    <th>iOS - Vertical exaggeration = 1.9 & 0</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/2bd9848d-8612-4c30-a726-1f22f83ccf1f"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/8933b8fe-6c1d-42ca-9756-a2291737da07"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/b19cc35c-3291-43ef-890d-e2b3ffe19da3"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/4811eb9d-bd5a-430e-8e8f-9df7fcde6390"  width="300" height="auto"/></td>
  </tr>
</table> 
</details> 



### Expected result

Angle of the map does not change

### Your Environment
OsmAnd Version: **OsmAnd~ 5.3.0#7146m, Released: 2026-02-11** / **OsmAnd Maps 5334, released 11.02.26**
Android/iOS version: 12 / 26.3

</details>

**Comment by Andrewschenko** [comment]
Tilt now on hold for 5 seconds each time camera touches a surface.

[Zooming are suspended as well](https://github.com/osmandapp/Osmand/commit/029f7009890328d548489ec695a04ba1cfbff614)

**Comment by Zirochkabila** [comment]
> OsmAnd Maps 5336, released 16.02.26
> OsmAnd~ 5.3.0#7175m, Released: 2026-02-16

The behavior has not changed, gaps have appeared in the route on Android (screenshot)



<details><summary>Details - Android</summary>
<table style="width:100%">
  <tr>
    <th>Vertical exaggeration = 0</th>
    <th>Gaps</th>
    <th>Vertical exaggeration = 2</th>
    <th>AA - Vertical exaggeration = 2</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/442175a0-c68e-4095-8581-ffd7d08cfce3"  width="300" height="auto"/></td>
<th><img src="https://github.com/user-attachments/assets/9283735c-33fa-4a77-82f9-7d2d5f495fd9"  width="300" height="auto"/> </th>
    <td><video source src="https://github.com/user-attachments/assets/9b513d9d-1c5f-4314-a321-b79457dfff32"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/e5b3dc8b-6e0b-4c15-828a-30f6a1521ce4"  width="300" height="auto"/></td>
  </tr>
</table> 
</details>







<details><summary>Details - iOS</summary>
<table style="width:100%">
  <tr>
    <th>Vertical exaggeration = 0</th>
    <th>Vertical exaggeration = 2</th>
    <th>CP - Vertical exaggeration = 2</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/dc60ca10-f93a-4dcd-87f3-a16c3fb56036"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/17d60ff6-da97-4bd0-b815-ff074407226d"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/1cccbb7c-c57f-40f2-a9f5-30198166d7e3"  width="300" height="auto"/></td>
  </tr>
</table> 
</details>

**Comment by Andrewschenko** [comment]
It looks like the iOS version needs the same corrections.

**Comment by Zirochkabila** [comment]
@Andrewschenko Issues are observed on both iOS and Android (as seen in the video).

**Comment by Andrewschenko** [comment]
> [@Andrewschenko](https://github.com/Andrewschenko) Issues are observed on both iOS and Android (as seen in the video).

The original issue was about an erratic behavior of tilting and zooming. It was fixed in OsmAnd for Android. Gaps on tracks is a completely different issue and task.

**Comment by Zirochkabila** [comment]
@Andrewschenko Unstable tilt behavior is still present (this can be seen in the video) - navigation is not comfortable to use (Android & iOS).

**Comment by dmpr0** [comment]
I have tested on iPhone and CarPlay, looks fine.

<table style="width:100%">
  <tr>
    <th colspan=2>CarPlay</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/4ec2df48-54ba-4af5-8c7c-74f8792e5d16"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/504429a1-3a2c-4e6b-b9a3-ee60ecdb8551"  width="300" height="auto"/> </td>
  </tr>
</table>   

<table style="width:100%">
  <tr>
    <th colspan 4>Android</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/e44785f4-dd1b-40d9-b221-dfbe4d606347"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/27f80230-47b8-468e-beca-5004ce835bef"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/3a4e617e-5b4f-49c0-a2c5-d936cf3ac64c"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/be97d5c6-acbf-4c0c-82c6-306f74d66036"  width="300" height="auto"/> </td>
  </tr>
</table>
