### ISSUE TITLE
Add translation of coffee_shop cuisine

### ISSUE THREAD

**Issue by literannn** [osmandapp/OsmAnd#23571]
### Description

There is no translation of coffee_shop cuisine in POI card:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/1b9e24e8-912e-4f65-b884-246f68777eb9"  width="300" height="auto"/> </th>
  </tr>
</table>

### Steps to reproduce

pick to poi (cafe e.g.) with cuisine=coffee_shop tag

### Actual result

Кухня: cuisine cafe

### Expected result

Кухня: кофейня

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 5.2.0#5939m
Android version: 15
Device model: realme 10 pro+
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
**The cuisine tag `coffee_shop` is not translated in the POI card and appears as “Cuisine: cuisine cafe” instead of a localized text (e.g. “Кухня: кофейня”).**

**Steps to reproduce:**

1. Open OsmAnd.
2. Pick a POI (for example, a café) that has the tag `cuisine=coffee_shop`.
   Example: [Stars Coffee on OsmAnd Web](https://test.osmand.net/map/poi/?name=Stars%20Coffee&type=cafe&lat=55.77336&lng=37.620358#20/55.77324/37.62048)
3. Open its context menu with details.

**Actual result:**

* The app displays: *Cuisine: cuisine cafe*.

**Expected result:**

* The app should display: *Cuisine: coffee shop* (localized as *Кухня: кофейня* in Russian).



<table style="width:100%">
  </tr>
  <tr>
    <th>Actual result</th>
    <th>Expected result (Example)</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/7fa7d0ae-2b5c-487d-ad42-70bd772eebe8"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/011f4456-830d-45ca-af3f-a4a6aa7b039d"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Fixed. New maps required. Russia_moskovskaya-oblast_asia will be regenerated in a couple of days.

**Comment by DmitryAlexei** [comment]
Stars Coffee 55.773091 37.620932 (tagged with cuisine=coffee_shop) https://www.openstreetmap.org/node/11880983269
In iOS still shown without a translation as Cuisine Cafe (both with moskovskaya_oblast or moskva maps).
Tested in the latest TestFlight and OsmAnd beta 4.2.6


<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/509c4511-a680-4bcb-90d0-9fa0119de261"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/5495cf86-778c-4de7-b3e6-083bfebdcbd7"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/e109e105-ce18-43ce-9002-37ca503c6221"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Map was not updated properly (it contains old data). Please wait for new maps.

**Comment by Zirochkabila** [comment]
# Testing 1

> Web - prod
> OsmAnd~ 5.3.0#6475m, Released: 2025-11-10
> 5279

Web and Android: Displayed correctly in search results and in the POI context menu — **Fixed.**

<details><summary>Details — Web, Android</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/072ef1f0-a049-41d0-9458-3ab54368b34d" width="300" height="auto"/> </th>
<th><img src="https://github.com/user-attachments/assets/2d3bccd2-bcd3-44d0-9143-fd32a31ae944" width="300" height="auto"/> </th>
<th><img src="https://github.com/user-attachments/assets/e7106ac4-c1e7-4ac0-977a-1b395cdebe04" width="300" height="auto"/> </th>
  </tr>
</table>  
</details>

## **Severity:** 🟠 Major

> **Priority:** 🟠 Normal / **Frequency:** Medium


* [ ] **iOS:** Information is missing in both the context menu and the search filter, and therefore absent from the results.

<details><summary>Details — iOS</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/621f9be0-060a-43b3-b126-27bdf4e6b2b3" width="300" height="auto"/> </th>
<th><img src="https://github.com/user-attachments/assets/67315b4f-b676-422f-b277-f16863a52273" width="300" height="auto"/> </th>
  </tr>
</table>  
</details>

**Comment by dmpr0** [comment]
## UI Review

- [ ] Remove `Cuisine` from `Cuisine coffee` Or convert it to `Dish: Coffee`

- - - - - -
 
<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
    <th>Web</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/ce74f1c3-6e61-4a7e-8511-d22d90f67872"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/fad95685-2a43-4291-8e51-4f9ff2ebeb52"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/542905fb-998c-405e-8c3b-44fee7265311"  width="300" height="auto"/> </td>
  </tr>
</table>  
 Object – https://www.openstreetmap.org/node/3191521443#map=19/44.931132/9.013921


- [ ] iOS Doesn't show Cuisine for  `Cuisine coffee` 
- [ ] Web shows it as Dish: Coffee shop
