### ISSUE TITLE
highway=passing_place not rendered

### ISSUE THREAD

**Issue by martinstingl** [osmandapp/OsmAnd#23629]
### Description

Using the Topo map style, highway=passing_place is not rendered.

### Steps to reproduce

Look at https://www.openstreetmap.org/node/3129745046 in Topo map style.

### Actual result

No rendering.

### Expected result

Render it similar to the working OsmAnd map style.

### Your Environment (required)

```
OsmAnd Version: 5.1.9
Android version: 15
```

**Comment by Zirochkabila** [comment]
> OsmAnd~ 5.2.0#6271m, Released: 2025-10-14
> 5.2.1.5250

1. iOS - no icon
2. Android - OSMid does not work (Probably related https://github.com/osmandapp/OsmAnd/issues/20153)
3. LightRS, Offroad, and Topo do not display the highway=passing_place object



<details><summary>Details 1</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/2b7526b2-89cb-4a6e-b24e-b0223d3572aa">
</details> 


<details><summary>Details 2</summary>
<video src="https://github.com/user-attachments/assets/1d159af5-de38-4336-b94d-fffe72dcde1c"></video>
</details> 

<details><summary>Details 3</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/674295a7-1a57-422d-b186-37d024fb342b"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/28d4d53f-a2fe-4a98-8ef3-dc48d98ae343"  width="500" height="auto"/> </th>
  </tr>
</table>  
</details>

**Comment by xmd5a2** [comment]
Fixed. Icon was added to Topo and derived styles (offroad). This icon shouldn't be in LightRS by design. No new maps required.

**Comment by Zirochkabila** [comment]
# Testing 1

> 5.3.0.5306

### Severity: 🟡 Minor

> Priority: 🟠 Normal / Frequency: High

* [ ] 1. iOS - missing icon in context menu (**still present**).

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/79dcf63b-26ec-436d-b46d-6192e47aa742" width="300"/></td>
    <td><img src="https://github.com/user-attachments/assets/e368b32f-d8e6-4375-aff3-7bf05b80dd99" width="300"/></td>
  </tr>
</table>
</details>

**Comment by dmpr0** [comment]
## UI Review

<img width="72" height="62" alt="Image" src="https://github.com/user-attachments/assets/134c8b01-2a11-43a8-9a23-60fdab9b1026" />

I propose to change icon to [icon](https://www.figma.com/design/N1wwtU2fkArkXxv02Phrht/Map-Icons---Transport?node-id=1-21&t=DYnrfxYexk4umgHA-1) with shield.

**Comment by xmd5a2** [comment]
Icon was updated

**Comment by Zirochkabila** [comment]
# Testing 2

> OsmAnd~ 5.3.0#6929m, Released: 2026-01-14
> OsmAnd Maps 5317, released 12.01.26

Icon was added

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/98c0cc1a-2c56-4e5e-b502-bed5da948e3d"  width="600" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/a18e4201-32ab-4831-abb2-21de836ee8d9"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details>

**Comment by dmpr0** [comment]
## UI Review

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d698d7ff-57c2-4b7c-87be-a5ad67bf1e6f"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/c8829a0e-c8a4-4152-be85-83edad379c88"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Icon on the map and in context menu should be similar

**Comment by xmd5a2** [comment]
Fixed

**Comment by Zirochkabila** [comment]
# Testing 3
 

> OsmAnd Maps 5336, released 16.02.26
> OsmAnd~ 5.3.0#7175m, Released: 2026-02-16

Icons on Android still differ


<details><summary>Details</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/e3eb5c36-673e-4646-88f2-e8ad10dbad1e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/77b6d643-82c5-4f9a-92a9-f7a45e27067e"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details>

**Comment by ivanPyrohivskyi** [comment]
Latest night-build Android:
<img width="372" height="828" alt="Image" src="https://github.com/user-attachments/assets/55c76f91-e356-424b-8736-9f3c8e87f57a" />
