### ISSUE TITLE
Paris and Madrid are not visible on 6-7 zoom levels

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#23887]
<table style="width:100%">
  <tr>
<th colspan="3">Madrid</th> 
</tr>
  <tr>
    <th>5</th>
    <th>6</th>
    <th>7</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/864a3e8b-d841-4440-8da6-e3e16c09e5b9"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/33d2db3f-f4bc-4003-ac0e-dcefefc56697"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/fa36808a-9088-4438-93f8-eb2fc291e614"  width="200" height="auto"/> </td>
  </tr>
</table> 
 

<table style="width:100%">
  <tr>
    <th colspan=3>Paris</th>
  </tr>
  <tr>
    <th>5</th>
    <th>6</th>
    <th>7</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/0859ccf8-8c61-47d8-aaf9-a955fc133970"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/587d7722-acc6-4743-89e3-43491e2abd91"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/bdff2275-f216-44e4-a063-9fd85e8461fd"  width="200" height="auto"/> </td>
  </tr>
</table> 

* Capital name and icon (red with black circle) starts to be visible from 7 zoom level.
* Fix
* Check all capitals

**Comment by Zirochkabila** [comment]
<details><summary>Details - iOS</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/e3477505-5bca-4244-83ed-226ab8e32beb"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/08607821-de62-449a-a522-7f0c89d7cd7e"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details>

**Comment by ihoryakovenko** [comment]
@Andrewschenko, Paris and Madrid are rejected by this filter
https://github.com/osmandapp/OsmAnd-core/blob/8c30c610aa81fbdf78d3c6a44ff498d1dbcf081b/src/Data/ObfMapSectionReader_P.cpp#L735

**Comment by Andrewschenko** [comment]
[Fixed](https://github.com/osmandapp/OsmAnd-core/commit/0054cd2b2023960da3b46a0236309391580ea8a7)

**Comment by Zirochkabila** [comment]
# Testing 1

> OsmAnd~ 5.3.0#6924m (Released: 2026-01-14)
> OsmAnd Maps 5318 (Released: 2026-01-14)


### **Severity**: 🟠 Major / **Priority**: 🟠 Normal 

- [x] 1. Madrid city label is not visible at zoom level 5 in Topo / LightRS / Offroad

<details><summary>Details - Android</summary>
<table style="width:100%">
  <tr>
    <th>Topo</th>
    <th>LightRS</th>
    <th>Offroad</th>
  </tr>
  <tr>
    <th><img src="https://github.com/user-attachments/assets/53e65008-110d-4a6a-84b8-02aaa905eaa6" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/89e59c70-636f-4b21-85a9-552f19e5c98c" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/584e1576-94ef-4d75-9a9c-ed9463058234" width="300" height="auto"/></th>
  </tr>
</table>
</details>

<details><summary>Details - iOS</summary>
<table style="width:100%">
  <tr>
    <th>Topo</th>
    <th>LightRS</th>
    <th>Offroad</th>
  </tr>
  <tr>
    <th><img src="https://github.com/user-attachments/assets/98b7e0a2-ae6a-4bc6-a222-a615ee622da9" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/2a495a99-16e4-4b67-9c06-2d8fbed9ed2a" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/cfec32b5-f05c-4b9d-a9ae-87b1b6713c44" width="300" height="auto"/></th>
  </tr>
</table>
</details>

**Comment by Andrewschenko** [comment]
It seems that the problem with visibility of Madrid city label is more related to the particular map styles now.

**Comment by xmd5a2** [comment]
Fixed. No new maps required.

**Comment by Zirochkabila** [comment]
# Testing 2

> OsmAnd~ 5.3.0#6973m, Released: 2026-01-19
> OsmAnd Maps 5321, released 19.01.26

Madrid city label is not visible at zoom level 5 in Topo / LightRS / Offroad - **Fixed**

<details><summary>Details - Android</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/c3466333-29b4-478d-83de-be00e50dc8d9"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/67f8f18d-b778-4aa9-9818-c90a43273949"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/5f2432f9-ec28-40df-8b7c-5bb918491f1a"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details> 

<details><summary>Details - iOS</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/3defe2d4-66f8-4243-be94-a2c6e8dfb3a7"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/4d8b5d04-703c-4a15-9786-d6882f8235e3"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/ee21dc7e-9411-4a07-b947-14849d722704"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details>

**Comment by dmpr0** [comment]
## UI Review

Issues with other capitals, can be fixed here or move to the new task? At least red (capital) icon should be visible.

* India?

### Taipei, Taiwan

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/ca0c2290-5b54-4850-86c9-6f8f194eea10"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/677580d7-a563-4972-ae12-94ff6ffd118f"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [x] Taipei doesn’t become visible until zoom level 8

### Dhaka, Bangladesh 

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/2acdd099-c257-4d08-963a-fd2a9d9f476f"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/05aa3b2b-4b8c-4d8b-beba-28d233aa9746"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [x] Dhaka doesn’t become visible until zoom level 6.


### Zagreb, Croatia

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/ffac14f5-7981-4672-9bb9-39c0f23d80b7"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/71380382-6e25-4f09-8da1-bd2c6eb7c093"  width="200" height="auto"/> </td>
  </tr>
</table>   


- [x] Zagreb doesn’t become visible until zoom level 6.

## Beijing, China

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/02e98d63-bb56-4727-a99a-60759853cfe9"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/4487c913-7226-4f0e-a316-7636abb65502"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [x] Beijing doesn’t become visible until zoom level 6.

**Comment by xmd5a2** [comment]
Fixed. Please retest.

**Comment by Zirochkabila** [comment]
# Testing 3

> OsmAnd Maps 5323 (Released: 2026-01-22)
> OsmAnd~ 5.3.0#7002m (Released: 2026-01-22)

### **Severity**: 🟠 Major / **Priority**: 🟠 Normal

* [ ] 1. Taipei, Dhaka, Zagreb (and many other European capitals), Beijing — still not displayed on Android (although red circles are present)

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th><img src="https://github.com/user-attachments/assets/e6850192-f28b-4e59-8a50-29431131e945" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/62a241b1-d6a7-413d-99b8-9edd5413f324" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/22c46dd5-e191-49ff-8da0-44f857edbaf6" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/289f1bc0-49b5-4e57-9dc7-116f48a0415a" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/74777b8a-5ef8-462b-b924-6b38ec801cb2" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/03b410b6-31a9-45bf-b450-a15f60b2fc8a" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/adbda79a-360b-4b06-926d-e3b0b79f42ff" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/872a6394-f814-4b88-b28b-1624139c6939" width="300" height="auto"/></th>
  </tr>
</table>
</details>

* [ ] 2. Washington — not displayed on iOS

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th><img src="https://github.com/user-attachments/assets/32972e04-fe70-45b8-a14b-98035466195b" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/ce8d2f6d-0c85-4e9a-9d1e-b4ab9efce9cb" width="300" height="auto"/></th>
  </tr>
</table>
</details>

**Comment by dmpr0** [comment]
# UI review

Unable to test due to rendering rules regarding zoom levels. 

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/19801a47-4880-4bbc-8376-576e0ce5555d"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/67080af4-2de5-41a2-a07c-54ecc6efc614"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
- [x] Globe: On high level zooms rendering style will depend on camera distance (different widget), so numbers in zoom widget could be adjusted or the same depends for developer needs
- [x] Flat: Propose to keep old semantics 4 means logical/rendering style Tile Zoom +0.26 means scaling factor

**Comment by Zirochkabila** [comment]
# Testing 4

> OsmAnd~ 5.3.0#7161m, released: 2026-02-13
> 5335

Tested at various zoom levels (Android + round earth) - the red dot and city name are displayed from the 5th zoom level


<details><summary>Details - iOS</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/754efcd6-5751-4bea-8da3-db78f1107b2f"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/0909b9db-7f9e-4c63-a013-1fe7eda58ea6"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details> 

<details><summary>Details - Android</summary>
<table style="width:100%">
  <tr>
    <th>Flat</th>
    <th>Flat</th>
    <th>Round</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/e552f402-80d6-4fa1-83ff-d4e889787373"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/b86aca88-73dc-4c15-afd7-dec9b4f06ba8"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/d063c01a-c6ea-4a44-8ab0-9d08c352b5bd"  width="300" height="auto"/> </th>
  </tr>
</table> 
</details>

**Comment by dmpr0** [comment]
## UI Review

<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/24af4dfd-bbae-40ef-b3b0-09647d576ad6"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/80a010ae-1fe4-49d2-ab5c-a1c3c44bf893"  width="300" height="auto"/> </td>
  </tr>
</table>   


- [ ] Riyadh, zoom level 5
