### ISSUE TITLE
Allow in Track - Waypoints list just Center map on the point

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#23931]
### Describe the idea

If a track on display containes waypoints, it is possible to see a list of them by tapping the track and then go to "points".
But it now is not possible to identify each WP without leaving this displayed list. Once you tap one WP, it gets centered and marked on the map, but the WP-list is closed/disappears (the only way to get back to the WP-list is "open track > points" again, but then you´re in a fresh list and back to it´s top - not knowing/finding where in the list you´ve been right before.

Androids "back" button does not help, it just closes the tracks details. Once a WP is tapped, there´s no way to get back to the previous list.

Suggestion: 
a possibility to follow the listed WP one by one, by tapping them in the list and pan the map to it (and keeping the prevoius zoom?) without closing the WP-list. That woud be a great help.

### Expected behaviour

.

### Alternatives you've considered

.

### Context

.

**Comment by yuriiurshuliak** [comment]
**QA Summary**

The user requests an improvement to handling **waypoints inside a track**.
Currently, opening **Track → Points** shows the waypoint list, but tapping any waypoint centers it on the map and **immediately closes the list**. The user must reopen **Track → Points**, and the list always resets to the **top**, making it hard to continue reviewing waypoints. The Android Back button does not return to the list.

**Requested behavior:**
Keep the waypoint list **open and in the same scroll position** while previewing waypoints on the map, allowing users to tap through waypoints one by one without losing their place.

**Comment by vshcherb** [comment]
We can add action to the right corner "Details" (Open Point menu) and just center the map on the waypoint on tap.

**Comment by dmpr0** [comment]
## ToDo
Add "Center on Map" pin action to waypoint list items.

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/a89c9a79-0cb3-4a20-81b6-05d75959c576"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Add a clickable pin icon to the right side of waypoint list items
- - [x] Use icon – `ic_action_marker_dark`
- - [x] Tapping the pin pans and centers the map on that waypoint, without changing map zoom level
- - [x] Pin button touch target should be – `48x48dp`
- - [x] TalkBack: Set the pin icon's `contentDescription` to `Show [Waypoint Name] on map`
- [x] Tapping the main body of the list item retains existing behavior (opens waypoint context menu)

**Comment by Rowin63** [comment]
Thanks for adding this great option, but unfortunately it centers the WP to the _screen_ center (where it is hidden by the menu) and not to the _visible map center_ (+5.3.2, S20+, 2400x1080) (also in the nightly on the Tablet) 

https://github.com/user-attachments/assets/efab11fb-4afe-4806-b4d3-a831b3a5a251

**Comment by Zirochkabila** [comment]
# Testing 1

> OsmAnd~ 5.4.0#7482m, Released: 2026-04-01

New features have been added and are now working 

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/bbbee74a-d998-40c0-8b8f-0758107adb3c"></video>
</details> 

The map alignment (map center) will be fixed here: https://github.com/osmandapp/OsmAnd/issues/24609

**Comment by dmpr0** [comment]
## UI Review

- [x] Icon color – `icon_color_default_light`
- [x] Add ripple effect on tap
- [x] Map center should be located in the visible Map area.

**Comment by Zirochkabila** [comment]
# Testing 2

> OsmAnd~ 5.4.0#7533m, released: 2026-04-08

**Severity**: 🟡 Minor / **Priority**: 🟠 Normal

* [x] 1. When moving to a point for the first time, the map jerks

* [x] 2. The map centers on the point, but the point is not highlighted, so there is no visual confirmation

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/83d73112-0d1d-4086-b580-022abefb9310"></video>
</details>

**Comment by vshcherb** [comment]
- [x] No shadow on click - not a button?
- [x] Center doesn't work correct on first click -  it jumps - center map?
- [x] After click on button - circle should temporarily be displayed (same as it displayed when you click zoom in)

**Comment by Rowin63** [comment]
After exiting the track/points menu, the screen remains centered to that previous top area, doesn´t switch back to screen center.


<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/13ba9859-0c3e-4b43-90ea-5842dd456c46"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
# Testing 3

> OsmAnd~ 5.4.0#7575m, released: 2026-04-14

**Severity**: Major / **Priority**: 🟠 Normal

* [ ] 1. When moving to a point for the first time, the map jerks — **Still present**

* [ ] 2. After exiting the track/points menu, the screen remains centered on the previous top area and does not return to the screen center

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/01c1c316-96d4-45da-8ccc-d71c0ae0caef"></video>
</details>

**Comment by isso-git** [comment]
Hello Osmand team, 
thank you very much for implementing this and for doing so in a way that preserves the previous behavior alongside the new feature.
If that feature didn't exist yet, I would suggest it

But for me the old behavior is broken in 5.3, it is no more possible to select the waypoint by tapping on the text of the waypoint in the list.
I check it on 5.3.7 and 5.3.8 where it do not work and also on Nightly 5.4.0#7480 (2026-04-01) where it worked.

Could you please retest and fix it if you get the same findings.

**Comment by dmpr0** [comment]
@isso-git 
Hi! Thanks for pointing this out. We completely missed this issue. It should be fixed in the latest nightly builds.

**Comment by isso-git** [comment]
Hello, thanks for taking a look and fixing this, for me it´s working now (nightly) - a real workflow booster.

**Comment by isso-git** [comment]
> But for me the old behavior is broken in 5.3, it is no more possible to select the waypoint by tapping on the text of the waypoint in the list.
> I check it on 5.3.7 and 5.3.8 where it do not work and also on Nightly 5.4.0#7480 (2026-04-01) where it worked.

> [@isso-git](https://github.com/isso-git)
> Hi! Thanks for pointing this out. We completely missed this issue. It should be fixed in the latest nightly builds.

> Hello, thanks for taking a look and fixing this, for me it´s working now (nightly) - a real workflow booster.

I still don't see this solution in the current version 5.4.0 (2026-07-23) - is it coming?
Thanks.

**Comment by dmpr0** [comment]
@isso-git Hi! It will be fixed for you with the next beta updates.

**Comment by isso-git** [comment]
@dmpr0 Hello
Great, thank you so much—that will be very helpful to me.
