### ISSUE TITLE
Broken coastline near Sharm El Sheikh at 14 zoom level

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#24064]
- [ ] https://github.com/osmandapp/OsmAnd/issues/24091
### How to reproduce
* Open map at `27.91616, 34.36666`
* Try 14 and 15 zoom levels

### Actual result

<table style="width:100%">
  <tr>
    <th>14</th>
    <th>15</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/c100df10-28d0-41e3-99e9-7f660c2a9b66"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/a368b57b-55da-4021-9c7d-e2cb793c1da9"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Broken coats line?

### Expected result

* Similar coast line at 14 and 15 zoom leve

**Environment**
OsmAnd Version: 5.3.0
Android: 16
Device model: Google Pixel 6A

**Comment by xmd5a2** [comment]
Fixed. Egypt will be regenerated in a couple of days.

**Comment by Zirochkabila** [comment]
# Testing 1

> OsmAnd Maps 5313, released 25.12.25
> OsmAnd~ 5.3.0#6771m, Released: 2025-12-25

- [ ] 1. Broken coast line - **Still present** (V1 - Coast line looks fixed)

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th>Android V2</th>
    <th>iOS</th>
    <th>Android V1</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/4bfdc0a9-2a7b-4828-9dd6-8cab2c740f88"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/1b6e97b6-68e4-4eb9-84a5-70530e434341"  width="300" height="auto"/> </td>
    <td><video source src="https://github.com/user-attachments/assets/af37d965-06cc-44fa-8d59-3055716187b5"  width="300" height="auto"/> </td>
  </tr>
</table>  
</details>

**Comment by xmd5a2** [comment]
Looks like issue is not related to broken coastline in data

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/way/971275427#map=19/27.912502/34.329098 small coastline?

**Comment by Zirochkabila** [comment]
@xmd5a2 @ivanPyrohivskyi Is it necessary to regenerate new maps for testing? - If so, please regenerate and specify which map has been regenerated.

**Comment by xmd5a2** [comment]
@Zirochkabila I don't know. I wasn't the one who fixed the bug.

**Comment by Zirochkabila** [comment]
# Testing 2

> OsmAnd Maps 5322, released 20.01.26
> OsmAnd~ 5.3.0#6990m, Released: 2026-01-21

**Fixed**

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/55d28e4e-c88d-40f3-b43c-0f19ea330c13"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/541f4169-f6e7-4826-9d7d-795e8f7310b3"  width="300" height="auto"/> </td>
  </tr>
</table> 

</details>
