### ISSUE TITLE
Avoid Roads not working on 2.3.3 and latest nightlies

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#2419]
On Samsung Galaxy Camera 2, Android 4.3

Both with PlayStore version 2.3.3 and latest nightlies.
Using OsmAnd offline routing.

Avoid Roads is not working.

Not in the old manner: Route Preparation Menu, Settings, Avoid Roads-Select, Tap point on route.
The point is not added to list of roads to avoid.

Not in the new manner:  Long tap on point on the route; Three Dots from ContextMenu - Avoid Road

The route is calculated again, but the blocked roads still used.

Shortly after the Avoid Road was added to ContextMenu all was working fine.
The new way to set a Blocked Road was a real improvement, with icons on the map showing all blocked locations.

Thanks and good luck.
Kees-Jan

**Comment by vshcherb** [comment]
Fixed, this week will be another release of 2.3

**Comment by CJTmmr** [comment]
Sorry, but with nightly from last night (2.4.0#12463D from 2016-04-04 23.25) 
"Avoid Roads" is still not working.

**Comment by crimean** [comment]
@CJTmmr can you see avoid road icon on map when adding? 
Please make screenshot of the issue.

**Comment by CJTmmr** [comment]
The AvoidRoadIcon does not appear.

There actually is nothing to make a screenshot of..

Procedure:
With a route calculated:
Tap on the map 
Tap on blue arrow
Tap on Settings/Gear-symbool
Tap on Select-button (next to Avoid Roads..)
On PopUp screen with Avoid roads: tap om SELECT ON MAP
Tap on a the map somewhere on the calculated route.
The PopUp-screen reappears - but without location to avoid...
Route is actually recalculated, but exactly the same as before
No Avoid-Road-Icon visible..

Other procedure:
With a route calculated:
Long tap on a point on the route:
ContextMenu shows up: Tap on ThreeDots;
Tap on Avoid Road
Route is recalculated, but using the tapped location, exactly the same as before
No Avoid-Road-Ion showing.

BTW: This last procedure was a real improvement

**Comment by vshcherb** [comment]
May be some screenshots and locations, so we could try to reproduce

**Comment by CJTmmr** [comment]
With nightly from this morning 08.22u OsmAndF~2.4.0#12574D; (with orange! turns- better visible! )
On Samsung Galaxy Camera 2, Android 4.3

With Mobizen-app  (4 overlay-buttons at the right) I could make a screen capture while driving [this route](http://www.openstreetmap.org/directions?engine=osrm_car&route=52.0515%2C4.7255%3B52.0920%2C4.7379#map=14/52.0707/4.7475)

[This is the .mp4 video](https://www.dropbox.com/s/aomavmxalxfabfl/mobizen_20160414_152645.mp4?dl=0)

Right at the begin I do a long tap somewhere on the route, tap "three dots", tap "Deze weg vermijden=Avoid road"; Route is recalculated, but still using location.

At 2:10 I tap the map; tap blue arrow; tap settings, tap "Blokkeer=Avoid road"; tap "SELECTEER OP DE KAART"  move map some distance; (notice slow rendering..maybe because Mobizen is capturing); short tap a location, but first not on the route; another time tap "SELECTEER OP DE KAART" and a tap on the route;
Route is recalculated, but still using location.
The tapped locations do not appear on the "Avoid"-card, as they did some weeks ago, making a list of "avoid roads"; no "avoid road"-icons..

Thanks
Kees-Jan

**Comment by crimean** [comment]
@CJTmmr Tried today with Samsung Galaxy S3 (android 4.4.4). Cannot reproduce. 
Please check if you have latest map installed (update if needed)

**Comment by CJTmmr** [comment]
I have latest available maps from Netherlands.
Also tried with Live Updates disabled.
I have both PlayStore-OsmAnd+2.3.3  and nightly OsmandF~2.4.0 installed, and a self-compiled Osmand+2.3.0(debug)
Maybe they share a location where Avoid Road are stored?
I will try to remove all, and make fresh install. (Annoying: my favorite settings have to be set again..)
I will test Avoid Roads before installing the other versions.

Thanks for testing and reply

**Comment by CJTmmr** [comment]
@crimean 
I removed all the OsmAnd-apps.
I freshly installed latest nightly.
On first start OsmAnd asks for storage location, 
I selected Intern Memory.
Data is stored in some hidden map:  /data/data/net.osmand.dev/files/osmand/osmand
When I selected Extern Memory: same location was used..

Even with 7zipper I can not locate this map...
Downloaded map for my region (only 1 map, Intern Memory is not so big...)
Now "Avoid Road" works OK.

Then I changed storage location to 32MB-SD-card: /storage/extSdCard/osmand
This is the original location, where I have all the maps and data and lot of space.
OsmAnd asks to move files to new location, is okay.

Now "Avoid Road" does not work anymore...
Even got some FC; in ImpassableRoadLayer. see [exception.log](https://www.dropbox.com/s/6157vb15d6io4w1/exception.log?dl=0)

Note: on Android 4.3; so no problems with acces-permissions..
Note: the most other apps use an other location for  storage, like:  /storage/emulated/0/Android/data/org.appname.app
(/storage/emulated/0 is Intern Memory)

Ideas?

**Comment by vshcherb** [comment]
From the video I see there is no avoid roads icon created, I think in the dialog you need to press "Selecteer op map" and select point on the map. The avoid road flag should be created and visible on the map, otherwise it is not taken into account. It is easier to check while you are not driving may be, just calculate the route and try to select point on the map

**Comment by CJTmmr** [comment]
With latest nightly "Avoid Road" is working again, after a complete fresh install.
With storage on SD-card...
But when I moved the OsmAnd-app to SD-card (with Android App-manager) I got several crashes, playing with routing and avoiding roads.
Three in this [exception.log](https://www.dropbox.com/s/6157vb15d6io4w1/exception.log?dl=0)
Maybe connected to reverse geo-lookup, which is still running when I selected road to avoid?
