### ISSUE TITLE
OSM Live: "error: SendToken error: user id is not found"

### ISSUE THREAD

**Issue by moy** [osmandapp/Osmand#2497]
> What version of OsmAnd are you using, on what device and Android/iOS version?

OSMAnd+ 2.3.3 on Android 6.0.1 (on a Nexus 5 in case it helps)

> Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

I'm currently using offline maps, but I'm trying OSM Live.

**The issue:** I just paid for an OSM Live subscription (I can see the transaction on my bank account so I did finish the payment), but the live update doesn't seem to work.

When I choose "OSM Live" in the menu, I get to the OSM Live screen, but an error is displayed: "error: SendToken error: user id is not found" (see attached screenshot). Even though I have the automatic update switch on, I do not seem to get any update (I did some edits last week, they are visible online, but didn't reach my phone).

I can click the "status" field and get to the parameters of the subscription, but clicking "enregistrer les modifications" (save modifications in english I guess), I get the message "Error: error".

Rebooting the phone doesn't make the problem go away.

Thanks in advance,

![screenshot_20160426-194802](https://cloud.githubusercontent.com/assets/14709/14828703/6a361730-0be8-11e6-9741-9a5e326952b0.png)

**Comment by vshcherb** [comment]
Can you provide please with stars or private message or a hint, what was the user name and email you used.

**Comment by moy** [comment]
My email addresses are matthieu.moy _@provider.tld_. I tried initially with my normal email address which isn't associated to my google account (@imag.fr), and tried with my gmail email (which is the one associated to the paiment I made, i.e. I see the subscription on https://play.google.com/store/account), and I get the same error for both.

**Comment by vshcherb** [comment]
Investigating...

**Comment by crimean** [comment]
@moy Please try to restart the app and enter OSM Live screen again.

**Comment by moy** [comment]
Thanks for investigating.

I just tried to restart OSMAnd+, and even tried to reboot my phone to be sure, and I still get the same error unfortunately.

**Comment by moy** [comment]
Playing with the app, I just got a different error message: when clicking "status: actif" to enter the configuration screen, I got a brief message talking about I/O error (I didn't have time to read it, and can't reproduce unfortunately). I still have plenty of space in my internal storage so I don't think this can be a "no space left on device".

**Comment by crimean** [comment]
@moy Thanks for the details. We will try to fix it ASAP.

**Comment by crimean** [comment]
@moy Could you please restart the app and enter OSM Live screen one more time?

**Comment by crimean** [comment]
@moy The issue should be fixed now. Please try again.

**Comment by moy** [comment]
C'mon, you're too quick. The time I wrote a message "still broken", you actually fixed it!

At least I don't get the error. I'll reopen if the actual update doesn't work.

Thanks a lot!
