### ISSUE TITLE
Program crash after start

### ISSUE THREAD

**Issue by tincturaginseng** [osmandapp/Osmand#2535]
Version: OsmAnd+ 2.3.5
APK version: 2.3.5 238

Device: Xiaomi Redmi 1S WCDMA
Firmware: miuipro 6.4.28
Adnroid: 4.4.4

Language: Russian (System default)

OsmAnd+ crash after 10-20 seconds after the start. First and subsequent launches also lead to a crash. If I have time to get to the menu item "Manage map files", it is possible to download maps. But when I exit to the main window of the program an error occurs and the program closes.
If I set "Safe mode" an error occurs "Native library is not supported on this device"
Maps: offline maps offered within the OsmAnd app for download, world overview map only.
Video with start and crash attached

[exception.txt](https://github.com/osmandapp/Osmand/files/258688/exception.txt)
[logcat.txt](https://github.com/osmandapp/Osmand/files/258689/logcat.txt)
[VID_20160511_094846.zip](https://github.com/osmandapp/Osmand/files/258706/VID_20160511_094846.zip)

**Comment by vshcherb** [comment]
If the exception you copied related to the startup (Version  OsmAnd+ 2.3.5
11.05.2016 11:08:08), then it is already fixed in the nightlies, please try it.

**Comment by tincturaginseng** [comment]
OsmAnd+ 2.4.0#16689M
Program still crashed. No exception.log found (how to make them?). Logcat is attached.
[log_1.txt](https://github.com/osmandapp/Osmand/files/260681/log_1.txt)

**Comment by vshcherb** [comment]
Did you try to reinstall the app by completely uninstall and install again. In the latest log I couldn't find anything reasonable except some messages about GC (possible run out of memory)

**Comment by tincturaginseng** [comment]
OsmAnd+ 2.4.0#16689M
Fresh install. Before install I clean cache and Dalvik cache in recovery.
Program still crashed.
[log-1.txt](https://github.com/osmandapp/Osmand/files/265779/log-1.txt)

**Comment by vshcherb** [comment]
Sorry coming back to you later but we are very puzzled what's the reason and have no clue.  I would recommend you to try earlier release http://download.osmand.net/releases/net.osmand-2.2.apk or 2.1 it had different target SDK version and it was packaged differently.
