### ISSUE TITLE
Zoom buttons get out of place (in landscape mode)

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2638]
Start Osmand night build, rotate the phone to landscape mode, and look at the lower right corner zoom buttons.

The (+) disappears or sometimes jumps to the left side, while the (-) looks squashed.

If we zoom in/out using 2 fingers, they reappear as normal, and then get out of shape again.

**Comment by vshcherb** [comment]
Fixed

**Comment by polarbearing** [comment]
Running the nightly from 2016-06-16, # 17145, or 2016-06-18 # 17146, while navigating, I still have the problem of the (+) button jumping to the left side, and covering the warning signs. 
In map mode it is correctly on the right, above the (-), and the (+) already goes to the left when navigating is activated, even when there is still more space under the widgets on the right than in the screenshot. 
![screenshot_2016-06-17-21-43-15](https://cloud.githubusercontent.com/assets/8266355/16176300/4a997f64-360b-11e6-8401-ee33cab3f16f.png)

**Comment by Barrocas** [comment]
I have the same exact results as polarbearing reports.

>

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by polarbearing** [comment]
Confirming fix. Thanks.
