### ISSUE TITLE
Remove junk tags

### ISSUE THREAD

**Issue by verdulo** [osmandapp/Osmand#2851]
Please remove all junk and nonsense tags (keys, POIs) from the program, by junk tags I mean: those undocumented on wiki.openstreetmap.org and depreciated.

Here is the list:
poi_dive (changed to shop:scuba_diving)
poi_organic (depreciated, use organic tag in combination with shop:)
poi_bailiff (non-existent)
poi_diving (changed to sport:scuba_diving)
poi_skating (removed, ambiguous)
poi_wine_cellar (https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dwine_cellar)
poi_payment_terminal - ??? - same as amenity:atm cash_in:yes
poi_general_barrier - ???
poi_deadlock
poi_piste_grooming_no - seems to be the same as poi_piste_grooming_backcountry
poi_stars_6/7 - marketing bullshit
poi_payment_account_cards_yes/no - what is an "account card"
poi_payment_efectivo_yes/no - "efectivo" seems to be Spanish word for "cash"
poi_toilets_access_community - what is it?
the list is not complete...

poi_korfbal is existing tag, but it should be poi_korfbal**l** (with 2 l)

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/11f1f8a96f0ef7d7712d3af4433168b2f0b826bc

**Comment by verdulo** [comment]
poi_memorial_jizo - completely undocumented tag
poi_memorial_koshinto - only once mentioned on Japanese wikia
poi_memorial_prasat - ???

**Comment by xmd5a2** [comment]
Fixed (partial) by https://github.com/osmandapp/OsmAnd-resources/commit/7f7d7ab7f874ea5aad557d067c3fa13564c86ebb

**Comment by verdulo** [comment]
It would be nice to remove these tags also from weblate...

"Korfbal" is still not fixed - it should be with 2 ll - (https://en.wikipedia.org/wiki/Korfball)

On the main page of OsmAnd on Github, and in a few strings describing OsmAnd, there's a phrase: "Approximate map coverage and quality". That phrase is missing "Oceania" continent/region. Maybe consider removing "+" from Antarctica, because using cylindrical projection maps around polar regions is impossible...

**Comment by verdulo** [comment]
It would be nice to remove these tags also from weblate...

"Korfbal" is still not fixed - it should be with 2 ll - (https://en.wikipedia.org/wiki/Korfball)

On the main page of OsmAnd on Github, and in a few strings describing OsmAnd, there's a phrase: "Approximate map coverage and quality". That phrase is missing "Oceania" continent/region. Maybe consider removing "+" from Antarctica, because using cylindrical projection maps around polar regions is impossible...

**Comment by verdulo** [comment]
poi_inscription_n and similar - it doesn't make any sense, is it intended to be used on signpost?
poi_nuclear_explosion - this tag itself exists, but all "country, site, type..." are unofficial and make sense, excepting "poi_nuclear_explosion_shot_name_en" - remove "en"; they also shouldn't be visible in POI list

**Comment by franco999** [comment]
@xmd5a2 Some of these strings, still exist in Weblate and should be removed or fixed.

**Comment by aceman444** [comment]
Thanks for clearing the junk tags verdulo. The weblate takes the strings from https://github.com/osmandapp/Osmand/blob/master/OsmAnd/res/values/phrases.xml . Please see if anything is superfluous there and I can remove it. Just make sure the tag/id no longer appears in https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml .

**Comment by ludodv** [comment]
@xmd5a2 Korfball is still untranslated due to the single "L" in phrases.xml?

**Comment by Zirochkabila** [comment]
# Testing 1

> Web - prod
> OsmAnd Maps 5350, released 19.03.26
> OsmAnd~ 5.3.0#7382m, Released: 2026-03-19

Tested correction of the spelling of “Korfball” proper removal of obsolete categories (organic), and proper remapping of tags `scuba_diving` for diving in all interface elements - **Fixed**

<details><summary>Details - Korfball</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/32bf6f0e-8220-4edc-bb5b-cee1c34d6db2"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/44fabc98-68e6-4703-ae63-bc7de04a6d4a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/99ba37d1-0389-4258-bcf0-4276960c1404"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/80f5448b-9641-405c-a401-8f755b723ffa"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/2511dfb5-750a-4545-be60-9572386d61f9"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/a5a9b1e6-5cf1-4520-a06f-193fb0eda718"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/8ac0190d-c664-41a7-a674-ea67e24c2c79"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details>

<details><summary>Details - Categories (organic)</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/500958ea-62cf-464e-9c1a-135d5bbaf3d5"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/b2844ede-c5fc-41e7-b2d7-8424e3959e9a"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details> 


<details><summary>Details - scuba_diving</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/5cd191e2-4aba-44ea-930b-a98f09f73856"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/4ae0c5dd-5c00-4c4d-8fca-3d7cd73e8ea5"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details>
