### ISSUE TITLE
Detour at end of route with only changing the startpoint

### ISSUE THREAD

**Issue by quelbs** [osmandapp/Osmand#2871]
When I use offline routing with profile "bike" from "Start correct" to "Destination" it shows me the expected route using the bicycle way along the street. But if I start from "Start incorrect", just some meters away on the same bicycleway the end of the route is completely different and takes a quite large detour.

Osmand 2.4.0#17685M

48.169724,11.528346,Start correct
48.169983,11.528283,Start incorrect
48.159176,11.547478,Destination

![screenshot_2016-07-27-09-29-33_correct](https://cloud.githubusercontent.com/assets/570222/17167971/21f31384-53e0-11e6-8b05-a9ebb6faff80.png)
![screenshot_2016-07-27-09-30-01_incorrect](https://cloud.githubusercontent.com/assets/570222/17167972/21f7db80-53e0-11e6-8436-0ee2fedbd049.png)

**Comment by vshcherb** [comment]
I could not reproduce issue, I think it was fixed with other many fixes

**Comment by quelbs** [comment]
I can still reproduce it with 2.4.0#18053M from today using Bike routing on two different devices.

**Comment by vshcherb** [comment]
Today fixes where done around 7 hours ago. Please try again. From my side I might be missing some definite locations.  Please let me know if it still there

**Comment by quelbs** [comment]
Still the same with build 18056M from today
**Destination**:
Position: geo:48.15894,11.547768?z=14
http://osmand.net/go?lat=48.15894&lon=11.547768&z=14

**Start**:
Position: geo:48.171448,11.528116?z=14
http://osmand.net/go?lat=48.171448&lon=11.528116&z=14

**Comment by vshcherb** [comment]
Short resume the original issue that detour depends  on  changing the startpoint is fixed. Now "detour" is consistent and it is actually faster route according to the routing engine (routing_time = "453.021").
If we remove penalties for traffic_signals =0, then detour is not there and routing_time = "325.93304" . 
With penalties for traffic_signals =20 seconds, there is no detour and routing_time = "425.93304".

Of course we could reduce a penalty for traffic signals, but there is another issue here, we should group traffic_signals and don't count them twice for same intersection.

**Comment by vshcherb** [comment]
If I count correctly with detour has 4 traffic_signals and without has 5 (each traffic signal +30 seconds)

**Comment by vshcherb** [comment]
The issue is fixed, there was a glitch in the routing.xml (penalty should be 10 seconds, not 30 seconds)

**Comment by quelbs** [comment]
Thank you for fixing this!
