### ISSUE TITLE
UK Map problems 

### ISSUE THREAD

**Issue by vrtareg** [osmandapp/Osmand#2931]
Hi

Looks like that something happened with UK main map.

Roads only renders ok but not full one.

Regards, 
Areg

**Comment by vrtareg** [comment]
![screenshot_2016-08-11-07-49-02](https://cloud.githubusercontent.com/assets/2562730/17580702/879e964a-5f98-11e6-845d-366d5ea439ba.png)
![screenshot_2016-08-11-07-48-33](https://cloud.githubusercontent.com/assets/2562730/17580708/8d989294-5f98-11e6-958f-0addbe9e3bf1.png)

**Comment by xmd5a2** [comment]
Which version of OsmAnd are you using and what is map date?

**Comment by xmd5a2** [comment]
Confirmed

**Comment by vrtareg** [comment]
Latest nightly

**Comment by xmd5a2** [comment]
Fixed

**Comment by vrtareg** [comment]
Hi

Is this available? 
I have downloaded latest one 8:15pm Aug 11 one and it still doesn't work. 

Regards, 
Areg

**Comment by xmd5a2** [comment]
Yes, it is available

**Comment by vrtareg** [comment]
Hi

It is not workin

g yet.

Regards,
Areg

**Comment by vrtareg** [comment]
Sorry but still no luck....

![screenshot_2016-08-13-07-11-03](https://cloud.githubusercontent.com/assets/2562730/17641797/1e906252-6126-11e6-8eb1-308e7e53e562.png)

![screenshot_2016-08-13-07-10-59](https://cloud.githubusercontent.com/assets/2562730/17641800/365d1ea2-6126-11e6-9696-7ed7f302277b.png)

![screenshot_2016-08-13-07-10-43](https://cloud.githubusercontent.com/assets/2562730/17641801/4325f4b0-6126-11e6-81fe-49e1a9f7594b.png)

**Comment by vrtareg** [comment]
Hi @xmd5a2 , @vshcherb 

Could you please recheck this and reopen if there is problem still?

Is this fix in APP or MAP?

Regards,
Areg

**Comment by xmd5a2** [comment]
We have tested map of England today one more time - it is working correctly and Cambridge (basically all East of England) is rendered without any problem
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2016-08-15-17-17-31.png
No need to update app.

**Comment by vrtareg** [comment]
Not working on mine. 
Latest nightly build.

![screenshot_2016-08-15-16-46-54](https://cloud.githubusercontent.com/assets/2562730/17670049/10a2536a-6308-11e6-8562-a45d5c020e7e.png)

**Comment by vshcherb** [comment]
Is it road only map? I also checked full map (redownloaded) and it works fine.

**Comment by vshcherb** [comment]
Could you please again delete the map file and download it, something is definitely wrong here

**Comment by vrtareg** [comment]
Hi

Roads only works fine.
I will redownload full one once more tomorrow.

Regards,
Areg

**Comment by vrtareg** [comment]
Case closed. 

Not sure why but I have downloaded UK full map multiple times and it was same size of 1192.2 non working one.
Today one is bigger but again dated Aug 1st. 

It is working now. 

Regards, 
Areg
