### ISSUE TITLE
shop=spices cannot be searched by name

### ISSUE THREAD

**Issue by nereocystis** [osmandapp/Osmand#3059]
First perform an address search for in 
United States of America California
Oakland
Grand Avenue
546
which is the location of Oakland Spice Shop, which shows up on the map.

From this location I perform a POI search by name for "Oaktown", and find nothing.

I can also perform a Nearest POIs search, and Oaktown Spice Shop does not show up.

Here is node info for Oaktown Spice Shop. This is a shop=spices location

http://www.openstreetmap.org/node/3853114282

What version of OsmAnd are you using, on what device and Android/iOS version?

OsmAnd~ 2.4.0#16902M
Cyanogenmod 13.0-20160904-NIGHTLY-jfltespr

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
offline maps

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

map United States of America California
August 31, 2016
The problem has been around for a long time.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/2c9c6d59835353525b92f74c08e032c70fbb2a3d

**Comment by nereocystis** [comment]
Thanks.

I  think that there is a bigger issue. A shop of unknown type should still show up in a search. There are many non-standard shops. Spices is a new official option, but sometimes I notice other missing places.
