### ISSUE TITLE
Fix layers: "Configure map > Transport > tram/train/underground routes"

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#3167]
I tried using "Configure map > Transport > tram/train/underground routes", and it's quite difficult in built-up areas (in large cities) as the routes are overshadowed by roads. I guess the roads are at layer=0, while routes are at layer=-1 (or lower), and so "underground routes" aren't always visible. In the end, I reverted to a paper map :)

If the above issue is to do with layers, then enabling "tram/train/underground routes" should ensure that irrespective of the "layer" value, tram/train/underground routes are rendered ontop of roads. Perhaps they should also be rendered thicker, to stand out.

**Comment by xmd5a2** [comment]
Screenshot please. Can't reproduce.

**Comment by bjohas** [comment]
Here are some pictures from Central Park, NY, with "Transport > ...routes" turned on. You can see that the subway runs underneath the roads (correct according to level settings, but not helpful). Only at the highest zoom level, the underground line is visible:

![ny1](https://cloud.githubusercontent.com/assets/7574634/19315424/9d56dc5a-906b-11e6-8d66-020981676f06.png)
![ny2](https://cloud.githubusercontent.com/assets/7574634/19315426/9d5e7ce4-906b-11e6-8ebc-d8fae6b5c5ac.png)
![ny3](https://cloud.githubusercontent.com/assets/7574634/19315425/9d5b61bc-906b-11e6-9057-073a6dae8d15.png)

**Comment by bjohas** [comment]
Here's another screenshot, with "Hide Overground Objects" turned on. "Hide Overground Objects" only works at high zoom, at of course it's pot luck whether the underground is picked out. However, when it works, it works well. 

![ny4](https://cloud.githubusercontent.com/assets/7574634/19315590/45f27e64-906c-11e6-865d-eaa16795dfa4.png)

Unfortunately (as you can also see in the above pictures) the labels disappear at high zoom - so you can only see the line, or the labels, which makes it hard to use.

(Nightly, 4713.)

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/a7a25729af02cf4d087f33be285f354be9b8d5e4

**Comment by bjohas** [comment]
Great, thanks. Will try it out!

**Comment by bjohas** [comment]
Works nicely - lines are on top of other features!

However, there is an issue remaining with labels - before, labels disappeared at high zoom, which has now been fixed. 

However, as you can see in the picture, there are some labels that are not visible at low zoom. Previously all labels were available at low zoom.

![screenshot_2016-10-23-11-55-08](https://cloud.githubusercontent.com/assets/7574634/19625699/ccd291e0-9917-11e6-8883-55bb3c58803b.png)
