### ISSUE TITLE
crash caused by traffic calming hump

### ISSUE THREAD

**Issue by verdulo** [osmandapp/Osmand#3215]
Both on version 2.4.7 and on the developer versions, when I click on the POI "traffic_calming_hump" (the phrase is not translateable) the app crashes.

**Comment by xmd5a2** [comment]
Fixed

**Comment by verdulo** [comment]
The bug is still not fixed (release from today) - the phrase is in English, and the program crashes:

Version  OsmAndF~ 2.5.0#15138D
01.11.2016 7:38:42
Apk Version : 2.5.0#15138D 240
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException
	at net.osmand.plus.osmedit.OsmEditingPlugin.registerMapContextMenuActions(OsmEditingPlugin.java:204)
	at net.osmand.plus.OsmandPlugin.registerMapContextMenu(OsmandPlugin.java:397)
	at net.osmand.plus.activities.MapActivityActions.contextMenuPoint(MapActivityActions.java:284)
	at net.osmand.plus.mapcontextmenu.MapContextMenu.buttonMorePressed(MapContextMenu.java:713)
	at net.osmand.plus.mapcontextmenu.MapContextMenuFragment$13.onClick(MapContextMenuFragment.java:469)
	at android.view.View.performClick(View.java:3528)
	at android.view.View$PerformClick.run(View.java:14235)
	at android.os.Handler.handleCallback(Handler.java:605)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4424)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
	at dalvik.system.NativeStart.main(Native Method)
