### ISSUE TITLE
Elevation graph regressions

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3514]
The recent refactoring of the elevation graph introduced the following bugs:

![untitled](https://cloud.githubusercontent.com/assets/845735/22995965/47708ba4-f3cd-11e6-8c23-84bd1d43f919.png)

(1) All axis labels do not any more respect the app theme's color pattern
(2) The meaning and significance of the orange step background pattern is unclear
(3) The prominent orange background suppresses the visibility of the actual "feature", i.e. the elevation curve (only visible as faint and thin dark line)
(4) The x axis is always labeled in kilometers, regardless of the distance unit selected in the app
(5) When returning from a prior view with split interval (and having selecting a point on the x-axis there by tapping the graph) to one without split interval, the scaling of the x-axis remains that of the split interval (should return to the overall scale)

Here for comparison the same graph in the previous version:

![untitled1](https://cloud.githubusercontent.com/assets/845735/22996319/b2b4ac8c-f3ce-11e6-98c2-24c559ff48b3.png)

**Comment by vshcherb** [comment]
(5) split interval will be changed and look differently
The graph looks buggy and the comment about km/miles setting is valid.

**Comment by crimean** [comment]
@sonora Thanks for report! Could you please send this gpx to me?

**Comment by utack** [comment]
Sorry to ask here:
Will the graph in the final 2.6 release support zooming, or is it not planned?

**Comment by sonora** [comment]
Hello Alexey,
sure, it's in your mail.
Best,
Hardy

**Comment by vshcherb** [comment]
Can you please also forward to me, Alexey looks like didn't get it.

**Comment by sonora** [comment]
Another comment regarding the new "MyTracks" overview screen: Can we please make sure we sort all track folders again alphabetically? I have a large number of sub-folders (under osmand-data-folder/tracks), and it looks like somehow these are now not sorted quite right any more, see screenshots with marked oddities.   Thx - Hardy

<img width="108" alt="1" src="https://cloud.githubusercontent.com/assets/845735/23228924/ba127e9e-f93e-11e6-9181-7b9dbcf2b98f.png">   <img width="108" alt="2" src="https://cloud.githubusercontent.com/assets/845735/23228929/bedce8d8-f93e-11e6-978c-8ffc5fa847cb.png">

**Comment by vshcherb** [comment]
Yes, that's a regression bug.

**Comment by crimean** [comment]
@sonora should be fixed now. Please check and close the issue if all is fine.

**Comment by sonora** [comment]
Victor, Alexey, Don't know, it looks really weird .... am I trying the correct build??

- Issues (2) and (3) from the first post above are still present, only now the orange steps have turned into different shades of blue. What is the meaning??

<img width="135" alt="screenshot_2017-02-23-16-33-10_" src="https://cloud.githubusercontent.com/assets/845735/23266180/4c6ca960-f9e7-11e6-9835-756f6f550974.png">

- The folder sorting is still incorrect: Now "Tracks" is way on the top (which may make sense, because it is the top folder). But the right-hand screenshot from 3 posts above is still unchanged (order at the bottom is still "Waller" / "Misc" / "Rec", which is clearly not alphabetic?).

- We now have created a tabbed view for different types of data, but I see no benefit from this, it is not practical. Now you have to flip tabs to see the data that really belongs together to one segment. All tabs look alike, they all use lots of space for the identical elevation graph, and contain very few numbers only. What's the purpose or motivation, what issue did we try to solve or improve here?

**Comment by crimean** [comment]
@sonora what OS do you have on the device?
Are you sure folders were sorted right way before this update?

**Comment by sonora** [comment]
Alexey, all screenshots I posted in this issue were taken on a Samsung S4 Mini with stock Android 4.4.2. I just verified that a Samsung S5 Mini with stock Android 5.1.1 behaves exactly alike.

But I apologize that I seem to have missed that going back to my current productive build, our nightly of January 31, behaves much the same: The folders are mostly sorted alphabetically, but there are occasional oddities. Hence I now think I was incorrect calling this a regression, it seems to have been present before you reworked the layout. Sorry for not catching that, my fault!

**Comment by crimean** [comment]
I see. Yesterday I've tested new chart with your gpx on S3 (android 4.4.4). It looks ok. Without any bricks. So this is not clear why you have broken chart even on 5.1.1.
Regarding messed list - please analyse tracks folder of osmand using an file browser. May be you will find the reason there.

**Comment by sonora** [comment]
Good idea playing with a file manager!  Finding is that, regarding the sorting, it is an upper case / lower case issue: Looks like folder names starting with an upper case letter are all sorted before any folder name starting with a lower case letter, which is why in my screenshot "misc" and "rec" are sorted all the way to the end. They are sorted earlier if I change the first letter to upper case.

Regarding the blue bricks: I see these on all devices I checked. Can you post a screenshot how it is supposed to look? In general I feel that the elevation curve is too thin and the axis captions are too tiny compared to how the rest looks on our screens, it looks like it is not compatible with the rest of our style guide?

**Comment by crimean** [comment]
Please check last build. See if chars are ok. Also list of folders should be sorted properly - case insensitive.

**Comment by sonora** [comment]
PS: The graph itself has changed some with the latest build. I now see that it is different curves on the different screens, which is good.  :)

But the colored step background is till present on all graphs  ..  see screenshot.

<img width="135" alt="screenshot_2017-02-24-19-53-21" src="https://cloud.githubusercontent.com/assets/845735/23316642/8c6cea68-facb-11e6-8a27-17d18c83ee09.png">

Side note: I have mixed feelings about the tabbed view, because I used to make single screenshots to document an overall summary of ALL key numbers for a certain track segment or split interval (both for sports and professional purposes), which is now distributed over 3 different tabs. Still not sure if there is a real benefit to loosely distribute this info over different screens, or if we could not put it back onto one screen with the code colors we had developed. But I guess this will take more people's opinions to judge.

**Comment by sonora** [comment]
PS: There are more bugs in connection with the new tabbed view: Take my file, and select split interval=1km (do not select "Show on map"). Scroll down on the different tabs you get. It is a mixture of different graphs (mixed from different tabs, I think), and not even the intervals and axis captions seem to properly reflect the selected 1km intervals in the right order?

**Comment by crimean** [comment]
It is not ready yet.

**Comment by sonora** [comment]
PS: I wonder if we could maybe fit all numerical data back onto only one tab again, and we could simply display or highlight the approriate curve(s) in the graph by tapping on the numerical data for speed or altitude? (by default display both as overlay, like you have it already on the first tab)?

**Comment by crimean** [comment]
![device-2017-02-25-135417](https://cloud.githubusercontent.com/assets/4689586/23330559/fe9ae13a-fb61-11e6-93b0-2c59ed0f4d91.png)
This is how char should look like. We cannot reproduce bricks. We tried on 4.0, S3 4.4, 6.0 and charts displays ok there.

**Comment by sonora** [comment]
I have just tried the latest build and the graph now looks like your screenshot. Good job!

**Comment by sonora** [comment]
Ok, to take things from here, let me for comparison post out old analysis screen again:

![screenshot_2017-02-26-08-38-24](https://cloud.githubusercontent.com/assets/845735/23338095/87c70066-fc01-11e6-8821-f9bfab4c6abe.png)

**Comment by sonora** [comment]
I know things are not ready yet. But here is my a tentative list of things we should think about and likely still fix:

- **(a) Overview screen:** We are missing the former info screen which contained all numerical values (per split interval, if selected). CF screenshot in post above. As is now, if you take my example file, split it into 1 km segments, and want to e.g. do a pace comparison (compare time and average speed per each kilometer, like trail runners would do), you need dozens of taps(!).

- **(b) Graphs:** The curves look wrong. It seems you are using some sort of spline or polygon interpolation to smoothen the curves? But this is wrong, we have discrete data, and that needs to be reflected!

- **(c) The green curve** may have a  bug: Is it meant to show the ascent/decline (steepness) on a percentage scale? It looks wrong ...

- **(d)** We are now **missing some numerical data** my GPX analysis module provide: "Number of data points" (indicates the resolution of a recording or interval), "Time span" vs. "Time Moving" (indicates breaks you may have made on trips during a recording), "Distance while moving" (gives an idea how much of a track was recorded "at rest", the track distance is overestimated)

- **(e) Scrolling:** When you have set a split interval and now need to scroll vertically, vertical scrolling is not possible when you happen to tap on a graph area (as the graphs only react to scrolling horizontally. Likely needs fixing.

**Comment by njohnston** [comment]
Thanks for your work on this @sonora and @crimean.

These changes look encouraging and useful. I compiled OsmAnd yesterday and tested the GPX analysis. I know work is still in progress but I wanted to provide some feedback as it might be useful.

### Handling of tracks with multiple segments

If a track has multiple segments, a chart is shown for each segment:

![normal_track_with_multiple_segments_small](https://cloud.githubusercontent.com/assets/638458/23585814/ae587664-017f-11e7-87c3-b1c2d860e8c4.png)

([GPX file](https://www.dropbox.com/s/tnh1kz6xi2qzflj/2017-03-04_13-28_Sat.gpx?dl=0))

This can be useful, but sometimes tracks can have many segments (particularly if there are pauses), so it would be useful to have a single chart showing the entire track, along with stats. In this case, the track is for a walk up a hill. To me, it's one logical track--there are two segments only because I paused at the top for a rest.

### Speed not always shown

No separate speed is shown for the above track (even though the track contains speed data). I'm not sure if that's because it's relatively slow (about 6 km/h on average). If I tap on the chart I can see my pace (number of minutes to walk one km) but I'd expect to see a separate line for speed, either in the main chart or the speed one.

### Blank track tab for GPX files containing routes instead of tracks

An empty track tab is shown for [GPX files containing routes instead of tracks](https://www.dropbox.com/s/gz04whm09ccvoh8/National_Trails_Cotswold_Way.gpx?dl=0):

![route_instead_of_track_-_nothing_shown_small](https://cloud.githubusercontent.com/assets/638458/23585918/210c9f58-0182-11e7-9c4a-81e4b8472b34.png)
 
Also, each route point is shown in the points tab as "important", which is probably wrong.

### Tracks without altitude and time aren't shown very clearly

[GPX files containing tracks without altitude and time](https://www.dropbox.com/s/70baxsnm1dz6w5f/south_west_coast_path.gpx?dl=0) aren't shown very clearly:

![track_without_altitude_and_time_also_names_not_shown_small](https://cloud.githubusercontent.com/assets/638458/23585977/9495ac34-0183-11e7-9142-81279fba1e51.png)

For tracks like this I think it would be clearer to show the time as '-' to indicate that the track contains no time data.

The detailed altitude tab also shows the hard-coded default minimum and maximum altitude from GPXUtilities.java--showing this isn't useful.

Unless there's a plan to extrapolate altitude using SRTM or other DEM data, the elevation chart shouldn't be shown if there is no elevation data in the track.

This track is also interesting as each segment is named. If a segment has a name, it would be great to show that as a heading for that segment.

Please let me know if I should open separate issues.

**Comment by sonora** [comment]
Thanks for the feedback! I guess it is fine for now to collect all the bugs and suggestions here. I have taken the liberty to re-size the screenshots a bit, and number the items for easier reference. Please note that

(j) the **"bricks" bug** (potential library issue?) is back also (on the devices affected). It was fixed in our nightly build of 2-25, but reappeared after tis commit: https://github.com/osmandapp/Osmand/commit/af8fbaec106bcccadf0189d7f073d3d62eed3243 (In last night's build the green and blue curve showed only very small bricks, this morning they are huge again for the blue curve, like in my initial screen shots above)

(k) The **Split interval** setting lost its functionality some time in recent days (both on the analysis screens and on the map display.)

**Comment by vshcherb** [comment]
Hi @sonora,
Looks like most of the issues are solved and it's time to reply to the feedback. I'm very keen to close this bug, so you could start new again where it could be easier to continue discussion.

(j) Bricks bug not reproducible on development devices and so far we don't want to loose "area" chart type which of course is a Plan B if we have it on many specific devices.
(k) Yes it is lost in favor of manual zoom in and pan the graphics. Statistic screen should also help with that. Split interval is something to display on the map, now.

(h) blank tab is fixed now
(f) may be a separate issue but this is done on purpose.

**Comment by vshcherb** [comment]
Again I would like to continue discussion and will be replying here as well. Though there is nothing from that list in active development, may be I missed something critical.

**Comment by sonora** [comment]
@vshcherb Hello Victor, I have don a quick run-through using this morning's build and from what I see our progress is good here!

Here are the remaining issues I still see, together with my judgment of how critical each is:

- **(a) Overview screen:** Still missing now. May be annoying for some people to not have one screen with all data any more, but no showstopper
- **(d) Missing some numerical data:** Should be checked. Why do we not display "Number of data points", "Time span" vs. "Time Moving" anywhere anymore? We have plenty of space. (No showstopper, but nuisance)
- **(j) The "bricks" bug:** 100% reproducible on a stock Samsung S4mini Android 4.4.2, not an uncommon device. I expect there should be other devices, but we will see. Question is: What did we do when it was 100% fixed with the nightly of Feb 25 (I tried again it was really fixed with that build) (No showstopper, but nuisance)
- **(k) The Split interval:** Split markers now appear again on the map curve. But we have currently lost our "pace display" capability, something runners or bikers commonly use to analyze their pace, i.e. time needed and average speed per kilometer or mile (formerly done via the split interval data display). I think losing this is something people may take badly, as it is common sports functionality, we should find a way to re-facilitate this functionality.

Best, Hardy

**Comment by vshcherb** [comment]
(a) Overview screen: Is it the same? I'm not sure if we understand what we are missing. May be you are talking about "split interval" numbers, over some time I've found it very cumbersome to use and it is far less intuitive comparing to UI we have now i.e. map, graph integrated
(d) Number of points is the only missing, time moving is on the last tab. It is indeed not clear how to organise better.
(j) We can disable only for the whole release 4.4.2 and it is not reproducible on all 4.4.2
(k) same as (a)

**Comment by njohnston** [comment]
I compiled OsmAnd again to look at the latest changes. I like the preview of the tracks, and the ability to tap on the chart to see the corresponding point indicated on the track.

However, there are still a few issues. I've continued @sonora's numbering.

### (l) No prompt to download maps

When previewing a track from a place that you haven't downloaded maps for, a blank background is shown. This is fine, but OsmAnd should prompt the user to download maps for the area.

### (m) The preview map can be very cluttered and unreadable

For this [sample GPX file](https://www.dropbox.com/s/tnh1kz6xi2qzflj/2017-03-04_13-28_Sat.gpx?dl=0), the preview looks very cluttered and is almost unreadable:

![cluttered_preview_map](https://cloud.githubusercontent.com/assets/638458/23963256/92f14ac8-09a8-11e7-9445-63200b862d1c.jpg)

Hopefully this is just an emulator issue.

### (o) "Flash" of main map after tapping "Details" back button

![details_back](https://cloud.githubusercontent.com/assets/638458/23963283/a02e5802-09a8-11e7-953d-5586cca7fbc3.jpg)

On the details view, when pressing "Details" to go back, the main map "flashes" briefly while the stats activity reloads. This is a bit disruptive.

## Follow-up on the other issues I raised

@vshcherb: if I understood correctly, you said (f) (separate charts and stats for each segment) is intentional. I really think that an overview section with stats and charts for the whole track is necessary. Unintentionally having multiple segments in a track is very common due to pausing or losing GPS signal. Showing each segment separately makes it hard to easily analyse an entire hike or drive.

(g) (speed not always shown) is still not fixed. For my [sample GPX file](https://www.dropbox.com/s/tnh1kz6xi2qzflj/2017-03-04_13-28_Sat.gpx?dl=0), the average and maximum speed (technically pace, not speed) is shown, but the separate speed chart is empty, and there is no speed series on the main chart:

![speed_missing](https://cloud.githubusercontent.com/assets/638458/23963311/b9945ad0-09a8-11e7-98f0-8855b3af2da8.jpg)

Being able to see speed as well as pace would be good too.

Thanks for your work on this. I'm looking forward to the changes being released :)

**Comment by vshcherb** [comment]
Yes pace is something to be fixed.

Taking a look at overall information of the track, something that deserves separate issue and again it was not working before. Right now overall information is displayed only distance.

**Comment by crimean** [comment]
Pace chart fixed

**Comment by sonora** [comment]
Victor, by "overview screen" I meant one  single overview tab containing ALL the numbers for a track, something you can send around as a screenshot on a geologic survey ...

Maybe we can add an overview tab back on, pretty much like the old track analysis screen we used to have?

**Comment by sonora** [comment]
@vshcherb, @crimean   Just in case this information got lost: I have just double-checked again the build we have in our download section of February 25 (osmand-master-nb-2017-02-25). That build produces perfect curves on the device in question they are filled (shaded) on the inside, and have no encapsulating "bricks" on the outside. What did we do to achieve this, can we not go back to that solution?
Thx - Hardy

**Comment by crimean** [comment]
@sonora I checked it - this build contained splines (interpolation between points). I could restore it, but  chart for bug gpx (starting from 100 km) will draw much slower.
Now I turned on hardware acceleration for the chart (Build #20757). May be it will help. Could you try?

**Comment by sonora** [comment]
Alexey, yes, you are right: The build #20493M which worked on that device had spline, which we should not do, it looks weird and wrong for tracks with few points.

I just tried #20765M, unfortunatrly no change, the encapsulating bricks are still there. Strange error. I wonder  what determines the "width" of the bricks. Sometimes there are many narrow ones, hence less visible, sometimes only 1-3, spanning the entire width of the graph ...

**Comment by njohnston** [comment]
@vshcherb @crimean: thanks for fixing the pace chart. I've tested the latest code and the chart works, but has some problems:

![pace_chart_stretched](https://cloud.githubusercontent.com/assets/638458/24074819/029340c8-0c08-11e7-9ee8-d72c298d520f.jpg)

In [this track](https://www.dropbox.com/s/tnh1kz6xi2qzflj/2017-03-04_13-28_Sat.gpx?dl=0), I stopped to take a photo. I didn't stop for long enough to trigger a pause, so OsmAnd just thinks I moved very slowly.

This causes high (slow) pace values like 80 min/km, which stretch the scale, making it harder to see the more normal data.

I think speed would be better than pace here, because low speed values would only cause a dip in the line chart, rather than stretching the scale like low pace does.

Pace also seems inappropriate for anything except walking, running or cycling. In this [track from a flight](https://drive.google.com/file/d/0ByKX_Fubbb4QbFhoWUlCTW9fLXM/view?usp=sharing), where the average speed is very high, it's strange to report this as 0.1 min/km:

![pace_chart_useless](https://cloud.githubusercontent.com/assets/638458/24074889/8a52f610-0c09-11e7-92c1-393c5a4bac33.jpg)

The speed chart isn't very helpful, because as before, the axis or scale has been stretched so much, and pace for most of the track is 0.1. Using speed rather than pace would fix this. Thanks :)

**Comment by sonora** [comment]
Yes, having a pace chart like this is flawed, I'm afraid. What is required in practice is what we had before: A primarily numerical (not chart) listing of all data for any split interval you may select. A runner must e.g. be able to again select 1 mile or 1 km splits and see the time he needed for each mile/km, alongside with the characteristics of each stretch (like elevation change etc.). I can think of no other way of fixing this significant regression than what I have said all along: Let's re-add an "Overview" tab (as the 1st tab) with all numerical data on one screen (and perhaps the combined elevation/speed chart as the statistically only significant one), and the screen must be split vertically in different equivalent copies per split interval if selected,  just like we had it until our Jan builds (there is a screenshot from me further up this issue).

Other information:
- Tested the "brick" bug on a Samsung Galaxy tab A3.7 with stock Android 4.4.2. Surprisingly there the bug does not show... I am beginning ro wonder how widespread the bug really is.

As I have noted elsewhere, some Issues on the UI as follows:
- The analysis screen on 4.5 inch displays now fails to show the second button row like start time etc. without scrolling, i.e.you only see the config buttons, tab headers, graph anf 2(!) numbers, very poor use of screen realty. I suggest to make the number display fields (but not the fonts!) smaller, i.e. less margins.
- Also our use of the string "Details" is wrong in 2 places. Should mean "Show on map" on the analysis screen and can there be combined with the existing Show on map item, saving more space.
- On the map screen we should replace Detsols by the track name(s).
- Also on the map screen, tapping the X after geting there via hitting the current "Details" button should also hide the track again, consistent with how we do it with trsnsport line display.

**Comment by sonora** [comment]
PS: I really feel sorry for Alexey having to follow all this in the middle of coding ...  for the next such major change I guess we could do a much more professional product management job in specifying all needed functionality,  UI, data, and discussing a strawman, rather than creating chain issues like this which partly talk about library bugs, partly about UI consistency, partly about regressions like dissapearing functionality or data, and partly about new feature requests like  a combined view over different track segments etc...

But now we are sort of in the middle of this, let me plesse re-open this at lesst until we fix the worst regressions
- missing split interval numerical pace analysis (best ALL data, untabbed)
- Worse screen real eatate use on 4-5 in  phone screens (re-adding a condensed overview tab may nicely workaround or solve this)
- missing display on number of data points (easy to fix, but sometimes crucial)
Ok?

**Comment by sonora** [comment]
@crimean, @vshcherb : Alexey, good idea about the hardware acceleration. I managed to fix things (generally, I think) after some research via https://github.com/osmandapp/Osmand/commit/84ecf92bd38853bcf36d95edb728675ad221a5a6

But while it now becomes usable for all devices,  let's please do something still about the above mentioned points before release, or I am afraid we may still earn as much praise as fire here ...:)

**Comment by sonora** [comment]
@crimean, @vshcherb : Alexey, good idea about the hardware acceleration. I managed to fix things (generally, I think) after some research via https://github.com/osmandapp/Osmand/commit/84ecf92bd38853bcf36d95edb728675ad221a5a6

But while it now becomes usable for all devices,  let's please do something still about the above mentioned points before release, or I am afraid we may still earn as much praise as fire here ...:)

**Comment by sonora** [comment]
Please see my idea under EDIT 2 posts above. I think that would fix all remaining regressions at least, and get us close to being able to release this without losing functionality?

**Comment by sonora** [comment]
Summary of what I see still open:
- Add ALL available numerical data (even if it is also shown on the more specific tas) on existing tab "General", rename tab to "Overview"
- Re-introduce duplication of all tabs for case where split interval is selected (fixes pace display, as thar data will be on overview tab for every split interval
- Condense vertical margins some for better UX on smaller screens
- Make "Show on map" text in line 1 orange and tappable, Remove "Details" text button on the bottom.
- On the map screen, replace text "Details" with currently viewed track name
- Also on the map screen, remove tracks from "Active" (better string would be "Visible") list if user taps X button (like we do for trsnsport line UI)

That's all I can think of!

**Comment by sonora** [comment]
PS: The excessive "clutter" reported by njohnston above in the little map preview seems to primarily result from sometimes showing many -and large- road shields. These disappear on the "real" map (i.e. once you tap "Analyze on map") ... so somehow we render that preview different.

**Comment by vshcherb** [comment]
@sonora  As I understand this is emulator issue, for native library that should not be an issue.

**Comment by vshcherb** [comment]
@sonora list.
2 issues won't be implemented this release and deserve separate issues/discussions:
- Re-introduce the split duplication of the tabs for the case when a split interval is selected.
That won't be done this release cause the interface is very cluttered with unnecessary graphics and quite slow. I'm not sure if it is useful representation at all.
- Add ALL available numerical data. 
That is useful representation but we will need to have design for this. Also this is not a regression. Introducing a new tab might be a solution but it still not clear whether it should be a first tab. So far only general distance information is available.

**Comment by sonora** [comment]
Please see my questions and screendhot here https://github.com/osmandapp/Osmand/commit/7f9bc4d5ce8afe9d83d5a7dcdd8bb6af9258c910#commitcomment-21504954
