### ISSUE TITLE
DoS from Online Tracking

### ISSUE THREAD

**Issue by Self-Perfection** [osmandapp/Osmand#4472]
After upgrade from 2.6.x to 2.7.5 Online Tracking feature started to produce an avalanche of requests to my server. I've noticed average request rate 25 req/s when Online Tracking is enabled. And if it does not sound scary here is a graph:
![nginx_requests](https://user-images.githubusercontent.com/3757038/30784870-ee70c59a-a165-11e7-8a8a-3375e5c7018a.png)
Eventually this excessive rate of requests depleted free space on server with logs which have broken several services and that's why I've named this bug "DoS".

It seems that OsmAnd keeps repeating the same GET request until it gets response code 200. That's wrong:

1. Any response 2xx code indicate successfully processed request. In fact properly implemented server side should reply with code 201 or 202.
2. It does not make sense to repeat same request thousands of times. OsmAnd should wait at least a second before repeating and/or limit number of repeats.

**Comment by vshcherb** [comment]
Fixed with pull request

**Comment by Self-Perfection** [comment]
@vshcherb that pull request does not fix bug completely. It leaves case of broken server unhandled. Server might break somehow and be unable to store data. Any error response from server now leads to indefinite resubmissions, that is extremely inefficient. In my case several hours of OsmAnd resubmitting online tracking data consumed about **100MB** of network traffic.

Limitation for resubmissions in response to error server reply is still required.

**Comment by vshcherb** [comment]
OsmAnd resubmits only last 10 minutes of the missing data & I guess it is configurable.

**Comment by Self-Perfection** [comment]
I believe you refer to "Time buffer for online tracking". And I strongly suspect  my explanation af a bug was not clear enough and you did not understand me. Thus I illustrate the issue with a portion of real log file. That is just 2 seconds from log file:

```
# zcat access.log.1.gz | sed -n "s|${ENDPOINT}|XXX|p" | grep '17/Sep/2017:13:30:0[01]'
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 90 0.003 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 91 0.003 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 92 0.003 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 93 0.003 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 94 0.004 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 95 0.003 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 96 0.003 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 97 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 98 0.001 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 99 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 100 0.001 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 1 0.001 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 2 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 3 0.001 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 4 0.001 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 5 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 6 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 7 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 8 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 9 0.001 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 10 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 11 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 12 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 13 0.003 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 14 0.001 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 15 0.001 -
213.87.156.6 - - [17/Sep/2017:13:30:00 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 16 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 17 0.003 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 18 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 19 0.003 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 20 0.003 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 21 0.004 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 22 0.003 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 23 0.003 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 24 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 25 0.003 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 26 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 27 0.001 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 28 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 29 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 30 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 31 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 32 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 33 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 34 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 35 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 36 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 37 0.002 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 38 0.003 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 39 0.003 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 40 0.003 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 41 0.004 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 42 0.003 -
213.87.156.6 - - [17/Sep/2017:13:30:01 +0300] "GET XXX.php?latitude=55.777084&longitude=37.583107&timestamp=1505643877787&hdop=10.0&altitude=0.0&speed=0.0&reporter=OsmAnd@JollaC&bearing=0.0 HTTP/1.1" 409 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; Jolla C Build/KTU84Q)" "-" self-perfection.homeip.net 43 0.003 -
```
That is 55 requests in just two seconds. And I had several hours of this, all the time track recording was enabled.

I don't see how changing "Time buffer for online tracking" to any possible value can reduce this gush of requests.

**Comment by Self-Perfection** [comment]
Final fix should be something like adding `sleep( 1 second)` here https://github.com/osmandapp/Osmand/blob/f8e798a0c1596cf87dfdfb70e078e4485470ebfb/OsmAnd/src/net/osmand/plus/monitoring/LiveMonitoringHelper.java#L122-L124

Summoning @PavelRatushnyi here, you are the last, who modified this part of source code and might be more able to understand what is wrong and how it should be fixed.

**Comment by Self-Perfection** [comment]
Or even better solution:
add `sleep( ("Online tracking interval" + 1second) / 4)` here after logging
https://github.com/osmandapp/Osmand/blob/f8e798a0c1596cf87dfdfb70e078e4485470ebfb/OsmAnd/src/net/osmand/plus/monitoring/LiveMonitoringHelper.java#L196-L200

**Comment by vshcherb** [comment]
@Self-Perfection in my eyes we should focus on using web-sockets which are designed to send lots of data with small overhead.

P.S. Sleeping is also possible to do on the server side.

**Comment by Self-Perfection** [comment]
> @Self-Perfection in my eyes we should focus on using web-sockets which are designed to send lots of data with small overhead.

If you propose this as a solution to this issue than I disagree. The proper fixing of sending lots of unneeded is not sending lots of unneeded data with smaller overhead but sending little of unneeded data.

> P.S. Sleeping is also possible to do on the server side.

That is correct. Actually the first my reaction to noticing this behavior from OsmAnd was configuring `limit_req` on nginx to throttle request rate. But if you insist on this approach, than manual page for online tracking feature should be expanded with notice like "Remember to throttle handling of requests on server side, otherwise OsmAnd might send requests at a thousand times faster rate then configured with "online tracking interval" ".

**Comment by vshcherb** [comment]
@Self-Perfection I'm not arguing there are solutions or it could be solved in many ways. Though I think I disagree with the statement itself " 25 req/s is DoS", it doesn't scary much me we also process sometimes 100 req/s and I don't see anything to worry.

So talking about the feature of throttling, I think it has slow priority just for now & won't be implemented in a near time.

**Comment by Self-Perfection** [comment]
Fair enough. I am more worried about battery drainage on device running OsmAnd than server's well-being though.
