### ISSUE TITLE
String "empty_state_markers_history" translatable?

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#4785]
I don't understand what they wanted to translate here. I think this string should not be translated or changed to one that is understood.

String:
https://github.com/osmandapp/Osmand/blob/66cca8c58cbb9940e1492d14a85f1b4a4f67793f/OsmAnd/res/values/strings.xml#L25

Photo:
![photo_2017-11-20_00-54-55](https://user-images.githubusercontent.com/12088580/33001563-7559081c-cd8d-11e7-999e-14bcae75283c.jpg)

**Comment by vshcherb** [comment]
It is may be attempt to use hidden feature of Android Build Platform? Anyway it looks wrong.

**Comment by PavelRatushnyi** [comment]
Fixed with https://github.com/osmandapp/Osmand/commit/9be31647fa026d55cfe6d751f7eedad2317c7a61

**Comment by yarons** [comment]
Although it was allegedly fixed I can still see this string, what am I supposed to do with it?

**Comment by vshcherb** [comment]
new build needs to be installed, sometimes it could be cached but a new build usually helps please also check the latest default version

**Comment by yarons** [comment]
@vshcherb, I'm talking about this:
https://hosted.weblate.org/translate/osmand/main/he/?checksum=f65e2baa2b7d33d3
