### ISSUE TITLE
Wrong routing in OsmAnd, but right on OSM site

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#5233]
The co-ordinates are -27.66222, 152.84986 
Normal route on the site, weird u-turn in OsmAnd. It's the latest version of the app and the Queensland maps are downloaded.

![screenshot_20180412-235339](https://user-images.githubusercontent.com/12711814/38736253-235ef6d4-3f34-11e8-8e50-76fa88605b53.png)
![screenshot_20180412-235039](https://user-images.githubusercontent.com/12711814/38736254-2390975c-3f34-11e8-8ac0-cd6230953aa9.png)

**Comment by ADepic** [comment]
1. Enable live updates, and click download update now, then check if this issue exists.

2. While on OSM, what navigation service did you use ? Try every service navigation osm offers and see if one of the gives that problem.

3. Enable "online tiles" plugin and try the different navigation services osmand offers (Settings > Navigation Settings) such as YOURS and OSMR. (You need to enable a online map for this)

**Comment by hakuchi** [comment]
For me this looks like a simple error in the osm data.
If you add a turn restriction to the poit where OsmAnd make a u-turn, this problem can fixed.

**Comment by scaidermern** [comment]
Yes, a turn restriction will help. Nevertheless unclear why OsmAnd prefers the route which is longer and has a sharper turn. Maybe because it avoids having to turn left on a traffic light?

**Comment by Catfriend1** [comment]
Hi,
we have the same problem here in germany, Hessen, Heusenstamm. Link to OSM Issue Note https://www.openstreetmap.org/note/1354174#map=18/50.05864/8.79343
Summary: Mapper aseerel4c26  investigated the issue and found out, OSM Map is correct, even with the up2date correct OSM map downloaded to the Android phone (Android 7.1.2, OSMAnd 2.9.3), the OSMAnd offline routing fails and forces a wrong u-turn on the user, see screenshot: https://ibb.co/hk4mWT
If you select "YOURS" in OSMand car navigation settings, turning left is suggested correctly  by the app. This issue cannot be reproduced using the OSM web page service so definitely must be an app issue.
Thanks for your help
Kind regards

**Comment by vshcherb** [comment]
The issue is fixed.

@Catfriend1 I also don't see your issue reproducible with latest map data.
<img width="620" alt="screen shot 2018-05-26 at 00 40 29" src="https://user-images.githubusercontent.com/1042025/40568845-6d3aadd8-607d-11e8-9f13-b3259db52e44.png">

**Comment by Catfriend1** [comment]
@vshcherb The issue can still be reproduced with osm 3.x, offline osmand route car mode and map data from 01.05.2018
It's still showing the u-turn from south to west

**Comment by Catfriend1** [comment]
Vote for Reopen

**Comment by Catfriend1** [comment]
@vshcherb This issue is still not solved and can be reproduced on 3.0.0 and 3.0.2 OSMAnd by me and user aseerel4c26, see link https://www.openstreetmap.org/note/1354174
The u-turn still occurs using OSMAnd offline routing. Please investigate and fix it. Thank you in advance.

**Comment by ADepic** [comment]
[osmand wrong routing translation.txt](https://github.com/osmandapp/Osmand/files/2087011/osmand.wrong.routing.translation.txt)
I have attached a copy of a translation of the Germany comments on the note @Catfriend1 provided us

**Comment by vshcherb** [comment]
Did you use new maps?

**Comment by Catfriend1** [comment]
@vshcherb yes maps are dated 01.06.2018

**Comment by Catfriend1** [comment]
Still occurring in 3.0.3

**Comment by Evgenij27** [comment]
![screenshot_2018-07-31-12-41-55](https://user-images.githubusercontent.com/7140273/43453816-bcf09930-94c3-11e8-834d-9ef4cbfc3de9.png)
![screenshot_2018-07-31-13-07-36](https://user-images.githubusercontent.com/7140273/43453817-bd19b07c-94c3-11e8-80e4-f12b2963c669.png)

failed to reproduce with 3.1 coming version

**Comment by Catfriend1** [comment]
I still have the u-turn with osm offline routing set in the car prefs.
![screenshot_20180823-184447](https://user-images.githubusercontent.com/16361913/44539858-80a87980-a705-11e8-95c3-8bb7f18a5d74.png)
App version is 3.1.6
Maps updated every month and up2date.
Please fix it or tell me what you need for deep analysis.
Just try to go from the center of Heusenstamm to Langen. It will propose the uturn.

**Comment by Catfriend1** [comment]
I still have the u-turn with osm offline routing set in the car prefs.
![screenshot_20180823-184447_1](https://user-images.githubusercontent.com/16361913/44540098-31167d80-a706-11e8-8308-76afe9599395.png)
App version is 3.1.6
Maps updated every month and up2date.
Please fix it or tell me what you need for deep analysis.
Just try to go from the center of Heusenstamm to Langen. It will propose the uturn.
