### ISSUE TITLE
Is OSM Live Broken? No map updates since 3/31/18. OSMand+ Version 2.9.3

### ISSUE THREAD

**Issue by tazva** [osmandapp/Osmand#5368]
I've noticed that the US Map receives frequent updates (just got one yesterday), however, it seems like individual State maps have stopped updating as of 3/31/18. As an OSM developer, I know for a fact maps are being updated.

I just noticed this as an issue yesterday, when I realized some changes to a map that I have made, weren't reflected in OSMand+, and I went to look for updates manually and it showed no new map data available since 3/31.

**Comment by vshcherb** [comment]
There was 2 days delay which was fixed yesterday. Please check UI in Android to see last update status or here https://osmand.net/api/osmlive_status

**Comment by tazva** [comment]
Suggest you re-open this and see what's going on. Now that you fixed whatever you fixed, map update files come through, but it's still missing many updates from 3/31/18 to present. Below is a screenshot example of what I'm talking about, using OSM map (right) and OSMAnd+ Live (center/left).

Link to OSM: https://www.openstreetmap.org/#map=18/36.73554/-76.23250

![osm_bug_5368](https://user-images.githubusercontent.com/29614385/39900063-5e05db54-548d-11e8-81fd-c8bad9921b85.jpg)

**Comment by paulburton0** [comment]
I also have not gotten OSMand+ Live updates for several days. I tried clearing app cache, force close and restart, etc. and still it says the last available map change is April 30. I just downloaded the latest "non-live" update for my state area, but the live updates (and I know there are many--I've added several over the last few days) are not showing up.
![screenshot_20180511-075528](https://user-images.githubusercontent.com/402935/39923321-2590cc3e-54f1-11e8-8861-bfe062609cc1.png)

**Comment by tuxayo** [comment]
The same happens to me on two devices. Was working well ~10 days ago. (before the 2 day lag mentionned above)
OsmAnd 2.9.3 from F-Droid
Device 1: Wiko CINK PEAX 2 - Android 4.1.2
Device 2: Galaxy S5 - Lineage OS 14.1, Android 7.1.2, no Google apps, no Google Play Service

Here is a logcat on a freshly booted device (Galaxy S5)
- start logging
- start the app
- try to update
- stop logging 

https://framabin.org/?bd47c108370c4e32#0O0ghdVNonBmetEl91bdW0ANKxTkM0Nk2BHplvf4RHk=

**Comment by tazva** [comment]
At least I'm not the only one..

**Comment by xraMsamohT** [comment]
The same here in Germany, Bavaria and North Rhine-Westphalia. Last map change was on the morning of 2018-05-07.

**Comment by vshcherb** [comment]
This is quite strange situation, checking it now

**Comment by vshcherb** [comment]
Just updated server side and looks downloads started working.

**Comment by majkaz** [comment]
@vshcherb 
Working OK:
Last map update shown as 13.5.2018, 22:20
my last changes were shown

**Comment by mguaylambert** [comment]
I just purchased OsmAnd live but it says the last update is last year for anything I try to download. Is this normal? 
![image 2019-02-04 15 05 13](https://user-images.githubusercontent.com/16389438/52233952-6b2ba400-288e-11e9-8091-340fff635d85.jpg)
