### ISSUE TITLE
Dual carriageway junctions - look ahead for 'name' and 'destination' for better turn instructions

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/OsmAnd#5752]
As discussed on SotM:
[<img src="https://wiki.openstreetmap.org/w/images/thumb/7/7c/Dualjunction.svg/144px-Dualjunction.svg.png">](https://wiki.openstreetmap.org/wiki/File:Dualjunction.svg) [<img src="https://wiki.openstreetmap.org/w/images/thumb/6/6f/Doublejunction.svg/198px-Doublejunction.svg.png">](https://wiki.openstreetmap.org/wiki/File:Doublejunction.svg)

[Dual carriageway junctions](https://wiki.openstreetmap.org/wiki/Junctions#Dual_carriageway_intersections) contain inner segments, m, n, p, q in the images above. These are not real roads, they are routing _abstractions_ from the junction area (grey in the images). 

As they don't exist in reality, naming them is ambiguous and done differently by mappers. In particular, for m an n, mappers either randomly chose B-Road or C-Road, or assign no name at all. 

Further, _destination_ can only be tagged for the outer way segments, leaving the junction, as the inner segments can lead to multiple destinations. 

This leads to the problem that only for a right turn, the correct name and destination can be announced. For the left turn, the name might be misleading, and the destination cannot be announced. 
(The above applies to right-hand traffic and needs to be mirrored for left-driving countries)

**Proposed Solution:**
* Recognise the inner sections of a junction, e.g. using the following heuristics:
** The length of the segment is relatively short (as long as the roads are wide, could be scaled with the number of lanes being crossed)
** The segment touches a carriageway with the same name twice, i.e. when routing h-q-m-a, segment m touches B-Road at both ends
* Ignore any name or direction on the inner segment, m in the example, and look ahead for the segment outside the junction, a in the example
* Thus h-q-m-a can be announced as "Turn left into A-Road towards A-Town"

**Comment by bitboy85** [comment]
i don't agree to this solution even i know the problem and i like to have a fix. The reason is that i think this would increase calculation time and those checks needs to be done every time a junction contain small segments.

In the long way there is no other solution than implement some new routing specific tags to fix this (and other) issues in a solid way.
In this case junction=abstract for p, q, m, n might be useful, which could mean "use for routing, ignore name and destination for announcement, announce first segment after leaving junction=abstract".

**Comment by vshcherb** [comment]
I think we're going to implement a simple algorithm if it satisfies both parties (mappers and devs).
If m/p/q/n will have "empty name" they will be ignored for the computation, otherwise it will still use the destination from p/q/m/n.

Usually it is not simple to detect whether it is a junction or a simple 2 short streets connection.  The alternative solution is to ignore all names within first 10-30 meters after a turn to lookup proper destination name will have more issues I think.

**Comment by bitboy85** [comment]
From the wiki page:
"Obviously, the pink segments m and n in the pictures can be named as A-Road without a conflict. On the other hand, the blue segments p and q might be named either B-Road or C-Road, or given no name at all. Similarly, the destination=* should be tagged on the outer segments where things are unambiguous."

so i think there is a Name given in many cases and so this solution will fail quite often.

**Comment by polarbearing** [comment]
@bitboy85 - I had written this ticket on the SotM simultaneously with the section in the wiki you quote, based on observing mapping behaviour, chatting with some people including vshcherb, looking for a solution that suits both mappers and consumers. Even if that requires to review the tagging.

@vshcherb - I'd be happy enough to test the implementation as you propose, though I agree with bitboy that name=* and destination=* should be evaluated for emptiness separately.

**Comment by MadWasp79** [comment]
@polarbearing can you provide real examples of such junctions where you experienced troubles with the street announcements? For example, here - https://www.openstreetmap.org/#map=19/53.89314/27.54191 - everything is OK - both in naming and voice announcement.
![image](https://user-images.githubusercontent.com/13146346/92402555-6bf67d00-f138-11ea-8455-6c7b9a8711a1.png)

**Comment by vshcherb** [comment]
Looks like it was already fixed

**Comment by mattmccutchen** [comment]
I am still seeing this problem for junctions in my area where the inner segment has a name.  What was the intended resolution here?  OsmAnd ignores inner segments that have no name, and mappers are expected to delete the name from OSM?  Is there consensus that such changes are legitimate to make to OSM?  If so, I'd expect it to be reflected on [the originally cited wiki page](https://wiki.openstreetmap.org/wiki/Junctions#Dual_carriageway_intersections).  The page still says, "the blue segments p and q might be named either B-Road or C-Road, or given no name at all", which I interpret as "applications are responsible for handling all of those cases".

Or was OsmAnd supposed to be changed to ignore inner segments even if they have a name and look at the next segment?  If so, that isn't working for me.  Here's an example where OsmAnd is using the name of the [inner segment](https://www.openstreetmap.org/way/553709228), "Twinbrook Parkway":
<img src="https://user-images.githubusercontent.com/8885753/142740646-02b2b872-7843-4bd4-a6ea-7ed145aef641.png" width="270" height="585"/>
This is with Us_maryland_northamerica.obf dated 2021-10-31 on a clean installation of "OsmAnd Nightly 4.1.0#33096m, released 2021-11-20".  [The openstreetmap.org directions](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=39.05827%2C-77.12082%3B39.05879%2C-77.12227#map=19/39.05859/-77.12146) correctly use the name of the target road, "Rollins Avenue".
