### ISSUE TITLE
Subway problems

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#6095]
Map style: Osmand. Taping subway stations, Osmand shows one of the stops of this stationv instead of showing the station. This is very important for showing routes of the station, because one stop only shows one way of the line instead of showing the two ways of the line.

There is a problem with https://www.openstreetmap.org/relation/7837168 and https://www.openstreetmap.org/relation/62917 because Osmand shows them with red colour and OSM data shows colour:#ee87b2

**Comment by Chumva** [comment]
This was fixed with https://github.com/osmandapp/Osmand/commit/6c0895b6e9b8ab29c707f5d645f864a902de7867

**Comment by OpenSourceForEver** [comment]
Sorry, but I think bus stops are right but the problem with subway stations is not fixed. When I tap a subway station only one direction is shown like a route of this station, the other direction is shown on "within 150m".
Osmand nightly build 3.2.0#22409d

**Comment by vshcherb** [comment]
They have same ref L8 that's why we don't display them both as shields, they should be in the list in the context menu both.

**Comment by OpenSourceForEver** [comment]
But this problem was fixed for buses. It can not be solved for subway?

**Comment by OpenSourceForEver** [comment]
Will this issue still be closed? The problem is not solved for subway.
