### ISSUE TITLE
OsmAnd live: POI search lists old data

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#6395]
With OsmAnd live the POI search still lists old results that have been modified meanwhile.

Example:
I've removed `atm=yes` from an `amenity=bank` object (https://www.openstreetmap.org/way/39426621) and added it as a separate `amenity=atm`. Additionally I've added opening hours, changed the website and telephone number. These changes are _correctly_ reflected when tapping on the object. However for example when searching for ATMs the bank gets _wrongly_ listed, including the old website, old phone number and no opening hours. The old POI somehow still remains in the POI search.

Correct data when tapping on the POI:
![photo_2018-12-26_13-52-16](https://user-images.githubusercontent.com/1040784/50446597-0b98bb00-0916-11e9-8abb-655cd1913fc3.jpg)

Same object from the POI search, but with old data:
![photo_2018-12-26_13-52-10](https://user-images.githubusercontent.com/1040784/50446618-2ff49780-0916-11e9-9d10-82482befff2e.jpg)

**Comment by xmd5a2** [comment]
This issue divides to two parts: 1)Overpass doesn't return correct diff 2)UI glitches regarding POI info. First part is confirmed and we can't do nothing about that. Also we can't reproduce second part of issue and hence can't fix it.

**Comment by scaidermern** [comment]
Can't reproduce? Did you even try? :(

Here is a similar issue. The name of [node 501955817](https://www.openstreetmap.org/node/501955817) recently changed from "Fahrschule André Eichler A-B-T" to "Fahrschule André Eichler". The renderer displays the correct name, the POI popup still displays the old name:

![photo_2019-02-12_09-49-55](https://user-images.githubusercontent.com/1040784/52623288-42b63200-2eac-11e9-84e0-c3c0ef5b63ea.jpg)

geo:51.047203,13.776813?z=20
https://osmand.net/go?lat=51.047203&lon=13.776813&z=20

If this is a Overpass API problem then please get into contact with the developers. It affects _your_ product. It affects OsmAnd Live which is the only reason why people pay you money every month. OsmAnd Live's usefulness is greatly reduced if it shows wrong POI categories and wrong names.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/Osmand/pull/6538

**Comment by scaidermern** [comment]
Thanks!

**Comment by scaidermern** [comment]
Unfortunately the original problem persists.

https://www.openstreetmap.org/node/1496351547 has previously been a restaurant. The renderer doesn't show it any more but the restaurant still gets listed via the search function:

![photo_2019-03-19_08-16-02](https://user-images.githubusercontent.com/1040784/54587134-73dfd000-4a1f-11e9-9fde-0b870e0d0875.jpg)

geo:51.046886,13.78194

In the POI details there is a "change delete" entry (see #6480). Shouldn't it be possible to exclude "change delete" objects from the search function?

**Comment by vshcherb** [comment]
This is a correct behavior, searching for an object which is "closed" / "deleted" will keep functioning cause it is still maintained in search index. Though it should have a red label instead of opening hours that place is shut down.
