### ISSUE TITLE
left;slight_left shown as just slight_left

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#6416]
https://www.openstreetmap.org/way/337186717#map=18/59.94505/30.47921

The original road sign looks following:
![img_20190103_184042](https://user-images.githubusercontent.com/14617699/50646457-26f36e00-0f87-11e9-8c4f-0be0b224cd03.jpg)

```turn:lanes=left;slight_left|slight_left|slight_left;right```

but osmand shows:

![screenshot_20190103-183928_osmand](https://user-images.githubusercontent.com/14617699/50646538-628e3800-0f87-11e9-95ec-a793c8bad844.png)
![screenshot_20190103-183934_osmand](https://user-images.githubusercontent.com/14617699/50646541-6326ce80-0f87-11e9-92bb-57f0785c654c.png)

**Comment by MadWasp79** [comment]
Fixed with #6416

**Comment by 532910** [comment]
Not fixed. Please reopen.
![image](https://user-images.githubusercontent.com/14617699/62534064-dca1da80-b850-11e9-92a5-04e6899c1434.png)

**Comment by 532910** [comment]
Not fixed in 3.4.8:
![image](https://user-images.githubusercontent.com/14617699/69198778-f8529780-0b46-11ea-8cf8-d864256e3781.png)
Please reopen.
