### ISSUE TITLE
when I search some streets it are shown twice, with the ward and with the suburb

### ISSUE THREAD

**Issue by Almorca** [osmandapp/Osmand#6418]
Using Spanish map offline when I search some streets it are shown twice, with the ward and with the suburb.

I think that problem occurs when a street has some address with tag address:ward

**Comment by vshcherb** [comment]
```marroquina``` it was fixed in 2025 maps, however it needs to be double checked. If we didn't reintroduce this bug.

**Comment by Almorca** [comment]
The same occurs with Paseo de la Castellana.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/98b4f538-df62-41b7-8e13-fffdd7328ee2"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
# Testing 1

> Wep-prod
> OsmAnd~ 5.3.0#6347m, Released: 2025-10-27
> 5.2.2.5265


The duplicate is still showing up in iOS — @vshcherb  maybe it's time to migrate?

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/8a8d8972-99f1-488c-bae1-ebe2e245a719"  width="600" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/7b50d7a5-53a3-4a40-9533-640389c1a00c"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/4fe3757b-ba82-41fd-a287-de72fb053324"  width="300" height="auto"/> </th>
  </tr>
</table>   
</details>

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/09e12bc2-fc72-45cb-b0e9-ef63f536bfe7"  width="300" height="auto"/> </td>
  </tr>
</table>  

* Some boundary is visible
