### ISSUE TITLE
Flooded: Istanbul

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#6565]
https://osmand.net/go?lat=41.007065&lon=28.97503&z=17
![screenshot_20190218-183300](https://user-images.githubusercontent.com/9365308/52964779-e40d1e80-33ab-11e9-8923-08cb769fe67d.png)

**Comment by xmd5a2** [comment]
Fixed

**Comment by Rpnpif** [comment]
Hi,
I do not understand why all this issues are closed but not fixed. What is the reason of these issues ?

**Comment by MadWasp79** [comment]
Florida keys (#7343) is OK with the latest mini-basemap and detailed maps, no floods.

**Comment by MadWasp79** [comment]
Fixed OSM data for #5972, will be ok in next map
