### ISSUE TITLE
Show GPX dialog automatically select all tracks to show.

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#6855]
Show GPX dialog automatically re-select all tracks to show, after next time dialog will open.

**Comment by MadWasp79** [comment]
Closed with https://github.com/osmandapp/Osmand/pull/6905

**Comment by sonora** [comment]
Maybe I misunderstand the issue, but the following feels still weird:
- Select some GPX files to be displayed, via any method.
- Then on the map screen, go to Configure map/GPX files, and turn the slider off, so that no GPX files are displayed any more. Leave the menu.
- Later go back to Configure map, tap on GPX files: In the pop-up list, **all formerly (but not any more) visible GPX files are again pre-selected.** 

Bug or feature?

**Comment by vshcherb** [comment]
It was fixed last week. So will be good in 3.4 this month

**Comment by sonora** [comment]
Talking about https://github.com/osmandapp/Osmand/pull/6905? What I reported above is still present in our nightly, after that commit...
