### ISSUE TITLE
Flooded: Gujan-Mestras, France

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7060]
Boulevard Pierre Dignac, Gujan-Mestras 
Position: geo:44.639614,-1.0842025?z=17 
https://osmand.net/go?lat=44.639614&lon=-1.0842025&z=17 

![image](https://user-images.githubusercontent.com/50198677/59780611-f730ec00-92c2-11e9-82ec-6324e210af4b.png)
![image](https://user-images.githubusercontent.com/50198677/59780631-fd26cd00-92c2-11e9-8acd-68f040b9d847.png)
![image](https://user-images.githubusercontent.com/50198677/59780647-04e67180-92c3-11e9-998a-d573250d5169.png)

**Comment by InsertUser** [comment]
Are you using the Live updates? If so, issue #6535 may be related. It was closed this morning, so hopefully, the change will make it into the released version soon.

**Comment by vshcherb** [comment]
Looks like the issue is already fixed

**Comment by Seaviator** [comment]
I have installed the newest version and updated my map but I am still having this problem
