### ISSUE TITLE
Crash when taping on "my Position"

### ISSUE THREAD

**Issue by oxxm** [osmandapp/Osmand#7943]
Osmand 3.5.2

Tap on the arrow to create a route and then tap on -My Position- : Osmand crashes directly.

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback.
What UI language you set?

**Comment by oxxm** [comment]
Thank you for the reply. UI language is german. It does not crash if system language is set to english btw.

**Comment by pebogufi** [comment]
I had this crash also some days ago, 
but no more with
3.5.0#28421m

**Comment by dmpr0** [comment]
@oxxm thank you.
We fixed this crash, and planning to make a 3.5.3 release in a few hours.

**Comment by oxxm** [comment]
@dmpr0 great! thank you.

**Comment by sonora** [comment]
@dmpr0 Maybe fox the version display issue, too, at the same time. The version we published on November 11 still shows as 3.4.8 on the Google Play web page.

**Comment by dmpr0** [comment]
@sonora We released 3.5.2 on Google Play only on 5%, today we launch 3.5.3 on 15%.

**Comment by sonora** [comment]
Ok, but somehow it looks weird: When I go to the Play Store website (on a Windows PC, not logged into google at all), it now shows that the last app update is of November 18, 2019, but it still shows version 3.4.8. Not sure this is not a bug, I think it used to be different in previous releases ...
