### ISSUE TITLE
Map issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8070]
The Indian River is almost invisible, except for the nautical route near the Sebastian city. 
27.8053 -80.4645
![image](https://user-images.githubusercontent.com/50198677/70626607-71687a80-1c2d-11ea-8c3b-2993f562deb7.png)

**Comment by xmd5a2** [comment]
Role of https://www.openstreetmap.org/way/43312236 should be "outer" not "inner" in Indian River relation

**Comment by xmd5a2** [comment]
OSM data were fixed

**Comment by chaco1lp** [comment]
The latest Florida map (dated Nov 30) still does not correctly show the Indian River from Ft Pierce to north of Titusville.  In most places it is a mile or more wide,  not a narrow channel.  Versions of Florida maps prior to November were correct.  Thank you.

**Comment by xmd5a2** [comment]
@chaco1lp we don't provide 30 nov maps. Maps are updated on a month basis and latest maps are from 1 december. But my fixed to OSM were 9 days ago so you should use january maps, or use OsmAnd Live.
