### ISSUE TITLE
Missing instruction to leave the freeway

### ISSUE THREAD

**Issue by joostschouppe** [osmandapp/Osmand#8164]
Over the last days, I had a recurring issue in osmand+ 3.5.5 (android) where the fact that I had to leave the freeway was not mentioned by the routing, but instead the next instruction was already shown. For example, I would get "take the roundabout in 20 km" instead of "take the exit in 1 km". I don't use voice, so no idea if those instructions are correct. I tried two places with the routing simulator but then the routing was correct. So it is not data related.
Telegram user AalEchs mentioned having similar issues on the Telegram group, and another user mentioning it there as well.

**Comment by scaidermern** [comment]
I experienced the same. OsmAnd routed me from a motorway to another road and neither the widgets nor the voice instruction informed me about it. Instead, widgets displayed the next turn a few kilometres ahead. I couldn't reproduce this issue.

**Comment by joostschouppe** [comment]
So it happened again, and I was able to make a screenshot. After this weird instruction showed, I happened to make a stop at a rest area. This did not trigger a correction. Adding a viapoint along the route did solve the issue. ![Screenshot_20200102-162228](https://user-images.githubusercontent.com/10122639/71768208-5c24fa00-2f14-11ea-992e-aadbc2c72654.png)
![Screenshot_20200102-161324](https://user-images.githubusercontent.com/10122639/71768233-955d6a00-2f14-11ea-830b-e248d17a2562.png)

**Comment by Glotzon** [comment]
I can confirm, same issue on Osmand 3.5.5 Android when using "car" in routing mode and traveling on a German or Austrian Autobahn. Any exit on the Autobahn is not considered in instructions, but the next turn after exiting the Autobahn.

Happy to support debugging if required.

**Comment by vshcherb** [comment]
It is interesting that issue was already in 3.5 cause we have thought it was introduced in the nightly builds. We have similar reports about missing instructions and it is not reproducible, simple stop and start sometimes helps .

**Comment by jypma** [comment]
I can confirm the same issue (all instructions missing _until the next one that's not on the freeway_). I'm navigating Denmark, but had the same issue in Germany.

Stopping and Re-starting the navigation always helps, but after a while (up to ~30 minutes) of navigating, the route sometimes seems to forget the highway instructions again.

**Comment by Discostu36** [comment]
I can reproduce at this exit:

Kronshagen-Nord
Olof-Palme-Damm, Schreventeich
Standort: geo:54.337162,10.111713?z=18
https://osmand.net/go?lat=54.337162&lon=10.111713&z=18

**Comment by vshcherb** [comment]
We've fixed an important issue with our core navigation (it was crashing behind the scenes), please try it with new nighly build

**Comment by sonora** [comment]
It looks like all occurrences reported are associated with highway exits, hence I would assume this is a remaining bug from when we introduced `class ExitInfo`, starting with https://github.com/osmandapp/Osmand/commit/55db01e9b4de973d1b73690f97d1838e438a4b8e.

**Comment by vshcherb** [comment]
@sonora issue is fixed and it was related to route recalculation and started from summer release originally.

**Comment by uvok** [comment]
Hi. I am still experiencing this with OsmAnd 4.7.17 from FDroid. Same behavior. Upon calculation, when previewing or simulating, the exit is shown as an arrow. When I'm actually driving, the instruction is "skipped" on the Autobahn. Since I only rarely drive Autobahn, I can't really bisect various versions.

GrapheneOS 14 on Pixel 6a, TTS enabled, Google Speech services.

 I know it was working properly on my previous phone, (Oneaplus 6T, LineageOS, with eSpeak, Android 12 or 13?, osmand 4.5 or 4.6 series)

**Comment by joostschouppe** [comment]
I had the same issue myself on a slow Android phone last February with up to date Osmand+ version. I haven't had the same issue since upgrading to a stronger phone.
