### ISSUE TITLE
Motorway junction voice guidance issue:  "undefined exit"

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#8299]
Recent night builds appear to give broken voice guidance instead of speaking the destination tags at some (all?) motorway_junction nodes.  I am now encountering this instruction:  "Turn slightly right to undefined exit onto" (not 100% sure about the last word, but that's kinda what it sounds like).

What version of OsmAnd are you using, on what device and Android/iOS version?

Night build 3.5.6#28763m, dated 2020-01-17

I haven't yet had the opportunity to test more recent builds, but will get to do that today.

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Offline maps

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

US Georgia, US Florida.  both dated Dec 31, 2019.

This is also on my "test everything" phone with OSMLive fully enabled.

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.

OsmAnd's in-app routing.

What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

Car profile

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also, a permalink from openstreetmap.org can be helpful.

I'll add some start/end points and other details after I do some more testing.

Note that the problem does not appear to occur when navigating through junctions that do not have highway=motorway_junction tags, but I'm not sure that the problem is actually based on that tag.  For example, I think I got good voice direction at this node:  https://www.openstreetmap.org/node/283247649#map=19/27.90963/-82.34094&layers=N

**Comment by jfburke3** [comment]
Additional information:

* Voice guidance in advance of an upcoming exit works (e.g., "In .9 miles, keep right to blahblahblah."  It is only the last voice guidance received at the exit that is wrong.

* The problem still occurs in night build 3.5.6#28803m, released 2020-01-22.

**Comment by jfburke3** [comment]
Additional comment:  I think I did encounter a couple of cases where the advance guidance was also wrong, and one or two cases where the actual exit node guidance *might* have been right.  Was late at night, I was tired, so not sure I'm remembering this correctly.

**Comment by jfburke3** [comment]
And as related question for @vshcherb :  Do you want us to report issues like this on the nightly builds, or just seriously broken things that make using OsmAnd impossible (e.g., the routing horrendously broken issue from a year or two ago), and reserve GitHub issues for the Beta releases or public releases?

**Comment by vshcherb** [comment]
I think it is good to let know asap in case it is in *master* branch.

**Comment by vshcherb** [comment]
Should be fixed now

**Comment by jfburke3** [comment]
@vshcherb I'll keep reporting (relatively) minor things like this, then. I just didn't want to overwhelm y'all with small issues that might get caught in automated regression testing.

**Comment by sonora** [comment]
@vshcherb ,@veliymolfar Is anyone still working on this? I still see a number of remaining issues which should be ironed out (both wording and logic), and can offer to help with this, but do not want to interfere with work in progress. Once reasonably final, I would like to transfer to all other voice files, but think we still need a bit of work on this.  Thx - Hardy

**Comment by vshcherb** [comment]
@sonora We've just copypasted to all languages hoping somebody will fix the order / translation next release. It should function fine for top 6-7 languages alreaady
