### ISSUE TITLE
Default color of Favorites changed to black

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#8926]
It looks like in recent nightlies the default color for favorites (i.e. those where no special color has ever been specified) has changed from our former shade of golden-yellow to black.

This is unnecessary and will confuse users. We should be backward compatible.

(On top of this being an unnecessary change, black is a bad choice for users using the dark UI theme, and a questionable choice for highlighting items a user had individually created on the map, both in day but particularly in night mode.)

**Comment by vshcherb** [comment]
It was already fixed. Yes, I've noticed as well. And of course we should be backward compatible.

**Comment by sonora** [comment]
I still see all my previous and not customized favorites in black... (latest nightly)

**Comment by vshcherb** [comment]
@sonora can you please that in file (favorites.gpx) there is no color or color is yellow. Probably it was corrupted in the middle

**Comment by vshcherb** [comment]
<extensions>
      <hidden>true</hidden>
      <icon>special_star</icon>
      <background>circle</background>
      <color>#eecc22</color>
    </extensions>

Since we've messed up with user data we need to revert all default values saved in favorites.gpx i.e. icon=special_star, background=circle, color=#eecc22 + color - black

**Comment by sonora** [comment]
I have looked at my 'offline' backup favorites.gpx file of October 2019. I am talking about `<wpts>` which contain only `<name>` and `<type>` tags there.

Looking at the 'live' favorites.gpx file in my osmand data folder now, it seems all these points have been 'enhanced' by
```
    <extensions>
      <icon>special_star</icon>
      <background>circle</background>
      <color>#000000</color>
    </extensions>
```

My request is to please keep the 'yellow star' default as we always had it (and display points coming without extension tags with this default), but do not save this default information as extension to the gpx file?

**Comment by sonora** [comment]
Looks like this is fixed again, thanks!

Something similar: I just notice that about the first 140 of my 1000 favorites, this time I am talking about the ones which **did** actually give a color, all of a sudden also contain an `<address>` tag, which I had never knowingly entered. (And it is not present in my Oxtober backup of the favorites.gpx file). It looks like only the alphabetically by name first 140 favorites are affected (so far).  Another bug?? Or a feaure??

**Comment by vshcherb** [comment]
Address will be set eventually for all favorites, it is planned. We didn't want to create them for all in background cause it could be time-consuming. If we want to display it all the time is questionable but now the answer is more yes.

**Comment by sonora** [comment]
It is not useful for all use cases: I have thousands of research favs which are in wilderness or uninhabitated areas, tagging them with 'Near highway XY' does not serve a purpose for them at all, other  than blowing up my backup files, osmand's database, and certainly burning CPU cycles.

If there is a true user advantage in storing the address, can I suggest we limit that to the favorites where an address could actually be  determined, i.e taking out e.g. our approximate hits which we label 'Near XYZ'.

**Comment by pebogufi** [comment]
What about using a checkbox for address in fav group. I think this desicion for the complete group would be nice.

**Comment by vshcherb** [comment]
This isssue is related to colors and default values, though addresses is still ongoing discussion probably it deserves another issue. Though keep in mind that it won't be related to this one cause 3.7 is not out yet and migration could be different for nightlies and 3.6 -> 3.7 where it could be valid
