### ISSUE TITLE
can't create poi internet_access = wlan

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#9462]
It is only possinle to create 
internet_access = yes.

In europe internet_access = wlan is quite common.
version 3.7.0#30147, 2020-07-10

**Comment by vshcherb** [comment]
I'm able to select it in POI Type, though when I switch to Advanced I have a crash.

**Comment by max-klaus** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-resources/commit/5c297ee6770fc9b2d45a34e6ceb59863d44ac929

**Comment by pebogufi** [comment]
@max-klaus 
For me it is not fixed, see screenshots german and english.
Checked with  3.7.0#30301, released 2020-08-04

![20200804_182159~01](https://user-images.githubusercontent.com/18628183/89319532-c1d69180-d66f-11ea-9674-0d3a089d6e30.jpg)
![20200804_182356~01](https://user-images.githubusercontent.com/18628183/89319607-e0d52380-d66f-11ea-8bf2-66dbe6da42aa.jpg)

**Comment by pebogufi** [comment]
Example:
https://www.openstreetmap.org/node/7227098374

**Comment by vshcherb** [comment]
You can create only "yes" in this UI and change the value via advanced tags "wlan". 
This is a limitation because we index all internet access in a simplified way to support easier tags search

**Comment by pebogufi** [comment]
Direct changing the "yes" into "wlan" is not possible in main tag.
But you inspired me to a different solution.
-> create "any" main tag, which will use as dummy, example "tree".
Then the tags you want to have.
Now I have:

natural=tree
internet_access=wlan
internet_access:fee=no
.. maybe more

Then remove dummy tree.
Save without main tag.
Now you have created the disired dedicated internet_access wlan with theese tags:

internet_access=wlan
inter_access:fee=no

I think for experienced users this is a nice trick, but I will not recommend it to newbees.

**Comment by vshcherb** [comment]
hm... you don't need to enter main type, I think we remove all validation for that. So you can simply create it with tags.
Though for advanced usage obviously Quick action is recommended, unfortunately we don't have custom poi types UI though you can also put poi_types.xml where you can define internet_access=wlan as a main type.

**Comment by pebogufi** [comment]
Thanks Victor, I edited my last comment at at same time, you did.
